### ISSUE TITLE
certificate not trusted

### ISSUE THREAD

**Issue by MWoidt** [alexreinert/debmatic#100]
wget -q -O - https://www.debmatic.de/debmatic/public.key | sudo apt-key add -
is not working
=>
gpg: no valid OpenPGP data found.
then with wget --no-check-certificate -q -O - https://www.debmatic.de/debmatic/public.key | sudo apt-key add -
I receive OK but 
sudo bash -c 'echo "deb https://www.debmatic.de/debmatic stable main" > /etc/apt/sources.list.d/debmatic.list'
and then
sudo apt update
gives

.....
Genegeerd:5 https://www.debmatic.de/debmatic stable InRelease
Fout:6 https://www.debmatic.de/debmatic stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  
Could not handshake: Error in the certificate verification. [IP: 95.216.13.95 443]
Pakketlijsten worden ingelezen... Klaar
E: De pakketbron 'https://www.debmatic.de/debmatic stable Release' heeft geen Release-bestand.
N: Bijwerken van de pakketlijst uit een dergelijke pakketbron kan niet veilig gebeuren en is daarom standaard uitgezet.
on raspi 4 /4GB
any solution? Thanks.
N: Zie de man-pagina apt-secure(8) voor details over het aanmaken van een pakketbron en over de configuratie langs gebruikerskant.

**Comment by alexreinert** [comment]
Duplicate to #99 

There was an issue with the intermediate certifcate while updating to a new ssl certificate and this issue should now be fixed.

**Comment by MWoidt** [comment]
I solved the problem by deleting one line out of the public.key file:
==> Version: GnuPG v1.4.14 (GNU/Linux) 

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.14 (GNU/Linux)

mQENBFJsL6IBCADMlaNsEi/CXNdYeacssVfjj+//N0VNjRdV+BIRB7WUvEZX6dS5

**Comment by MWoidt** [comment]
please check clean your public.key

**Comment by MWoidt** [comment]
ok, thanks. I can now go on with the installation
Kind regards and stay healthy
michael

**Comment by MWoidt** [comment]
installation went well
