### ISSUE TITLE
Anlernen von HM Komponenten

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#101]
Habe wieder das Problem wenn ich Homematic Komponenten anlerne, das als Interface RemoteApi eingetragen ist und ich somit nichts einstellen kann. Es kommt auf der Einstellungsseite folgende Meldung "Das Gerät mit der Seriennummer 'NEQ0271580' vom Interface 'RemoteApi' konnte nicht abgefragt werden! "

**Comment by smooty1970** [comment]
Hallo. Habe heute auch drei HmRF Komponenten angelernt - bei kommt diese Meldung auch. Die Devices erscheinen auch in der XML-API unvollständig. Über devconfig kann man sie sehen und steuern, über die WebGUI ercheinen sie nur in Einstellungen/Geräte, aber nicht imzugeördneten Status und bedienen/Raum und auch nicht über Status und bedienen/Geräte
