### ISSUE TITLE
CUxD 2.4.1

### ISSUE THREAD

**Issue by Spont09** [alexreinert/debmatic#102]
Hey,

habe folgendes Problem, und zwar habe ich das Add-on [https://github.com/j-a-n/homematic-addon-hue](https://github.com/j-a-n/homematic-addon-hue) installiert und das hue addon verlangt die cuxd version >2.4 leider ist die aktuelle version von cuxd nur 2.3.3 

Wird es eine angepasste CUxD 2.4.1 geben.

Vielen Dank

Mit freundlichen Grüßen

**Comment by alexreinert** [comment]
Ich habe die Version 2.4.1 von CUxD grade im testing Repository hochgeladen. Aufgrund der Abhängigkeiten zur libc6 >= 2.28 läuft diese aber nicht unter Ubuntu 18.04 (wohl aber in Debian Buster oder Ubuntu >= 18.10 und auf allen ARM Platformen)

**Comment by chrkan** [comment]
Läuft bei mir ohne Probleme
