### ISSUE TITLE
HmIP-FROLL Aktuelle Position

### ISSUE THREAD

**Issue by AndynordSee** [alexreinert/debmatic#104]
Moin Alex, 

 In der WebUI wird unter dem "Startseite > Status und Bedienung > Geräte"  beim HmIP-FROLL die Aktuelle Position leider nicht angezeigt wird. 

![HmIP-FROLL](https://user-images.githubusercontent.com/34406013/78883741-33078e80-7a5a-11ea-9e0b-ee78c59754d7.PNG)

Das gleiche gilt leider auch für die Keymatic.

![Keymatic](https://user-images.githubusercontent.com/34406013/78884018-92fe3500-7a5a-11ea-9c85-aa730ec0c9db.PNG)

**Comment by alexreinert** [comment]
Ist das nur nach einem Neustart der Fall oder auch, nachdem man den Zustand physikalisch verändert hat?

**Comment by derdon999** [comment]
Ich kann bestätigen, dass auch nach einigen Malen hoch und runterfahren der Rollos, die Fragezeichen bleiben. Man kann zwar einen Wert eingeben, z.B. 50% und die Rollos fahren entsprechend nur bis "zur Hälfte", aber dann tauchen direkt wieder die ?? auf.
Nächste Woche kann ich das ganze Mal mit der neuen Firmware für HmIP-FROLL, die heute rausgekommen ist, testen.
