### ISSUE TITLE
Web-UI kann nicht geöffnet werden

### ISSUE THREAD

**Issue by Thomas55555** [alexreinert/debmatic#105]
Hallo,
habe gerade debmatic installiert aber ich komme nicht auf die Web-Oberfläche. Wenn ich folgendes eingebe: `http://192.168.178.54/` passiert nicht. Habe deswegen mal in der config geschaut, auf welchem Port das ganze läuft. Nach Eingabe von `http://192.168.178.54:8183/` werde ich dann auf `http://192.168.178.54:8183/pages/index.htm?sid=@5d24jxiX3n@` weitergeleitet. Es tut sich also was. Allerdings bleibt der Browser leer. Habe auch schon den Cache gelöscht und einen anderen Browser probiert. Wenn ich im Browser `http://192.168.178.54:8183/login.htm` eingebe kommt zumindest das ein Formular um Benutzername und Kennwort einzugeben. Allerdings ohne Buttons.

Da kann ich aber auch nichts eingeben. Hier die Info aus der debmatic-info:
`debmatic version: 3.51.6-43
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   QEQ0406790
Radio MAC:      0x6cfef1
SGTIN:          3014F711A061A7DA498F9D06
`
Die debmatic läuft auf einem RPi4b.

Habe auch schon mehrmals neu gestartet und gewartet, ob noch etwas passiert. Aber leider nichts. Ich weiß jetzt nicht genau, ob ich hier auf github mit meinem Problem richtig bin. Muss ja kein Problem sein, vielleicht hab ich auch nur was falsch gemacht. Wenn jemand eine Idee hat, bitte ich um Info, danke.

**Comment by alexreinert** [comment]
Die WebUI läuft auf Port 80. Was genau heißt hier, dass beim Aufruf nichts passiert?

**Comment by alexreinert** [comment]
Leider keine Rückmeldung, daher mache ich hier zu. Falls weiter Klärungsbedarf besteht, bitte wieder aufmachen.

**Comment by Thomas55555** [comment]
Sorry für die späte Rückmeldung. Mit "beim aufrufen passiert nichts" war gemeint, dass das UI nicht geladen wird. Zwischenzeitlich hat der Port 8183 für das UI spordaisch funktioniert. Warum auch immer... Ich gehe aber nun grundsätzlich über Port 80 drauf. Da funktioniert es ohne Probleme. Für den RPC-Zugriff nutze ich Port 32001. Danke für die Hilfe

**Comment by RoPe311** [comment]
Ich muss mich hier mal anschließen, da ich seit einiger Zeit den gleichen Fehler habe:

Ich betreibe das HM-MOD-RPI-PCB an einem Pi3B+ mit aktuellem Raspbian und FHEM.

`uname -a` ergibt:
`Linux fhempi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux`

`sudo debmatic-info` liefert (gekürzt):
`debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  QEQ0410xxx
 Radio MAC:     0x6D0xxx
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7DA49xxxxxx
 Radio MAC:     0xBEDxxx`

`systemctl status lighttpd.service` zeigt mir `[..] active (running) [..]`

`systemctl status debmatic-lighttpd.service` ergibt:
`[..] active (running) [..]`
`Okt 13 18:23:14 fhempi systemd[1]: Starting debmatic lighttpd...`
`Okt 13 18:23:14 fhempi lighttpd[757]: (server.c.1464) server started (lighttpd/1.4.53)`
`Okt 13 18:23:14 fhempi systemd[1]: Started debmatic lighttpd.`

Ich habe debmatic bereits neu installiert via `sudo apt --reinstall install debmatic`, ohne Erfolg.

Der Aufruf über Port 80 von `http://<IP>/` führt zu einer leeren Seite, die endlos lädt.
Via Port 8183 wird man zu einer leeren Seite `http://<IP>:8183/pages/index.htm?sid=@W4OruTuUKQ@` weitergeleitet.

debmatic lief in der letzten Winterperiode noch problemlos. Zwischendurch gab es am System aber einige SW-Updates. An der Hardwarekombination kann es nicht liegen.
