### ISSUE TITLE
HM-MOD-RPI-PCB wird nicht erkannt auf Raspi 4

### ISSUE THREAD

**Issue by Alexander060101** [alexreinert/debmatic#109]
Hallo zusammen,

auf meinem Raspberry Pi 4 wird leider das HM-MOD-RPI-PCB Modul nicht erkannt.

sudo debmatic-info liefert:
_debmatic version: 3.51.6-43
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown_

Woran könnte das liegen? Wie kann ich den Fehler finden?

Habe schon andere Issues hier gelesen, aber da war das Problem immer, dass entweder "Kernel modules" oder "Raw UART dev" nicht verfügbar waren.. Das scheint ja bei mir zu passen.

Danke schon mal.

Beste Grüße
Alexander

**Comment by alexreinert** [comment]
Bitte mal Bilder von Vorder- und Rückseite des Funkmoduls posten, auf welcher man die Lötstellen gut erkennt.

**Comment by Alexander060101** [comment]
Danke für die schnelle Hilfe.
Hier die Bilder.

Kann es eventuell am PoE HAT liegen?

![IMG_1119](https://user-images.githubusercontent.com/12053064/80908515-c615aa80-8d20-11ea-9373-544492ed82b0.jpeg)
![IMG_1118](https://user-images.githubusercontent.com/12053064/80908518-c9a93180-8d20-11ea-92af-d635a522302e.jpeg)
![IMG_1117](https://user-images.githubusercontent.com/12053064/80908520-cada5e80-8d20-11ea-961e-7957f5a55e44.jpeg)
![IMG_1116](https://user-images.githubusercontent.com/12053064/80908521-cb72f500-8d20-11ea-902d-d8943e9c8fe6.jpeg)

**Comment by alexreinert** [comment]
Die Buchsenleiste ist auf der falschen Seite angelötet, vgl. z.B. https://files2.elv.com//public/14/1421/142141/Internet/142141_f11_plhomematic_600x600.jpg

**Comment by Alexander060101** [comment]
🤦🏻‍♂️

**Comment by Alexander060101** [comment]
Hallo,

mein Bekannter, der so Kleinigkeiten für mich lötet, hat es heute geändert.
Ich kann leider nicht löten.

Leider wird es immer noch nicht erkannt.

Hast du vielleicht noch eine Idee?

Besten Dank.


Gruß
Alexander

**Comment by alexreinert** [comment]
Zeig bitte nochmal Bilder.

**Comment by Alexander060101** [comment]
![4A0FB71A-7654-4BB4-A75E-D1E187D07A29_1_105_c](https://user-images.githubusercontent.com/12053064/82156449-53a5de00-987b-11ea-933d-b93192a39ee0.jpeg)
![07C66731-D355-4C30-A0F6-D54C2F7A34C4_1_105_c](https://user-images.githubusercontent.com/12053064/82156455-56083800-987b-11ea-89b3-7ad61e301ecd.jpeg)
![CB18A7DF-0954-4DEE-8750-B5217DA1DBB0_1_105_c](https://user-images.githubusercontent.com/12053064/82156456-57396500-987b-11ea-84f2-f2d91da9188b.jpeg)
![BF1A1925-50B4-4268-9763-66DC8BB20497_1_105_c](https://user-images.githubusercontent.com/12053064/82156457-57d1fb80-987b-11ea-874c-e6461ad73bfc.jpeg)

**Comment by alexreinert** [comment]
Handelt es sich um das gleiche Modul wie am Anfang? Aufgrund der Lötstellen an der Antenne würde ich grade darauf tippen. Das könnte dann natürlich einen Schaden abbekommen haben, weil der Pin für die 3.3V Stromversorgung an 5V angeschlossen war.
Außerdem könnte es sein, dass Pin 10 einekalte Lötstelle hat, aber man erkennt es auf dem Bild leider nicht richtig.

Was liefert debmatic-info?

**Comment by Alexander060101** [comment]
Danke für deine Unterstützung.
Ja, es ist das selbe Modul.
debmatic-info liefert immer noch das selbe.
```
debmatic version: 3.51.6-43
Kernel modules: Available
Raw UART dev: Available
HMRF Hardware: unknown
HMIP Hardware: unknown
Board serial: unknown
Radio MAC: unknown
SGTIN: unknown
```
Die Lötstellen sollten passen.
Da werde ich wohl ein neues Modul bestellen müssen, vermutlich ist das alte dann durch den Fehler am Anfang defekt gegangen.. 😕

**Comment by alexreinert** [comment]
Eine Idee habe ich ggf. noch, kannst du bitte mal deine /boot/config.txt posten?

**Comment by Alexander060101** [comment]
Sehr gerne.

```
pi@raspberrypi:~ $ sudo cat /boot/config.txt
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=16
dtoverlay=pivccu-raspberrypi
dtoverlay=pi3-disable-bt
```

**Comment by alexreinert** [comment]
Ok, die sieht gut aus, das ist es leider nicht.

**Comment by Alexander060101** [comment]
Alles klar, danke.
Dann habe ich wohl ein Funkmodul auf dem Gewissen.. 😪
Ein neues ist schon unterwegs.. hoffentlich funktioniert es dann diesmal endlich.
Melde mich am Wochenende wieder.

**Comment by Alexander060101** [comment]
Es funktioniert jetzt mit dem neuen Modul! :)
Danke für deine Hilfe während der Fehlersuche.

sudo debmatic-info
debmatic version: 3.51.6-43
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
...
