### ISSUE TITLE
debmatic funktioniert nicht mit openhab 2 (error 500)

### ISSUE THREAD

**Issue by holly79** [alexreinert/debmatic#11]
Hallo Alex,

ich habe debmatic auf dem gleichen System wie openhab 2 laufen. Wenn ich debmatic als Thing hinzufügen möchte, bekomme ich einen Error 500 im PaperUI (openhab 2). Ein Test mit pivccu3 war erfolgreich. Leider kann ich nichts im openhab Logfile finden. 

Ich benutze debmatic aktuell ohne Modul am Raspberry PI.

Danke
Holly

**Comment by holly79** [comment]
Ich habe jetzt noch etwas herausgefunden. Bei meiner CCU2 (YAHM) wird eine UID im paperui beim Thing mit angezeigt."You are about to add a new thing eQ3-HM-CCU2-App - XXX.XXX.XXX.XXX (homematic:bridge:**OEQ0302614**) from the inbox."

Bei debmatic wird diese nicht mit angezeigt. Ich habe das Logging nun an der richtigen Stelle eingestellt. "You are about to add a new thing eQ3-HmIP-CCU3-App - XXX.XXX.XXX.XXX (homematic:bridge:) from the inbox."

Auszug aus dem Openhab2 logfile.
19:33:01.056 [DEBUG] [.io.rest.JSONResponse$ExceptionMapper] - exception during REST Handling
java.lang.IllegalArgumentException: UID must have at least 3 segments.
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:70) ~[?:?]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[?:?]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) ~[?:?]
	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:126) ~[?:?]

Ich hoffe das erspart dir etwas Zeit.

**Comment by alexreinert** [comment]
Ich habe jetzt mehrfach versucht, dieses Problem zu reproduzieren, aber es funktioniert bei mir wunderbar.
Allerdings muss man auch beachten, dass man mind. openhab 2.5 braucht, weil durch die Anpassungen in Firmware 3.41.x keine Kommunikation mit openhab <= 2.4 möglich ist (bei allen CCU3 Varianten, egal ob Original CCU3, piVCCU3, debmatic oder RaspberryMatic)

**Comment by holly79** [comment]
Ich habe jetzt von meinen laufendes System mit Funkmodul getestet und da hat es nun funktioniert. Wie ich oben geschrieben hatte, habe ich es ohne Funkmodul getestet gehabt und da wird keine ID an openhab2 gegeben. Das habe ich auch validieren können. Gleiches System mit Funkmodul funkioniert, ohne nicht. Eventuell kann eine ID erzeugt werden, wenn kein Funkmodul vorhanden ist.

**Comment by alexreinert** [comment]
Konnte es ohne Funkmodul nachvollziehen. Ist in Version 3.45.7-19 gefixt.
