### ISSUE TITLE
falsche LED-Statusfarbe nach Systemstart - RPI4 - RPI-RF-MOD

### ISSUE THREAD

**Issue by SpRiNgToIfEl** [alexreinert/debmatic#111]
Hallo,

ich habe heute Debmatic auf Rasbian neu aufgesetzt und folgendes festgestellt:
Die Status-LED auf dem Funkmodul (RPI-RF-MOD) leuchtet nach dem kompletten Hochfahren "rot" statt bisher wie gewohnt "blau" (rasberrymatic). Nur ein Neustart mittels "sudo service debmatic restart" von Debmatic bringt sie wieder blau zu leuchten, bis zum nächsten reboot, danach ist alles wieder beim alten > "rot".

Nutze eine RPI 4 - 4GB mit RPI-RF-MOD, neustes Rasbian sowie Debmatic, alles up-to-date...

Das Thema gab es anscheind schon einmal:
RPI-RF-MOD nach System reboot mit falschem LED Status
https://github.com/alexreinert/debmatic/issues/49

**Comment by SpRiNgToIfEl** [comment]
Ergänzend dazu:

- RPI4 per LAN angeschlossen, DHCP, statische IP kommt von der Fritzbox
- Rasbian: Buster (up-to-date)
- Debmatic: 3.51.6.43 (keien Statusmeldungen weil kein Gerät angelernt ( angemeldet) ist, also installation frisch "out-of-the-box" und up-to-date.
- iobroker (up-to-date)

Ich hatte vor einiger Zeit pivccu3 ausprobiert, da leuchtete sie blau wie sie soll. Geräte können trotz roter Kontrolleuchte angelernt werden.

**Comment by SpRiNgToIfEl** [comment]
![IMG_20200506_192846](https://user-images.githubusercontent.com/64694788/81209392-c6d46800-8fd0-11ea-9677-76e48dd7af68.jpg)
![IMG_20200506_193007~3](https://user-images.githubusercontent.com/64694788/81209405-c9cf5880-8fd0-11ea-96a2-adc692ac8664.jpg)

**Comment by SpRiNgToIfEl** [comment]
1. rot (rpi ((re)boot)
![1](https://user-images.githubusercontent.com/64694788/81212375-1ddc3c00-8fd5-11ea-9f43-852cabcc9152.png)
![2](https://user-images.githubusercontent.com/64694788/81212393-23d21d00-8fd5-11ea-873e-89eb333b3b44.png)
![3](https://user-images.githubusercontent.com/64694788/81212406-2765a400-8fd5-11ea-96b6-5e61291547e2.png)
2. blau (sudo service debmatic restart)
![1_1](https://user-images.githubusercontent.com/64694788/81212425-2b91c180-8fd5-11ea-8aac-98c3420e916c.png)
![2_1](https://user-images.githubusercontent.com/64694788/81212433-2f254880-8fd5-11ea-99cd-f71215d24410.png)
![3_1](https://user-images.githubusercontent.com/64694788/81212444-32203900-8fd5-11ea-9711-36668f0fd76f.png)

Ich sehe da keinen Unterschied was der "debmatic restart" bringt, außer das nach dem Befehl die LED blau leuchtet. Nach "sudo reboot" ist alles wieder wie vorher, also rot...

**Comment by alexreinert** [comment]
Die LED wird vom hss_led gesteuert. Dieser liegt leider nur als Closed Source vor und vorsichtig ausgedrückt, er macht komische Dinge und mir ist bisher leider noch nicht 100% klar, was er alles überprüft um zum Ergebnis blau oder rot zu kommen.

**Comment by SpRiNgToIfEl** [comment]
...alles kein Problem. Debmatic funktioniert ansonsten super!
Danke das du es entwickelst...

**Comment by ts624** [comment]
Leider funktioniert nicht alles super. Nach Neustart leuchtet die LED rot UND einige Geräte (zb HMIP-WTH) liefern keine Daten bzw. reagieren überhaupt nicht. Erst ein "sudo service debmatic restart" behebt das Problem. Habe einen Raspberry 4 mit 4GB, Debian-Image, debmatic, iobroker, webmin und Nextcloud. Da der Raspberry an einer USV hängt, kann ich mit dem Problem leben, da ansonsten das System SUPER läuft. Vielen Dank an Alex!!!
Die Systemlogs sind identisch mit denen von  SpRiNgToIfEl und der Fehler tritt auch mit anderen Images, die nicht ganz so überladen sind wie mein derzeitiges, auf. Mit oder ohne WLAN hat auch keinen Einfluß.
