### ISSUE TITLE
remote homematic-script api aktivieren

### ISSUE THREAD

**Issue by roesl** [alexreinert/debmatic#113]
Hallo, wie kann ich die remote homematic-script api aktivieren, da es bei Debmatic keine Firewalleinstellungen gibt und ich von IP-Symcon sonst keine Verbindung aufbauen kann.
XML-API ist installiert - die Frage ict nur ob die auch richtig funktioniert ?

**Comment by alexreinert** [comment]
Die kann auch in einer CCU nicht deaktiviert werden, sie ist immer an, auch in debmatic.

**Comment by roesl** [comment]
Warum meckert dann IPS ?
Sind die in Debmatic verwendeten Ports identisch mit der Homematic ?
Oder stimmt etwas mit der XML-API nicht ?
Ich habe das Debmatic und das IPS auf der gleichen VM installiert

**Comment by alexreinert** [comment]
Ich habe leider keine Ahnung von IPS. debmatic hat die gleichen Ports wie eine CCU. Allerdings werden nur die Ports aktiviert, für welche auch eine Unterstützung in der Funkhardware vorhanden ist, mögl. liegt es daran?

**Comment by roesl** [comment]
Gibts bei der Debmatic eine Firewall ?

**Comment by alexreinert** [comment]
Nur wenn man sie manuell mit Denian Bordmitteln einrichtet.

**Comment by roesl** [comment]
komisch - ich frag mal bei Symcon nach, vielleicht haben die einen Tip.
XML-API scheint zu funktionieren, da ich mit der Home24 App auf die Debmatic komme.
Wie kann man das Debmatic temporär deaktivieren, so daß es beim Systemstart nicht hochgefahren wird ?

**Comment by alexreinert** [comment]
Beenden: systemctl stop debmatic
Start verhindern (aber nicht stoppen): systemctl disable debmatic

**Comment by roesl** [comment]
Nachdem ich  Ubuntu komplett aktualisiert habe funktioniert es nun.
Ist SSL schon möglich ?
Ich habe nun auf der Synology VM das Ubuntu mit IP Symcon mit integriertem MQTT Broker , Debmatic und Zigbee2mqtt ( mit CC2530 über Lan) am Laufen.
Vorteil des Ganzen: Da bei Synology Snapshotreplication möglich ist, ist es easy, schnell Backups und Replikas von VMs zu erzeugen.
Vielleicht wärs eine Idee, OVA-Dateien mit der Debmatic für andere Nutzer zu Verfügung zu stellen.
Fehlt nur noch ein Lan-Gateway für HM-RF und HM-IP - dann bräuchte man keinen USB-Port mehr und wäre flexibel, vor Allem da beim Neustart der Synology das USB-Modul beim hochfahren der VM nicht rechtzeitig aktiv ist und somit die VM ohne USB-Modul hochfährt und dann das Debmatic auch kein Modul hat.
Wenn man das USB-Modul dann wieder in der VM anmeldet, erkennt Debmatic das trotzdem nicht und man muß die komplette VM nochmal neu starten bzw manchmal auch unsanft abschalten wenn sie ganz hängt.

Das Debmatic reagiert auch ziemlich sauer ( die komplette VM stürzt ab) wenn das USB Modul abgezogen oder deaktiviert wird.
Vielleicht kannst Du da was abfangen bzw einbauen, damit sich das USB-Modul auch im laufenden System einhängt falls es mal nötig ist, es zu resetten oder nachträglich einzuhängen.
Die Raspberrymatic auf einer VM macht da weniger Probleme ( braucht aber eine eigene VM und hat derzeit mit dem neuen Synology VMM Probleme)

**Comment by alexreinert** [comment]
SSL bzw. TLS kann (manuell) eingebunden werden, allerdings gibt es keine direkten Optionen in der WebUI dafür.
OVA ist angedacht, aber bisher kam ich zeitlich nicht dazu.
LAN GW verweise ich mal auf https://homematic-forum.de/forum/viewtopic.php?f=76&t=51754
USB Platine resetten ist nicht möglich, weil die Closed Source Programme von eQ-3 davon ausgehen, dass das Funkmodul per GPIO fest angeschlossen ist und ich da nichts anpassen kann. Die einzige Möglichkeit für einen Reset wäre ein kompletter Restart dieser Programme, was gleichbedeutend mit einem Komplett Restart von debmatic ist. Das RaspberryMatic sich da anders verhält, kann ich mir eigentlich nicht vorstellen, dass dort ebenfalls meine Treiber verwendet werden und auch die gleichen Programme.

**Comment by roesl** [comment]
Danke für die Info - gibts für das SSL eine Anleitung ?
Bezüglich des abgehängten Funkmoduls ist mir nur aufgefallen, dass sich bei der Debmatic die ganze VM abgeschossen wird während sich das Raspberrymatic dann normal neustarten läßt - ist aber in Endeffekt egal, da in beiden Fällen ein kompletter Neustart notwendig wird - was halt nach Synology reboot nervt ( z.B wenn die Synology bei Netzausfall von der USV runtergefahren wird und dann bei Netzrückkehr wieder hochfährt.
Das wäre z.B während eines Urlaubs fatal, da dann die gesamte Haussteuerung und Alarmanlage tot ist.
