### ISSUE TITLE
Keine Steuerbarkeit/Rückmeldung Homematic IP-Geräte Debmatic (3.51.6.43)

### ISSUE THREAD

**Issue by saxophonuser** [alexreinert/debmatic#115]
Alle bei mir verwendeten Homematic-IP-Komponenten lassen sich seit dem Update auf Debmatic 3.51.6.43 nicht mehr über die Weboberfläche steuern, es werden keine Werte angezeigt. Schaltflächen sind inaktiv.

Betroffen sind bei mir:
- Wandthermostate HmIP-BWTH
- Schaltsteckdosen HMIP-PS
- Außenthermometer HmIP-STHO-A
- Helligkeitssensor HmIP-SLO

Homematic-Geräte sind nicht betroffen. Steuerung über IoBroker funktioniert fehlerfrei.

**Comment by Noschvie** [comment]
Habe eine Schaltsteckdosen HMIP-PS und andere HMIP Komponenten ohne Probleme mit Debmatic 3.51.6.43 in Verwendung.
