### ISSUE TITLE
Bind IP ändern

### ISSUE THREAD

**Issue by SMHRambo** [alexreinert/debmatic#116]
Hi,
ich versuche grade auf meinem Pi mehrere Dienste für meine Smarthome-Steuerung zu installieren.
Leider kommt es bei mehrere Dienste bzgl. ihrer Ports zu Problemen.

Da es bei machen Diensten nicht möglich ist den Port zu ändern,
habe ich mir gedacht, dass ich dem Pi einfach mehrere IP-Adressen gebe und 
die in Konflikt stehenden Dienste an unterschiedlichen IP-Adressen lauschen lasse.

Leider ist mir dies bisher bei debmatic nicht gelungen.
Irgendeine Idee wie ich da rangehen muss?
Mein bisheriger Ansatz war in lighttpd eine bind ip hinzuzufügen und in der 20-debmatic Datei die Sockets auch auf die IP horchen zu lassen.
Leider ohne Erfolg.

Bei den in konflikt stehenden Dienste handelt es sich um diyHue und debmatic.
Mit Docker könnte ich diesem Problem zwar aus dem weg gehen, 
nur leider musste ich feststellen, dass wenn ich alle Dienster per Docker laufen lasse, der Ressourcenverbrauch doppelt so hoch ist.

**Comment by alexreinert** [comment]
Beim Lighttpd muss die Option server.bind gesetzt werden und bei allen Vorkommen von $SERVER["socket"] die entsprechende IP angegeben werden (ggf. nicht nur in der 20-debmatic.conf)

Die Closed Source Prozesse von eQ-3 bieten leider keine Option zum Binden auf eine einzelne IP.

Eine andere Option wäre es natürlich auch, dass man debmatic einfach von Port 80 auf einen anderen Port legt, eine entsprechende Option ist ja über die /etc/debmatic/webui.conf vorgesehen.

**Comment by SMHRambo** [comment]
Könnten bei der Änderung des Port 80 irgendwelche Probleme Smarthome Systemen wie openhab entstehen bzw. gibt es so etwas wie eine REST-API bei der CCU die über Port 80 läuft wo ich aufpassen muss?

**Comment by alexreinert** [comment]
Ich kann es natürlich nicht für sämtliche verfügbare Software sagen, aber eigentlich sollte es da keine Probleme geben, da die APIs der CCU über andere Ports laufen.
