### ISSUE TITLE
Lowbat Warnung übertragen

### ISSUE THREAD

**Issue by Thomas55555** [alexreinert/debmatic#117]
Hallo,

ich nutze debmatic in Verbindung mit home assistant und es gibt in home assistant auch einen Sensor, der mir die Warnung ausgeben sollte. Ich habe erst vermutet, dass es an home assistant liegt, bin mir jetzt aber nicht sicher. Ich habe mir das xml-api addon installiert, um zu sehen, was ausgegeben wird. Allerdings verstehe ich den Zusammenhang nicht ganz.
Ich habe jetzt folgende Situation. An meinem Thermostat leuchtet, dass Batteriesymbol auf. Auch in der debmatic Web-UI wird mir als Servicemeldung die Batteriewarnung auf channel 4 angezeigt.
Wenn ich mir den devicestate anschaue, steht im Channel 0 und auch im Channel 4 (dieser gibt die Spannung aus) keine Batteriewarnung an. Müsste im Channel 0, der Status von lowbat nun nicht auf "true" springen?

Hier noch zwei Auszüge:

systemNotification.cgi
`<systemNotification>
<notification ise_id="2029" name="BidCos-RF.NEQ1637315:4.FAULT_REPORTING" type="FAULT_REPORTING" timestamp="1590592758"/>
</systemNotification>`

statelist.cgi
`<device name="WZ3" ise_id="1988" unreach="false" sticky_unreach="false" config_pending="false">
<channel name="WZ3:0" ise_id="1989" index="0" visible="" operate="">
<datapoint name="BidCos-RF.NEQ1637315:0.UNREACH" type="UNREACH" ise_id="2010" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="2006" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="7"/>
<datapoint name="BidCos-RF.NEQ1637315:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="1991" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.LOWBAT" type="LOWBAT" ise_id="2000" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2004" value="1" valuetype="8" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.RSSI_PEER" type="RSSI_PEER" ise_id="2005" value="230" valuetype="8" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="1995" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="2014" value="false" valuetype="2" valueunit="" timestamp="1590592488" operations="5"/>
</channel>
<channel name="HM-CC-RT-DN NEQ1637315:1" ise_id="2018" index="1" visible="true" operate="true"/>
<channel name="HM-CC-RT-DN NEQ1637315:2" ise_id="2019" index="2" visible="true" operate="true"/>
<channel name="HM-CC-RT-DN NEQ1637315:3" ise_id="2020" index="3" visible="true" operate="true"/>
<channel name="HM-CC-RT-DN NEQ1637315:4" ise_id="2021" index="4" visible="true" operate="true">
<datapoint name="BidCos-RF.NEQ1637315:4.CONTROL_MODE" type="CONTROL_MODE" ise_id="2028" value="1" valuetype="16" valueunit="" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.FAULT_REPORTING" type="FAULT_REPORTING" ise_id="2029" value="6" valuetype="16" valueunit="" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.BATTERY_STATE" type="BATTERY_STATE" ise_id="2024" value="2.300000" valuetype="4" valueunit="V" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.VALVE_STATE" type="VALVE_STATE" ise_id="2064" value="0" valuetype="16" valueunit="%" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.BOOST_STATE" type="BOOST_STATE" ise_id="2026" value="0" valuetype="16" valueunit="min" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.ACTUAL_TEMPERATURE" type="ACTUAL_TEMPERATURE" ise_id="2022" value="21.400000" valuetype="4" valueunit="°C" timestamp="1590593524" operations="5"/>
<datapoint name="BidCos-RF.NEQ1637315:4.SET_TEMPERATURE" type="SET_TEMPERATURE" ise_id="2063" value="12.000000" valuetype="4" valueunit="°C" timestamp="1590593524" operations="7"/>
<datapoint name="BidCos-RF.NEQ1637315:4.AUTO_MODE" type="AUTO_MODE" ise_id="2023" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.MANU_MODE" type="MANU_MODE" ise_id="2052" value="" valuetype="4" valueunit="°C" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.BOOST_MODE" type="BOOST_MODE" ise_id="2025" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.COMFORT_MODE" type="COMFORT_MODE" ise_id="2027" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.LOWERING_MODE" type="LOWERING_MODE" ise_id="2051" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_MODE_SUBMIT" type="PARTY_MODE_SUBMIT" ise_id="2053" value="" valuetype="20" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_TEMPERATURE" type="PARTY_TEMPERATURE" ise_id="2062" value="5.000000" valuetype="4" valueunit="°C" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_START_TIME" type="PARTY_START_TIME" ise_id="2056" value="0" valuetype="16" valueunit="minutes" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_START_DAY" type="PARTY_START_DAY" ise_id="2054" value="1" valuetype="16" valueunit="day" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_START_MONTH" type="PARTY_START_MONTH" ise_id="2055" value="1" valuetype="16" valueunit="month" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_START_YEAR" type="PARTY_START_YEAR" ise_id="2057" value="0" valuetype="16" valueunit="year" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_STOP_TIME" type="PARTY_STOP_TIME" ise_id="2060" value="0" valuetype="16" valueunit="minutes" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_STOP_DAY" type="PARTY_STOP_DAY" ise_id="2058" value="1" valuetype="16" valueunit="day" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_STOP_MONTH" type="PARTY_STOP_MONTH" ise_id="2059" value="1" valuetype="16" valueunit="month" timestamp="1590593524" operations="3"/>
<datapoint name="BidCos-RF.NEQ1637315:4.PARTY_STOP_YEAR" type="PARTY_STOP_YEAR" ise_id="2061" value="0" valuetype="16" valueunit="year" timestamp="1590593524" operations="3"/>`

**Comment by alexreinert** [comment]
Der These würde ich zustimmen. Allerdings bin ich da leider der falsche Ansprechpartner: Die Werte kommen der Channel werden vom Gerät gesendet und dann vom (Closed Source) rfd auseinandergenommen. Das das Lowbat Flag nicht gesetzt wird ist daher entweder ein Bug in der Gerätefirmware oder innerhalb des rfd. Beides kann ich leider nicht korrigieren.
