### ISSUE TITLE
[Question] HomeKit via hap-homematic AddOn

### ISSUE THREAD

**Issue by j-p-l** [alexreinert/debmatic#118]
Hi @alexreinert !
Wird es die Möglichkeit geben, dieses AddOn zu nutzen: https://github.com/thkl/hap-homematic, oder ist das technisch nicht möglich? 

Beste Grüße!

**Comment by j-p-l** [comment]
Hallo @alexreinert , konntest du dir das AddOn schon mal anschauen?

**Comment by thkl** [comment]
siehe hier : https://github.com/thkl/hap-homematic/blob/master/doc/debmatic.md

**Comment by j-p-l** [comment]
Hi @alexreinert, wirst du die Integration von @thkl als Addon bei dir integrieren, oder sollen/können wir das über das Skript einfach separat installieren?

**Comment by alexreinert** [comment]
Im Endeffekt könnte ich nichts anderes machen, als die (sehr gute) Anleitung 1:1 in ein .deb Paket zu packen, wobei die Installation von Node.js dennoch manuell erfolgen müsste (zumindest das einbinden des entsprechenden APT Repositories). Daher glaube ich nicht, dass das wirklich Sinn macht.
