### ISSUE TITLE
WebUI : Wie kann die URL geändert werden?

### ISSUE THREAD

**Issue by Noschvie** [alexreinert/debmatic#119]
Hallo,
die WebUI ist derzeit über `http://192.168.1.75:8010/logout.htm?lang=de` erreichbar, nicht jedoch über den Hostname.
Was muss wie geändert werden, sodass die WebUI im LAN über `http://<hostname.domain.local>:8010/login.htm` erreichbar ist ?
(<hostname.domain.local> wird auf 192.168.1.75 aufgelöst.
Danke!

**Comment by alexreinert** [comment]
Wo kann der Hostname aufgelöst werden? Sofern die Namensauflösung korrekt funktioniert, funktioniert auch der Zugriff auf die WebUI. Das ist im Zweifel aber kein debmatic Thema, sondern lokale Netzwerkthematik.

**Comment by Noschvie** [comment]
Hallo Alex,
Namensauflösung erfolgt durch Router (pfsense) und ist ok.
Sowohl `http://192.168.1.75` als auch `http://<hostname.domain.local>` bringen die "Placeholder page" von "Lighttpd server package".
`http://<hostname.domain.local>:8010` wird weitergeleitet auf `http://<hostname.domain.local>:8010/pages/index.htm?sid=@Ysk45DlOv8@` und zeigt eine "404 Not Found" Page.

Kann es sein, dass bei einem `sudo apt-get update && sudo apt-get upgrade -y` was verstellt wurde?

Host ist ein RPi3+ Buster nur mit Debmatic und HB-RF-USB
```
debmatic version: 3.51.6-43
Kernel modules: Available
Raw UART dev: Available
Rasp.Pi3 UART: Not assigned to GPIO pins
HMRF Hardware: RPI-RF-MOD
HMIP Hardware: RPI-RF-MOD
```
Unmittelbar nach einem Neustart des RPi zeigt `http://<hostname.domain.local>:8010` kurz die HM Seite "Die Homematic CCU ist noch nicht bereit" und anschliessend "404 Not Found".

Tests haben gezeigt, dass die Änderung des WebUI Ports (/etc/debmatic/webui.conf) keinen Einfluß hat.

Weitere Tests haben nun gezeigt, dass `http://<hostname>:8010` (weglassen der Domain) die WebUI korrekt angezeigt wird.

-> offensichtlich kommt lighttpd (?) mit einem Domain Namen nicht zurecht.
Somit scheint es jetzt eine Frage für Linux-Spezialisten zu sein.

btw: hat jemand Erfahrung mit traefik und Weiterleitung an dematic WebUI ?
Habe einen traefik und Node-RED Container laufen, traefik routet einen bestimmten Hostname erfolgreich an das Node-RED Dashboard weiter (Dashboard visualisiert HM/DM Temperaturwerte).
In einem nächsten Schritt möchte ich gerne versuchen, dass traefik `debmatic.domain.local` an die WebUI routet...

ps: thank you for this project!
