### ISSUE TITLE
Probleme mit CUxD

### ISSUE THREAD

**Issue by MSStyle** [alexreinert/debmatic#12]
Guten Abend,
Habe probleme mit dem Addon CUxD. Habe es installiert mit apt und lief einwandfrei, konnte auch Geräte erstellen. Nach einiger Zeit funktioniert CUxD aber nicht mehr. Komme zwar noch auf die Seite aber unter Status wird nichts mehr angezeigt. Auch die Geräteliste ist weg.
Auf der Seite unter CUxD Syslog sind keine einträge.
Full Syslog:
>Apr  9 21:50:51 Homematic kernel: [    3.893891] [TTM] Zone  kernel: Available graphics memory: 1026016 kiB
Apr  9 21:50:51 Homematic kernel: [    3.893892] [TTM] Initializing pool allocator
Apr  9 21:50:51 Homematic kernel: [    3.893897] [TTM] Initializing DMA pool allocator
Apr  9 21:50:51 Homematic kernel: [    3.896032] fbcon: bochsdrmfb (fb0) is primary device
Apr  9 21:50:51 Homematic kernel: [    3.916898] Console: switching to colour frame buffer device 128x48
Apr  9 21:50:51 Homematic kernel: [    3.918408] bochs-drm 0000:00:02.0: fb0: bochsdrmfb frame buffer device
Apr  9 21:50:51 Homematic kernel: [    3.930785] [drm] Initialized bochs-drm 1.0.0 20130925 for 0000:00:02.0 on minor 0
Apr  9 21:50:51 Homematic kernel: [    3.950623] generic_raw_uart: loading out-of-tree module taints kernel.
Apr  9 21:50:51 Homematic kernel: [    4.003130] usb 2-1: Found HB-RF-USB at usb-0000:00:1d.0-1
Apr  9 21:50:51 Homematic kernel: [    4.061229] Adding 2094076k swap on /dev/sda5.  Priority:-1 extents:1 across:2094076k FS
Apr  9 21:50:51 Homematic kernel: [    4.252804] usbcore: registered new interface driver hb_rf_usb
Apr  9 21:50:52 Homematic kernel: [    4.740735] raw-uart raw-uart: Reset radio module
Apr  9 21:50:53 Homematic kernel: [    5.394598] random: crng init done
Apr  9 21:50:53 Homematic kernel: [    5.394599] random: 7 urandom warning(s) missed due to ratelimiting
Apr  9 21:51:06 Homematic update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Apr  9 21:51:06 Homematic kernel: [   18.484345] eq3loop: created slave mmd_hmip
Apr  9 21:51:06 Homematic kernel: [   18.484456] eq3loop: created slave mmd_bidcos
Apr  9 21:51:08 Homematic kernel: [   20.564126] eq3loop: eq3loop_open_slave() mmd_bidcos
Apr  9 21:51:14 Homematic kernel: [   26.092348] eq3loop: eq3loop_open_slave() mmd_hmip
Apr  9 21:51:14 Homematic kernel: [   26.092432] eq3loop: eq3loop_close_slave() mmd_hmip
Apr  9 21:51:14 Homematic kernel: [   26.093457] eq3loop: eq3loop_open_slave() mmd_hmip
Apr  9 21:51:14 Homematic kernel: [   26.093528] eq3loop: eq3loop_close_slave() mmd_hmip
Apr  9 21:51:14 Homematic kernel: [   26.096722] eq3loop: eq3loop_open_slave() mmd_hmip
Apr  9 21:51:14 Homematic kernel: [   26.097772] eq3loop: eq3loop_ioctl_slave() mmd_hmip: unhandled ioctl 0x5459
Apr  9 21:51:14 Homematic kernel: [   26.097776] eq3loop: eq3loop_ioctl_slave() mmd_hmip: unhandled ioctl 0x545D

Habe auch schon alles neuinstalliert aber das Problem tritt immer wieder auf. debmatic funktioniert ohne Probleme.
Zu meinem System:
Intel Nuc mit Proxmox
Linux Debian Kernel 4.9.0-8-amd64
HB-RF-USB mit RPI-RF-MOD

Danke im Voraus

**Comment by alexreinert** [comment]
Wenn das Problem erneut auftritt, bitte Ausgabe von `sudo ps aux` und alles was an Logs für den Zeitpunkt des Problems verfügbar ist (dmesg, /var/log/messages, /var/log/syslog, /var/log/hmserver.log). Zusätzlich bitte dann auch den verfügbaren Arbeitsspeicher prüfen. Perfekt wäre auch eine Analyse, ob da ein zeitliches Muster erkennbar ist.

**Comment by MSStyle** [comment]
Habe cuxd noch einmal neu installiert. Und alles genau beobachtet. Mir ist jetzt aufgefallen das cuxd bis dahin läuft bis ich in Iobroker hm-rega und hm-rpc starte (Homematic IP Daemon).
- Nach Installation RPI-RF-MOD LED Rot, CUxD läuft 23:22Uhr
- service debmatic stop / start ausgeführt RPI-RF-MOD LED Blau, CUxD läuft
- VM CPU Last 4.30% ~500MB RAM von 2GB (Debmatic+CUxD)
- Verbindung mit Iobroker hm-rega hm-rpc.0 CUxD fällt aus 23:35Uhr
- VM CPU Last 30% ~ 500MB RAM wenn CUxD hängt
Wie gesagt ich komme noch auf die Weboberfläche von CUxD aber bekomme z.B. bei Status nichts mehr angezeigt, auch die Geräte sind weg und kann auch keine weiteren anlegen. 

Vielleicht kannst du damit ja was anfangen. Im Anhang sind noch die Logs.

[Debmatic Log.zip](https://github.com/alexreinert/debmatic/files/3101627/Debmatic.Log.zip)

**Comment by MSStyle** [comment]
Also das mit Iobroker kann ich wieder ausschließen. Habe CUxD neu installiert ohne Homematic mit Iobroker zu verbinden und hatte wieder nach einigen Minuten den absturz. 
Hier mal noch den Log von lighttpd hat es vielleicht damit zutun?
[error.log](https://github.com/alexreinert/debmatic/files/3139791/error.log)

**Comment by MSStyle** [comment]
Hallo,
Ich habe glaube den Übeltäter gefunden. Und zwar hatte ich immer nach der Cuxd Installation das Gerät (90) Universal Wrapper Device angelegt und in Homematic eingebunden. Danach hat sich cuxd aufgehangen. Habe jetzt mal ein anderes Gerät erstellt und siehe da es läuft jetzt schon seit 3 Tagen ohne Fehler.
Kann also geschlossen werden. 
Lg Markus
