### ISSUE TITLE
HmRF Komponenten nach Anlernen nicht in Liste und nicht über WebUI steuerbar

### ISSUE THREAD

**Issue by smooty1970** [alexreinert/debmatic#122]
Hallo. Habe drei HmRF Komponenten (HM-LC-Dim1PWM-CV) angelernt - bei mir kommt diese Meldung "Das Gerät mit der Seriennummer 'OEQ2080647' vom Interface 'RemoteApi' konnte nicht abgefragt werden! ". Die Devices erscheinen auch in der XML-API unvollständig. Über devconfig kann man sie sehen und steuern, über die WebGUI erscheinen sie nur einmal Einstellungen/Geräte, aber nicht im zugeordneten Status und bedienen/Raum und auch nicht über Status und bedienen/Geräte.
3x HM-LC-Dim1PWM-CV - die waren schon einmal 2019 erfolgreich angelernt und steuerbar, wurden ordungsgemäß abgelernt und sollten nun wieder angelernt werden.
Reset/Werkseinstellungen der Devices brachte nichts, Neustart CCU brachte auch nix.
Über iobroker sind die States auch steuerbar..., nur über WebGUI gehts nicht.

**Comment by Yattien** [comment]
Ich denke, so ein ähnliches Problem habe ich mit der HMRF-Statusanzeige _HM-Dis-TD-T_, diese erscheint beim Anlernen zwar im Posteingang, jedoch lässt sie sich dort schon nicht mehr konfigurieren. Alles weitere dann so wie im ersten Post. Die Fehlermeldungen im syslog beim Anlernvorgang sehen so aus:
```
ReGaHss: ERROR: interface pointer is null. ID=1010 [GetInterfaceByID():iseXmlRpc.cpp:2556]
ReGaHss: WARNING: XMLRPC 'getParamsetDescription': invalid interface id provided (interface: 1010, params: {"OEQ0711196:1","MASTER"}) [CallXmlrpcMethod():iseXmlRpc.cpp:2621]
ReGaHss: ERROR: XMLRPC 'getParamsetDescription' call failed (interface: 1010, params: {"OEQ0711196:1","MASTER"}) [GetAESMasterOperation():iseXmlRpc.cpp:2388]
```
VG
