### ISSUE TITLE
[Question] Funkmodul RPI-RF-MOD : LED blau : Intensität reduzierbar

### ISSUE THREAD

**Issue by Noschvie** [alexreinert/debmatic#123]
Hallo
gibt es eine Möglicheit, die Intensität der LED des Funkmoduls (zumindest) im Normalbetrieb (= Blau) zu reduzieren?
mfg
Norbert

**Comment by alexreinert** [comment]
Leider nein und das ist auch nicht nachrüstbar, da die Hardware das nicht hrrgibt.

**Comment by Noschvie** [comment]
ok, danke! Alternative: könnte die LED im Status "Normalbetrieb" (= Blau) nach einer bestimmten Zeit (zB 15 Minuten) ausgeschaltet werden? Solange alles ok bleibt ?

**Comment by alexreinert** [comment]
Auch wenn ich die Idee gut finde, ich kann das nicht umsetzen, weil das im Closed Source von eQ-3 passiert und ich da keinen Zugriff drauf habe.

**Comment by Noschvie** [comment]
Habe den Wunsch bei ELV-/eQ-3 deponiert.
