### ISSUE TITLE
Doku für Anwendungszenario als reine vccu

### ISSUE THREAD

**Issue by tobox** [alexreinert/debmatic#124]
Ich steige gerade von FHEM auf Home Assistant um. 

Ich habe einen HM-CFG-LAN und einen HM-LGW-O-TW-W-EU die bisher von FHEM als VCCU betrieben wurden. 

Ich würde jetzt gerne Debmatic für exakt denselben Zweck einsetzen. Brauche ich dafür wirklich die ganzen Kernel-Header und das Modul? Debmatic wäre doch in dem Fall einfach nur ein Dienst, der Netzwerktraffic macht, und keine Hardware-Zugriffe.

Ist mein Vorhaben mit Debmatic realisierbar? Sollte man die Doku bzw. die Dependencies so anpassen, dass sich Debmatic installieren lässt, ohne Kerneltreiber zu benötigen?

**Comment by alexreinert** [comment]
Vermutlich wird es auch ohne gehen, aber ich habe das nie explizit getestet. Mittel- bis langfristig sehe ich da auch keinen Sinn drin, HM wird auslaufen und HmIP wird mehr und mehr. Und dort braucht man die Kernel Module. Kurzfristig sehe ich nur eine überschaubar kleine Gruppe, welche das betreffen könnte, die Doku komplizierter für die Allgemeinheit zu machen für diese kleine Gruppe, sehe ich nicht zielführend an.

**Comment by tobox** [comment]
OK, ich teste mal, ob es einfach funktioniert. Danke schonmal für die schnelle Rückmeldung. 

Schade, dass HmIP keine LAN-Gateways unterstützt, für größere, verteilte Installationen fand ich das sehr praktisch. Aber das ist eine andere Baustelle.
