### ISSUE TITLE
Debmatic not working with HM-MOD-RPI-PCB on RPI4? 

### ISSUE THREAD

**Issue by ThomasLukasiewicz** [alexreinert/debmatic#125]
Hi, 

Debmatic seems to have a problem with HM-MOD-RPI-PCB (bought fully assembled from https://smartkram.de/) on RPI4 8GB (see attached file for more details on the configuration).: 

pi@raspberrypi:~ $ sudo debmatic-info debmatic 
debmatic version: 3.51.6-45
Kernel modules: Available
Raw UART dev:   Available
try HM-CFG-USB-2
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown

[debmatic.txt](https://github.com/alexreinert/debmatic/files/4872916/debmatic.txt)

Can this be fixed? Any ideas? 

Many thanks, 
Thomas

**Comment by alexreinert** [comment]
I have no 8GB Pi4 as test device, but with my 1GB Pi4 I cannot see any issues. As the 8GB and the 1GB have the same CPU and GPIO architecture, I'm pretty sure, that there will be no issues as well. Can you please provide pictures of your radio module: back, front, attached to pi.

**Comment by alexreinert** [comment]
Pne additional question: Did you buy a full package with radio module, Pi and the SD card at smartkram?

**Comment by ThomasLukasiewicz** [comment]
Thanks for your quick reply! That sounds promising. 

I bought the Pi in the UK (at that time, the 8GB version was not available yet in Germany) separately from the HM-MOD-RPI-PCB at smartkram.

The photos are here:
[pi4.zip](https://github.com/alexreinert/debmatic/files/4873040/pi4.zip)

Many thanks, 
Thomas

**Comment by alexreinert** [comment]
Ok, the module looks good. But maybe I found the issue:

In your /boot/config.txt you use ```dtoverlay=miniuart-bt```
This should be ```dtoverlay=pi3-miniuart-bt```

**Comment by ThomasLukasiewicz** [comment]
No, unfortunately, this doesn't help. (I had tried this before.)  

The "miniuart-bt" is from the official Pi 4 pages (I guess it's just a renaming):
https://www.raspberrypi.org/documentation/configuration/uart.md

**Comment by ThomasLukasiewicz** [comment]
OK, from what I see, this is either a hardware problem with the new Pi 4 8GB, a software problem with Pi OS (dated 2020-05-27), or a hardware problem with the radio module. Could you please let me know the Raspbian version where you got it to work on? So, I'll try that one as well to exclude that this is an OS problem. (Note that I also tried the piVCCU option without success.) 

Many thanks, 
Thomas
