### ISSUE TITLE
RSSI Werte

### ISSUE THREAD

**Issue by Goersch** [alexreinert/debmatic#127]
Hallo,
suche seit langem verzweifelt nach der Möglichkeit die Qualität der Funkverbindung wieder auslesen zu können - der hmcompanion, den ich dazu sehr lange verwendet habe, funktioniert seit dem Umstieg auf die CCU3 leider nicht mehr (ich vermute, weil es das Interface nicht mehr gibt).

Heute bin ich auf diese Möglichkeit gestossen: [https://www.homematic-inside.de/faq/geheimmenue](url). Leider scheint debmatic das nicht zu unterstützen.

Gibt es andere Wege wieder die Verbundungsqualität zwischen Gerät und CCU auszulesen? Oder könnte man die oben genannte Funktion evtl. auch in debmatic integrieren?

Direkt noch eine Frage: "Früher" (also so vor 10 Jahren, als ich mit Homematic begonnen habe), konnte man nur für Fernsteuerungen die feste Zuordnung aufheben (ich hab 5 LAN-Konfig-Adapter im Haus verteilt). Gilt diese Beschränkung eigentlich heute immer noch?

Danke
Georg

**Comment by alexreinert** [comment]
Die devconfig.cgi ist in debmatic vorhanden und funktioniert auch. Wie in den Original CCU allerdings nur für HM und nicht für HmIP.

Von der Beschränkung höre ich heute zum ersten mal, aber ich bin auch noch nicht so lange bei Homematic dabei. Von dem her würde ich jetzt einfach mal mutmaßen, dass sie nicht mehr existiert.

**Comment by Goersch** [comment]
mh, ich habs probiert wie in der Beschreibung im Link (also https://ip/tools/devconfig.cgi?sid=xxx“) - bekomme dann aber nur die Meldung, dass die Verbindung fehlgeschlagen ist. 

Muss ich noch was anderes machen?

**Comment by Goersch** [comment]
habs - http; nicht https

**Comment by Goersch** [comment]
Du könntest das nicht auch direkt integrieren, so dass man den Umweg über die SID nicht gehen muss?

**Comment by alexreinert** [comment]
Können ja, die Frage ist nur, ob es Sinn macht. Auf den Seiten kann man jede Menge Dinge anstellen, welche nicht grade gut für die Stabilität des Systems sind. Das etwas zu verstecken, macht schon Sinn. Und man kann es sich ja auch mit minimalem Aufwand dauerhaft in der Systemsteuerung einblenden und muss dann auch nicht mehr manuell die sid anpassen.

**Comment by Goersch** [comment]
da bin ich bei Dir. Hab eben auch gesehen, dass die anderen Menüpunkte heikel sind.

Muss mir mal anschauen, wie ich das einblenden kann. Hab noch nicht verstanden, wie ich die ssh Verbindung zu debmatic öffne (hab aber auch noch nicht wirklich gesucht).

**Comment by alexreinert** [comment]
Einfach per Putty direkt auf die IP. Oder über  direkt angeschlossenen Monitor und Tastatur. Die CCU Software läuft direkt auf dem System und nicht innerhalb eines Containers.

**Comment by Goersch** [comment]
ah, OK, danke, das machts einfach
