### ISSUE TITLE
Illegal reflective access Warnings debmatic:amd64 3.51.6-45

### ISSUE THREAD

**Issue by Ayngush** [alexreinert/debmatic#128]
Hallo,

OS: Debian GNU/Linux 10 (buster) (als VM auf einen Proxmox-Server)

beim Retsart nach dem Update auf debmatic amd64 3.51.6-45 von Release 3.51.6-43 erscheinen folgende Warnings:

```
Jul 20 11:56:52 debmatic systemd[1]: Starting debmatic hmserver...
Jul 20 11:56:52 debmatic start_hmserver.sh[624]: Init Hardware Info
Jul 20 11:56:53 debmatic start_hmserver.sh[624]: WARNING: An illegal reflective access operation has occurred
Jul 20 11:56:53 debmatic start_hmserver.sh[624]: WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/opt/HMServer/HMIPServer.jar) to field java.nio.Buffer.address
Jul 20 11:56:53 debmatic start_hmserver.sh[624]: WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
Jul 20 11:56:53 debmatic start_hmserver.sh[624]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jul 20 11:56:53 debmatic start_hmserver.sh[624]: WARNING: All illegal access operations will be denied in a future release
```

Ich füge mal die daemon.log eines vollständigen Startups nach Reboot hier an.

[daemon.log](https://github.com/alexreinert/debmatic/files/4947030/daemon.log)

Schöne Grüße

**Comment by alexreinert** [comment]
Welche Java Version ist installiert?

**Comment by Ayngush** [comment]
Die, die ein Debian Buster installiert, wenn man Java installiert:

```
java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)
```

**Comment by alexreinert** [comment]
Der HMServer verwendet Java 8 oder 9 und nutzt da scheinbar Featutes, welche da ab Java 12 verboten sein werden und in Java 11 eine entsprechende Warning anzeigen.
Da der Close Source von eQ-3 ist, kann ich da leider nicht wirklich was machen, außer im deb Paket einen Konflikt mit Java 12 aufnehmen.

**Comment by Ayngush** [comment]
Das wäre sicherlich brauchbar, bevor etwas daran bricht. 
Allerdings müsste das jedoch auch "regelmäßig" geprüft werden, wann diese Sperre dann wieder herausgenommen werden kann.

Es gibt ja Anleitungen im Netz, wie man eine andere Java-Version unter Debain Buster vom AdoptOpenJDK Repository installiert, die müsste man dann entsprechend befolgen. 

Ich werde mich dann auch mal hinsetzen und auf openJDK 8 wechseln.

Vielen Dank für das ganze Projekt!
