### ISSUE TITLE
Installation innerhalb einer Docker Umgebung

### ISSUE THREAD

**Issue by DutchmanNL** [alexreinert/debmatic#13]
Danke Alex fuer deine source, super Arbeit und ich freue mich bereits über die Weiterentwicklung und bin sehr gespannt auf dan Punkt am horizon.

Eines meiner ziehe waehre es um die CCU native als adapter in iobroker zu integrieren.

Leider scheitere ich daran die source in einer Docker Umgebung zum laufen zu bekommen, native linux klappt super !

ist dies ein bekanntes problem oder eventuell noch Baustelle ? Ich würde die CCU gerne in einer docker Umgebung betreiben

**Comment by alexreinert** [comment]
Das ist keine Baustelle, Docker wird schlicht nicht unterstützt.

Hintergrund ist der, dass man spätestens für die Ansteuerung der Funkmodule spezielle Kernel Module benötigt und diese innerhalb eines Docker Containers nicht geladen werden können. Daher muss man das entweder auf Bare Metall machen oder innerhalb einer vollvirtualisierten VM.

**Comment by gamma** [comment]
Moin,

Ich habe auf der DS1515+ bereits erfolgreich Homebridge im Docker laufen und einen Hardware Dongel von Jeelink verbunden - Treiber/Kernel Module laufen auf der Syno.

Einen Dongel für HM habe ich auch und er steht als /dev/ttyACM0 zur Verfügung - kann also problemlos in den Container gelinkt werden.

Fehlt noch etwas an Voraussetzungen für ein Docker Image? Lauft die Kommunikation zum USB nicht auch quasi via Serial Protokoll?

**Comment by alexreinert** [comment]
Ich zitiere mich selbst:
> Hintergrund ist der, dass man spätestens für die Ansteuerung der Funkmodule spezielle Kernel Module benötigt und diese innerhalb eines Docker Containers nicht geladen werden können.

Mir wäre auch kein Dongle für HM bekannt, welches sich unter /dev/ttyACM0 meldet.

Es funktioniert aber angeblich einwandfrei, auf der Synology eine (vollvirtualisierte) VM mit debmatic und einem durchgereichten HB-RF-USB zu betreiben, mangels Synology konnte ich das selbst aber bisher nicht verifizieren.

**Comment by DutchmanNL** [comment]
> Ich zitiere mich selbst:
> Es funktioniert aber angeblich einwandfrei, auf der Synology eine (vollvirtualisierte) VM mit debmatic und einem durchgereichten HB-RF-USB zu betreiben, mangels Synology konnte ich das selbst aber bisher nicht verifizieren.

kan ich bestätigen, de Ressourcen. von einer Synology sind aber begrenzt...
Auch das mit dem docker. (und lxc) wie bereits erwähnt wegen den kernel Modulen unmöglich, daher separate vm oder native auf device x.

in einer vm läuft es aber wirklich. einwandfrei !!!

**Comment by clockwork6666** [comment]
nachdem ich sowieso nur die funk- und wired-gateways benutze, wär das in containerisiert trotzdem voll toll :(
wollte eigentlich langsam mal die ganzen ich-laufe-nur-für-einen-service-vms durch container ersetzen

**Comment by nicx** [comment]
Ich fände es auch klasse wenn die Abhängigkeit zu Hardware-USB-Funkmodulen bzw. deren Kernel-Module irgendwie optional in Debmatic eingebaut wäre, da ich ebenso nur LAN Gateways nutze und nur für Debmatic eine VM laufen lassen muss.

**Comment by DutchmanNL** [comment]
ich habe es jetzt im Proxmox lxc laufen

**Comment by nicx** [comment]
@DutchmanNL kannst du uns erklären was genau dazu notwendig ist? kann man das mit der docker lösung vergleichen? ich suche immer noch nach einer möglichkeit dematic o.ä. in docker zu betreiben.

**Comment by alexreinert** [comment]
Für Proxmox LXC gibt es hier im Repo doch bereits eine komplette Anleitung.

**Comment by nicx** [comment]
@alexreinert sorry, da hast du natürlich recht. danke für den hinweis.

eine optionale abhängigkeit für die funkmodule einzubauen ist nach wie vor nicht geplant?
