### ISSUE TITLE
raspi 2b - ubuntu 18.04 - HM-MOD-RPI-PCB not recognized

### ISSUE THREAD

**Issue by ferdinandhelmer** [alexreinert/debmatic#131]
Hallo,

ich habe leider Probleme, das HM-MOD-RPI-PCB zum Laufen zu bekommen. Die üblichen Schritte (debmatic Installation, Kernel-module etc.) scheinen geklappt zu haben. Die Bindung der Linux-Konsole an /dev/ttyAMA0 habe auch gemäß vieler Anleitungen entfernt.

debmatic-info liefert:

```
root@raspi:~# debmatic-info
debmatic version: 3.51.6-46
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
root@raspi:~#
```

wie kann ich die korrekt Kommunikation/Funktion des HM-MOD-RPI-PCB testen? Bzw. was kann hinter dem "Raw UART dev:   Not available" stecken?

Ich habe unter /etc/multimacd.conf:

Coprocessor Device Path = /dev/ttyAMA0

eingetragen, weil es mit dem /dev/raw-uart nicht ging (dieses device existiert nicht).

dmesg | grep AMA0 liefert:

root@raspi:~# dmesg |grep AMA0
[    3.731396] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2

also irgendetwas scheint dort zu sein :).

Vielen Dank fürs Anschauen!

**Comment by alexreinert** [comment]
Siehe https://github.com/alexreinert/debmatic#vorraussetzung-f%C3%BCr-hm-mod-rpi-pcb-und-rpi-rf-mod
Das direkte Aufstecken des Funkmoduls wird auf dem Raspberry mit Ubuntu aktuell nicht unterstützt, weil ich bisher einfach nicht dazu kam, die notwendigen Anpassungen am Device Tree Overlay von Raspbian auf Ubuntu zu portieren. Aktuelle Lösung: Raspbian nutzen oder Funkmodul per HB-RF-USB(-2) oder per HB-RF-ETH anschließen.

**Comment by ferdinandhelmer** [comment]
wow! Vielen Dank für die quasi instantane Antwort! Ich hatte die Anleitung nicht so verstanden, als ob es mit Ubuntu nicht funktioniert. Aber egal. Ich bin schon sehr erleichtert, dass es offenbar nichts spezielles mit meiner Hardware ist oder ein diffiziles individuelles Softwareproblem.

Gibt es eine realistische timeline, wann die Änderungen für Ubuntu kommen könnten?
Wenn nicht, wo im Code sind denn (grob) die Anpassungen zu machen oder ist das sehr verteilt? Ich  könnte dann auch versuchen, die Anpassungen vorzunehmen.
Andere Frage: Da ich ja das HM-MOD-RPI-PCB schon habe: Kann man das HB-RF-USB-2 irgendwo alleine ohne Funkmodul bestellen? Bei ELV habe ich es nur im Paket gefunden, das macht ja irgendwie keinen Sinn.

**Comment by alexreinert** [comment]
Ich habe eben ein Update für das Paket pivccu-modules-raspberrypi ins testing APT Repository geladen, mit welcher theoretisch eine Installation unter Ubuntu 20.04 64 Bit für den Raspbbery Pi möglich ist. Was allerdings noch fehlt ist die komplette Doku dafür (Die Abweichungen bei den Befehlen für die Anpassung der config.txt)

**Comment by boppbo** [comment]
@alexreinert Danke, scheint zu funktionieren. Habe gerade mein erstes Gerät mit dem Raspberry Pi 4 mit Ubuntu 20.04 arm64 angelernt. Nach den Änderungen musste ich einige Male rebooten bevor HMIP Hardware dann auch korrekt erkannt wurde. Zuvor sah es so aus:
debmatic version: 3.53.34-57
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  QEQ04 <removed>
 Radio MAC:     0x6D0 <removed>
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         n/a
 Radio MAC:     0x000000

**Installiert**
```
pivccu-modules-raspberrypi/testing,now 2.0-14 all [installed]
  Raspberry Pi kernel modules needed for Homematic
```

**Änderungen**
```
sudo cat /boot/firmware/usercfg.txt
# Place "config.txt" changes (dtparam, dtoverlay, disable_overscan, etc.) in
# this file. Please refer to the README file for a description of the various
# configuration files on the boot partition.
dtoverlay=disable-bt
```

```
sudo cat /boot/firmware/cmdline.txt
net.ifnames=0 dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
```

```
/etc/multimacd.conf:
Coprocessor Device Path = /dev/ttyAMA0
```

**Comment by alexreinert** [comment]
/dev/ttyAMA0 in der /dev/multimacd.conf ist falsch, es muss für den multimacd ein raw-uart verwendet werden. Ein normales tty kann einige ioctls nicht und hat eine massiv zu hohe Latenz.

Daher bitte dort die config verwenden, welche auch ausgeliefert wird.

Was die Komm-Störungen angeht: Der Raspberry Pi 4 erzeugt jede Menge Störstrahlung, vor allem, wenn die USB3 Ports, WLAN oder BT verwendet wird (aber auch ohne diese), welche insb HmIP mit dem Listen-Before-Talk massiv beeinträchtigt. Hier hilft nur ein Absetzen des Funkmoduls.

**Comment by boppbo** [comment]
Das Funkmodul wird jetzt auch mit der ausgelieferten Konfiguration erkannt. Ich war wohl bei den ersten Versuchen zu ungeduldig.

Die Störungen wirken sehr ungewöhnlich auf mich. Ich empfange sämtlichen Statusänderungen selbst in den entferntesten Räumen. Ein ausgesendeter Steuerbefehl führt jedoch direkt zur Komm-Störung. Das wirkt auf mich eher wie ein Defekt im Funkmodul oder kann es auf einen Fehler im Device-Tree hindeuten?

**Comment by alexreinert** [comment]
Fehler im Device Tree wird das nicht sein, die Kommunikation zwischen Raspi und Funkmodul klappt ja.

Externe Antenne macht es meistens schon etwas besser, aber wirklich gut wird es erst, wenn man das Funkmodul wirklich weiter weg bringt, weil auch der Funkchip selber unabhängig von der Antenne gestört wird.
Das kann ein Flachbandkabel sein oder aber die HB-RF-USB(-2) oder die HB-RF-ETH. Die Platinen haben noch den Vorteil, dass sie eine entstörte Spannung bereistellen.
