### ISSUE TITLE
debmatic.de (debian repo) down

### ISSUE THREAD

**Issue by heinemml** [alexreinert/debmatic#133]
From my Debian `apt update` I get:

```
Err:4 https://www.debmatic.de/debmatic stable InRelease                                      
  Could not connect to www.debmatic.de:443 (2a01:4f9:2a:da0:7::8), connection timed out Could not connect to www.debmatic.de:443 (95.216.13.95), connection timed out
```

I checked with `https://downforeveryoneorjustme.com/debmatic.de?proto=https&www=1` which also reports it as not reachable.

**Comment by alexreinert** [comment]
Seems that there were an issue with the provider. I could see some downtime in my monitoring, too. But right now, everything works fine.

**Comment by heinemml** [comment]
can confirm. seems to be reachable again.
