### ISSUE TITLE
How to get CCU HMID?

### ISSUE THREAD

**Issue by djusHa** [alexreinert/debmatic#135]
Good Morning,

for the script [FreqTest.ino](https://github.com/pa-pa/AskSinPP/blob/master/examples/FreqTest/FreqTest.ino) i need the HMID
from CCU.

How can i get it?

In "/etc/config/ids" there is a value but with four digits, which is not enough in my opinion, it must be six digits.
The value is "BidCoS-Address = 4386".

In "/var/ids", the Key "BidCoS-Address=" ist empty.

Can you help?

**Comment by alexreinert** [comment]
The file /var/ids has the default BidCos address of the currently attached radio module.
The file /etc/config/ids has the currently used BidCos address, which could different, mainly if you switch your radio modules.

In both files it could be formatted as decimal without any prefix and without leading zeros or as hex number with "0x" as prefix.

In your case, it is a decimal number, which could also be formatted as 0x001122, which look a little bit, like you have choosed manually.

**Comment by djusHa** [comment]
Thanks for explanation, Alex. Keep up the good work! 👍
