### ISSUE TITLE
DutyCycle LGW

### ISSUE THREAD

**Issue by Triton-KS** [alexreinert/debmatic#137]
Hallo,

ist es geplant auch beim Lan Gateway den DutyCycle darstellen zu lassen?
Gerade wenn man versucht die Geräte auf Gateways aufzuteilen ist es eine gute Erweiterung.

Danke

**Comment by alexreinert** [comment]
Das ist doch schon längst drin seitdem das auch in der Original CCU umgesetzt ist?!?

**Comment by Triton-KS** [comment]
Ok habe es bei RaspberryMatic gesehen wo ich das mal hatte.
Aber beim Debmatic wurde mir das nicht sichtbar angezeigt.
Muss ich da was einstellen?

**Comment by monotonus** [comment]
DutyCycle war bei mir gestern auch nicht nativ drin mit Neuinstallation. Hab es dann über Systemvariable und CuXD hinbekommen. Sollte das generell nativ drin sein?
