### ISSUE TITLE
debmatic (3.53.30-50) und HB-RF-ETH Probleme

### ISSUE THREAD

**Issue by Piri22** [alexreinert/debmatic#138]
Nachdem die Stable Version von dematic (3.51.6-46) zwar mit HB-RF-ETH stabil läuft aber die LED des Funkmoduls stur auf rot "hängen" bleibt, habe ich die Testingversion (3.53.30-50) ausprobiert. 
Was hier auffällt: das HB-RF-ETH Modul (Firmware 1.2.3) ist permanent dabei den Kontakt zu verlieren und ihn dann wieder aufzubauen. Eine stabile Verbindung kommt nicht zustande.

**Comment by alexreinert** [comment]
Welche Hardware wird verwendet? Host für debmatic, Netzteil vom HB-RF-ETH, Netzwerk (switch, etc.)

**Comment by Piri22** [comment]
Hier werkelt ein RPI 4 mit 8GB Speicher. Darauf installiert ist debmatic und IP-Symcon.
Als Switch setze ich einen TP-Link T2600G-28MPS PoE Switch ein, der sowohl den RPI, als auch das HB-RF-ETH Modul mit Saft versorgt. Dabei hängt vor dem RPI einPoE-Splitter, der 5.1V bei bis zu 4A liefert, das HB-RF-ETH Modul ist mit der PoE Option versehen.
Das ganze hängt hinter einer Fritzbox 6591 Cable.

**Comment by willi5** [comment]
Moin
Das gleiche Problem habe ich auch im Forum beschrieben. Ich weiß nicht ob Du es gelesen hast?
[https://homematic-forum.de/forum/viewtopic.php?f=81&t=61671](url)
[https://homematic-forum.de/forum/viewtopic.php?f=76&t=60150&p=614574#p614574](url)

Bei den Pingzeiten kann es kein Netzwerkproblem sein, zumal ich schon alles getauscht habe. 
Ein paar beruhigende Worte wären nicht schlecht.

Gruß Dieter
