### ISSUE TITLE
[Frage/idee] Möglichkeit ändern der Webports (80)

### ISSUE THREAD

**Issue by DutchmanNL** [alexreinert/debmatic#14]
Es währe schon wen man die Möglichkeit hätte den webport anders als standard 80 zu legen da auf dem 80ger port (vor allem bei VM ähnlichen Umgebungen) oft bereits andere Dienste darauf laufen.

**Comment by alexreinert** [comment]
Kein Problem, einfach die /etc/lighttpd/conf-available/20-debmatic.conf anpassen.
Einige externe Smarthome Lösungen können dann aber nicht mehr ohne Anpassung auf die CCU zugreifen, also dran denken, dass das ggf. auch dort umgestellt werden muss.

**Comment by DutchmanNL** [comment]
> Kein Problem, einfach die /etc/lighttpd/conf-available/20-debmatic.conf anpassen.

super, vielen dank!
