### ISSUE TITLE
 PreDepends: wait-sysfs-notify but it is not installable

### ISSUE THREAD

**Issue by red81-x** [alexreinert/debmatic#140]
Hello,
i getting a error at installing debmatic, can someone help?
```
pi@raspberrypi:~ $ sudo apt install debmatic
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 debmatic : PreDepends: wait-sysfs-notify but it is not installable
E: Unable to correct problems, you have held broken packages.
```
RPi 3+
Raspberry Pi OS Lite (32bit) (buster based, 2020-08-20) installed with RPi Imager v1.4, fresh installation
did update & upgrade, then followed the install manual

Many Thanks

**Comment by bug84** [comment]
same problem

**Comment by gesslein** [comment]
This package is currently missing in the stable repository. I'm sure @alexreinert has that fixed in no time, but meanwhile here are the download URLs to the missing package available via testing, run `dpkg-architecture` if you are not sure which one your system needs,  `wget <url>; dpkg -i wait-sysfs-notify-....deb`

```
https://www.debmatic.de/debmatic/pool/main/w/wait-sysfs-notify/wait-sysfs-notify-1.0-1-amd64.deb
https://www.debmatic.de/debmatic/pool/main/w/wait-sysfs-notify/wait-sysfs-notify-1.0-1-arm64.deb
https://www.debmatic.de/debmatic/pool/main/w/wait-sysfs-notify/wait-sysfs-notify-1.0-1-armhf.deb
https://www.debmatic.de/debmatic/pool/main/w/wait-sysfs-notify/wait-sysfs-notify-1.0-1-i386.deb
```

**Comment by alexreinert** [comment]
The package was not correctly copied to the stable repository. I just fixed that, please retry with `apt update` and `apt upgrade`.

**Comment by red81-x** [comment]
looks like it works now. thank you very much!
