### ISSUE TITLE
Update auf 3.53.30-50 - The following packages have been kept back

### ISSUE THREAD

**Issue by Scrounger** [alexreinert/debmatic#141]
Hi @alexreinert 

wollte heute auf die v3.53.30-50 updaten und bekomme die Meldung "The following packages have been kept back":

![grafik](https://user-images.githubusercontent.com/6370451/94675888-bd9abd80-031a-11eb-8ec3-92e5c02766f8.png)

Das ganze läuft auf einem Intel Nuc, debmatic als LXC, Installation laut deiner Anleitung erfolgt:
https://github.com/alexreinert/debmatic/blob/master/docs/setup/proxmox.md

Verwendet wird dein USB Modul.

**Comment by bug84** [comment]
selbes problem

**Comment by soccer0176** [comment]
Schließe mich an ... 

Aktuelles System: Debian 10 buster auf VMWare ESXi 6.7

**Comment by gesslein** [comment]
Same reason as #140 where I describe a workaround, install the missing package first then the upgrade will work.

**Comment by soccer0176** [comment]
> 
> 
> Same reason as #140 where I describe a workaround, install the missing package first then the upgrade will work.

worked fine ... thx

**Comment by alexreinert** [comment]
Ein Paket wurde leider nicht korrekt in das stable Repository übernommen. Ich habe das grade gefixt, bitte neu mit `apt update` und `apt upgrade` probieren

**Comment by smooty1970** [comment]
Hallo.

Soeben versucht.... folgende Meldung:
![1](https://user-images.githubusercontent.com/17856075/94788761-59d4cb00-03d4-11eb-891f-c1794f347c71.PNG)

**Comment by alexreinert** [comment]
Klassisches Problem, wenn man apt-get und nicht das empfohlene apt verwendet, dann werden Pakete zurückgehalten, wenn zusätzliche Abhängigkeiten dazu kommen. Daher bitte apt verwenden.

**Comment by smooty1970** [comment]
sorry - mein Fehler - nun geht es.... THX

**Comment by Scrounger** [comment]
Funktioniert bei mir auch wieder, danke!
