### ISSUE TITLE
Funkmodul wird nach Update auf 3.53.30-50 nicht mehr erkannt

### ISSUE THREAD

**Issue by chris3b** [alexreinert/debmatic#143]
Nach dem heutigen Update des Promox Host und LXC Container wird das Funkmodul nicht mehr erkannt.
Folgende Pakete sind auf dem Host installiert:
pve-headers    6.2-2
pivccu-modules-dkms 1.0.45
debmatic-lxc-host 1.0.3

Auf dem LXC Container:
debmatic       3.53.30-50

debmatic-info gibt:
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

Ich finde unter /dev kein ttyUSB* jedoch raw-uart und nach einer Weile raw-uart1

dmesg liefert:
[  588.633484] usb 1-10: new full-speed USB device number 2 using xhci_hcd
[  588.787967] usb 1-10: New USB device found, idVendor=0403, idProduct=6f70, bcdDevice= 6.00
[  588.787972] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  588.787974] usb 1-10: Product: HB-RF-USB
[  588.787975] usb 1-10: Manufacturer: Alexander Reinert
[  588.787976] usb 1-10: SerialNumber: A95ALS3S
[  588.800535] usb 1-10: Found HB-RF-USB at usb-0000:00:14.0-10
[  588.861949] usbcore: registered new interface driver hb_rf_usb
...
[  656.958210] raw-uart raw-uart: Reset radio module
[  668.149992] raw-uart raw-uart1: Reset radio module
[  668.149997] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  668.257716] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  668.284608] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  671.284549] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  672.284578] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  673.987787] raw-uart raw-uart: Reset radio module
[  675.284629] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  676.284771] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  679.284821] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  679.284896] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  685.166104] raw-uart raw-uart1: Reset radio module
[  685.166108] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  685.273257] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  685.299778] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  688.299697] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  689.299849] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  692.299888] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  693.300032] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  696.300066] hb-rf-eth hb-rf-eth: Error sending packet, not connected
[  696.300137] hb-rf-eth hb-rf-eth: Error sending packet, not connected

Habe ich etwas übersehen?

**Comment by kleinischer** [comment]
Hallo,

genau das selbe bei mir.
Raspberry Pi 4 mit HB-RF-USB-2 und RPI-RF-MOD: Es wird kein Funkmodul erkannt :-(

LG
Dirk

**Comment by kleinischer** [comment]
Nachtrag: Es liegt definitiv an Debmatic :-(
Ich habe das Funkmodul RPI-RF-MOD mit HB-RF-USB-2 soeben auf dem selben Pi4 mit RaspberryMatic getestet: Geht sofort. Debmatic hingegen will leider seit dieser Version die Hardware nicht mehr erkennen.

LG
Dirk

**Comment by alexreinert** [comment]
@chris3b Ich konnte dein Problem reproduzieren und bring kurzfristig einen Bugfix raus.

@kleinischer Dein Problem ist definitiv etwas anderes. Kannst du bitte einen neuen Issue aufmachen und dabei auch die Ausgabe von `sudo pivccu-info` angeben?

**Comment by kleinischer** [comment]
Hallo Alex,

zuerst einmal vielen dank für die schnelle Reaktion. Gerne mache ich einen neuen Issue auf. ABER:
Ich denke es ist das gleiche Problem. Die Ausgabe von sudo debmatic-info und auch der anderen Ausgaben ist identisch mit der von chris3b.
Eine SD-Karte mit RaspberryMatic Image eingesetzt und es geht.

LG
Dirk

**Comment by alexreinert** [comment]
@chris3b Ich habe ein aktualisiertes Paket für den Host bereitgestellt, welches das Problem lösen sollte.
Nach der Installation müsste der Host aber einmal neu gestartet werden.

**Comment by chris3b** [comment]
@alexreinert Ich habe debmatic-lxc-host auf 1.0.4 aktualisiert. Leider wird das Funkmodul immer noch nicht erkannt. Erstmal vielen Dank für die schnelle Rückmeldung. Brauchst du weitere Informationen?

**Comment by alexreinert** [comment]
Hast du den kompletten Host neu gestartet?
Ansonsten bitte nochmal das gleiche, was du Eingangs bereits gepostet hast.

**Comment by chris3b** [comment]
Ein Reboot des gesamten Systems, danach einmal Shutdown des gesamten Systems.

**Host**
pve-headers    6.2-2
pivccu-modules-dkms 1.0.45
debmatic-lxc-host 1.0.4

@pve:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0403:6f70 Future Technology Devices International, Ltd HB-RF-USB
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

@pve:/dev$ ls -ll
crw-------  1 root root    240,     0 Oct  6 19:29 raw-uart
Kein ttyUSB*

@pve:/dev$ dmesg
...
[    1.744330] usb 1-10: new full-speed USB device number 2 using xhci_hcd
...
[    1.903739] usb 1-10: New USB device found, idVendor=0403, idProduct=6f70, bcdDevice= 6.00
[    1.904057] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.904372] usb 1-10: Product: HB-RF-USB
[    1.904671] usb 1-10: Manufacturer: Alexander Reinert
[    1.904980] usb 1-10: SerialNumber: A95ALS3S
...
[   12.725709] usb 1-10: Found HB-RF-USB at usb-0000:00:14.0-10
...
[   12.784533] usbcore: registered new interface driver hb_rf_usb


**LXC**
debmatic       3.53.30-50

@debmatic:/dev# debmatic-info
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
 
@debmatic:/dev# cat /var/hm_mode
HM_HOST='DEBMATIC'
HM_HOST_RAW_UART=''
HM_HOST_GPIO_UART=''
HM_HOST_UART_DEVICE_TYPE=''
HM_HOST_GPIO_RESET=''
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_RTC=''
HM_MODE='NORMAL'
HM_HMRF_DEVNODE=''
HM_HMIP_DEVNODE=''
HM_HMRF_DEV=''
HM_HMIP_DEV=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMIP_SGTIN=''
HM_HMIP_SERIAL=''
HM_HMIP_VERSION=''
HM_HMIP_ADDRESS=''

@debmatic:/dev# ls -ll
crw-r--r-- 1 root root 240, 0 Oct  6 19:32 raw-uart
Kein ttyUSB*

Kurze Frage zu raw-uart auf dem Host: "crw-------  1 root root" als Berechtigungen ist korrekt so?

**Comment by chris3b** [comment]
Ich habe der Installationsanleitung folgend, alle aktuellen Pakete nochmal auf einem zweiten, frischen Proxmox Host installiert und das Funkmodul angeschlossen. Leider mit dem gleichen Ergebnis.
Würde ein manueller downgrade mit apt-get install --reinstall abc=1.0.0 helfen?

**Comment by alexreinert** [comment]
Ich habe im testing APT Repository eine neue Version des Tools für die Funkmodulerkennung eingespielt. Bitte mal testen, ob es damit jetzt läuft.

**Comment by chris3b** [comment]
Leider auch kein Erfolg:

@debmatic:/dev# debmatic-info
debmatic version: 3.53.30-53
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

dmesg:
[    1.724175] usb 1-10: new full-speed USB   device number 2 using xhci_hcd
[      1.878350] usb 1-10: New USB device found, idVendor=0403,   idProduct=6f70, bcdDevice= 6.00
[      1.878678] usb 1-10: New USB device strings: Mfr=1, Product=2,   SerialNumber=3
[      1.878961] usb 1-10: Product: HB-RF-USB
[      1.879241] usb 1-10: Manufacturer: Alexander Reinert
[      1.879520] usb 1-10: SerialNumber: A95ALS3S
[     12.644380] usb 1-10: Found HB-RF-USB at usb-0000:00:14.0-10
[     12.711057] usbcore: registered new interface driver hb_rf_usb

System wurde komplett neugestartet.

**Comment by kleinischer** [comment]
Leider kein Erfolg :-(
Ich habe es jetzt aber aufgegeben und gehe einen anderen Weg. Aber vielen vielen Dank Alex für deine Mühe :-)

LG
Dirk

**Comment by chris3b** [comment]
Oct 17 12:20:10 debmatic postfix/postfix-script[1653]: refreshing the Postfix mail system
Oct 17 12:20:10 debmatic postfix/master[484]: reload -- version 3.4.14, configuration /etc/postfix
Oct 17 12:25:44 debmatic systemd[1]: debmatic-startupfinished.service: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped debmatic startup finished.
Oct 17 12:25:44 debmatic systemd[1]: debmatic-updaterffirmware.service: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped debmatic update rf firmware.
Oct 17 12:25:44 debmatic systemd[1]: Stopped target Timers.
Oct 17 12:25:44 debmatic systemd[1]: systemd-tmpfiles-clean.timer: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped Daily Cleanup of Temporary Directories.
Oct 17 12:25:44 debmatic systemd[1]: apt-daily-upgrade.timer: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped Daily apt upgrade and clean activities.
Oct 17 12:25:44 debmatic systemd[1]: apt-daily.timer: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped Daily apt download activities.
Oct 17 12:25:44 debmatic systemd[1]: Stopping debmatic rega...
Oct 17 12:25:44 debmatic systemd[1]: debmatic-updatelgwkey.service: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped debmatic update lgw key.
Oct 17 12:25:44 debmatic systemd[1]: debmatic-updatelgwfirmware.service: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped debmatic update lgw firmware.
Oct 17 12:25:44 debmatic systemd[1]: Stopped target Graphical Interface.
Oct 17 12:25:44 debmatic systemd[1]: Reached target Unmount All Filesystems.
Oct 17 12:25:44 debmatic systemd[1]: Stopping debmatic eq3configd...
Oct 17 12:25:44 debmatic systemd[1]: logrotate.timer: Succeeded.
Oct 17 12:25:44 debmatic systemd[1]: Stopped Daily rotation of log files.
Oct 17 12:25:44 debmatic systemd[1]: Stopped target Multi-User System.
**Oct 17 12:25:55 debmatic systemd-sysctl[88]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Read-only file system
Oct 17 12:25:55 debmatic systemd-sysctl[88]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: Read-only file system**
Oct 17 12:25:55 debmatic systemd[1]: Starting Flush Journal to Persistent Storage...
Oct 17 12:25:55 debmatic systemd[1]: Started Create Static Device Nodes in /dev.
Oct 17 12:25:55 debmatic systemd[1]: Reached target Local File Systems (Pre).
Oct 17 12:25:55 debmatic systemd[1]: Reached target Local File Systems.
Oct 17 12:25:55 debmatic systemd[1]: Starting Raise network interfaces...
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in udev Kernel Device Manager being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Started Flush Journal to Persistent Storage.
Oct 17 12:25:55 debmatic systemd[1]: Starting Create Volatile Files and Directories...
Oct 17 12:25:55 debmatic systemd[1]: Started Create Volatile Files and Directories.
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in Network Time Synchronization being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Reached target System Time Synchronized.
Oct 17 12:25:55 debmatic systemd[1]: Starting Update UTMP about System Boot/Shutdown...
Oct 17 12:25:55 debmatic systemd[1]: Started Update UTMP about System Boot/Shutdown.
Oct 17 12:25:55 debmatic systemd[1]: Reached target System Initialization.
Oct 17 12:25:55 debmatic systemd[1]: Started Daily man-db regeneration.
Oct 17 12:25:55 debmatic systemd[1]: Listening on D-Bus System Message Bus Socket.
Oct 17 12:25:55 debmatic systemd[1]: Reached target Sockets.
Oct 17 12:25:55 debmatic systemd[1]: Reached target Basic System.
Oct 17 12:25:55 debmatic systemd[1]: Started Regular background program processing daemon.
Oct 17 12:25:55 debmatic systemd[1]: Starting System Logging Service...
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in getty on tty2-tty6 if dbus and logind are not available being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Starting Login Service...
Oct 17 12:25:55 debmatic systemd[1]: Started D-Bus System Message Bus.
Oct 17 12:25:55 debmatic cron[138]: (CRON) INFO (pidfile fd = 3)
Oct 17 12:25:55 debmatic cron[138]: (CRON) INFO (Running @reboot jobs)
Oct 17 12:25:55 debmatic systemd[1]: Starting piVCCU DKMS Modules...
Oct 17 12:25:55 debmatic systemd[1]: Started Daily rotation of log files.
Oct 17 12:25:55 debmatic systemd[1]: Started Daily apt download activities.
Oct 17 12:25:55 debmatic systemd[1]: Started Daily apt upgrade and clean activities.
Oct 17 12:25:55 debmatic systemd[1]: Started Daily Cleanup of Temporary Directories.
Oct 17 12:25:55 debmatic systemd[1]: Started System Logging Service.
Oct 17 12:25:55 debmatic rsyslogd: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.1901.0]
Oct 17 12:25:55 debmatic rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="139" x-info="https://www.rsyslog.com"] start
Oct 17 12:25:55 debmatic systemd[1]: Started Login Service.
Oct 17 12:25:55 debmatic systemd[1]: Started Raise network interfaces.
Oct 17 12:25:55 debmatic systemd[1]: Reached target Network.
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in fast remote file copy program daemon being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Starting Permit User Sessions...
Oct 17 12:25:55 debmatic systemd[1]: Reached target Network is Online.
Oct 17 12:25:55 debmatic systemd[1]: Starting Postfix Mail Transport Agent (instance -)...
Oct 17 12:25:55 debmatic systemd[1]: Starting Lighttpd Daemon...
Oct 17 12:25:55 debmatic systemd[1]: Starting OpenBSD Secure Shell server...
Oct 17 12:25:55 debmatic systemd[1]: Started Permit User Sessions.
Oct 17 12:25:55 debmatic systemd[1]: Condition check resulted in Container Getty on /dev/tty0 being skipped.
Oct 17 12:25:55 debmatic systemd[1]: Started Container Getty on /dev/tty1.
Oct 17 12:25:55 debmatic systemd[1]: Started Container Getty on /dev/tty2.
Oct 17 12:25:55 debmatic systemd[1]: Started Console Getty.
Oct 17 12:25:55 debmatic systemd[1]: Reached target Login Prompts.
Oct 17 12:25:55 debmatic systemd[1]: Started OpenBSD Secure Shell server.
Oct 17 12:25:55 debmatic systemd[1]: Started Lighttpd Daemon.
Oct 17 12:25:55 debmatic ensure_modules.sh[143]: Error! Your kernel headers for kernel 5.4.65-1-pve cannot be found.
Oct 17 12:25:55 debmatic ensure_modules.sh[143]: Please install the linux-headers-5.4.65-1-pve package,
Oct 17 12:25:55 debmatic ensure_modules.sh[143]: or use the --kernelsourcedir option to tell DKMS where it's located
Oct 17 12:25:55 debmatic postfix/postfix-script[442]: warning: symlink leaves directory: /etc/postfix/./makedefs.out
Oct 17 12:25:55 debmatic postfix/postfix-script[482]: starting the Postfix mail system
Oct 17 12:25:55 debmatic postfix/master[484]: daemon started -- version 3.4.14, configuration /etc/postfix
Oct 17 12:25:55 debmatic systemd[1]: Started Postfix Mail Transport Agent (instance -).
Oct 17 12:25:55 debmatic systemd[1]: Starting Postfix Mail Transport Agent...
Oct 17 12:25:55 debmatic systemd[1]: Started Postfix Mail Transport Agent.
Oct 17 12:26:03 debmatic systemd[1]: pivccu-dkms.service: Succeeded.
Oct 17 12:26:03 debmatic systemd[1]: Started piVCCU DKMS Modules.
Oct 17 12:26:03 debmatic systemd[1]: Starting debmatic...
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic.
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic ssdpd...
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic update rf firmware...
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic prepare InterfacesList.xml...
Oct 17 12:26:22 debmatic systemd[1]: Reached target Multi-User System.
Oct 17 12:26:22 debmatic systemd[1]: Reached target Graphical Interface.
Oct 17 12:26:22 debmatic systemd[1]: Starting Update UTMP about System Runlevel Changes...
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic HssLED...
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic eq3configd...
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic update rf firmware.
Oct 17 12:26:22 debmatic systemd[1]: Condition check resulted in debmatic multimacd being skipped.
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic ssdpd.
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic eq3configd.
Oct 17 12:26:22 debmatic systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
Oct 17 12:26:22 debmatic systemd[1]: Started Update UTMP about System Runlevel Changes.
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic HssLED.
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic prepare InterfacesList.xml.
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic lighttpd...
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic update lgw firmware...
Oct 17 12:26:22 debmatic lighttpd[969]: (server.c.1464) server started (lighttpd/1.4.53)
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic update lgw firmware.
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic lighttpd.
Oct 17 12:26:22 debmatic systemd[1]: Condition check resulted in debmatic hs485d being skipped.
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic update lgw key...
Oct 17 12:26:22 debmatic update_lgw_key.sh[970]: ls: Zugriff auf '/etc/config/*.keychange' nicht möglich: Datei oder Verzeichnis nicht gefunden
Oct 17 12:26:22 debmatic systemd[1]: Started debmatic update lgw key.
Oct 17 12:26:22 debmatic systemd[1]: Condition check resulted in debmatic rfd being skipped.
Oct 17 12:26:22 debmatic systemd[1]: Starting debmatic hmserver...
Oct 17 12:26:22 debmatic start_hmserver.sh[972]: Init Hardware Info
**Oct 17 12:26:22 debmatic start_hmserver.sh[972]: WARNING: An illegal reflective access operation has occurred
Oct 17 12:26:22 debmatic start_hmserver.sh[972]: WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/opt/HMServer/HMServer.jar) to field java.nio.Buffer.address
Oct 17 12:26:22 debmatic start_hmserver.sh[972]: WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
Oct 17 12:26:22 debmatic start_hmserver.sh[972]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Oct 17 12:26:22 debmatic start_hmserver.sh[972]: WARNING: All illegal access operations will be denied in a future release**
Oct 17 12:26:26 debmatic systemd[1]: Started debmatic hmserver.
Oct 17 12:26:26 debmatic systemd[1]: Starting debmatic rega...
Oct 17 12:26:26 debmatic systemd[1]: Started debmatic rega.
Oct 17 12:26:26 debmatic systemd[1]: Starting debmatic startup finished...
Oct 17 12:26:26 debmatic systemd[1]: Started debmatic startup finished.
Oct 17 12:26:26 debmatic systemd[1]: Condition check resulted in debmatic Monitor HB-RF-ETH being skipped.
Oct 17 12:26:26 debmatic systemd[1]: Condition check resulted in debmatic set interface clock timer being skipped.
Oct 17 12:26:26 debmatic systemd[1]: Reached target Timers.
Oct 17 12:26:26 debmatic systemd[1]: Startup finished in 31.651s.
Oct 17 12:26:26 debmatic start_rega.sh[1015]: successfully loaded "/etc/config/homematic.regadom"
Oct 17 12:26:26 debmatic start_rega.sh[1015]: Load interfaces from file
Oct 17 12:26:26 debmatic start_rega.sh[1015]: HTTP server started successfully (6 workers)
Oct 17 12:26:26 debmatic start_rega.sh[1015]: Waiting for child to finish
Oct 17 12:26:26 debmatic start_rega.sh[1015]: Executing /bin/hm_startup in child 1027
Oct 17 12:26:33 debmatic ReGaHss: WARNING: XMLRPC 'getValue': empty interface URL (interface: 1007, params: {"OEQ0022562:2","ENERGY_COUNTER"}) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0022562:2","ENERGY_COUNTER"}) [CallGetValue():iseXmlRpc.cpp:1435]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Oct 17 12:26:33 debmatic ReGaHss: WARNING: XMLRPC 'getValue': empty interface URL (interface: 1007, params: {"OEQ0022646:2","ENERGY_COUNTER"}) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0022646:2","ENERGY_COUNTER"}) [CallGetValue():iseXmlRpc.cpp:1435]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Oct 17 12:26:33 debmatic ReGaHss: WARNING: XMLRPC 'getValue': empty interface URL (interface: 1007, params: {"NEQ1558755:2","ENERGY_COUNTER"}) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"NEQ1558755:2","ENERGY_COUNTER"}) [CallGetValue():iseXmlRpc.cpp:1435]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Oct 17 12:26:33 debmatic ReGaHss: WARNING: XMLRPC 'getValue': empty interface URL (interface: 1007, params: {"OEQ0022646:2","POWER"}) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0022646:2","POWER"}) [CallGetValue():iseXmlRpc.cpp:1435]
Oct 17 12:26:33 debmatic ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]


Die oberen fett markierten Zeilen machen mich stutzig. Auf dem Host meldet er jedoch:
cat /proc/version
Linux version 5.4.65-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200)

dpkg -l pve-headers*
||/ Name                     Version      Architecture Description
+++-========================-============-============-=================================
ii  pve-headers              6.2-2        all          Default Proxmox VE Kernel Headers
ii  pve-headers-5.4          6.2-7        all          Latest Proxmox VE Kernel Headers
ii  pve-headers-5.4.65-1-pve 5.4.65-1     amd64        The Proxmox PVE Kernel Headers

Die Header sollten also installiert sein.

**Comment by MikeRoxx** [comment]
Hallo,

bei mir sieht es genauso aus wie bei Chris unter Proxmox 6.2-15

Gruß
Mike

**Comment by chris3b** [comment]
Hallo Alex,
der LXC-Snapshot mit 3.51.6-43 läuft noch, auch mit aktuellen Host Paketen
Das neuste Container Update mochte leider immer noch nicht. Kann ich noch irgendwie helfen?
VG
Chris

**Comment by alexreinert** [comment]
Innerhalb des Container soll das Paket pivccu-modules-dkms nicht installiert sein, das braucht es nur auf dem Host (Bei Verwendung von Containern, bei VMs ist es grade andersrum).

Eine Möglichkeit das noch etwas weiter zu debuggen: Auf dem Host das Paket detect-radio-module mit apt installieren. Container beenden, dann den Befehl `detect_radio_module /dev/raw-uart` aufrufen.

**Comment by chris3b** [comment]
Danke Alex!

debmatic version: **3.53.34-55**
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:00:14.0-10 (/dev/raw-uart)
 Board serial:  58A992F101
 Radio MAC:     0xFFF101
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A992F101
 Radio MAC:     0xBDBB31
