### ISSUE TITLE
System-Sicherheitsschlüssel kann nicht gesetzt werden.

### ISSUE THREAD

**Issue by Thuffir** [alexreinert/debmatic#144]
Hallo, ich versuche den System-Sicherheitsschlüssel nachträglich zu setzen. Es sind diverse Komponente bereits angelernt.
Allerdings bekomme ich immer die Meldung:

    Sicherheitsschlüssel setzen - Fehler
    Der Schlüssel konnte nicht gesetzt werden. Informationen dazu finden Sie in den Servicemeldungen.

Die Servicemeldungen sind aber leider leer.

```
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         (entfernt)
 Radio MAC:     (entfernt)

Linux rpi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

Mache ich vielleicht grundsätzlich was falsch?

**Comment by alexreinert** [comment]
Ein Sicherheitsschlüssel ist nur für BidCos (aka HmRF) zutreffend. Bei HmIP wird die Verschlüsselung mit Geräte spezifischen Keys (SGTIN und Key) durchgeführt und kann nicht geändert werden.

**Comment by Thuffir** [comment]
Super! Vielen dank für die schnelle Antwort.
