### ISSUE TITLE
Frage: Debmatic und CCU ports interface bindings

### ISSUE THREAD

**Issue by Thuffir** [alexreinert/debmatic#145]
Bei mir läuft debmatic und fhem auf die gleiche Maschine. Nun möchte ich die offene CCU Steuerports auf localhost begrenzen.
Gibt es eine einfache Möglichkeit dies irgendwo einzustellen (interface binding o.Ä.) oder muss ich zwangsweise Firewall regeln erstellen?

**Comment by alexreinert** [comment]
Aktuell gibt es da noch keine eingebaute Möglichkeit für, u.A. weil das in den Binaries von eQ-3 bisher noch nicht vorgesehen ist.

**Comment by Thuffir** [comment]
Danke
