### ISSUE TITLE
Funkmodul RPI-RF-MOD auf HB-RF-USB-2 wird nicht erkannt

### ISSUE THREAD

**Issue by kleinischer** [alexreinert/debmatic#146]
Hallo Alex,

wie gewünscht ein neues Issue...
Debmatic 3.53.30-50 installiert.
Einzigste Änderung ist der HTTP Port von 80 auf 8100 (in webui.conf und lighttpd.conf).
Allerdings wird das Funkmodul RPI-RF-MOD auf HB-RF-USB-2 nicht erkannt. Es können daher keine Geräte angelernt werden.
Wenn ich in den selben Pi4 eine SD-Karte mit RaspberryMatic Image stecke, geht es direkt. Das Funkmodul wird korrekt erkannt und funktioniert.

debmatic-info:
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev: Available
HMRF Hardware: unknown
Board serial: unknown
Radio MAC: unknown
HMIP Hardware: unknown
SGTIN: unknown
Radio MAC: unknown

/dev:
kein ttyUSB* (Fehlt!)
raw-uart ist vorhanden.

LG
Dirk

**Comment by kleinischer** [comment]
Nachtrag:
So wurde installiert:

$ wget -q -O - https://www.debmatic.de/debmatic/public.key | sudo apt-key add -
$ sudo bash -c 'echo "deb https://www.debmatic.de/debmatic stable main" > /etc/apt/sources.list.d/debmatic.list'
$ sudo apt update
$ sudo apt install build-essential bison flex libssl-dev
$ sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms
$ sudo reboot
$ sudo apt install debmatic
$ sudo reboot

**Comment by alexreinert** [comment]
Was liefert lsusb?

**Comment by alexreinert** [comment]
Welchen Inhalt hat die Datei /var/hm_mode?

**Comment by kleinischer** [comment]
lsusb:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 10c4:8c07 Cygnal Integrated Products, Inc. 
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

/var/hm_mode
HM_HOST='DEBMATIC'
HM_HOST_RAW_UART=''
HM_HOST_GPIO_UART=''
HM_HOST_UART_DEVICE_TYPE=''
HM_HOST_GPIO_RESET=''
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_RTC=''
HM_MODE='NORMAL'
HM_HMRF_DEVNODE=''
HM_HMIP_DEVNODE=''
HM_HMRF_DEV=''
HM_HMIP_DEV=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMIP_SGTIN=''
HM_HMIP_SERIAL=''
HM_HMIP_VERSION=''
HM_HMIP_ADDRESS=''

LG
Dirk

**Comment by alexreinert** [comment]
Und weil du im andere  Issue von identischen Fehlern sprichst: Sind bei dmesg auch die Einträge vom hb-rf-eth drin?

**Comment by kleinischer** [comment]
Natürlich in meinem Fall HB-RF-USB-2 ;-)

Auszug, als Anhang auch komplett...
[    0.128766] usbcore: registered new interface driver usbfs
[    0.128863] usbcore: registered new interface driver hub
[    0.128993] usbcore: registered new device driver usb
[    1.121565] usbcore: registered new interface driver r8152
[    1.121644] usbcore: registered new interface driver lan78xx
[    1.121726] usbcore: registered new interface driver smsc95xx
[    1.122144] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    1.122192] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    1.124535] xhci_hcd 0000:01:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000001000000890
[    1.125772] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    1.125809] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.125842] usb usb1: Product: xHCI Host Controller
[    1.125869] usb usb1: Manufacturer: Linux 5.4.51-v7l+ xhci-hcd
[    1.125896] usb usb1: SerialNumber: 0000:01:00.0
[    1.126490] hub 1-0:1.0: USB hub found
[    1.126594] hub 1-0:1.0: 1 port detected
[    1.127133] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    1.127173] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    1.127213] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    1.127668] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.04
[    1.127704] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.127736] usb usb2: Product: xHCI Host Controller
[    1.127762] usb usb2: Manufacturer: Linux 5.4.51-v7l+ xhci-hcd
[    1.127789] usb usb2: SerialNumber: 0000:01:00.0
[    1.128343] hub 2-0:1.0: USB hub found
[    1.128440] hub 2-0:1.0: 4 ports detected
[    1.130683] usbcore: registered new interface driver uas
[    1.130800] usbcore: registered new interface driver usb-storage
[    1.140892] usbcore: registered new interface driver usbhid
[    1.140918] usbhid: USB HID core driver
[    1.490521] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    1.673128] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    1.673171] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    1.673201] usb 1-1: Product: USB2.0 Hub
[    1.675058] hub 1-1:1.0: USB hub found
[    1.675374] hub 1-1:1.0: 4 ports detected
[    2.020545] usb 1-1.4: new full-speed USB device number 3 using xhci_hcd
[    2.023900] systemd[1]: Set hostname to <raspberrypi>.
[    2.158137] usb 1-1.4: New USB device found, idVendor=10c4, idProduct=8c07, bcdDevice= 1.01
[    2.158194] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.158230] usb 1-1.4: Product: HB-RF-USB-2
[    2.158258] usb 1-1.4: Manufacturer: Alexander Reinert
[    2.158285] usb 1-1.4: SerialNumber: 9eca23a43d32ea11b7971576472be6b9
[    4.892071] usb 1-1.4: Found HB-RF-USB-2 at usb-0000:01:00.0-1.4
[    4.901215] usbcore: registered new interface driver hb_rf_usb_2
[    4.945689] usbcore: registered new interface driver brcmfmac

[dmesg.txt](https://github.com/alexreinert/debmatic/files/5329269/dmesg.txt)

**Comment by alexreinert** [comment]
Also soch nicht identische Fehlermeldungen. ;-)

Welches OS setzt du genau ein?

**Comment by kleinischer** [comment]
Hätte "gedacht", das passt zusammen, weil bei dieser Version die Funkmodule nicht erkannt werden :-(
Anbei die Daten. Wenn du noch etwas brauchst, stehe ich natürlich zur Verfügung.

Raspberry Pi OS (32-bit) Lite auf einem Pi4 mit 4MByte

hostnamectl
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.4.51-v7l+

uname -a
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
vcgencmd version
Sep  2 2020 21:13:13 
Copyright (c) 2012 Broadcom
version 4439d2aaa6c376a2d1ef4402f142e1cf4de37c43 (clean) (release) (start)

Aktuell laufen auf dem Pi:
* RPI-Monitor
* SMB (Samba) Server
* Webserver (apache, php, mysql...)
* DLNA Server
+ debmatic (leider ohne Funktion)

LG
Dirk

**Comment by kleinischer** [comment]
RE:> Also soch nicht identische Fehlermeldungen. ;-)
Da hast du sicher Recht, denn ein apt update/upgrade (bzgl Issue #143) auf die neue Version bringt keine Besserung...

LG
Dirk

**Comment by Hooch76** [comment]
Ich vermute, dass ich das gleiche Problem habe ... 
dematic heute auf folgendem System installiert (Intel(R) Celeron(R) CPU J3355 @ 2.00GHz) mit HB-RF-USB-2 und RPI-RF-MOD.

**cat /etc/os-release**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian

Ich bin nach folgender Anleitung vorgegangen: https://github.com/alexreinert/debmatic/blob/master/docs/setup/otheros.md

**debmatic-info:**
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

Unter /dev kein ttyUSB* jedoch /dev/raw-uart

**lsusb**
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 125: ID 10c4:8c07 Cygnal Integrated Products, Inc.
Bus 001 Device 004: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB
Bus 001 Device 003: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**/var/hm_mode**
HM_HOST='DEBMATIC'
HM_HOST_RAW_UART=''
HM_HOST_GPIO_UART=''
HM_HOST_UART_DEVICE_TYPE=''
HM_HOST_GPIO_RESET=''
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_RTC=''
HM_MODE='NORMAL'
HM_HMRF_DEVNODE=''
HM_HMIP_DEVNODE=''
HM_HMRF_DEV=''
HM_HMIP_DEV=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMIP_SGTIN=''
HM_HMIP_SERIAL=''
HM_HMIP_VERSION=''
HM_HMIP_ADDRESS=''

**Comment by alexreinert** [comment]
Ich habe im testing APT Repository eine neue Version des Tools für die Funkmodulerkennung eingespielt. Bitte mal testen, ob es damit jetzt läuft.

**Comment by Hooch76** [comment]
Zusätzliche Rückmeldung:  
Funktioniert bei mir:

debmatic version: **3.53.30-53**
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB-2@usb-0000:00:15.0-7 (/dev/raw-uart)
 Board serial:  5A...
 Radio MAC:     0x...
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         30...78
 Radio MAC:     0x...

DANKE!
