### ISSUE TITLE
fehlende Entities bei Wetterstation Plus

### ISSUE THREAD

**Issue by MarpleA** [alexreinert/debmatic#147]
Hallo,

ich nutze debmatic in der aktuellsten Version in Verbindung mit der Wetterstation Plus um Automatisierungen in Home Assistant umzusetzen.
In HA werden für den Regensensor in HA zwei Entities erkannt. 
sensor.xxxxxxxxxxxx_rain_counter
binary_xxxxxxxxxxxxx_raining

Der rain_counter ist in Homematic die Gesamtregenmenge, die niemals zurückgesetzt wird. Zusätzlich gibt es dort aber die "Regenmenge Heute" und die "Regenmenge Gestern"

Ist es möglich diese beiden Werte ebenfalls als Entities in HA nutzbar zu machen, da diese Werte für die meisten Automatisierungen weit sinnvoller sind als die Regengesamtmenge.

**Comment by alexreinert** [comment]
Das ist alles im Closed Source von eQ-3 auf welchen ich keinen Zugriff habe. Daher kann ich da leider nichts machen.

**Comment by MarpleA** [comment]
Alles klar. Danke für die Klarstellung.

Dann ist vermutlich der Beste Weg, dass ich eine Systemvariable in der CCU erstelle, diese mit svHmIPRainCounterToday befülle und HA zur Verfügung stelle.

oder gibt es einen eleganteren Weg?

**Comment by alexreinert** [comment]
Das ist eine Möglichkeit. Möglicherweise gibt es innerhalb von HA eine bessere Variante, das kann ich aber nicht beurteilen.
