### ISSUE TITLE
Frage: Umstieg von homegear

### ISSUE THREAD

**Issue by Hooch76** [alexreinert/debmatic#148]
Hallo,

hat jemand Erfahrung, ob man direkt von Homegear zu debmatic "migrieren" kann? Ich habe unter homegear keine Möglichkeit gefunden, ein CCU-kompatibles Backup zu erstellen.
Jedoch gibt es eine homematicbidcos.conf, in der es die Einträge centralAddress = 0x_xxxxxx_ und rfKey = _yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy_ gibt. Beide Werte wurden von mir bei der Installation angegeben, also bevor die Geräte angelernt worden sind. 
Kann man bei debmatic evtl beide Werte übernehmen, so dass die Geräte nahtlos übernommen würden? Oder steckt da mehr dahinter?

Danke im Voraus & viele Grüße,
 Tom

**Comment by alexreinert** [comment]
Ich habe keinerlei Erfahrung mit Homegear und kann daher nicht wirklich was zu sagen. Aus dem Bauch raus würde ich aber vermuten, dass das schwierig bis unmöglich wird.

**Comment by Hooch76** [comment]
Ok, danke. Dann halt der "manuelle" Weg über ab-/anlernen.
