### ISSUE TITLE
HM-MOD-RPI-PCB - HM funktioniert - HM-IP funktioniert nicht

### ISSUE THREAD

**Issue by mb1499** [alexreinert/debmatic#149]
Hallo - ich setze gerade eine neue produktive Umgebung auf, die meine alte PI3/FHEM Instanz ablösen soll. Hierfür wird eine neuer RPI4 - 4GB RAM und ein HM-MOD-RPI-PCB verwendet. Die anderen Komponenten ziehen später um.

Allerdings bekomme ich den HM-MOD-RPI-PCB und Debmatic nicht wirklich zum laufen. Es lassen sich erwartungsgemäß verschiedene HM Geräte anlernen und verwalten. Doch ich habe es noch nicht geschafft, HM-IP Geräte erfolgreich anzulernen!

Es handelt sich hier um neue HM-IP Wandthermostate (WTH-2), FBH Heizungsaktoren (FALMOT-C12) und die Multi-IO Box (MIOB). Kein Gerät lässt sich anlernen. Mittlerweile habe ich viel gelesen und probiert (anlernen über Internet, mit Seriennummern, mit Anlerntaste, Batterie einsetzen, Reset) den RPI im Raum und über Etagen verteilt, etc... Kein Erfolg.

Habe zwar auch die folgende Fehlermeldung im Log, doch das soll ja nicht das Problem sein.
`Okt. 11 07:27:23 de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker ERROR [vert.x-worker-thread-2] AP 3014F711A061A7DA498F9C2D: Could not parse outgoing routing frame 
de.eq3.cbcs.util.core.InvalidParameterLengthException: The parameter key must be 16 byte long`

Der RPI ist frisch installiert, die Software ist up-to-date. Debmatic ist nach Anleitung installiert worden und läuft augenscheinlich problemlos. Hier noch ein paar Basisdaten:

> pi@raspberry4:~ $ sudo debmatic-info
debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  QEQ0406573
 Radio MAC:     0x6CFE12
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7DA498F9C2D
 Radio MAC:     0xB5E33F

Mir ist nicht klar ob es sich hier um ein Hardware, Software oder User-Problem handelt. :-)
Vielleicht hat ja jemand eine Idee.

Vielen Dank!
PS. Ach ja - der Ferritring für den HM-MOD-RPI-PCB kam schon in zwei Teilen hier an. Habe den Ring geklebt und es mit 4 und auch 6 Wicklungen probiert. Kein Unterschied.

**Comment by alexreinert** [comment]
Wie es bereits im Homematic Forum auf deine Anfrage geschrieben wurde: Der USB3 Controller vom Pi 4 erzeugt jede Menge Störstrahlung, welche insb. HmIP stört.
Ein anderes häufiges Problem ist die Stromversorung: Das HM-MOD-RPI-PCB hat keine wirkliche Spannungstabilisierung, wenn man da dann ein Netzteil am Pi hat, welches schwingt, dann stört das auch massiv den Empfang von HmIP. Beim Pi 4 ist daher meine absolute Empfehlung ein HB-RF-USB-2 zu verwenden, weil man hier zum Abstand zwischen Pi und Funkmodul bekommt und zum anderen eine stabilisierte Spannungsversorgung des Funkmoduls hat.

Ein weiterer Punkt, weil du Anlerntaste erwähnst:
Das einzige wirklich funktionierende Vorgehen zum Anlernen von HmIP Geräten:

- Werksreset vom anzulernenden Gerät (selbst bei fabrikneuen Geräten)
- Spannungsversorgung vom anzulernenden Gerät trennen bzw. Batterien raus.
- Anlernmodus in der CCU starten
- Spannungsversorgung wieder herstellen, **nichts drücken**
- Warten bis der Countdown in der CCU abgelaufen ist, erst danach in den Posteingang wechseln

**Comment by alexreinert** [comment]
Gitb es hier ein Update?

**Comment by mb1499** [comment]
Hallo Alex,
vielen Dank für die fundierte Rückmeldung! Habe darauf hin direkt am Montag das HB-RF-USB-2 bestellt. Warte noch auf die Lieferung. Lötkolben, etc. steht schon bereit.

Zwischenzeitlich habe auch mal das produktive HM-MOD-RPI-PCB auf den neuen RPI4 mit Debmatic gesteckt. Auch das funktionierte nicht. Im Umkehrschluß wurde die Firmware vom HM-MOD-RPI-PCB dadurch übrschrieben und das Modul lief dann nicht mehr in der produktiven FHEM Installation. Somit mußte ich hier auch noch einmal flashen...   Jetzt läuft auch die produktive Umgebung wieder. :-)

Hoffe, dass HB-RF-USB-2 kommt morgen an.

**Comment by mb1499** [comment]
Kurzes Update. Warte immer noch auf die Lieferung. Werde mich wieder melden sobald das HB-RF-USB-2 geliefert und montiert ist.

**Comment by fabian727** [comment]
gibts was neues?
Würde mich ebenfalls interessieren, da ich den HM-MOD-RPI-PCB bald auf ein raspbi4 stecken werde.

**Comment by mb1499** [comment]
Tatsächlich ist die Platine Anfang der Woche angekommen und zusammen gelötet worden. Das HB-RF-USB-2 funktioniert einwandfrei mit dem HM-MOD-RPI-PCB! Homematic und Homematic-IP Geräte konnten problemlos angemeldet werden!

Ich bin noch mitten in der Installation bzw. Konfiguration von FHEM. Mittlerweile sind 14 Geräte eingebunden. Zurzeit habe ich noch die Herausforderung, dass FHEM einfriert (keine Last auf dem System!). Da muss ich noch weiter untersuchen. Allerdings ist das Thema unabhängig von diesem Problem.

Ein Nachsatz noch. Ohne einen kompletten Werksreset ließ sich KEIN HM-IP Gerät einbinden! Da hilft auch kein Batterie entfernen oder Pairing-Taste drücken. Macht einen Werksreset (gemäß Anleitung), startet das Gerät und bringt die CCU in den Pairing Modus. Dann klappt es i.d.R. auch. :-)

**Comment by marconetzlande** [comment]
I had the very same problem. After reading this I just extended the pi4s IO header about 15cm through an extension wire. All the HMIP devices start working again.
Somethin to mention: My HM-MOD-RPI-PCB has an modified antenna, not just that wire it comes with.
