### ISSUE TITLE
Support für HB-UNI-Sensor1

### ISSUE THREAD

**Issue by RamSauerB** [alexreinert/debmatic#15]
Hallo Alex,

planst Du auch einen Support für das Addon HB-UNI-Sensor1?

https://github.com/TomMajor/SmartHome/tree/master/HB-UNI-Sensor1

Das wäre toll! 

Viele Grüße
Markus

**Comment by alexreinert** [comment]
Ja, ist in Arbeit und wird das nächste portierte Addon.

**Comment by RamSauerB** [comment]
Spitzenmäßig!!!!!

Kommt mit der nächsten Version auch die Unterstützung für die aktuelle CCU Firmware?

**Comment by alexreinert** [comment]
> Kommt mit der nächsten Version auch die Unterstützung für die aktuelle CCU Firmware?

Das Addon ist unabhängig von der debmatic Version. Allerdings hat eQ-3 die Version bisher noch nicht bereitgestellt, daher kann ich sie nicht einpflegen.

**Comment by alexreinert** [comment]
Addon ist released.
