### ISSUE TITLE
Neues Update + RPI-RF-MOD

### ISSUE THREAD

**Issue by SHAXperiment** [alexreinert/debmatic#152]
Bei mir nach dem Update ein ähnliches Problem wie bei chriwo83 mit dem neuen Update und RPI-RF-MOD. Keine Geräte laden und auf der Startseite steht:
Aktuelle Firmwareversion: --

OS: Raspbian GNU/Linux 10 (buster) armv7l
Host: Raspberry Pi 3 Model B Plus Rev 1.3
Kernel: 5.4.35-v7+

Alles was nicht mit Homematic zutun hat funktioniert. Hue usw. Sobald ich die Geräteliste laden will kommt "Konfigurationsdaten werden geladen..." "Bitte warten..." und das hört nicht auf. Man kann warten solange man will. Backup einspielen hat den gleichen Effekt. Das System lief sehr lange stabil und ich hatte nie Probleme.

Übrigens auch RPI-RF-MOD und gleiche Version.

Ich hab dann "sudo dpkg-reconfigure pivccu-modules-dkms" gemacht, da kam dann:
Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.4.70-v7+ ARCH=arm all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.70-v7+ (armv7l)
Consult /var/lib/dkms/pivccu/1.0.45/build/make.log for more information.

UPDATE 1:
Glaube also ich habs jetzt ganz kaputt gemacht.

**debmatic version: 3.53.30-50
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown**

Das ist debmatic-info nach meiner Aktion...

UPDATE 2:
Nachdem ich das nochmal gemacht hab, habe ich zumindest jetzt:
**debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown**

UPDATE 3:
Komplett frischen Raspberry Pi genommen (komplett anderes Gerät), 
Raspian und Debmatic komplett neu aufgesetzt ohne einspielen des Backups.

debmatic version: 3.53.30-50
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

Anscheinend ist seit dem in Homematic stand "Firmware updaten" und ich apt upgrade gemacht hab irgendwas passiert.
Ist eigentlich alles durchgelaufen. Kann von Raspbian irgendwas gekommen sein, welches den RPI-RF-MOD ausser gefecht setzt?

Syslog:
**Oct 16 00:07:27 raspberrypi systemd[1]: Starting debmatic hmserver...
Oct 16 00:07:30 raspberrypi start_hmserver.sh[966]: Init Hardware Info
Oct 16 00:07:31 raspberrypi start_hmserver.sh[966]: WARNING: An illegal reflective access operation has occurred
Oct 16 00:07:31 raspberrypi start_hmserver.sh[966]: WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/opt/HMServer/HMServer.jar) to field java.nio.Buffer.address
Oct 16 00:07:31 raspberrypi start_hmserver.sh[966]: WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
Oct 16 00:07:31 raspberrypi start_hmserver.sh[966]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Oct 16 00:07:31 raspberrypi start_hmserver.sh[966]: WARNING: All illegal access operations will be denied in a future release**

**Comment by alexreinert** [comment]
Ich habe gestern eine überarbeitete Version des Tools für die Erkennung des Funkmoduls (detect_radio_module) bereitgestellt, bitte mit apt mal darauf aktualisieren und berichten, ob das Problem dann immer noch besteht.

**Comment by chriwo83** [comment]
genau das Problem besteht bei mir auch. Nur hab ich halt nur HM Geräte verbunden - bei mir ists allerdings das USB Modul, welches ich verwende.

**Comment by chriwo83** [comment]
@SHAXperiment: Hat sich das Problem bei Dir mit dem Update gelöst?

**Comment by SHAXperiment** [comment]
@chriwo83 Leider noch nicht ich bin auch noch auf Fehlersuche. Konnte leider noch nicht groß weitersuchen wegen meiner Tochter.

Hier noch ein paar Infos:
Package: pivccu-modules-raspberrypi
Status: install ok installed
Priority: extra
Section: kernel
Maintainer: Alexander Reinert <alex@areinert.de>
Architecture: armhf
Version: 2.0-12
Depends: raspberrypi-kernel-headers, pivccu-modules-dkms, bc
Pre-Depends: debconf (>= 0.5) | debconf-2.0
Description: Raspberry Pi kernel modules needed for Homematic
  This package contains the Raspberry Pi kernel needed for Homematic.
Homepage: https://github.com/alexreinert/piVCCU

**Comment by SHAXperiment** [comment]
Ich habe gerade 3.53.30-53 aus dem Testing branch installiert als Test:
debmatic version: 3.53.30-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

**Comment by SHAXperiment** [comment]
Bekomme es nicht hin. Habe testweise auf einem anderen Pi mal RaspberryMatic getestet, Modul funktioniert.

**Comment by SHAXperiment** [comment]
Ergänzung: Mit der neuesten RaspberryMatic gleiches Problem. Habe extrem viel mit Debmatic und dem Gerät rumgetestet, ich weiß nicht genau woran es liegt. Das Modul leuchtet in Debmatic auch garnicht, während RaspberryMatic die neueste Version die LED rot leuchten lässt. 

Vielleicht kam irgendwas ins System durch ein Update (Raspbian) oder in der CCU Firmware ist was drin was die Probleme macht?

**Comment by DominikErdle** [comment]
HI , 
ich habe das gleiche Problem mein Funkmodul wird einfach nicht erkannt weder mit dbmatic noch mit vccu3 bekomme immer wieder folgendes Ergebnis: 

pi@homatic:~ $ sudo debmatic-info
debmatic version: 3.53.30-53
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown


folgende Meldung bekomme ich mit der vccu3

ubuntu@ubuntu:~$ sudo pivccu-info
piVCCU version: 3.53.30-48
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi UART:   Not assigned to GPIO pins
HMRF Hardware:  unknown
 Connected via:  (/dev/raw-uart5)
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
State:          STOPPED

OS ist auf aktuellem stand und alle Updates sind eingespielt. Ob das Funk Modul funktioniert kann ich nicht sagen da es neu ist.

**Comment by SHAXperiment** [comment]
Da ich nicht weiter komme, teste ich jetzt mal ob es in vccu3 läuft. Ansonsten bleibt mir nicht mehr soviel, denke dann hol ich mir eine Homematic Zentrale... auch wenn ich das extrem ungern mach. Ich mag so geschlossene Geräte nicht so.

**Comment by heinemml** [comment]
Ich habe grad einen Pi 3B+ frisch aufgesetzt und hatte dabei ein ähnliches Problem wie hier beschrieben.

Was bei mir des Rätsel Lösung war: in `/boot/config.txt` war `dtoverlay=pivccu-raspberrypi` nicht in einer neuen Zeile eingefügt sondern an die letzte angehängt. Vielleicht hilft das?

Eigentlich sieht das Install Script [hier](https://github.com/alexreinert/piVCCU/blob/04ed49403b24eec5933dd8e5e0f0fc1d3b3b933c/package/pivccu-modules-raspberrypi/postinst) korrekt aus. Von daher ist mir nicht klar wie das zustanden kam...

**Comment by SHAXperiment** [comment]
Das ist leider bei mir nicht der Fall. Habe das Problem seit etwas an der Modulerkennung geändert wurde.

**Comment by SHAXperiment** [comment]
Ich teste heute nochmal ob ich was rausfinde.

**Comment by SHAXperiment** [comment]
Keine Chance. Seit dem Tag hab ich die Probleme. Übrigens auch auf einem baugleichen Teil das ich mir geliehen habe. Somit kann ich einen Defekt ausschließen.

**Comment by SHAXperiment** [comment]
Ok das Problem liegt definitiv an: detect_radio_module

Alte Versionen funktionieren, sowohl debmatic als auch raspberrymatic. Modul leuchtet sofort blau und funktioniert.

**Comment by Alex18081** [comment]
Hallo zusammen)
seit letzte update 3.57.4-68 wird HB-RF-USB-2 nicht mehr erkant, 
alex@alex-HP-Z230:/dev$ sudo debmatic-info
debmatic version: 3.57.4-68
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
alex@alex-HP-Z230:/dev$ sudo detect_radio_module --debug /dev/raw-uart
Sending HM frame: fd 00 03 fe 00 01 14 1e
Received HM frame: fd 00 0f fe 00 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c 68 c7
Sending HM frame: fd 00 03 fe 01 01 92 1d
Received HM frame: fd 00 0f fe 01 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c e9 c5
Sending HM frame: fd 00 03 fe 02 03 18 12
Received HM frame: fd 00 04 fe 02 05 00 87 3b
Sending HM frame: fd 00 03 00 03 00 12 00
Received HM frame: fd 00 04 00 03 04 03 19 0e
Sending HM frame: fd 00 03 fe 04 01 8c 1d
Received HM frame: fd 00 0f fe 04 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ec c0
Sending HM frame: fd 00 03 fe 05 03 8a 11
Received HM frame: fd 00 04 fe 05 05 00 07 54
Sending HM frame: fd 00 03 00 06 00 0c 00
Received HM frame: fd 00 04 00 06 04 03 19 4a
Sending HM frame: fd 00 03 fe 07 01 86 1d
Received HM frame: fd 00 0f fe 07 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ef c3
Sending HM frame: fd 00 03 fe 08 03 24 12
Received HM frame: fd 00 04 fe 08 05 00 87 b3
Sending HM frame: fd 00 03 00 09 00 2e 00
Received HM frame: fd 00 04 00 09 04 03 19 86
Error: Radio module was not detected

Alles hat seit jahren funktionirt, also erst seit update habe ich diese problem.

**Comment by alexreinert** [comment]
Welches Funkmodul hast du? Von welcher Version aus hast du das Update gemacht?

**Comment by Alex18081** [comment]
> Welches Funkmodul hast du? Von welcher Version aus hast du das Update gemacht?

ein RPI-RF-MOD. Habe jetzt ein HM-MOD-RPI-PCB eingesteckt und es Funktioniert alles wieder. Bin jetzt verwirrt, liegt es am neu Software oder RPI-RF-MOD kaputt. Werde auf eine Raspberry Pi 3 mit neue Image die RPI-RF-MOD testen.

**Comment by alexreinert** [comment]
Ich würde vermuten, dass das RPI-RF-MOD "kaputt" geflasht ist:

> Sending HM frame: fd 00 03 fe 02 03 18 12
> Received HM frame: fd 00 04 fe 02 05 00 87 3b

Mit dem gesendeten Frame wird das RPI-RF-MOD vom Bootloader in den App Modus versetzt, allerdings wird das mit einem NACK beantwortet. Das kann man aber reparieren:

- System starten
- debmatic beenden: `sudo systemctl stop debmatic`
- RPI-RF-MOD neu flashen: `sudo java -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.2.14.eq3`
- debmatic wieder starten `sudo systemctl start debmatic`

**Comment by SHAXperiment** [comment]
Bei mir war es genau das Gleiche. Glaube nicht das was "kaputt" geflasht wurde. Da alte Versionen von Debmatic funktionierten. Es hat mit dem detect_radio_module zutun. Mittlerweile habe ich es durch einen Umstieg gelöst. Mich haben aber viele kontaktiert die genau das gleiche Problem hatten und es kam mit dem Update wo das detect_radio_module geändert wurde. (Siehe Oben)

**Comment by alexreinert** [comment]
Im Fall von Alex18081 ist es aber eindeutig: Es kann nicht vom Bootloader in den App-Modus umgeschaltet werden, das sieht man anhand der gesendeten und empfangenen Frames.

**Comment by Alex18081** [comment]
> 
> 
> Ich würde vermuten, dass das RPI-RF-MOD "kaputt" geflasht ist:
> 
> > Sending HM frame: fd 00 03 fe 02 03 18 12
> > Received HM frame: fd 00 04 fe 02 05 00 87 3b
> 
> Mit dem gesendeten Frame wird das RPI-RF-MOD vom Bootloader in den App Modus versetzt, allerdings wird das mit einem NACK beantwortet. Das kann man aber reparieren:
> 
>     * System starten
> 
>     * debmatic beenden: `sudo systemctl stop debmatic`
> 
>     * RPI-RF-MOD neu flashen: `sudo java -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.2.14.eq3`
> 
>     * debmatic wieder starten `sudo systemctl start debmatic`

Super! Hat funktioniert!

alex@alex-HP-Z230:~$ sudo debmatic-info
debmatic version: 3.57.4-68
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:00:14.0-5 (/dev/raw-uart)
 Board serial:  58A9930542
 Radio MAC:     0xFF0342
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A8830342
 Radio MAC:     0x1FEA3D

Vielen Dank!
