### ISSUE TITLE
Fehlerhafte Diagramme 

### ISSUE THREAD

**Issue by MisterBJ** [alexreinert/debmatic#154]
Hallo Alex,

ich weiß nicht ob es ein Problem vom debmatic oder der ccu von eq3 ist. Ich habe eine Fußbodenheizung installiert und da habe ich gemerkt das keine Diagramme mehr funktionieren. Es steht da „Für dieses Diagramm stehen noch keine Daten zur Verfügung“, bei allen Diagrammen. Löschen über die webui funktionierte auch nicht, nur per ssh in den beiden Ordnern. Habe dann neue Diagramme neu angelegt und 24 Stunden gewartet und das gleiche Problem.
Also habe ich den Pi neu aufgesetzt, debmatic installiert, alle hmip Komponenten wieder neu angemeldet, Diagramme erstellt und siehe da es funktioniert.
Aber nach ein paar Tagen, ich habe den pi nicht mehr angerührt, ist das Problem wieder da.
Hast du schon davon etwas gehört und/oder hast du vielleicht eine Lösung dafür?
Ich benutze einen Pi3 und debmatic FW 3.53.30.50.

Gruß Björn

**Comment by MisterBJ** [comment]
Fehlende Daten:
- OS ist 32 Bit
- debmatic-info:
debmatic version: 3.53.30-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  NEQ0230770
 Radio MAC:     0x470549
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D5698CED72
 Radio MAC:     0xBC9AB0

Immer wiederkehrende (alle 30 Sekunden) Fehlermeldung aus der /var/log/hmserver.log:
`Nov. 16 15:11:05 de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker ERROR [vert.x-worker-thread-2] AP 3014F711A061A7D5698CED72: Could not parse outgoing routing frame
de.eq3.cbcs.util.core.InvalidParameterLengthException: The parameter key must be 16 byte long
        at de.eq3.cbcs.util.core.ByteArrayUtils.validateParameterLength(ByteArrayUtils.java:200)
        at de.eq3.cbcs.util.core.CbcMacAes.calculateMIC(CbcMacAes.java:423)
        at de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker.sendBackboneFrameToBackbone(BackboneWorker.java:773)
        at de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker.lambda$start$16(BackboneWorker.java:132)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`

/var/log/messages:
`Nov 15 00:00:18 smartpi rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="362" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
Nov 16 00:00:33 smartpi rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="362" x-info="https://www.rsyslog.com"] rsyslogd was HUPed`

Ich hoffe das kann weiterhelfen.


[syslog.txt](https://github.com/alexreinert/debmatic/files/5548714/syslog.txt)

Gruß,
Björn

**Comment by de-ramon** [comment]
Hi Björn,

ich hatte auch Probleme mit den Diagrammen.
Lösung für mein Setup (Raspi, SD-Karte) war einen USB-Stick einzubinden. Diesen nach `/media/usb0`mounten und gut. Hab die Ursachen nicht länger verfolgt. Vorschlag kam von hier:
- https://homematic-forum.de/forum/viewtopic.php?f=65&t=40353&start=30

cu,
Ralf

**Comment by MisterBJ** [comment]
Hallo und danke Ralf für den Hinweis. Aber ich verwende ja ein USB-Stick. Die CCU sagt auch das einer aktiv existiert und für ein paar Tage funktionierte es ja.
Aber danke für den Link, ich werde ihn mir nochmal genau durchlesen

Gruß Björn

**Comment by MisterBJ** [comment]
Also ich weis jetzt echt nicht mehr weiter. Ich weis nicht was ich noch machen soll.
- Ich habe den Service von debmatic beendet.
- Alle Files von /media/usb0/measurement/ und /etc/config/measurement gelöscht.
- Pi neugestartet und in der CCUWebUI kontrolliert das die Diagramme nicht mehr existieren.
- Service von debmatic erneut beendet.
- USB-Stick erneut formatiert:
`/dev/sda1: LABEL="CCU" UUID="65f3f07e-5d10-4a76-ab8f-4de8c9841d7e" TYPE="ext4"`
- Im /etc/fstab eingerichtet das der Stick immer gemauntet ist auch wenn kein User angemeldet ist:
`UUID=65f3f07e-5d10-4a76-ab8f-4de8c9841d7e /media/usb0 ext4 defaults 0`
- Pi neugestartet
- lsblk:
`NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT`
`sda           8:0    1 14,3G  0 disk`
`└─sda1        8:1    1 14,3G  0 part /media/usb0`
- In der UI neues Diagramm erstellt und seit mehreren Tagen immer noch keine Daten vorhanden:
ls -l /etc/config/measurement: `-rw-r--r-- 1 root root 504 Dez 19 19:30 1.dic`
ls -l /media/usb0/measurement/: `-rw-r--r-- 1 root root 470560 Dez 22 13:26 1.rrd`

Hat vielleicht jemand noch eine Idee? Ich mag den Pi nicht wieder neuinstallieren und nach drei Tagen habe ich das gleiche Problem.

Gruß,
Björn

**Comment by pow4all** [comment]
Hallo @MisterBJ

Ich habe dasselbe Problem wie du. Und zusätzlich noch #165.
Eine Lösung habe ich leider auch nicht. Da viele RaspberryMatic-Benutzer auch von Problemen mit den Diagrammen berichten denke ich nicht, dass das Problem bei debmatic liegt.

Gruss

**Comment by pow4all** [comment]
Was mir noch aufgefallen ist:

Im WebUI von debmatic unter _Einstellungen -> Systemsteuerung -> Allgemeine Einstellungen -> Externer USB-Speicher_ steht immer "Status: externer USB-Speicher vorhanden." Egal ob ich einen USB-Stick eingesteckt, eingebunden oder entfernt habe. Der RPi wurde zwischen den Tests mindestens einmal neu gestartet.

Ist das so richtig? Ist das bei dir auch so, @MisterBJ ?

**Comment by MisterBJ** [comment]
Hi pow4all,

mit dem USB-Stick hatte ich bereits mitgeteilt:
> Die CCU sagt auch das einer aktiv existiert und für ein paar Tage funktionierte es ja.

> Da viele RaspberryMatic-Benutzer auch von Problemen mit den Diagrammen berichten

Das ist ein guter Hinweis, aber soweit ich es jetzt sehe gibt es dort auch keine richtige Lösung.

Gruß,
Björn

**Comment by aaf-caliban** [comment]
Den Fehler ich auch mit der neuen Version 3.57.4.68, egal ob mit oder ohne USB Stick

**Comment by MisterBJ** [comment]
Nachdem ich heute das Funkmodul HM-MOD-RPI-PCB vom Pi3 auf dem Pi4 umgezogen habe und das Systembackup eingespielt habe ist mir aufgefallen das unter Allgemeinen Einstellungen "externer USB-Speicher vorhanden" angezeigt wird.
Einen USB-Stick ist aber gar nicht angeschlossen aber eine SSD (Pi läuft nicht über SD-Karte) über USB. 
@alexreinert 
Kann das zu Problemen mit den Diagrammen führen?

Gruß,
Björn
