### ISSUE TITLE
FW auf Startseite aber nicht auf GeraeteFW Übersicht

### ISSUE THREAD

**Issue by RoberTo1111** [alexreinert/debmatic#156]
Hallo,

ich werde auf der Startseite über FW Updates informiert. Wenn ich auf die Geräte FW Übersicht gehe, werden diese nicht angezeigt und auch nicht eine Möglichkeit manuell upzudaten. Unter der Spalte Aktion ist nichts vorhanden. 

Ist das so gewollt?

CU

R.

**Comment by alexreinert** [comment]
Das ist nicht unbedingt intuitiv von eQ-3 in der CCU umgesetzt worden. Man muss die Firmware erst selber runterladen und auf die CCU übertragen. Anleitung z.B. hier:
https://homematic-guru.de/quicktipp-homematic-update-geraete-firmware

**Comment by alexreinert** [comment]
Und bitte beim Download darauf achten, dass das tgz nicht vom Browser automatisch entpackt wird, das betrifft vor allem den Safari auf dem Mac, welcher das in der Standardeinstellung macht.

**Comment by RoberTo1111** [comment]
Wunderbar. Hat funktioniert. Danke.
