### ISSUE TITLE
Seit 3.53.30.53 nur noch "Empfangen" möglich

### ISSUE THREAD

**Issue by SkeeveKlah** [alexreinert/debmatic#157]
Hi, seit dem Upgrade der Debmatic auf 3.53.30.53 können keine Befehle mehr an die Hm(-IP) Geräte gesendet werden.
Andersherum werden aber Statusänderungen der Geräte von der Debmatic empfangen.

**Comment by SkeeveKlah** [comment]
Läuft wieder. Wie auch immer das passieren konnte, Kabelbruch im Antennenkabel vom Funkmodul, das Update war wahrscheinlich zu heftig, Alex die nächsten Updates bitte sanfter ;-)

**Comment by alexreinert** [comment]
Ok, fürs nächste Update baue ich Streicheleinheiten ein. ;-)

**Comment by SkeeveKlah** [comment]
Sehr nett von Dir :-D
