### ISSUE TITLE
Funkmodul wird nicht erkannt

### ISSUE THREAD

**Issue by lelatabathy** [alexreinert/debmatic#158]
Ich habe piVCCU anscheinend erfolgreich installiert, aber mein Funkmodul (über HB-RF-USB-TK per USB angeschlossen) wird nicht erkannt.

Ergebnis von pivccu-info:

```
piVCCU version: 3.53.30-47
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi UART:   Assigned to GPIO pins
lxc doesn't exist
/usr/sbin/pivccu-info: line 35: [: ==: unary operator expected
HMRF Hardware:  unknown
 Connected via:  (/dev/)
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
lxc doesn't exist
```

Zunächst dachte ich, es liegt an dem rpi-update Problem, was hier im Forum auch schon beschrieben wurde. Bei Installation meines Systems habe ich das wohl mal laufen lassen. Aber ich habe dann sowohl auf die vorherige stabile Kernel Version zurückgesetzt via `sudo apt-get update; sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel` als auch die Unterstützung für rpi-update gemäß Github installiert.
Trotzdem wird das Modul nicht erkannt.

Ich habe auch schon versucht, das HM-MOD-RPI-PCB direkt auf GPIO anzustecken, aber auch dort wird es nicht erkannt (obwohl ich die Schritte der Installation hierfür auch durchgeführt und nicht übersprungen habe).

Kann mir jemand helfen?

**Comment by alexreinert** [comment]
Leider falsches Projekt, hier geht es um debmatic.
Da du das auch im Forum aufgemacht hast, kannst du gerne dort noch die Ausgabe von lsusb nachliefern, an zwei Stellen braucht das Thema nicht abgehandelt werden.

**Comment by lelatabathy** [comment]
@alexreinert Vielen Dank, lsusb ergänze ich im Forum. Sorry für das Versehen!
