### ISSUE TITLE
HMIP-HAP

### ISSUE THREAD

**Issue by fooke123** [alexreinert/debmatic#159]
Hallo,
gestern habe ich debmatic auf einer Ubuntu 18.04 VM installiert und habe versucht einen HMIP-HAP über den Button "Access-Point mit inkompatibler FW" mit in das System einzubinden. Leider wird beim Klicken auf den Button nur das Fenster gegraut, es taucht aber kein Popup oder ähnliches auf (siehe Screenshot). Mache ich etwas falsch oder ist diese Funktion mit debmatic nicht möglich?
Vielen Dank schon jetzt für eure Antworten!
Gruß
Fooke
![grafik](https://user-images.githubusercontent.com/41750762/98508949-a677b580-2260-11eb-8d59-9e77b53d8839.png)

**Comment by alexreinert** [comment]
Das ist  mit debmatic möglich, allerdings aufgrund von Einschränkungen im Closed Source von eQ-3 nur dann, wenn man ein RPI-RF-MOD angeschlossen hat (per GPIO, HB-RF-USB-2 oder HB-RF-ETH). Ist das bei dir der Fall?

**Comment by fooke123** [comment]
Ich habe zur Zeit einen Raspberry Pi mit HM-MOD-RPI-PCB mit piVCCU im Einsatz. Jetzt wollte ich auf meinen ESXi Server umziehen (weg vom Pi) und dort debmatic ohne direkte Hardware nur mit zwei HMIP-HAP (über LAN) nutzen.
Gibt es hier eine Möglichkeit, oder komme ich um den Kauf des HB-RF-USB-2 nicht herum?

**Comment by alexreinert** [comment]
Wie geschrieben, du brauchst zwingend ein RPI-RF-MOD für die Funktionalität. Ggf. kannst du aber einen HmIP-HAP einsparen, wenn du statt der HB-RF-USB-2 die HB-RF-ETH für das RPI-RF-MOD nutzt und die durch den Netzwerk-Anschluss im Zweifel räumlich deutlich weiter vom ESXi Server absetzen kannst an die Stelle, wo du einen HmIP-HAP einsetzen wolltest.

**Comment by fooke123** [comment]
Alles klar, danke für deine schnelle und hilfreiche Antwort!!
