### ISSUE TITLE
Debmatic don't works on Raspberry Pi 4B 8GB with 64-bit Raspberry Pi OS

### ISSUE THREAD

**Issue by nanotux1** [alexreinert/debmatic#160]
pi@raspberrypi:~ $ sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  dkms
Vorgeschlagene Pakete:
  python3-apport menu
Die folgenden NEUEN Pakete werden installiert:
  dkms pivccu-modules-dkms raspberrypi-kernel-headers
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 35,1 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 229 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://deb.debian.org/debian buster/main arm64 dkms all 2.6.1-4 [74,4 kB]
Holen:2 http://archive.raspberrypi.org/debian buster/main arm64 raspberrypi-kernel-headers arm64 1.20201022-1 [35,0 MB]
Holen:3 https://www.debmatic.de/debmatic stable/main arm64 pivccu-modules-dkms all 1.0.45 [34,0 kB]
Es wurden 35,1 MB in 7 s geholt (5.275 kB/s).                                                                                                                                                                                              
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket dkms wird gewählt.
(Lese Datenbank ... 93317 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../archives/dkms_2.6.1-4_all.deb ...
Entpacken von dkms (2.6.1-4) ...
dkms (2.6.1-4) wird eingerichtet ...
Vormals nicht ausgewähltes Paket pivccu-modules-dkms wird gewählt.
(Lese Datenbank ... 93345 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../pivccu-modules-dkms_1.0.45_all.deb ...
Entpacken von pivccu-modules-dkms (1.0.45) ...
Vormals nicht ausgewähltes Paket raspberrypi-kernel-headers wird gewählt.
Vorbereitung zum Entpacken von .../raspberrypi-kernel-headers_1.20201022-1_arm64.deb ...
Entpacken von raspberrypi-kernel-headers (1.20201022-1) ...
raspberrypi-kernel-headers (1.20201022-1) wird eingerichtet ...
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v7+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v7l+
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.72-v8+
pivccu-modules-dkms (1.0.45) wird eingerichtet ...

Creating symlink /var/lib/dkms/pivccu/1.0.45/source ->
                 /usr/src/pivccu-1.0.45

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.4.72-v8+ ARCH=arm64 all.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.72-v8+ (aarch64)
Consult /var/lib/dkms/pivccu/1.0.45/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Trigger für man-db (2.8.5-2) werden verarbeitet ...

pi@raspberrypi:~ $ cat Consult /var/lib/dkms/pivccu/1.0.45/build/make.log for more information.
cat: Consult: Datei oder Verzeichnis nicht gefunden
DKMS make.log for pivccu-1.0.45 for kernel 5.4.72-v8+ (aarch64)
Mi 11. Nov 10:01:07 CET 2020
make -C /lib/modules/5.4.72-v8+/build M=/var/lib/dkms/pivccu/1.0.45/build modules
make[1]: Verzeichnis „/usr/src/linux-headers-5.4.72-v8+“ wird betreten
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/dw_apb_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/meson_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/fake_hmrf.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/rpi_rf_mod_led.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/dummy_rx8130.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/led_trigger_timer.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/hb_rf_usb.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/hb_rf_usb-2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.o
/var/lib/dkms/pivccu/1.0.45/build/fake_hmrf.c: In function ‘fake_hmrf_write’:
/var/lib/dkms/pivccu/1.0.45/build/fake_hmrf.c:266:1: warning: the frame size of 2080 bytes is larger than 2048 bytes [-Wframe-larger-than=]
 }
 ^
  CC [M]  /var/lib/dkms/pivccu/1.0.45/build/rtc-rx8130.o
/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c: In function ‘connect_store’:
/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c:543:3: warning: ISO C90 forbids variable length array ‘ip’ [-Wvla]
   char ip[count + 1];
   ^~~~
/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c: In function ‘hb_rf_eth_init’:
/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c:620:3: warning: ignoring return value of ‘sysfs_create_file’, declared with attribute warn_unused_result [-Wunused-result]
   sysfs_create_file(&dev->kobj, &dev_attr_is_connected.attr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.c:621:3: warning: ignoring return value of ‘sysfs_create_file’, declared with attribute warn_unused_result [-Wunused-result]
   sysfs_create_file(&dev->kobj, &dev_attr_connect.attr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Building modules, stage 2.
  MODPOST 14 modules
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/rtc-rx8130.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/hb_rf_eth.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/hb_rf_usb-2.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/led_trigger_timer.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/rpi_rf_mod_led.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/fake_hmrf.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/dw_apb_raw_uart.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/generic_raw_uart.ko] undefined!
ERROR: "__stack_chk_guard" [/var/lib/dkms/pivccu/1.0.45/build/eq3_char_loop.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:94: __modpost] Fehler 1
make[1]: *** [Makefile:1645: modules] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-5.4.72-v8+“ wird verlassen
make: *** [Makefile:25: all] Fehler 2
cat: for: Datei oder Verzeichnis nicht gefunden
cat: more: Datei oder Verzeichnis nicht gefunden
cat: information.: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi:~ $

**Comment by alexreinert** [comment]
Siehe https://github.com/raspberrypi/firmware/issues/1477
TL;DR; Problem in der verwendeten Toolchain von Raspberry OS, mit dem nächsten Kernel Update sollte es gehen.

**Comment by luzifer84** [comment]
Hello Alex,
as far as i followed the post above the bug was mentioned for kernel 5.4.69-v8+, I am currently on 5.4.72-v8+ still experiencing this bug. Is there already a fixed version and can you tell me where to get it?
Thanks in advance - great job by the way. 
Coffee follows as soon as I sucessfully migrated from homegear to debmatic.

Best regards!

**Comment by alexreinert** [comment]
The latest post in the linked issue, there they stated, it should be fixed, was just 19 days ago, there was no kernel since then.
Instead of waiting it would also be an option to use the 32 Bit Version, which is working well. Even if it is 32 Bit, it supports the 8GB Raspberry (but "only" 3GB per process).

**Comment by alexreinert** [comment]
The testing APT Repo now contains an updated kernel module package, which works on 64bit Raspberry Pi OS, too.

**Comment by nanotux1** [comment]
What do you mean with testing APT Repo? Raspian OS apt repo or debian testing apt repo? Can you give me an URL please? How can I install the updated kernel module package

**Comment by alexreinert** [comment]
debmatic testing apt repo: https://www.debmatic.de/debmatic
Package is pivccu-modules-dkms, Version 1.0.51

**Comment by jutonium** [comment]
Thanks for the effort. I moved from 32-Bit Raspberry Pi OS to 64-Bit on a Pi 4 8GB. After booting the device the LED of the RPI-RF-MOD lights up green and turns completely off. Communication with HmIP devices does not work "Gerätekommunikation gestört".
`sudo systemctl list-dependencies debmatic.service
debmatic.service
● ├─debmatic-eq3configd.service
● ├─debmatic-hmserver.service
● ├─debmatic-hs485d.service
● ├─debmatic-hssled.service
● ├─debmatic-lighttpd.service
● ├─debmatic-monitor-hb-rf-eth.service
● ├─debmatic-multimacd.service
● ├─debmatic-prepareinterfaceslist.service
● ├─debmatic-rega.service
● ├─debmatic-rfd.service
● ├─debmatic-setinterfaceclock.timer
● ├─debmatic-ssdpd.service
● ├─debmatic-startupfinished.service
● ├─debmatic-updatelgwfirmware.service
● ├─debmatic-updatelgwkey.service
● ├─debmatic-updaterffirmware.service
● ├─pivccu-dkms.service
● ├─system.slice
● └─sysinit.target
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─fake-hwclock.service
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot.mount
●   │ ├─systemd-fsck-root.service
●   │ └─systemd-remount-fs.service
●   └─swap.target`
black dots: debmatic-hs485d.service, debmatic-monitor-hb-rf-eth.service, pivccu-dkms.service, dev-hugepages.mount, sys-fs-fuse-connections.mount, systemd-binfmt.service, systemd-hwdb-update.service & systemd-machine-id-commit.service

`sudo debmatic-info
debmatic version: 3.53.34-57
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  ---
 Radio MAC:     ---
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         ---
 Radio MAC:     ---`
Board serial, MACs and SGTIN are reported propperly.

Restarting the debmatic service helps with the status LED but communication still does not work.

System: Raspberry Pi 4 B 8GB, SSD (UASP, bootdevice), headless
I hope this helps!

**Comment by jutonium** [comment]
I might have found the culprit:

DKMS: add completed.
Error! Your kernel headers for kernel 5.4.51-v8+ cannot be found.
Please install the linux-headers-5.4.51-v8+ package,
or use the --kernelsourcedir option to tell DKMS where it's located

There is a bug report here: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/4

**Comment by alexreinert** [comment]
@jutonium Are you using the full 64 bit Image or just a 32 bit Image with 64 bit Kernel?

The 32 bit Image will not work, as the kernel header package only includes the headers for the 32 bit kernel and not the headers for the 64 bit kernel.

**Comment by jutonium** [comment]
It's the one I downloaded from https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/

I would assume that it is has a 64 bit Kernel:
uname -m
aarch64

**Comment by alexreinert** [comment]
Ok, do an apt update and upgrade, reboot your system and the chances are good, that it will work then.

**Comment by jutonium** [comment]
Thank you for your help. I still encountered some communication problems. I read that this might be due to using the USB bus for mass storage.
However following your setup instructions up until "sudo apt install raspberrypi-kernel-headers", rebooting and installing pivccu-modules-dkms afterwards did the trick.
