### ISSUE TITLE
Updating the "debmatic" package causes an error.

### ISSUE THREAD

**Issue by Plazmin** [alexreinert/debmatic#161]
Error updating from version 3.53.30.53 to version 3.53.34.55. Only present when "no" is selected in the pre-install backup configuration screen. If you select "yes", the package update is error free.
![debmatic](https://user-images.githubusercontent.com/62091912/98821602-0ff9ee80-2430-11eb-8908-1f1b5097a5c9.png)

**Comment by alexreinert** [comment]
Can you please provide a translation of the non-english (polish?) error messages?

**Comment by Plazmin** [comment]
![1d](https://user-images.githubusercontent.com/62091912/98944029-b279a680-24f0-11eb-9957-5c97fd3c8d7c.png)
dpkg: błąd przetwarzania archiwum -> archive processing error
podproces nowy pakiet debmatic skrypt preinstalation zwrócił kod błedu 2 -> subproces new packet debmatic preinstalation  script returned on error code 2

![2d](https://user-images.githubusercontent.com/62091912/98944251-10a68980-24f1-11eb-8760-638572946065.png)
Wystąpiły błędy podczas przetwarzania -> Errors were encountered while processing

**Comment by alexreinert** [comment]
Does with issue exists with the current version?

**Comment by Plazmin** [comment]
I have two ccu3 devices. When updating the first ccu3 device, the pre-install backup configuration screen 

![debmatic](https://user-images.githubusercontent.com/62091912/102136220-64dabb80-3e59-11eb-9088-ce2141f2bd97.png)

does not appear at all. On the second device, after answering "no", the previously described error still occurs. The device configuration is virtually identical. I don't know why the question screen appears on one CCU3 and not on the other.

**Comment by alexreinert** [comment]
The screen does only occur, if the a new CCU firmware is installed and not on minor debmatic updates. (3.53.30.53 --> 3.53.34.55 it will occur, 3.53.34.55 --> 3.53.34.52 it will not occur). This is by design, because you cannot install a CCU backup to a prior CCU version.
If selecting "No" the update a prequisite of the update process is not fullfilled and therefor the update will fail. Maybe there should be an additional error message for that.

**Comment by Plazmin** [comment]
I think it was like this for me:

-my first CCU3 "Upgrade: debmatic:armhf (3.53.34-55, 3.53.34-59)". The pre-install backup configuration screen does not appear at all
-my second CCU3  "Upgrade: debmatic:armhf (3.53.30-53, 3.53.34-59)". The backup configuration screen appears.

I'll check on the next occasion. Thanks for the clarification.
