### ISSUE TITLE
RPI-RF-MOD wird nicht erkannt

### ISSUE THREAD

**Issue by raspi-scotty** [alexreinert/debmatic#162]
Bin ein Neueinsteiger und habe ein Problem. 
Habe einen Raspberry Pi 4 B mit einem RPI-RF-MOD ausgestattet. 
Das Funkmodul lief unter RaspbianMatic fehlerfrei, obwohl es nur schwif drauf gepasst hat. Habe den Sockel jetzt erhöht. 
Jetzt bin ich  umgestiegen auf Raspbian OS (2020-08-20-raspios-buster-armhf-full.img nach initialem Boot alle Updates) und debmatic. 
Dachte eigentlich, dass ich die Anleitung unter https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md komplett befolgt habe.
Das Modul wird aber nicht erkannt. Keine LED. Gar nichts.

pi@raspberrypi:~ $ lsusb
Bus 002 Device 002: ID 18a5:0250 Verbatim, Ltd 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 046d:c069 Logitech, Inc. M-U0007 [Corded Mouse M500]
Bus 001 Device 003: ID 046a:0023 Cherry GmbH Keyboard
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.53.34-55
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

Kann jemand helfen?

**Comment by alexreinert** [comment]
Wurden die Reboot aus der Anleitung ebenfalls ausgeführt? Wie sieht die /boot/config.txt aus?

**Comment by raspi-scotty** [comment]
Reboot wurde durchgeführt

pi@raspberrypi:~ $ less /boot/config.txt

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
dtoverlay=pi3-disable-bt
enable_uart=1

**Comment by alexreinert** [comment]
Wurde Schritt 5 ausgeführt (Installation des Pakets pivccu-modules-raspberrypi)? Diese fügt normalerweise einen Eintrag in die /boot/config.txt ein, welcher aber oben fehlt.

**Comment by raspi-scotty** [comment]
Ich habe das so eingegeben

pi@raspberrypi:~ $ sudo bash -c 'cat << EOT >> /boot/config.txt
> dtoverlay=pi3-disable-bt
> EOT'
pi@raspberrypi:~ $ 

Da kam dann keine Rückmeldung

Wenn ich das in einer Zeile absetze, scheint da ein Fehler vorzuliegen. 
pi@raspberrypi:~ $ sudo bash -c 'cat << EOT >> /boot/config.txt dtoverlay=pi3-disable-bt EOT'
bash: Warnung: Das in der Zeile 0 beginnende Here-Dokument geht bis zum Dateiende (erwartet wird `EOT').
cat: 'dtoverlay=pi3-disable-bt': Datei oder Verzeichnis nicht gefunden
cat: EOT: Datei oder Verzeichnis nicht gefunden

**Comment by alexreinert** [comment]
Schritt 5 war ein Tippfehler von mir, das hatte ich direkt nach dem Abschicken korrigiert, es geht um Schritt 4.

**Comment by raspi-scotty** [comment]
Schritt 4 habe ich gerade nochmal ausgeführt. 

pi@raspberrypi:/boot $ sudo apt install pivccu-modules-raspberrypi
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libexiv2-14 libgfortran3 libgmime-2.6-0 libncurses5 libssl1.0.2 uuid-dev
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden zusätzlichen Pakete werden installiert:
  bc
Die folgenden NEUEN Pakete werden installiert:
  bc pivccu-modules-raspberrypi
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 104 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 220 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 http://mirror1.hs-esslingen.de/pub/Mirrors/archive.raspbian.org/raspbian buster/main armhf bc armhf 1.07.1-2 [101 kB]
Holen:2 https://www.debmatic.de/debmatic stable/main armhf pivccu-modules-raspberrypi armhf 2.0-12 [2.720 B]
Es wurden 104 kB in 1 s geholt (184 kB/s).             
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket bc wird gewählt.
(Lese Datenbank ... 221901 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../archives/bc_1.07.1-2_armhf.deb ...
Entpacken von bc (1.07.1-2) ...
Vormals nicht ausgewähltes Paket pivccu-modules-raspberrypi wird gewählt.
Vorbereitung zum Entpacken von .../pivccu-modules-raspberrypi_2.0-12_armhf.deb ...
dpkg-divert: Warnung: Bitte geben Sie »--no-rename« explizit an, die Vorgabe wird in 1.20.x
auf »--rename« geändert werden
»Umleitung von /boot/overlays/pivccu-raspberrypi.dtbo zu /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo durch rpikernelhack« wird hinzugefügt
Entpacken von pivccu-modules-raspberrypi (2.0-12) ...
bc (1.07.1-2) wird eingerichtet ...
pivccu-modules-raspberrypi (2.0-12) wird eingerichtet ...
»Umleitung von /boot/overlays/pivccu-raspberrypi.dtbo zu /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo durch rpikernelhack« wird entfernt
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-rpi-modules.service → /lib/systemd/system/pivccu-rpi-modules.service.
Trigger für man-db (2.8.5-2) werden verarbeitet ...
Trigger für install-info (6.5.0.dfsg.1-4+b1) werden verarbeitet ...
pi@raspberrypi:/boot $

**Comment by raspi-scotty** [comment]
Reboot und die LED leuchtet blau

**Comment by alexreinert** [comment]
Dem Log nach war das vorher nicht installiert, da es neu installiert wurde.
Problem dürfte damit erledigt sein, oder?

**Comment by raspi-scotty** [comment]
Ja, das Problem ist behoben. Das Funkmodul scheint nun komplett installiert. Die Blaue LED leuchtet. Vielen lieben Dank. 

pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.53.34-55
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993EC42
 Radio MAC:     0xFFEC42
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993EC42
 Radio MAC:     0xBFE768

Wenn jetzt noch das Anlernen des HmIP-MOD-OC8 klappen würde, wäre ist im 7. Himmel. Hier erhalte ich ein schnelles gelbes Blinken - keine Verbindung zum Netzwerk/Router. Also im WLAN ist die PI, sonst könnte ich ja nicht per SSH zugreifen.

**Comment by alexreinert** [comment]
Ich verstehe leider nicht, was du sagen willst.

**Comment by raspi-scotty** [comment]
Das Modul läuft ja jetzt, dank Deiner Hilfe. Jetzt möchte ich das 8-Kanal-Empfangsmodul anlernen. Unter Rasbianmatic ging das direkt. Mit dem aktuellen Setting erhalte ich nach dem Anlernversuch ein schnelles gelbes Blinken. Die Doku sagt dazu "keine Verbindung zum Netzwerk/Router". Das verstehe ich nicht. Also im WLAN ist die PI, sonst könnte ich ja nicht per SSH zugreifen.

**Comment by alexreinert** [comment]
Hast du am Modul einen Werksreset gemacht? Hängt irgendwas an den USB3 Ports (die blauen)? Was genau blinkt schnell gelb, das RPI-RF-MOD? Was bedeutet schnell konkret? Kannst du vom Pi aus auch externe Server anpingen, der SSH Zugang heißt erstmal nur, dass der Pi in deinem Netzwerk erreichbar ist, aber nicht, dass er auch Internet-Zugang hat.

**Comment by raspi-scotty** [comment]
Das schnelle Blinken war auf dem Funkmodul RPI-RF-MOD

Werks-Reset beim HmIP-MOD-OC8 habe ich gemacht: TA9 für 4 Sekunden halten, bis die LED orange blinkt, dann loslassen und erneut für 4 Sekunden halten, bis die LED grün leuchtet.

Im USB 3 hatte ich einen USB-Stick. Den habe ich entfernt. Reboot. Mit ssh auf die PI, 

pi@raspberrypi:~ $ ping web.de
PING web.de (82.165.229.138) 56(84) bytes of data.
64 bytes from bs.web.de (82.165.229.138): icmp_seq=1 ttl=245 time=18.3 ms
64 bytes from bs.web.de (82.165.229.138): icmp_seq=2 ttl=245 time=14.10 ms
64 bytes from bs.web.de (82.165.229.138): icmp_seq=3 ttl=245 time=17.0 ms
64 bytes from bs.web.de (82.165.229.138): icmp_seq=4 ttl=245 time=15.4 ms

Anlernversuch. Der Posteingang bleibt leer. Das Funkmodul RPI-RF-MOD leuchtet weiterhin blau. Kein Blinken mehr.

**Comment by alexreinert** [comment]
Ganz allgemein: Der Pi4 ist leider für seine Störstrahlung bekannt, insb. bei aktiviertem WLAN und/oder USB3. Und diese Störstrahlung betrifft vor allem HmIP, weil das Listen Before Talk macht. Die einzige mir bekannte zuverlässige Lösung ist es, das Funkmodul abzusetzen, also Abstand zwischen Pi und Funkmodul zu schaffen, z.B. mittels HB-RF-USB-2, HB-RF-ETH oder notfalls auch mit einem Flachbandkabel.

**Comment by raspi-scotty** [comment]
Hab jetzt auf Lan gewechselt. Jetzt hat es geklappt. 
Vielen Dank
