### ISSUE TITLE
Keine Daten in Debmatic z.B. IoBroker bekommt sie aber..

### ISSUE THREAD

**Issue by trevon88** [alexreinert/debmatic#163]
Hallo,
Vielleicht habe ich einen Bug, nur weiss ich nicht, wie ich das herausfinden könnte.

Ich habe Debmatic schon 2 mal neu Aufgesetzt und habe immer den gleichen Fehler.

Ich sehe auf der Weboberfläche von Homematic IP keine Temperatur Meldungen etc...
Befehle senden geht aber...

Komisch ist, rufe ich die Daten im ioBroker ab, sehe ich die Temperatur, Status, etc. alles....

Ich nutze die neuste Version. Das ganze läuft auf dem Raspberry Pi 4, 4GB v3.
Das Funkmodul ist per USB-Modul angeschlossen. 

Wie finde ich/ihr heraus woran das liegen könnte? :-)

Danke für die Hilfe.

Gruss

**Comment by alexreinert** [comment]
Welches OS wird genutzt, 32 oder 64 Bit?
Was liefert debmatic-info? Wie sieht die /var/log/hmserver.log aus, wie die /var/log/syslog und /var/log/messages?
Wurde der Browsercache gelöscht und die Webseite mal Strg+F5 neu geladen?

**Comment by trevon88** [comment]
Hallo, 
Ich habe alles nun ein 3tes mal neu Installiert.
Ich habe das Gefühl das irgend ein Addon die Homematic runtergezogen hat.

Nun läuft IoBroker und Debmatic ohne irgend eine Einstellung zu ändern seit 2 Tagen.
Ich werde nun langsam die Addons wieder hinzufügen, um zu schauen an was es lag.

Was ich bei der 3ten Installation anders gemacht habe: - Kernelupdate per "sudo rpi-udpate"
Es wird zwar überall geschrieben, das zu unterlassen. Aber vielleicht hat das schon das Problem gelöst.

Raspberry PI 4
Platform: linux
os: linux
Architecture: arm
CPUs: 4
Speed: 1500 MHz
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.7 GB 
System uptime: 2 T. 22:33:24
Node.js: v12.19.0
NPM: 6.14.8
Disk size: 14.3 GiB
Disk free: 11.9 GiB
adapters count: 312
Uptime: 2 T. 23:06:21
Active instances: 3

**Comment by trevon88** [comment]
Hi, 
Also ich bin der Sache ein wenig näher gekommen.
Wird das Raspberry PI4 vom Netz genommen und wieder eingesteckt, bekomme ich keine Verbindung zu den Geräten.
Die Homematic WebUI funktioniert, das blaue Licht leuchtet. Aber keine Verbindung zu HomematicIP Geräten. Auch nach 30 Minuten nicht.

Mache ich dann in der Konsole "Sudo Reboot"...
Erhalte ich nach dem Reboot direkt 20 Sekunden später die Werte im IoBroker. 
Das Homematic WebUI zeigt nun, das die Heizungssteuerung Geräte (HmIP-eTRV-B) "AUS" sind.

Drücke ich dann auf EIN springen die Steuerung und die Regler auf 30 Grad, -> Dann drücke ich AUTO.

Ab diesem Zeitpunkt läuft alles einwandfrei und es gibt keine Probleme mehr.
Reboot und Updates lassen sich auch jederzeit machen. Die Geräte werden automatisch wieder erkannt.

Beim nächsten Spannungsverlust geht das Spiel wieder von vorne los, die oben erwähnten Schritte, funktionieren jedes mal.

Komische Sache....
Um also keine Überraschungen zu erleben, wird das ganze an eine USV gehängt, somit ist das Problem erstmal "überbrückt".

**Comment by alexreinert** [comment]
Tritt das Problem mit der aktuellen Version noch auf?

**Comment by trevon88** [comment]
HI,
Hab alles geupdatet, Raspberry, Debmatic etc... 
Funktioniert soweit alles...

Ist es normal, das wenn ich mich direkt einlogge, die Heizungsregler auf AUS sind?
Ich konnte dann auf EIN klicken, und die Verbindung war direkt und ohne Probleme da...
2 Reboots gemacht, beide mal hat es direkt geklappt.

Scheint okey zu sein 👍 Ich beobachte! Danke fürs nachfragen.

**Comment by alexreinert** [comment]
Es ist (leider) normal, das die HmIP Regler nach einem Neustart nicht den korrekten Status zeigen. Das kann man entweder durch eine Aktion aktualisieren oder wenn die sich zyklisch wieder melden.

**Comment by trevon88** [comment]
Alles klar, dann teste ich das noch eine Woche. Wenn nichts mehr kommt, werde ich den Beitrag schliessen. Danke für den schnellen Support :D

**Comment by trevon88** [comment]
Läuft Stabil und ohne Fehler. Darum schliesse ich hier.

Vielen Dank für denn schnellen Support!

**Comment by eloo** [comment]
Hi, 
ich würden dieses Issue gern wieder aufmachen, da ich aktuell das selbe beobachtet hab.

Infos:
Linux odroidc2 5.9.12-meson64
debmatic version: 3.55.5-61
HMRF Hardware:  RPI-RF-MOD
UI: HomeAssistant
Homematic Devices:
- HmIP-BWTH
- HmIP-STHO
- HmIP-RC8

Worum gehts:
Ich hab auch wie @trevon88 beobachtet dass in Homematic keine aktuellen Daten mehr vorhanden sind, jedoch meldet der Temperatur-Sensor brav weiterhin an HomeAssistant.
Auch meine Fernbedienung funktioniert einwandfrei. 
Regeln des BWTH funktioniert auch.
In Homematic wird jedoch das "last modified" Feld nicht gesetzt. Auch ändert sich kein Status in Homematic. 
Das wäre im allgemeinen kein Problem und wäre mir auch egal, aber leider scheinen Systemvariablen auch betroffen zu sein. Ich habe eine Variable für den Zustand des Heizungsventils und dieses wird jetzt nicht mehr geupdated. 

Wie auch bei @trevon88 gab es einen Stromausfall, ob dieses Verhalten aber jedoch nur bei Stromausfall ist kann ich aktuell noch nicht sagen.

Bei mir hat ein restart von debmatic geholfen.
Im Allgemeinen ist es so aber recht blöd da ich mich nicht drauf verlassen kann. 
Gibt es aktuell eine Möglichkeit dieses Problem feststellen zu können? Eine Systemvariable mit der aktuellen Zeit oder sowas? Die dann vlt stehen bleibt? 

Beste Grüße
eloo

**Comment by eloo** [comment]
@alexreinert können wir dieses thema wieder aufmachen? 
oder soll ich neues ticket erstellen? 

ich hab das problem mit dem stromausfall auch wie von trevon beschrieben. Ist auch reproduzierbar. 
Bei einem normalen neustart tritt es nicht auf.

Besten Dank
