### ISSUE TITLE
Update 3.53.34.55

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#164]
Hallo , ich habe heute das Update aufgespielt und bekomme nun als Servicemeldung : HB-UNI-Sen-TEMP-DS18B20 UNITEMP001:0 Garätekommunikation gestört. Dieses Gerät habe ich aber nicht und ist auch nicht unter den Geräten aufgeführt.
Was kann ich nun machen?

**Comment by alexreinert** [comment]
Update von welcher Version aus?
Das ist kein Gerätename, sondern ein Kanalname. Daher die Frage, hast oder hattest du mal ein entsprechendes Gerät?

**Comment by heinog** [comment]
Ich habe von der vorigen Version die du Bereitgestellt hattest auf 3.53.34.55 upgedatet. Dieses Gerätkenne ich nicht und habe ich auch nie gehabt.

**Comment by heinog** [comment]
Gerät befand sich im Posteingang. Habe zufällig mal nachgesehen. Dort konnte ich es problemlos löschen. Nun ist alles Ok
