### ISSUE TITLE
Diagramme lassen sich nicht löschen oder bearbeiten

### ISSUE THREAD

**Issue by mhofmann365** [alexreinert/debmatic#165]
Hallo, ich habe eine Sicherung aus PiVCCU3 in Debmatic eingespielt. Debmatic läuft auf einer VM in Proxmox. Ich wollte heute bestehende Diagramme im WebGUI editieren, was nicht funktioniert. Auch löschen der Diagramme ist nicht möglich. Liegt es vieleich an der Rechtevergabe der Diagramm Dateien im Verzeicniss /media/usb0/measurement ?

mhofmann@debmatic-vm:/media/usb0/measurement$ ls -alh
total 3.1M
drwxr-xr-x 2 root root 4.0K Nov 19 20:34 .
drwxr-xr-x 3 root root 4.0K Nov 18 16:09 ..
-rw-r--r-- 1 root root 460K Nov 19 20:28 13.rrd
-rw-r--r-- 1 root root 460K Nov 19 20:29 19.rrd
-rw-r--r-- 1 root root 613K Nov 19 20:28 23.rrd
-rw-r--r-- 1 root root 154K Nov 19 20:27 24.rrd
-rw-r--r-- 1 root root 613K Nov 19 20:29 25.rrd
-rw-r--r-- 1 root root 154K Nov 19 20:28 26.rrd
-rw-r--r-- 1 root root 307K Nov 19 20:28 3.rrd
-rw-r--r-- 1 root root 307K Nov 19 20:29 4.rrd
mhofmann@debmatic-vm:/media/usb0/measurement$

Vielen Dank für die Untertützung

**Comment by alexreinert** [comment]
Welche Version wird eingesetzt? (Am besten Ausgabe von debmatic-info)

**Comment by pow4all** [comment]
Hallo, bei meiner Installation habe ich dasselbe Problem. 

Ich habe debmatic auf neustem Raspberry OS Lite aufgespielt und drei Diagramme erstellt. Wenn ich eines der Diagramme löschen möchte kommt beim ersten Versuch keine Fehlermeldung, es wird das Diagramm aber nicht gelöscht. Beim zweiten Versuch kommt dann die Fehlermeldung: "Das Diagramm konnte nicht gelöscht werden".

In der Logdatei finde ich dann folgenden Eintrag:
`Dez. 30 21:49:05 de.eq3.lib.datalogging.rrd.RrdDatalogging WARN  [vert.x-worker-thread-14] The diagram 2 is unknown`

Beim Editieren kommt gleich die Fehlermeldung "Das Diagramm konnte nicht gespeichert werden".

Ein USB-Stick (8 GB, ext4) ist angeschlossen und soweit ich sehe auch eingebunden. Pro Diagramm wurde eine *.rrd-Datei erstellt. (Bemerkung: Ich habe den USB-Stick aber erst nach dem Erstellen der ersten beiden Diagrammen eingesteckt)

Folgende Informationen meiner Installation (letzte vier Zeichen -> zzzz)
```
debmatic version: 3.53.34-59
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993zzzz
 Radio MAC:     0xFFzzzz
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993zzzz
 Radio MAC:     0xB8zzzz
```
Ein Neustart des RPi bringt nichts. Wie kann ich die Diagramme wieder löschen?
