### ISSUE TITLE
Zigbee TI CC2532 under Homeassistant not working after installing debmatic on Pi 4 under Rasbian os 32 Bit

### ISSUE THREAD

**Issue by Flitzebogen** [alexreinert/debmatic#166]
I have a fresh setup with Supervised Homeassistant using the TI CC2532 for Zigbee Home Automation. It works very well until i install debmatic as you describe. Homeassistant does not find the zigbee devices anymore the operate led on the stick is not on anymore. I have tried the setup a few times, as sonn as i install the debamtic packages it does not work anymore.

**Comment by alexreinert** [comment]
Please provide some more information how that device is connected to your pi.
