### ISSUE TITLE
Debmatic als HM LAN Gateway nutzen

### ISSUE THREAD

**Issue by custodis-intestina** [alexreinert/debmatic#167]
Huhu

Habe heute mal einen Versuch gestartet.

Problem: Einige HM Aktoren/Sensoren haben schlechte RSSI Werte.
Idee: Orange Pi Zero als HM LAN Gateway verwenden.
OS: Armbian 20.11 Focal Kernel 5.8.16-sunxi

Debmatic hat sich ohne Probleme installieren lassen. Funkmodul ist das HM-MOD-RPI-PCB
Wurde gefunden und ist ansprechbar.

Jetzt kam ich auf die Idee Debmatic genauso umzustellen wie Raspimatic.
Aber die Datei "/usr/local/HMLGW" hat keinerlei Auswirkungen.

WebUI nachwievor erreichbar und die Zentrale sagt "keine Verbindung"

Meine Frage ist...
-Kann man Debmatic als HM LAN Gateway nutzen? Wenn ja wie?
-Gibt es als alternative ein Raspimatic Image (Würde meinem WLAN Zugangs Projekt im Wege stehen)

LG Steve

**Comment by alexreinert** [comment]
siehe #142

**Comment by custodis-intestina** [comment]
Ok Danke, das hat mir meine Google Suche nicht gezeigt. Allerdings scheint das Projekt nicht weitergeführt zu werden.

**Comment by alexreinert** [comment]
Korrekt, aber das ist auch genau das Projekt, welches hinter dem hmlangw Modus von RaspberryMatic steckt.
