### ISSUE TITLE
Debmatic stürzt ab nach Update vom 07.12.2020

### ISSUE THREAD

**Issue by meier81** [alexreinert/debmatic#169]
Hallo und guten Abend,

erst mal vorne weg, super Entwicklung und echt stabile Releases hier.

Habe aber seit dem Update vom 07.12.2020 reproduzierbare Abstürze vom debmatic, diese legen dann letzendlich das ganze System lahm.

Zu meinem Aufbau: Bei mir läuft Debian 10.7 auf einer QNAP-NAS als VM (kein Docker). Als Funkmodul habe ich das HM-MOD-RPI-PCB in Verbindung mit der HB-RF-ETH, FW-Version 1.2.3.
Als Hardware habe ich bis auf ein Gerät nur HMIP im Einsatz, diese funktionieren auch alle weiterhin einwandfrei. Als "klassisches" HM-Gerät habe ich ein HM-Dis-WM55, dieses wird über ein Skript aus der CCU angesprochen. Sobald ich dieses jetzt bediene und blättern möchte geht der erste Tastendruck noch und das Display zeigt mir auch die dazugehörige Seite an, ab dann ist das System wie eingefroren, es geht nichts mehr.

Lediglich auf der Shell sehe ich Fehlermeldungen, hier ein Screenshot:
![Error](https://user-images.githubusercontent.com/40598096/101531059-06ae6400-3993-11eb-8c91-10a0c6c93e98.JPG)

Im Status der HB-RF-ETH sehe ich das auch keine Verbindung zur CCU besteht, ich muss die VM hart ausschalten und neu starten, dann geht wieder alles bis zur Bedienung mit dem Display.

Ich halte mein System so gut es geht immer aktuell, d.h. ich war mit debmatic auch aktuell vor der Version von gestern, von daher kann ich ziemlich sicher sagen der Fehler muss im gestrigen Update sein.

Könnest du dir das mal anschauen, falls ich weiter Infos liefern soll melde dich einfach.

Gruß

Markus

**Comment by meier81** [comment]
Hab eben gesehen es kam vorhin nochmal ein Update raus, das habe ich installiert und der Fehler von oben ist jetzt soweit ich es testen konnte erstmal behoben, habe nun aber das Problem das in den Geräten unter Status und Bedienung die HMIP-Geräte nicht mehr aufgelistet werden, sie funktionieren zwar und ich bekomme die Werte in mein FHEM rein, sie fehlen aber in der CCU. Auch bei den Einstellungen sind die Geräte nicht gelistet. Hier mal ein Screenshot:

![Status](https://user-images.githubusercontent.com/40598096/101536280-11b8c280-399a-11eb-8e16-970e5865376e.JPG)

Gruß

Markus

**Comment by alexreinert** [comment]
Kann es sein, dass die VM nur einen CPU Core zugewiesen hat? Dann bitte mal auf 2 oder mehr stellen und nochmal testen.

**Comment by meier81** [comment]
Hallo und guten Abend, ja die VM hatte nur einen Core, habe jetzt 2 zugewiesen und von 1GB auf 2GB Ram hochgestellt. Habe anschließend bemerkt das die Sensoren alle im Posteingang waren, musste dann alle bestätigen und wieder mit dem Namen benennen, jetzt läuft´s wieder.

Gruß Markus
