### ISSUE TITLE
Doku: Other Systems, Debian

### ISSUE THREAD

**Issue by eric2905** [alexreinert/debmatic#17]
Hinweise für die Debian-Doku:

sudo muss mit "apt install sudo" installiert werden (ist bei Debian standardmäßig nicht mehr dabei)

Im Abschnitt "Installation" ==> "1. Hinzufügen des .. Repo" muss als erstes noch ein "sudo apt-install transport-https" eingefügt werden - sonst kommt eine entspr. Fehlermeldung.

**Comment by alexreinert** [comment]
Danke für den Hinweis, werde ich anpassen.

**Comment by eric2905** [comment]
Sorry, der richtige Command lautet
"sudo apt install apt-transport-https"

**Comment by alexreinert** [comment]
Fixed
