### ISSUE TITLE
HAP-Homematic Addon für Debmatic

### ISSUE THREAD

**Issue by Max-80** [alexreinert/debmatic#170]
Hallo Alex Reinert, 
ist für Debmatic das HAP-Homematic Addon in Planung bzw. kann man es schon in Debmatic installieren?

**Comment by alexreinert** [comment]
Bisher hatte ich dieses Addon komplett nicht auf dem Schirm. Kann ich im Moment noch nichts zu sagen.

**Comment by Max-80** [comment]
Schade, den das Addon ist wirklich super, da man die Geräte ganz leicht und vor allem gleich nach Räumen sortiert in Homekit bekommt. 
Ich hoffe das das Addon vielleicht doch noch kommt, denn ich würde auch gerne auf Debmatic umsteigen, denn das ist wirklich eine super Entwicklung.
Aber trotzdem Danke für die Rückantwort.

**Comment by j-p-l** [comment]
Hallo @Max-80, hallo @alexreinert! 
Das [HAP-Homematic Addon](https://github.com/thkl/hap-homematic) würde mich auch sehr interessieren https://github.com/alexreinert/debmatic/issues/118. 
Liebe Grüße!

**Comment by thkl** [comment]
Ich hab echt schon viele Test und Integrations CCU Systeme laufen, ich möchte ungern noch ein neues dazu... hier müsste mir also mal jemand etwas Input liefern.

Vorraussetzungen für den Betrieb ist eine node.js Installation auf der CCU (die CCU3 und RM haben eine) 
Ich bin mit der Version recht konservativ das die CCU3 mit einer alten 8er Node Version daher kommt, also unterstütze ich das ab dieser.

Das Addon macht im Prinzip bei der Installation folgendes:

Anlegen des Pfades /usr/local/addons/hap-homematic und /etc/config/addons/hap-homematic
in /usr/local/addons/hap-homematic wird dann einmal npm install hap-homematic ausgeführt um alles was nötig ist zu installieren. Anschließend wird noch der launcher nach rc.d kopiert.

**Comment by thkl** [comment]
ok falls jemand möchte, hier die Anleitung für die Installation:

https://github.com/thkl/hap-homematic/blob/master/doc/debmatic.md

**Comment by thkl** [comment]
nachtrag ich habe die sachen mal in ein shellscript zusammengefügt:


https://raw.githubusercontent.com/thkl/hap-homematic/master/doc/debmatic.sh

das installiert node + hap + erzeugt den Serviceeintrag und startet den service 
Aufruf ist dann http://ip:9874 ...

**Comment by alexreinert** [comment]
@thkl Vielen Dank dafür!

**Comment by thkl** [comment]
Kein Problem, ich habe leider Null Ahnung, wie man ein debian Packet baut  ... daher so

**Comment by ChrWi** [comment]
Cool, danke Thomas! Dann kann ich demnächst mal debmatic ausprobieren. 
@alexreinert dann würde mir nur noch hm_pdetect als addon fehlen, um auf pivccu verzichten zu können

**Comment by thkl** [comment]
@ChrWi für hm_pdetect gibt es doch eine manuelle Installationsanleitung auf der GitHub Seite https://github.com/homematic-community/hm_pdetect

Mal probiert ?

**Comment by ChrWi** [comment]
In der Tat bisher nicht wahrgenommen. Dann hindert mich nichts daran, debmatic auszuprobieren!
