### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by 00joshi** [alexreinert/debmatic#171]
editiert: Ich habe inzwischen herausgefunden wie man das Passwort resettet. Vielleicht kann man das in die Anleitung aufnehmen.

1. systemctl stop debmatic
2. in /etc/config/homematic.regadom hinter <property>pwdSet</property> <value> true </value> auf false ändern
3. systemctl start debmatic.service

**Comment by trevon88** [comment]
Stimmt das noch? Bei mir scheint das nicht zu klappen =(
Danke

**Comment by 00joshi** [comment]
Ich würde davon ausgehen, dass sich das nicht geändert hat.

Wenn es nicht funktioniert liegt das evtl. daran dass debmatic noch läuft. Das äußert sich u.a. darin, dass die Datei sich immer wiederzurück ändert.

**Comment by ste1nstone** [comment]
Falls jemand das selbe Problem hat man muss nicht nur den pwdSet wert auf false ändern sondern auch den alten Passwort Hash aus pwsha512 löschen
