### ISSUE TITLE
Kann HmIP Thermostat anlernen, aber nicht nutzen

### ISSUE THREAD

**Issue by Einhardj** [alexreinert/debmatic#172]
Hi,

Config: Raspberry Pi 4/4GB/SSD Boot mit RPI-RF-MOD auf Raspberry OS.

Ich kann meine HmIP Thermostate ( HmIP-eTRV-B und mehrere HMIP-eTRV-2) zwar mit dem beschriebenen Prozedere koppeln. Gleich danach bricht aber jegliche Kommunikation ab und wenn ich den PI reboote sind alle Geraete weg. Was kann ich tun, um Licht ins Dunkel zu bringen?

![Screenshot_2020-12-11 HomeMatic WebUI](https://user-images.githubusercontent.com/60143590/101932038-8417e580-3bda-11eb-810e-ccc8df31d914.png)

Grueße Einhard

**Comment by alexreinert** [comment]
Such mal nach "Raspberry Pi 4", "USB 3" und HmIP. Der Pi sendet in der Kombi einfach massiv Störstrahlung aus und die stört HmIP mit seinem Listen-Before-Talk. Softwaremäßig nicht lösbar, sondern nur durch entsprechenden Abstand zwischen Pi und Funkmodul, z.B. mittels HB-RF-USB-2 oder HB-RF-ETH.

**Comment by Einhardj** [comment]
Ich habe die Threads dazu gelesen, wollte es aber trotzdem erstmal so versuchen. 
Danke trotzdem fuer die schnelle Antwort:
Zusatzfrage: Warum verliert debmatic die Geraete nach einem reboot? Das sollte nicht an der schlechten Kommunikation liegen oder?

Gruß Einhard

**Comment by alexreinert** [comment]
Von sowas höre ich zum ersten Mal.

**Comment by alexreinert** [comment]
Bitte mehr Infos dazu.

**Comment by Einhardj** [comment]
Scheint jetzt nicht mehr der Fall zu sein. Das HmIP-eTRV-B hat den letzten reboot ueberstanden. Vielen Dank erstmal fuer die schnellen Antworten.

**Comment by Einhardj** [comment]
Ich muss hier leider nochmal reingraetschen: Ich habe jetzt auf Pi3 umgestellt, und dieselben Probleme. Die Thermostate (HMIP-eTRV-2) werden nicht gefunden und HmIP-eTRV-B hat große Kommunikationsprobleme. An welcher Schraube koennte ich noch drehen?

**Comment by alexreinert** [comment]
Was für ein Netzteil setzt du ein? Wenn es nicht das von ELV an der Buchse vom Funkmodul ist, könnte es auch das sein. Insgesamt hilfreich wäre es mit deinem Problem das Homematic Forum zu besuchen, das tritt in ähnlicher Weise recht oft auf und dort gibt es schon etliche Einträge, wie man das Problem systematisch eingrenzen kann.

**Comment by Einhardj** [comment]
Vielen Dank fuer deine Antwort. Ich nutze das originale Raspberry Pi 3 Netzteil. Ich weiß, dass auch das nicht ideal ist. Im Moment bin ich aber schon weiter. Debmatic hat meine Versuchsthermostate angenommen, behaelt sie und die Kommunikation scheint im Moment auch zu funktionieren. Mal sehen, was noch auf mich zu kommt. Vielen Dank auch schon mal an dich fuer deine Arbeit an Debmatic. 

Gruß Einhard
