### ISSUE TITLE
Geräte anlernen nicht möglich

### ISSUE THREAD

**Issue by hoggle64** [alexreinert/debmatic#173]
Hallo,

ich habe folgende Hardware:
Raspberry Pi 4 8GB
RPI-RF-MOD
2 Homematic Fensterkontakte HMIP-SWDO

Ich habe debmatic nach Anleitung ohne Probleme installieren können.
Services laufen, Webgui funktioniert.

Nun zum Problem:
Die LED leuchtet zunächst konstant blau.
Dann auf: "Geräte anlernen"
Weiter mit: "Homematic IP Gerät mit Internetzugang anlernen"
LED leuchtet immer noch blau
Dann drücke ich kurz den Pairing Button auf dem Sensor
Die LED blinkt ab diesem Zeitpunkt dann nur noch blau/gelb
Der Posteingang bleibt immer leer - keine Geräte werden gefunden

Nur ein systemctl restart debmatic lässt die LED dann wieder dauerhaft blau leuchten.

    pi@raspberrypi:~ $ sudo su - 
    root@raspberrypi:~# debmatic-info 
    debmatic version: 3.53.34-59
    Kernel modules: Available
    Raw UART dev:   Available
    HMRF Hardware:  RPI-RF-MOD
    Connected via: GPIO (/dev/raw-uart)
    Board serial:  5A4993DA5C
    Radio MAC:     0xFFDA5C
    HMIP Hardware:  RPI-RF-MOD
    SGTIN:         3014F711A0001F5A4993DA5C
     Radio MAC:     0xB266C0

Danke vorab für jede Unterstützung.

**Comment by hoggle64** [comment]
PS: Wer den Fehler findet kriegt ne Kiste Bier.

**Comment by alexreinert** [comment]
Ich sehe hier zwei potentielle Problemursachen:

Der Raspberry Pi 4 erzeugt jede Menge Störstrahlung, welche HmIP mit seinem Listen-Before-Talk massiv stört, vor allem, wenn USB3 genutzt wird. Einzige wirkliche Lösung dafür ist das Absetzen des Funkmoduls per Flachbandkabel, HB-RF-USB-2 oder HB-RF-ETH.

Zusätzlich sollte man HmIP Geräte anders anlernen:
* Werksreset vom anzulernenden Gerät (selbst bei fabrikneuen Geräten)
* Spannungsversorgung vom anzulernenden Gerät trennen bzw. Batterien raus.
* Anlernmodus in der CCU starten
* Spannungsversorgung wieder herstellen, nichts drücken
* Warten bis der Countdown in der CCU abgelaufen ist, erst danach in den Posteingang wechseln

**Comment by hoggle64** [comment]
Beide Maßnahmen haben leider nichts bewirkt.
Es bleibt beim gelb-blauen blinken und einen leeren Posteingang.

**Comment by alexreinert** [comment]
Sind die Geräte möglicherweise schon alleine vom Posteingang weitergewandert zu den Geräten.

**Comment by hoggle64** [comment]
Hallo Alex, hatte ich auch schon geschaut. Leider nicht.
Ich habe gestern noch alles Mögliche ausprobiert. Das Verhalten ist immer wie oben beschrieben. Ist möglicherweise die Platine kaputt ?

**Comment by hoggle64** [comment]
Ich habe mir jetzt nochmal das Modul nachbestellt "**HM-MOD-RPI-PCB**" damit ich über die Feiertage wenigstens eine kleine Chance habe dass irgendwas funktioniert.

**Comment by hoggle64** [comment]
Was interessant ist, ist die Tatsache dass die Funkverbindung vom Sensor in Richtung Platine funktionieren muss.
Die LED wechselt vom Status "blau" zum Status "blinkt blau/gelb" immer dann wenn ich die Batterie in den Sensor einlege und dieser dann kurz blinkt. Lass ich die Batterie raus bleibt die LED auf dem Board weiterhin blau.

Also diese Richtung funktioniert. Das was danach kommen müsste hakt dann.

**Comment by alexreinert** [comment]
Bitte editier mal die Datei /etc/config/log4j.xml und änder im Block
```
        <category name="de.eq3">
                <priority value="INFO" />
        </category>
```
INFO in DEBUG.

Danach dann einmal debmatic neu starten, 5 Minuten warten und nochmals anlernen.

Danach dann bitte den Inhalt der /var/log/hmserver.log ab dem Zeitpunkt des Neustarts hier posten.

**Comment by hoggle64** [comment]
[hmserver.log](https://github.com/alexreinert/debmatic/files/5701154/hmserver.log)

**Comment by hoggle64** [comment]
Genau so gemacht...

**Comment by hoggle64** [comment]
Ich lese im Zusammenhang mit meinem Problem immer wieder von Leuten die das Problem lösen konnten indem Sie eine Firewall Einstellung in der WebGUI? gesetzt haben für Port 8443. Diese Einstellung gibt es aber (offensichtlich) in Debmatic nicht.

Im Log sehe ich jetzt aber folgenden Eintrag:

    AP 3014F711A0001F5A4993DA5C: send data to Frontend Server (jdID 3014F711A00000DBE997279D) at secgtw.homematic.com:8443

**Comment by hoggle64** [comment]
Vielleicht ist folgende Info noch wichtig:

![Bildschirmfoto vom 2020-12-16 09-27-37](https://user-images.githubusercontent.com/3114746/102323671-13c5e700-3f81-11eb-8830-beb6badd9f88.png)

**Comment by alexreinert** [comment]
Das hier ist das zentrale Problem:
```
Dez. 16 08:55:07 de.eq3.cbcs.lib.hmiptrxcommadapter.internal.HMIPStack DEBUG [Thread-5] AP 3014F711A0001F5A4993DA5C: HMIP Stack response TIMEOUT
```

Das Funkmodul kann seine Antwort nicht senden. Die wahrscheinlichsten Gründe dafür sind entweder ein Defekt der Sendeeinheit bzw. Antenne des Funkmoduls oder ein Störer auf 868 MHz, so dass das Funkmodul aufgrund des Listen-Before-Talks nicht senden kann. Störer kann hier der bereits genannten Raspi 4 sein, ein anderes Gerät auf 868 MHz, aber theoretisch auch eine unsaubere Spannungsversorgung mit einem hohen  Ripple.

**Comment by hoggle64** [comment]
O.k. - erstmal danke für die Info...
Dann probiere ich jetzt noch ein anderes Netzteil und versuche Funkmodul und Pi noch besser voneinander abzuschirmen.

**Comment by hoggle64** [comment]
...leider erfolglos

**Comment by hoggle64** [comment]
Ich habe jetzt nochmal den Versuch unternommen das Funkmodul gegen den Pi4 mit einer Blechplatte abzuschirmen(siehe Foto).
Auch hier kein Erfolg. Ich bin der Meinung dass Störstrahlung nicht der Grund sein kann - vor allem wenn User [reporten ](https://github.com/alexreinert/debmatic/issues/175#issuecomment-747070863) dass es unter Raspberrymatic funktioniert.

Ich wär Dir sehe dankbar @alexreinert wenn Du nochmal in den Code schauen könntet. Es muss einen Unterschied geben.

**Comment by alexreinert** [comment]
Ich kann da nicht in den Code schauen, der hmserver is Closed Source von eQ-3 und wird in gleicher Form in der CCU3 und RaspberryMatic  verwendet. Und die Kommunikation zwischen hmserver und Funkmodul funktioniert ja offensichtlich.

Noch dazu verwendest du jetzt das HM-MOD-RPI-PCB, welches direkt von der 3.3V Versorgung des Pis abhängt und die ist alles andere als sauber. Je nach Netzteil wird das dann noch schlimmer. Das ist die große Verbesserung vom RPI-RF-MOD, das erzeugt sich seine 3.3V Versorgung selber und das ELV Netzteil ist sauber entstört.

Die Diskussion mit dem Raspberry Pi 4 habe ich jetzt aber schon mehrfach geführt und regelmäßig bekomme ich da dann die Rückmeldung, dass es auf "magische" Weise funktioniert, sobald die HB-RF-USB bzw. die HB-RF-USB-2 verwendet wird, welche zum einen das Funkmodul weit vom Pi absetzt und zum anderen einige Bauteile zu Spannungsstabilisierung drauf hat.

**Comment by hoggle64** [comment]
O.K. dann kaufe ich mir jetzt noch das dritte Modul.
Welches würdest Du dann empfehlen ?
HB-RF-USB oder HB-RF-USB-2 ?

**Comment by alexreinert** [comment]
Die HB-RF-USB-2 hat den besseren Formfaktor (identisch zum Raspberry Pi 3B). Wobei nur natürlich vor dem Kauf gerne auch mal probieren kannst, ob du die Probleme mit RaspberryMatic auch hast.

**Comment by jutonium** [comment]
Ich hatte erst in #175 gepostet, aber der Thread ist passender.
Hardware: RPI 4B, 8GB RAM, ofizielles RPI Netzteil, SSD-Boot (USB3), RPI-RF-MOD an ca. 30cm langem Flachbandkabel. Gleicher Timeout Fehler.

Gleiches Setup, keine Geräte am USB, Start von SD Karte und auf einmal lassen sich Geräte problemlos anlernen und Befehle an die Geräte senden.

Würde es helfen die +5V und die +3,3V Stromversorgung für den RPI-RF-MOD zu filtern?

Ich habe auch das dumpfe Gefühl, dass die Probleme erst mit einem Kühlkörper auf dem USB-Contoller gekommen sind. Ich möchte den jetzt aber auch nicht wieder abnehmen. Vorher ging das anlernen, es gab Service Meldungen, aber die waren jeweils nach spätestens einer Minute abgearbeitet. Ein Firmware Update eines HmIP-eTRV-2 war auch über Nacht ausgeliefert.
Danach hatte ich erst die Kühlkörper installiert.

**Comment by alexreinert** [comment]
Das unterstreicht meine Aussage am Anfang.
Von Intel gibt es eine App-Note, dass die USB3 Controller Störstrahlung auf 868 MHz emmittiert. Ein direkt aufgeklebter Kühlkörper kann hier u.U. natürlich als Antenne wirken.
Das Filtern kann möglicherweise helfen, aber auch dann ist man halt nur ca. 10cm zwischen Störer und Funkmodul.

**Comment by hoggle64** [comment]
Ich habe mit jetzt on-top die externe USB Platine(HB-RF-USB-2) bestellt die nächste Woche ankommt lt. Webshop.
Das ist jetzt meine letzte Hoffnung. Ich berichte dann wieder hier...

**Comment by jutonium** [comment]
+30cm Flachbandkabel. Mein Gedanke war in das Kabel einen (EMV) Filter auf +5V mit in die Spannungsversorgung einzusetzen.

Würde es helfen die Antenne mit Coax-Kabel vom RPI-RF-MOD abzusetzen? Anleitungen gibt es dafür diverse. Ich frage mich, ob die Abschirrmung des Funkmoduls ausreichend ist.

RPI von SD gestartet, USB-Platte angeschlossen und schon wieder erscheinen die Servicemeldungen, wenn Befehle an die Geräte übermittelt werden sollen.
Schade.

**Comment by jutonium** [comment]
Nachtrag:
Von der SSD am oberen USB-2 Port gestartet, unterer USB-2 Port frei, keine Devices an den USB-3 Ports.
30cm Flachbandkabel zwischen GPIO und RPI-RF-MOD.
Funktioniert zu 100%

Ich nehme sehr stark an, dass ich beim ersten Versuch den Massenspeicher versehentlich am USB-2 hatte. Dadurch, dass der RPI-RF-MOD direkt auf einem Stacking Header steckte, werden die Störungen so stark gewesen sein, dass jede zweite Aktion zu einer Service Meldung geführt hat, die dann aber nach spätestens 2 Minuten abgearbeitet war.
Also war es wahrscheinlich nicht der Kühlkörper auf dem USB-Chip.

Das Sahnehäubchen wäre natürlich die USB-3 Ports nutzen zu können, auf der anderen Seite will ich die Zentrale weder permanent neu starten, noch  werde ich Videos darauf schneiden. Insofern ist das zu verkraften.

SSD-Boot war mir wichtig, nachdem ich mehrfach von defekten SD-Karten gelesen hatte.

**Comment by alexreinert** [comment]
Ich kann hier wirklich nur die HB-RF-USB-2 empfehlen, man spart sich den Stacking Header, kann alles in gescheite Gehäuse bauen, kann problemlos Abstand zwischen Funkmodul und Raspi bringen und hat noch die Stabilisierung bzw. Entstörung von der Spannungsversorgung. Einfach deutlich weniger Gebastel.

**Comment by jutonium** [comment]
Wenn ich das richtig sehe wird die Platine von der debmatic, piVCCU und Raspberrymatic untersützt. Gibt es Nachteile? z.B. "Reconnects" o.ä.?

**Comment by EinfachMario** [comment]
Da ja jetzt anscheinend alles auf das Absetzen des Funkmoduls hinausläuft, wie ist deine Meinung zum HB-RF-ETH? @alexreinert 

Ist ja noch als experimentell gekennzeichnet, hat ja aber auch noch ein paar Vorteile.

**Comment by alexreinert** [comment]
Das ist die tollste Platine der Welt, was soll ich als Entwickler schon anderes dazu sagen. ;-)

Sie ist experimental, weil da einfach noch etwas die Erfahrung in der Wildbahn fehlt und die im Gegensatz zur USB Platine viel mehr potentielle Unterschiede in den Installationen haben kann (Unterschiedliche Switche, Router, Betriebssysteme, ...) und ich daher sicher bin, dass ich bisher einige Kombinationen im meinem "Testcenter" nicht abgedeckt habe.

In meinen Augen hat sie zwei riesige Vorteile, welche aber nicht überall zum Tragen kommen: Man kann sie deutlich einfacher weit absetzen (z.B. Server im Keller, Funkmodul im EG) und man kann sie auch in Verbindung mit HyperV nutzen, USB fällt dort raus, weil HyperV kein USB Pass Through hat.

**Comment by hoggle64** [comment]
> Ich kann hier wirklich nur die HB-RF-USB-2 empfehlen, man spart sich den Stacking Header, kann alles in gescheite Gehäuse bauen, kann problemlos Abstand zwischen Funkmodul und Raspi bringen und hat noch die Stabilisierung bzw. Entstörung von der Spannungsversorgung. Einfach deutlich weniger Gebastel.

 HB-RF-USB-2 ist heute angekommen. Zusammengelötet, RPI-RF-MOD draufgesteckt, funktioniert.

**Comment by hoggle64** [comment]
PS: Wenn jemand günstig(10 EUR + Versand) das kleine Funkmodul(HM-MOD-RPI-PCB) haben will bitte melden
:-)
Issue kann geschlossen werden.

**Comment by jutonium** [comment]
Hab mir die HB-RF-USB-2 jetzt auch bestellt. Versandkostenfrei war der letzte Impuls, der per Newsletter kam.

**Comment by alexreinert** [comment]
Dann mach ich hier mal zu.

@hoggle64 Danke für das Angebot mit dem Funkmodul, aber ich habe mittlerweile einige davon.

Aber wer bekommt jetzt den Kasten? :stuck_out_tongue_closed_eyes:
(Da ich kein Biertrinker bin, bin ich raus.)
