### ISSUE TITLE
Geräte anlernen nicht möglich 2

### ISSUE THREAD

**Issue by EinfachMario** [alexreinert/debmatic#175]
Hallo,

im Wesentlichen hab ich das gleiche Problem wie in #173 beschrieben. Da sich mein Fall aber nicht 100% gleich darstellt, habe ich mal einen neuen Fall aufgemacht. 

Was habe ich getan:
- ein komplett frisches Raspberry Pi OS auf einem Raspi 4 8 GB installiert
- dann wie in https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md beschrieben alles installiert
- danach kann auf Port 80 auch die WebUI erreicht werden
- dann "Geräte anlernen" betätigt und HmIP Gerät anlernen
- Termostat HmIP-eTRV-2 resettet und nochmals in diversesten Varianten versucht zu koppeln (nebenbei bemerkt, hatte vorher auch schon mal RaspberryMatic  versucht, und dort funktionierte alles mehrfach ohne Probleme, also am anlernen und dem verwendetern RPI-RF-MOD liegt es nicht)
- dann bin ich mal in die Analyse übergegangen

- Inhalt von /var/hm_mode sieht gut aus, das RPI-RF-MOD wird richtig erkannt, auch LED leuchtet blau (Seriennummern usw. habe ich mal durch XYZ ersetzt):
```
HM_HOST='DEBMATIC'
HM_HOST_RAW_UART='raw-uart'
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_HOST_UART_DEVICE_TYPE='GPIO'
HM_HOST_GPIO_RESET=''
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_RTC=''
HM_MODE='NORMAL'
HM_HMRF_DEVNODE='/dev/mmd_bidcos'
HM_HMIP_DEVNODE='/dev/mmd_hmip'
HM_HMRF_DEV='RPI-RF-MOD'
HM_HMIP_DEV='RPI-RF-MOD'
HM_HMRF_SERIAL='XXXXXXXXXX'
HM_HMRF_VERSION='4.2.6'
HM_HMRF_ADDRESS='0xFFZZZZ'
HM_HMIP_SGTIN='YYYYYYYYYYYYYYYYYYYYYYY'
HM_HMIP_SERIAL='XXXXXXXXXX'
HM_HMIP_VERSION='4.2.6'
HM_HMIP_ADDRESS='0xBFZZZZ'
```
- /var/log/hmserver.log enthält folgende Warnung, gefolt von der Info, dass das anlernen abgebrochen wurde (ID vom AP und die ID vom Termostat habe ich wieder durch XY ersetzt)
```
Dez. 16 18:16:33 de.eq3.cbcs.server.core.vertx.keyserver.KeyServerOperation WARN  [vert.x-worker-thread-2] AP YYYYYYYYYYYYYYYYYYYYYYY: Exception while communicating to Frontend Server:
java.net.UnknownHostException: failed to resolve 'secgtw.homematic.com' after 3 queries
        at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:473)
        at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:393)
        at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:188)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
        at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:194)
        at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:177)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:872)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.base/java.lang.Thread.run(Thread.java:844)
Dez. 16 18:16:33 de.eq3.cbcs.server.core.internal.InclusionHandling INFO  [vert.x-eventloop-thread-4] AP YYYYYYYYYYYYYYYYYYYYYYYY: Aborting inclusion process; device XXXXXXXXXXXXXXXXXXXXXXXX will stay in inclusion state UNKNOWN
```
--> Die Kommunikation per Funk funktioniert also, die richtige ID des Termostat wird ja übermittelt

- der HM-Server versucht also secgtw.homematic.com zu erreichen und bekommt das nicht hin, und was ich bisher dazu gefunden habe, kann das Anlernen nicht funktionieren, solange der Server nicht erreichbar ist. Den Sinn habe ich zwar noch nicht verstanden, aber nehmen wir mal so hin. 

- Der Port ist 8443, steht auch so in der /etc/crRFD.conf
```
### Configuration for Inclusion with key server (internet) or local key (offline)
KeyServer.Mode=KEYSERVER_LOCAL
KeyServer.Gateway.URL=secgtw.homematic.com
KeyServer.Gateway.Port=8443
KeyServer.Gateway.SSL.Enabled=true
```

- jetzt mal geprüft, ob der Raspie da hinkommt, also telnet bemüht:
```
telnet secgtw.homematic.com 8443
Trying 81.14.202.208...
Connected to secgtw.homematic.com.
Escape character is '^]'.
```

--> funktioniert also

Jetzt stellt sich nur noch die Frage, wie bekommt man den HM-Server dazu den Server zu finden. In die Richtung habe ich die Datei /etc/config/netconfig gefunden, welche folgendes enthielt:
```
HOSTNAME=0.0.0.0
MODE=DHCP
CURRENT_IP=192.168.0.125
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.0.1
CURRENT_NAMESERVER1=
CURRENT_NAMESERVER2=
IP=0.0.0.0
NETMASK=0.0.0.0
GATEWAY=0.0.0.0
NAMESERVER1=0.0.0.0
NAMESERVER2=0.0.0.0
CRYPT=0
```
Dies habe ich wie folgt abgeändert, da ich vermutete, dass der Server nur mit dieser Konfigurationsdatei versucht einen Nameserver zu finden. In der resolve.conf steht auf jeden Fall der richtige drin.

```
HOSTNAME=0.0.0.0
MODE=DHCP
CURRENT_IP=192.168.0.125
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.0.1
CURRENT_NAMESERVER1=192.168.0.1
CURRENT_NAMESERVER2=
IP=0.0.0.0
NETMASK=0.0.0.0
GATEWAY=0.0.0.0
NAMESERVER1=0.0.0.0
NAMESERVER2=0.0.0.0
CRYPT=0
```

Danach den Server neu gestartet und selbes Bild wie vorher. (Wie ich jetzt beim schreiben dieser Zeilen merke, ist die Datei wieder zurückgesetzt auf die Ausgangswerte, also ohne Nameserver.

Wie kann ich das Problem lösen? Mir sind gerade die Optionen ausgegagen. Im WebUI habe ich zumindest auch keine Option gefunden die Netzwerkdaten zu editieren.

Vielen Dank schon mal für die Hilfe! 

VG Mario

P.S.: die blau/gelbe LED hatte ich übrigens auch mal kurz, aber das scheint mir erstmal eher ein Nebenschauplatz.

**Comment by alexreinert** [comment]
Die /etc/config/netconfig wird nicht vom hmserver verwendet, eine Anpassung dort ist also nicht notwendig.

Wie sieht deine /etc/resolv.conf aus?

**Comment by alexreinert** [comment]
Ein Workaround wäre es, die Anmeldung mit SGTIN und Key zu machen, dann wird der Keyserver gar nicht erst angefragt.

**Comment by EinfachMario** [comment]
Die resolv.conf sieht wie folgt aus:
```
domain Speedport
nameserver 192.168.0.1
nameserver fe80::1%eth0
```

Aber da telnet den Namen auch auflösen kann, muss die eigentlich stimmen.

**Comment by alexreinert** [comment]
Entfern mal die erste und die dritte Zeile der /etc/resolv.conf und starte debmatic neu.
Ich kann mir vorstellen, dass die Java-Komponente nicht damit klar kommt, vor allem, weil da ja eine doch schon recht alte Version genutzt wird.

**Comment by EinfachMario** [comment]
habe die resolv.conf so angepasst, dass nur noch die nameserver Zeile drin ist, hat aber nichts gebracht, selber Fehler.
`nameserver 192.168.0.1`

Wenn ich die Anmeldung mit SGTIN und Key vornehme, komme ich jedesmal in den Zustand, dass blau und gelb abwechselnd blinkt, was ja eigentlich bedeuten sollte, dass eine Servicemeldung bestätigt werden will. Es existiert nur keine.

**Comment by alexreinert** [comment]
Kannst du als Nameserver mal den von Google nehmen (8.8.8.8)?

**Comment by EinfachMario** [comment]
So, geändert auf:

`nameserver 8.8.8.8`

Das gute, es hat anscheinend was gebracht. Das schlechte, es gibt im Log zwar nicht mehr die obige Fehlermeldung, jedoch lande ich jetzt auch hier immer im Zustand, dass die LED gelb und blau blinkt. Scheint fast so, dass sobald vermutlich etwas gesendet werden soll, irgendwas aussteigt. Im Log steht leider abselut nichts in die Richtung. Das logging habe ich im WebUI auch schon so umgestllt, dass alles geloggt werden soll. 

Nachdem ich den Nameserver wieder zurück gestellt habe, bekomme ich im Log wieder die obige Fehlermeldung. Schaut der HM-Server wirklich in die resolv.conf um sich dort den Server zu holen und dann selbst eine DNS-Anfrage zu machen? Scheint ja so zu sein, dass er ein Problem mit dem DNS-Server des Routers zu hat und beim OS fragt er ja anscheinend nicht an, sonst hätte es ja immer funktionieren müssen.

Gibt es noch weitere Logdateien?

Irgendwie muss es doch gehen. In RaspberryMatic läuft es ja auch oder gibt es da noch unterschiede? Der HM-Server scheint ja Java zu sein, das läuft doch bestimmt in allen Variationen ohne große Änderungen.

**Comment by alexreinert** [comment]
In der WebUI kann man leider das Logging des hmservers nicht umstellen, das geht nur über direktes Editieren der /etc/config/log4j.xml (siehe auch #173)
Vermutlich wird dann wie dort auch eine Timeout Meldung auftauchen, welche auf die Störstrahlung vom Raspi 4 hindeutet.

**Comment by hoggle64** [comment]
Hallo,

wie in #173 beschrieben habe ich das gleiche Setup. Ich habe jetzt ein anderes Modul getestet (HM-MOD-RPI-PCB) und wieder exakt das gleiche Problem. Geräte lassen sich nicht anlernen. Ich habe die Platine mittels Kabel abgesetzt und es macht keinen Unterschied. Wenn das Problem Störstrahlung wäre würde ich ein Verhalten erwarten wie "...manchmal geht es - manchmal nicht". Hier geht es aber gar nicht. Kein einziges Mal kam ein Pairing zustande und ich habe es mindestens 50 Mal probiert.

**Comment by jutonium** [comment]
RPI 4, 8GB, SSD-Boot (mit SD-Boot, keine USB-Devices kein Unterschied), offizielles RPI 4 Netzteil
RPI OS 64bit
RPI-RF-MOD mit 30cm langem Kabel vom RPI4 abgesetzt.

Es lassen sich keine Geräte anlernen, gelb-blaue Blinkfolge beim anlernen. Beim Anlernen über Key/SGTIN das gleiche. Reset des Ventils macht keinen Unterschied.

Im Log keine oder kaum verwertbare Einträge:
(kommt über mehrere Versuche hinweg nur einmal vor)
`Dec 17 02:27:17 de.eq3.cbcs.server.core.internal.InclusionHandling INFO  [vert.x-eventloop-thread-5] AP xxxxxxxxxxxxxxxxxxxxxxxx: Device included xxxxxxxxxxxxxxxxxxxxxxxx `
sowohl AP als auch HmIP-eTRV-B SGTIN stimmen. Das Gerät taucht nicht in der Inbox auf.

Bei manchen Anlernversuchen steht kein Eintrag im Log.

Jetzt das abgefahrene: Egal, wie der Versuch verläuft unter /etc/config/crRFD/data/ finde ich jedes Mal die passende 'SGTIN.dev' Datei. Nichts in der Inbox, nichts in debmatic-Web-GUI.

Weiterhin konnte ich die Geräte Anlernen (4.12.20). Damals hatte ich den RPI 4 mit 32 Bit OS aufgesetzt, RPI-RF-MOD war auf Stacking Header und das System (noch) auf einem USB Stick. Damals gab es selten bis manchmal Servicemeldungen beim Konfigurieren.

Der HmIP-eTRV-2 tauchte mit -41dB auf und konnten mit einer frischen Firmware versorgt werden.

Das Backup hatte ich später in eine debmatic 64 Bit eingespielt, alles abgelernt, 2 Thermostate (HmIP-eTRV-B und -2) zurückgesetzt und versucht anzulernen. Kein Erfolg, aber die Dateien unter /etc/config/crRFD/data/ erscheinen verlässlich.
Spiele ich das Backup vom 4.12. ein, kann debmatic mit den nicht-Reset-Thermostaten in 50% der Zeit sprechen.

Inzwischen bin ich mit debmatic auf testing/3.55.5.60 - kein Unterschied.

Welche Version wurde bis zum / am 4.12. ausgeliefert, um das noch ein Mal zu testen.

**Comment by jutonium** [comment]
Oder das hier:
`Dec 14 00:27:56 de.eq3.cbcs.server.core.vertx.keyserver.KeyServerOperation WARN  [vert.x-worker-thread-4] AP 3014F711A0001F5A4993F41E: Exception while communicating to Frontend Server: 
io.netty.channel.ConnectTimeoutException: connection timed out: secgtw.homematic.com/81.14.202.208:8443
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:834)
Dec 14 00:27:56 de.eq3.cbcs.server.core.internal.InclusionHandling INFO  [vert.x-eventloop-thread-5] AP xxxxxxxxxxxxxxxxxxxxxxxx: Aborting inclusion process; device xxxxxxxxxxxxxxxxxxxxxxxx will stay in inclusion state UNKNOWN `

**Comment by EinfachMario** [comment]
Kurzer Zwischenstand auch noch mal hier.

Wie in #173 beschrieben habe auch ich das System über eine SSD am USB-Port am laufen. Als ich es mit RaspberryMatic ans laufen bekommen hatte, wurde über eine SD-Karte gebootet (ohne Gerät am USB-Port). Es scheint also tatsächlich so zu sein, dass bei Geräten am USB-Port Probleme entstehen. 

Das Funkmodul hatte ich schon immer über ein 30cm Flachbandkabel abgesetzt, da sonst kein Standardgehäuse passt (Gehäuse ist übrigens auch aus Metall, was ja anscheinend auch nicht zur Abschirmung beitragen kann. Vermutlich wirken die USB Kabel dann auch noch mal wie Antennen.) 

Ich habe das Flachbandkabel jetzt noch mal dahingehend optimiert, dass das Modul so weit wie möglich vom USB-Port weg kommt und jetzt konnte ich das Gerät anlernen. Auch wenn kurzzeitig die LED rot leuchtete. Auch Einstellungen zu Senden war kein Problem. 

Wie in #173 beschrieben scheint aber das absetzen über ein entsprechendes USB oder vielleicht Netzwerkmodul sinnvoller, dann kann man auch noch ein passendes Gehäuse drum bauen.   

Ich werde weiter berichten :-)

**Comment by hoggle64** [comment]
Muss ich leider auch bestätigen. Wenn ich meine Samsung EVO via USB3 an den Pi hänge ist die Kommunikation wieder gestört. Es lassen sich keine Geräte anlernen. Ziehe ich die Platte raus funktioniert. Sehr ärgerlich...

**Comment by jutonium** [comment]
@hoggle64 ich nehme an, dass es mit der HB-RF-USB-2 jetzt auch mit SSD an USB-3 geht? Hab den Adapter grad geordert.

**Comment by hoggle64** [comment]
Da muss ich Dich leider enttäuschen. Hatte gestern schon im anderen Thread diesbezüglich geschrieben dass bei gleichzeitig angesteckter USB SSD die Kommunikation nicht funktioniert, was das ganze als "Zentrale für alles" wieder ad absurdum führt.

**Comment by hoggle64** [comment]
Wenn das jetzt nicht funktioniert überlege ich gerade debmatic auszulagern auf einen stromsparenden **Pi Zero W**.
Hat da schon jemand Erfahrung ob das funktioniert ?

**Comment by alexreinert** [comment]
Hattest du den Pi und das Funkmodul jeweils in einem Gehäuse? Wie lang ist das USB Kabel? Ich hatte das hier in einem Testaufbau auch mit USB3 laufen, da war aber alles in Gehäusen drin und gut ein Meter Abstand dazwischen.

**Comment by hoggle64** [comment]
Hi Alex,
das USB Kablel ist 1,50m lang. Ich habe es zum Testen maximal weit vom Pi4 entfernt aufgestellt.

**Comment by hoggle64** [comment]
Ich hab's erst nicht geglaubt aber es scheint wirklich wirklich ausschließlich mit Störstrahlung zu tun zu haben.
Gerade hat's gar nicht mehr funktioniert. Habe dann das Funkmodul noch weiter weg geschoben und plötzlich hat es wieder funktioniert. Wenn Du meinst dass ein Metallgehäuse um den Pi hier die Situation verbessern kann probiere ich das auch nochmal aus. Danke für die Info.

**Comment by jutonium** [comment]
Gefühlt kommen wir hier grad in "esoterische Gefilde".
@hoggle64 Hast Du den Adapter jeweils am USB-2 und -3 Port getestet?
Ist am USB-Kabel ein Ferritkern?
Die nächste Eskalationsstufe wäre die USB-Daten durch einen Optokoppler zu schicken für eine 100%ige galvanische Trennung.

**Comment by alexreinert** [comment]
Die Platinenvon mir haben jeweils einen LC-Filter drauf, welche Einkopplungen über das USB Kabel weitgehend eliminieren, die komplette galvanische Trennung dürfte hier noch mehr Probleme bringen (aber dann vin anderer Art). Im Zweifel würde ich da eher den USB Zwischenstecker von ELV zwischenschalten mit einen weiteren LC Filter Array. Sinnvoll ist sicherlich auch ein geschirmtes USB Kabel, damit das Kabel nicht noch zur Antenne wird.
Metallgehäuse kann sicher sinnvoll sein, den exakten Effekt kann ich mangels EMV Labor nicht abschließend beurteilen. Allgemein dürfte jede Abschirmung helfen.

**Comment by alexreinert** [comment]
Wirklich esoterisch ist das ganze nicht. Der Raspi 4 ist einfach bescheiden entstört und dürfte als Fertiggerät in meinen Augen kein CE bekommen. Als Bausatz ohne Gehäuse kann allerdings manche Vorschriften (ganz legal) ignorieren und vollkommen korrekt ein CE Zeichen draufpappen. Wer das ganze dann zum Fertiggerät fertig baut, hat dann halt ein Problem.
