### ISSUE TITLE
Port ändern

### ISSUE THREAD

**Issue by tim-vogel** [alexreinert/debmatic#176]
Hallo,
wie kann man den Port der GUI zuverlässig verändern? 

Ich habe vor das Zusatzpaket ```RedMatic``` zu installieren, da dort die Integration von ```Node-Red``` und ```HomeMatic``` bereits vollständig integriert ist. Zusätzlich möchte ich das Zusatzmodul ```node-red-contrib-amazon-echo``` installieren. Das Zusatzmodul muss auf dem Port 80 lauschen können um für Alexa-Geräte auffindbar zu sein. 
Somit zu meinen Hintergründen. 

Ich habe in der Konfigurationsdatei ```/etc/debmatic/webui.conf``` den Wert ```var.debmatic_webui_http_port``` auf ```8080``` geändert, den Server neu gestartet und die Oberfläche, unter Verwendung des Ports ```8080``` neu aufgerufen. Die Seite hat wurde geladen, aber die Texte werden nur mit den Platzhaltern angezeigt. 

Wo muss ich noch alles den Port von ```80``` auf ```8080``` ändern, damit das System nicht mehr den Port ```80``` blockiert?

![gui](https://user-images.githubusercontent.com/76432438/102772247-7525f580-4387-11eb-84eb-52097bde31ca.PNG)

**Comment by mokkka** [comment]
Hi,

du musst im lighttpd-Server den Port freigeben. Du kannst das normalerweise unter /etc/lighttpd/lighttpd.conf ändern. Die Option heißt server.port und müsste bei dir auf 80 stehen. Wenn du das auf 8080 änderst und den lighttpd server mit 
'sudo systemctl restart lighttpd` 
neustartest müsste der Port frei sein. Danach kannst du etwaige Software installieren die den Port benötigt.
