### ISSUE TITLE
Dialog zum anlernen nicht sichtbar bei Versuch, ohne Funkhardware einen Access Point anzulernen

### ISSUE THREAD

**Issue by kongo09** [alexreinert/debmatic#177]
Ich habe dieses Issue gesehen: #54 und verstehe, dass der Dialog nur etwas anzeigt, wenn auch eine Funkhardware vorhanden ist. Funkhardware habe ich nicht. Debmatic soll im Keller auf einem Raspi laufen, ein HomeMatic IP Access Point ist oben in der Wohnung und den würde ich gerne anlernen.

Das Verfahren ist doch prinzipiell hier beschrieben: https://technikkram.net/blog/2020/09/27/homematic-ip-access-point-als-lan-router-auf-ccu3-installieren-und-anlernen/

Geht das nicht als ausschließlicher Access Point? 

debmatic-info berichtet:

```
pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.53.34-59
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Not assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
```

**Comment by alexreinert** [comment]
Der Access Point kann nur genutzt werden, wenn ein RPI-RF-MOD angeschlossen ist, weil das RPI-RF-MOD nicht nur zum Funken verwendet wird, sondern auch für Kryptooperationen. Mit der HB-RF-ETH wäre es auch möglich, den Rechner im Keller zu haben und das Funkmodul per Netzwerk in die Wohnung abzusetzen.

**Comment by kongo09** [comment]
Vielen Dank für die rasche Aufklärung. Ich hatte gehofft, ohne extra-Investition die CCU testen zu können, bevor ich von der Cloud weg wechsle. Ein extra RPI-RF-MOD hätte ich mir nicht unbedingt kaufen wollen, da ich im Keller ja eh nicht funke. Die Krypto Funktion war mir nicht klar. Schade, dann bleib ich erst mal bei der Cloud, auch wenn das etwas eingeschränkt ist.

**Comment by kongo09** [comment]
Wenn man weiß wonach man suchen muss, findet man die Antworten natürlich auch im Netz: https://homematic-forum.de/forum/viewtopic.php?t=61116

Daher nochmal extra Danke für die schnelle Reaktion, @alexreinert . Und frohes Fest.
