### ISSUE TITLE
Wie kann ich prüfen ob die Echtzeit uhr über HB-RF-USB-2 erkannt wurde

### ISSUE THREAD

**Issue by Kebehsenuef** [alexreinert/debmatic#178]
Hallo und guten Tag

Ist jetzt nicht wirklich ein Fehler, aber eine frage zum RTC modul.
System: RPI 4 mit DietPi.
HM Module HM-MOD-RPI-PCB auf HB-RF-USB-2. 

Funktioniert auch alles. Jetzt habe ich mir mal das RPI-RF-MOD mal angeschaut. Die RTC wird dort über den I2C abgefragt.
Ich hab noch ein RTC  mit einem HYM1307, hab beides mal auf der HB-RF-USB-2 platziert.
Aber wo kann ich jetzt schauen ob die RTC funktioniert?

MfG Kebe

**Comment by alexreinert** [comment]
Der I2C wird auf der HB-RF-USB-2 nicht angebunden, daher funktioniert das so nicht.

**Comment by Kebehsenuef** [comment]
Hallo Alex.

Also würde die RTC des RPI-RF-MOD auch nicht angesprochen werden?

**Comment by alexreinert** [comment]
Genau, die HB-RF-USB-2 wurde ursprünglich von mir dazu entwickelt, das Funkmodul an einen PC anzuschließen und dort braucht man die RTC vom Funkmodul nicht, weil die bereits deutlich genauere RTCs eingebaut haben. Und auf einem Pi kann man bei leerem GPIO Header für weniger als einen Euro eine RTC nachrüsten und auf den GPIO stecken.

**Comment by Kebehsenuef** [comment]
Japp da gebe ich dir recht. Aber die Status-LED wird angesteuert?
Oki da kann ich dann mein Rpi Pcb erstellen das in meinen Pi stack passt. 
Danke dir und ich liebe Deine/Eure Arbeit.

**Comment by alexreinert** [comment]
Ja, die Ansteuerung der LED wird unterstützt.
