### ISSUE TITLE
debmatic auf eine bestimmte IP "binden"

### ISSUE THREAD

**Issue by lullerboi** [alexreinert/debmatic#179]
Hi,

ich würde gerne, statt den/die Port(s) zu ändern, meinem Pi einfach eine zusätzliche IP verpassen und debmatic nur unter dieser laufen lassen.
Außerdem wäre es super, wenn man das vor der Installation schon festlegen könnte, derzeit zerschiesst sie nämlich ungefragt ein installiertes PiHole.

Lässt sich das machen?

Danke!

**Comment by alexreinert** [comment]
Das geht leider nicht, weil die Binaries von eQ-3 das nicht unterstützen und ich diese nicht anpassen kann, weil sie Closed Source sind.

**Comment by alexreinert** [comment]
Einzig könnte man den Lighttpd auf eine entsprechende IP setzen, damit man zumindest Port 80 freibekommt, hier verweise ich auf die entsprechende Doku von Lighttpd.

**Comment by lullerboi** [comment]
Alles klar, vielen Dank für die schnelle Antwort. Zu dem Problem mit dem Installer evtl. eine Idee?

**Comment by alexreinert** [comment]
Das ist kein Problem im Installer, wenn man zwei Anwendungen installiert, welche auf Port 80 arbeiten, dann wird eine davon nicht funktionieren. Welche das ist kann man dabei mit Sicherheit nicht sagen, es kommt da drauf an, welche zuerst gestartet wird und das hängt von vielen Faktoren ab.
