### ISSUE TITLE
Starten nicht möglich mit CUxD

### ISSUE THREAD

**Issue by tidde88** [alexreinert/debmatic#18]
Guten Tag,

ich habe debmatic auf einer VM mit Debian 9 Basis installiert. Das läuft auch alles reibungslos. 

Nun wollte ich gerne CUxD installieren per apt, was funktioniert, aber nun bleibt das Webinterface  bei "Die Homematic CCU ist noch nicht bereit" stehen. Ich habe über 1 Std gewartet und auch schon die VM neugestartet. 

Erst wenn ich CUxD wieder deinstalliere, bootet das Webinterface.

Kann ich Ihnen Logs zur Verfügung stellen, die Ihnen helfen können?

Das System ist folgendes:
Intel NUC mit Proxmox
Kernel: Debian 4.19.28-2~bpo9+1 
HMIP Funkmodul USB

Gruß

Tobi

**Comment by alexreinert** [comment]
Welches Funkmodul wird genau benutzt?

**Comment by tidde88** [comment]
Das HmIP-RFUSB von ELV

**Comment by alexreinert** [comment]
Ok, dann habe ich eine Vermutung: CUxD nimmt im Default alle USB Geräte in Beschlag, welche ein tty Device bereitstellen, dadurch haben die CCU Dienste keinen Zugriff mehr darauf.
Mit TTYASSIGN in den CUxD Settings kann man das Verhindern, siehe CUxD Handbuch.

**Comment by tidde88** [comment]
Das schaue ich mir mal an und gebe dann Feedback, Danke sehr

**Comment by tidde88** [comment]
Es hat geklappt. Vielen dank

**Comment by tidde88** [comment]
Da habe ich mich zu früh gefreut. Mit den Settings 

TTYPARAM=ttyUSB0:9600:8N1
TTYASSIGN=ttyUSB0:CUX
 
in CUxD startet zwar die CCU, aber ich kann kein Geräte mehr anlernen.

**Comment by alexreinert** [comment]
Mit ttyUSB:CUX wird der Stick ecplizit von CUxD genutzt. Wie im Handbuch steht, soll NC verwendet werden, damit keine Verbindung aufgebaut wird. Und die TTYPARAM sollten nicht verwendet werden, weil dadurch die Schnittstellen Parameter verstellt werden. Also insgesamt einfach
```
TTYASSIGN=ttyUSB0:NC
```

**Comment by tidde88** [comment]
Das hat soweit geklappt, danke sehr.

Nun hängt sich die CCU auf, wenn ich ein CUxD Device anlege. 

Ich werde mal weiter schauen
