### ISSUE TITLE
CuxD 2.5

### ISSUE THREAD

**Issue by smooty1970** [alexreinert/debmatic#180]
Hallo.

Nach Neuinstallation von DEBIAN 9 und allen notwendigen IOBROKER und DEBMATIC Komponenten läuft DEBMATIC, aber das AddOn CuxD lässt sich nicht installieren. XML-API konnte ich installieren, CuxD nicht.
Meldung:
`root@vdebian:~# sudo apt install cuxd
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 cuxd : Hängt ab von (vorher): libc6-i386 (>= 2.28) aber 2.24-11+deb9u4 soll installiert werden
        Empfiehlt: digitemp soll aber nicht installiert werden
        Empfiehlt: dfu-programmer soll aber nicht installiert werden
        Empfiehlt: etherwake soll aber nicht installiert werden
        Empfiehlt: socat soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
`
Wie bekomme ich CuxD installiert? Danke

**Comment by alexreinert** [comment]
Leider gar nicht: CuXD braucht mindestens die libc6 in Version 2.28. Debian Stretch ist aber mittlerweile so alt, dass es die nicht hat, sondern nur die Version 2.24. Ohne Update auf Debian Buster wirst du die leider nicht ohne weiteres updaten können.

**Comment by smooty1970** [comment]
Hallo.

Danke für die rasche Rückmeldung.
Nach Upgrade auf BUSTER nun auch CuxD Installation erfolgreich.

Danke
