### ISSUE TITLE
debmatic lässt Aktor HM-LC-Sw4-PCB abstürzen

### ISSUE THREAD

**Issue by 7weazel7** [alexreinert/debmatic#181]
Hallo Herr Reinert,

ich habe ein komisches Phänomen mit einem HM-LC-Sw4-PCB Aktor. Immer wenn ich einen Kanal (inkl. Last ~8V/4mA) über debmatic schalte, ist der Aktor danach nicht mehr erreichbar und ich muss diesen kurzzeit stromlos machen. Dieses Problem hatte ich vor dem Umstieg auf debmatic nicht (alle anderen Aktoren funktionieren wunderbar). Wenn ich den Knopf/Kanal am Aktor mechanisch betätige, passiert hab ich dieses Problem nicht. Einen Reset des Aktors habe ich bereits versucht, leider ohne Erfolg. 

Hier die eingesetzten Komponenten:
- Ubuntu 20.04.1 VM unter Proxmox mit debmatic 3.53.34.59
- LAN-Adapter und HM-CFG-USB
- HM-LC-Sw4-PCB (Firmware 1.12)

Die Dienste laufen alle. Nur den debmatic-ssdpd.service muss ich nach einem Neustart des Systems manuell anschupsen.
![grafik](https://user-images.githubusercontent.com/67899424/103476646-0483cd80-4db8-11eb-9758-2068ae90f60f.png)

Haben Sie eine Idee oder kann ich Ihnen ein paar Logs zur Verfügung stellen?
Grüße

**Comment by alexreinert** [comment]
Ich habe hier leider keine wirkliche Idee und leider wird das auch schwierig zu debuggen sein: Die Kommunikation passiert vollständig im Closed Source des rfd.
Möglicherweise kann man etwas erkennen, wenn man das Loglevel in der WebUI hochschraubt, damit der rfd mehr ins syslog schreibt.

Welche Lösung war denn vorher im Einsatz? Und wie ist der HM-LC-Sw4-PCB konfiguriert?

Je nach Alter könnte ich mir auch ein Problem in der Stabilisierung der Spannung des HM-LC-Sw4-PCB z.B. durch einen sterbenden Elko vorstellen, weil beim Schalten über Funk das Funkmodul zu einem anderen Zeitpunkt senden muss, wie beim manuellen Schalten und zusammen mit dem Schalten des Relays möglicherweise ein Spannungseinbruch passiert.

**Comment by alexreinert** [comment]
Für letzeren Punkt wäre es ein interessanter Test eine Direktverknüpfung mit einem beliebigen Sender zu machen und das Gerät mal darüber zu schalten, ob das Problem dann auch auftaucht.

**Comment by 7weazel7** [comment]
> Für letzteren Punkt wäre es ein interessanter Test eine Direktverknüpfung mit einem beliebigen Sender zu machen und das Gerät mal darüber zu schalten, ob das Problem dann auch auftaucht.

Ich glaube es war so wie sie es geschrieben haben. Der Aktor ist jetzt nach 5 Jahren hinüber und dies ist eben zeitlich zufällig in den Zeitraum des Umzuges auf debmatic gefallen. Habe den Aktor ausgetauscht und alles funktioniert wieder. Danke für Ihre Hilfe.

Was den debmatic-ssdpd.service anbelangt, habe ich einfach eine Startverzögerung in den Dienst eingebaut (ExecStartPre=/bin/sleep 30). Nun funktioniert auch ein Neustart ohne manuelle Nacharbeiten.

Was anderes: Vielleicht könnten Sie in die Doku mit aufnehmen, wie man die Plugins installiert. Es steht zwar drin, dass diese über apt installiert werden können, aber nicht wie :) letztendlich war es ein simples "apt install xm-api"

**Comment by alexreinert** [comment]
> Was den debmatic-ssdpd.service anbelangt, habe ich einfach eine Startverzögerung in den Dienst eingebaut (ExecStartPre=/bin/sleep 30). Nun funktioniert auch ein Neustart ohne manuelle Nacharbeiten.

Das dürfte sich mit Version 3.55.5.61 erledigen, da habe ich eine entsprechende Lösung eingebaut, welche wartet, bis das Netzwerk vollständig gestartet ist, bevor der eigentliche Dienst gestartet wird.

**Comment by 7weazel7** [comment]
Super, freue mich auf das Update. Wann wird dieses veröffentlicht? Soll ich dann diesen sleep wieder rausnehmen?

**Comment by alexreinert** [comment]
Im stable Repository wird es gar nicht veröffentlicht, da in der CCU3 Software 3.55.5 einige kritische Bugs sind. Im testing apt Repository ist sie schon seit fast einem Monat verfügbar. Sobald von eQ-3 eine neue Version rausgebracht wird mit Bugfixes, nehme ich die auch im testing Repository auf und dann nach ca. 2 Wochen ins stable, wenn nicht wieder kritische Bugs drin sind.

Das sleep kannst du erstmal drin lassen, das fliegt bei dem Update von alleine raus, weil alle nicht Config Dateien bei einem apt Update überschrieben werden (nicht nur auf debmatic bezogen, sondern ganz allgemein bei allen Paketen)

**Comment by 7weazel7** [comment]
Danke für die Aufklärung. Ein schönes Wochenende wenn es soweit ist :)
