### ISSUE TITLE
iobroker bekommt keine Antwort mehr über Port 2001

### ISSUE THREAD

**Issue by Schattenruf** [alexreinert/debmatic#182]
Hallo zusammen und hallo @alexreinert und frohes Neues :) 

Ich habe über die Weihnachtstage mein Debmatic neu aufgesetzt, da meine SD-Karte sich verabschiedet hatte. So läuft alles im Bereich HM-IP. Allerdings machen meine Heizkörperthermostate etwas Probleme. Diese sind normale HM und nicht die IP-Varianten.

Ich bekomme in iobroker dazu keine Daten mehr rein. Habe das erneute Auslesen dieser in iobroker probiert aber er legt nix an:
![image](https://user-images.githubusercontent.com/12720317/103484830-07031900-4df2-11eb-8b71-11d9f542874c.png)

Er lädt nur diese Standard-Parameter:
![image](https://user-images.githubusercontent.com/12720317/103484845-1aae7f80-4df2-11eb-8bc6-77b97da2885f.png)

Im Logfile der CCU finde ich folgendes unter /var/log/messages
[messages.txt](https://github.com/alexreinert/debmatic/files/5761993/messages.txt)

Ich sehe hier aber leider nichts für den Port 2001 nur 2010, was HM-IP wäre. 
Wird der Port überhaupt gestartet?
Auf dem Pi 3B ist aktuell nur debmatic installiert, sonst nix. An den iobroker Settings hatte ich nichts gemacht, nur halt die Debmatic-Installation neu angetriggert.
Muss ich hier noch etwas installieren wie die XML-API oder wie kann ich das Problem beheben?

Danke schon mal :)

**Comment by alexreinert** [comment]
Was liefern
```
sudo debmatic-info
sudo cat /var/hm_mode
sudo ifconfig
systemctl list-dependencies debmatic (Bitte Farben der Punkte kenntlich machen)
systemctl status debmatic-rfd
```

**Comment by alexreinert** [comment]
Wird das Thermostat in der WebUI von debmatic korrekt angezeigt?

**Comment by Schattenruf** [comment]
Hi,

danke für die schnelle Info. Ja, die Anzeige ist korrekt und die Steuerung funktioniert auch. Habe gerade auch einen Werksreset auf die beiden Thermostate gemacht und komplett neu angelernt. Leider immer noch keinen Erfolg.

Zu deinen Fragen:
sudo debmatic-info
![image](https://user-images.githubusercontent.com/12720317/103485792-32d5cd00-4df9-11eb-9183-f249fb78a277.png)

sudo cat /var/hm_mode
![image](https://user-images.githubusercontent.com/12720317/103485801-47b26080-4df9-11eb-8df0-a32f198519b1.png)

sudo ifconfig
![image](https://user-images.githubusercontent.com/12720317/103485808-5731a980-4df9-11eb-815a-57da6c716370.png)

systemctl list-dependencies debmatic
![image](https://user-images.githubusercontent.com/12720317/103485823-703a5a80-4df9-11eb-98c6-f2756ca6e23c.png)

systemctl status debmatic-rfd
![image](https://user-images.githubusercontent.com/12720317/103485841-8c3dfc00-4df9-11eb-92ef-b9aa00a66743.png)

Hier liegt wohl der Hund begraben. Hier steht (grüner Punkt):
● debmatic-rfd.service - debmatic rfd
   Loaded: loaded (/lib/systemd/system/debmatic-rfd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-01-03 19:02:34 CET; 23min ago
  Process: 3854 ExecStart=/usr/share/debmatic/bin/start_rfd.sh (code=exited, status=0/SUCCESS)
 Main PID: 3864 (rfd)
    Tasks: 5 (limit: 2063)
   CGroup: /system.slice/debmatic-rfd.service
           └─3864 /bin/rfd -l 5 -f /etc/config/rfd.conf -d

Jan 03 19:22:28 Raspmatic rfd[3864]: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","OEQ2094673:4","CONTROL_MODE",0}],[methodName:"event",params:{"hm-rpc.0","OEQ2094673:4","FAULT_REPORTING",0}],[methodNam
Jan 03 19:22:28 Raspmatic rfd[3864]: XmlRpc transport error
Jan 03 19:23:38 Raspmatic rfd[3864]: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","OEQ2094641:4","CONTROL_MODE",0}],[methodName:"event",params:{"hm-rpc.0","OEQ2094641:4","FAULT_REPORTING",0}],[methodNam
Jan 03 19:23:38 Raspmatic rfd[3864]: XmlRpc transport error
Jan 03 19:24:12 Raspmatic rfd[3864]: XmlRpc transport error calling system.listMethods({"hm-rpc.0"}) on http://192.168.1.202:42001/RPC2:
Jan 03 19:24:12 Raspmatic rfd[3864]: XmlRpc transport error calling listDevices({"hm-rpc.0"}) on http://192.168.1.202:42001/RPC2:
Jan 03 19:25:00 Raspmatic rfd[3864]: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","OEQ2094673:4","CONTROL_MODE",0}],[methodName:"event",params:{"hm-rpc.0","OEQ2094673:4","FAULT_REPORTING",0}],[methodNam
Jan 03 19:25:00 Raspmatic rfd[3864]: XmlRpc transport error
Jan 03 19:25:42 Raspmatic rfd[3864]: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","CENTRAL","PONG","hm-rpc.0"}]}) on http://192.168.1.202:42001/RPC2:
Jan 03 19:25:42 Raspmatic rfd[3864]: XmlRpc transport error

**Comment by alexreinert** [comment]
Ich kenne mich mit ioBroker zu wenig aus, aber die Ausgabe sieht danach aus, dass sich ioBroker mit der Adresse 192.168.1.202 beim rfd registriert, aber eigentlich unter 192.168.1.204 erreichbar ist (dem ersten Screenshot nach).

**Comment by Schattenruf** [comment]
Nee... Also wie gesagt am iobroker habe ich nichts geändert. Der iobroker hat die IP 192.168.1.204 und debmatic die .202 am Ende. HM-IP geht mit denselben Einstellungen und dem Port 2010 und 42010... nur HM bekommt unter dem Port 2001 nix. Es geht auch erst seit dem erneuten Aufsetzen nicht mehr, als ob er den Port 2001 bzw. 42001 nicht richtig versteht... 
Was heißt denn die Ausgabe vom debmatic rfd-service. Das sind ja alles Fehler. Denke es liegt daran.

**Comment by Schattenruf** [comment]
Nachtrag: Er versucht es auch immer wieder, aber alles Fehler:
![image](https://user-images.githubusercontent.com/12720317/103487624-150f6480-4e07-11eb-9dc3-290f7030dba6.png)

**Comment by alexreinert** [comment]
Kannst du bittemal die vollständigen Settings vom Adapter in ioBroker posten, insb. die Einstellung Adapter Callback Address?
Die Fehlermeldung sagt aus, dass der rfd keine Verbindung zum ioBroker aufbauen kann, allerdings wird das auch mit der falschen IP versucht.

**Comment by Schattenruf** [comment]
Die Callback-Adresse ist leer...

Anbei mal die Settings für HM-IP, wo es klappt:
![image](https://user-images.githubusercontent.com/12720317/103487995-a41d7c00-4e09-11eb-93a6-abbdbbcbdda7.png)
![image](https://user-images.githubusercontent.com/12720317/103487998-a7186c80-4e09-11eb-9b8a-dc8b36a51da0.png)

Und hier die für HM:
![image](https://user-images.githubusercontent.com/12720317/103488007-c3b4a480-4e09-11eb-8a88-12837fdeed1a.png)

**Comment by Schattenruf** [comment]
Also eigentlich unterscheidet sich hier nur der Abfrage-Port.

**Comment by Schattenruf** [comment]
So ich habs glaub ich gelöst... Ein
sudo dpkg-reconfigure debmatic mit anschließendem Reboot hat geholfen. Meine Objekte sind jetzt da:
und der Service läuft nun ohne Fehler:
![image](https://user-images.githubusercontent.com/12720317/103488089-476e9100-4e0a-11eb-8e0b-413ec03fe6da.png)
![image](https://user-images.githubusercontent.com/12720317/103488097-51908f80-4e0a-11eb-9a83-a597b9bbf8ef.png)

Falls das nochmal auftritt, melde ich mich... Lag also irgendwie an diesem Service.
