### ISSUE TITLE
Kommunikation zu Homematic IP Thermostat gestört

### ISSUE THREAD

**Issue by Hagenmue** [alexreinert/debmatic#184]
Nach Stromausfall _bleibt_ die  Kommunikation zu den HMIP Thermostaten gestört. DIe Kommunikation wird jedoch sofort wieder aufgenommen, sobald der Thermostat manuell betätigt wird. Fehler ist reproduzierbar durch Abstecken der USB-CCU und erneuten Anstecken. Dieses Verhalten ist fatal, wenn Stromausfall in Abwesenheit auftritt. Gibt es einen Workaround?

**Comment by alexreinert** [comment]
Was bedeutet die Kommunikation bleibt gestört?
Was ist eine USB-CCU?
Welche Thermostate sind genau gemeint?

**Comment by Hagenmue** [comment]
Betrifft die Homematic IP Heizkörperthermostate. Wenn ich über die Weboberfläche eine Temperatur versuche zu ändern, kommt sofort die Fehlermeldung.
![Bildschirmfoto_2021-01-04_22-51-09](https://user-images.githubusercontent.com/36644825/103585596-9b00dd80-4ee3-11eb-8fe1-686361ac0339.png)
 Sichtkontrolle am Thermostat: Temperatur wurde nicht geändert.
Die Fehlermeldung verschwindet, sobald ich einmalig manuell die Temperatur geändert habe.

**Comment by Hagenmue** [comment]
USB-CCU: der USB Stick der Brücke am Raspi für die 866Mhz Kommunikation dient.

**Comment by alexreinert** [comment]
Bitte genaue Bezeichnungen, es gibt da sowohl vei den Thermostaten, als auch bei den USB Geräten vollkommen unterschiedliche Geräte.

**Comment by alexreinert** [comment]
Und auch gleich noch eine Frage hinterher: Welche debmatic Version ist im Einsatz?

**Comment by Hagenmue** [comment]
debmatic 3.53.34-59   armhf
HmIP-eTRV-2

**Comment by Hagenmue** [comment]
Der USB-Stick:
![RF-USB-Stick](https://user-images.githubusercontent.com/36644825/103586789-1cf20600-4ee6-11eb-970d-c0f3934886c5.png)

**Comment by alexreinert** [comment]
Leider habe ich kein entsprechendes Testgerät hier um das nachstellen zu können.

Das Abziehen des USB Sticks sollte man unterlassen, meines Wissens nach ist es im Closed Source von eQ-3 nicht vorgesehen, dass der Stick im laufenden Betrieb abgezogen wird und er wird daher nicht sauber neu initialisiert. Da ist es sogar verwunderlich, dass es überhaupt wieder zu einer Kommunikation kommt.

Einen Stromausfall sollte man nicht nur wegen diesem Problem vorbeugen: Sollte der Stromausfall zu einem sehr ungünstigen Zeitpunkt erfolgen, könnte es sein, dass die gesamte Zentrale wegen Fehlern im Dateisystem nicht mehr hoch kommt. Hier bietet sich eine kleine USV an, welche kurze Ausfälle abpuffert und bei langen das System sauber herunterfährt.

**Comment by Hagenmue** [comment]
https://user-images.githubusercontent.com/36644825/103713467-affd6f80-4fbc-11eb-923b-83aaf24ef470.mp4


Hallo Alex, vielen Dank für die schnelle Reaktion und die Hinweise. Das gleiche Verhalten habe ich jedoch auch, wenn ich debmatic mit
`systemctl restart debmatic `
neu starte. Im Video ist am Ende zu sehen, wie die Störung wieder verschwindet, nachdem ich manuell die Temperatur am Thermostaten geändert hatte.

**Comment by alexreinert** [comment]
Für Batteriebetriebene Geräte gibt es zwei Varianten, wie diese erreicht werden können, weil sie nicht dauerhaft auf Empfang sind (sonst würden die Batterien nur wenige Tage reichen):

- Aufwecken per Burst
- Timeslot Verfahren

Es sieht so aus, als würde der HmIP-eTRV-2 nur letzeres unterstützen. Mangels Testgerät kann ich das aber leider nicht verifizieren und in den Closed Source von eQ-3 kann ich leider auch nicht reinschauen.

In dem Fall müsste es nach einem Neustart aber reichen, dass man wartet, bis sich der Thermostat selbstständig über die Cyclic Status Message meldet, diese erfolgt normalerweise grob im Stundenraster, kann aber auch in den Geräteneinstellungen häufiger konfiguriert werden (Anzahl auszulassender Statusmeldungen * ~3min). Das geht dann halt auf die Batterielaufzeit. Du kannst ja einfach mal probieren, was mit der Servicemeldung passiert, wenn du das Thermostat nicht manuell bedienst und einfach mal eine Stunde wartest. Meine Erwartungshaltung wäre, dass sie danach weg ist.

**Comment by Hagenmue** [comment]
Entschuldige bitte, dass ich auf deine schnelle Antwort nicht genau so schnell reagiert habe, aber ich wollte miich erst einmal zum Burstverfahren vs. Timeslotverfahren schlau machen. Leider konnte ich trotz intensiver Suche keine wirklich ausreichende Erläuterung finden, wie das realisiert wird. Vielleicht hast du einen Link für mich?
Im übrigen scheint mir die Firmware der Homematic IP Geräte noch sehr buggy zu sein. Ich wollte die "auszulassenden Statusmeldungen" über das Webinterface ändern, über kurzen Druck der Systemtaste das Gerät in den Anlernmodus gebracht (jedoch keine Rückmeldung durch Blinken der Taster erhalten) und bekam die Servicemeldung "Kommunikation gestört". Habe dann die Kommunikation getestet, indem ich die Temperatur im Webinterface geändert habe und das funktionierte. Die Servicemeldung ging aber nicht weg. Erst ein Power-On Reset führte zum Erfolg. Dafür konnte danach die Adapterfahrt nicht gestartet werden. Erst ein nochmaliger Power-On Reset führte dann zum Erfolg. 
Mal eine Anfrage an alle Mitlesenden: Habt ihr auch solche Erfahrungen gemacht?

**Comment by alexreinert** [comment]
Sehr viel gute Infos hat man auf dem letzten Usertreffen beim Vortrag von Frank Grass zu der Funkthematik bekommen, ich bin mir aber nicht sicher, ob der online verfügbar ist.

**Comment by Hagenmue** [comment]
> .... In dem Fall müsste es nach einem Neustart aber reichen, dass man wartet, bis sich der Thermostat selbstständig über die Cyclic Status Message meldet,...
Du hattest recht. Habe gestern Abend debmatic neu gestartet und heute sind die Fehlermeldungen verchwunden.
Danke für deine Unterstützung.

**Comment by alexreinert** [comment]
"Konfigurationdaten stehen zu Übertragung an" ist aber keine Kommunikationsstörung. Die kommt, wenn man am Gerät bestimmte Parameter ändert und diese ans Gerät übertragen werden müssen.
Bei Netzgeräten passiert das automatisch, bei Batteriegeräten muss man das ggf. manuell am Gerät anstoßen.

**Comment by Hagenmue** [comment]
"Bei Netzgeräten passiert das automatisch, bei Batteriegeräten muss man das ggf. manuell am Gerät anstoßen...."
Das habe ich gemacht. Inzwischen ist aber gar keine Kommunikation mit den HMIP Geräten mehr möglich. Habe den Stick dann an meinen alten RaspberryMatic angesteckt und auch da ist keine Kommunikation mehr mit den Geräten möglich. Stick wird aber erkannt. Meine Vermutung ist nun, dass der Stick schon vorgeschädigt war und nun ganz (auf der HF-Seite) den Geist aufgegeben hat. Habe mir eben einen neuen Stick bestellt und werde dann berichten.

**Comment by Hagenmue** [comment]
Neuer Stick angekommen - keine Kommunikation mit den Geräten möglich. Neuen Stick an RaspberryMatic angesteckt - keine Kommunikation mit den Geräten möglich. Alle Geräte neu angelernt (unter RaspberryMatic) - Kommunikation funktioniert wieder.Raspberry mit RaspberryMatic von der Stromversorgung getrennt, danach Stromversorgung wieder angeschlossen - Kommunikation mit den Thermostaten  funktioniert. Gleiches mehrfach wierholt.
Zum USB Stick: Der neue USB Stick zeigt bei allen Geräten einen um ca. 10 - 20dB höheren RSSI Wert an. 
Meine nächsten geplanten Aktionen: 
1) Alten USB Stick wieder anstecken.
2) Neuen USB Stick an Raspberry mit debmatic anstecken
@alexreinert: Soll ich weiter berichten oder ist das für dich uninteressant? Ich will dich nicht mit irgendwelchen Berichten nerven, wenn du deine Zeit vielleicht besser in andere Sachen investieren möchtest.  Ich hätte volles ("vollstes" verkneife ich mir, da m.E. Dummsprech) Verständnis dafür. Mit der momentanen Lösung kann ich leben, würde aber gern debmatic verwenden, da ich den Raspberry mit debmatic auch für andere Serverzwecke verwende. Falls es andererseits interessant für dich sein sollte, würde ich dir auch ssh Zugriff auf den Raspberry geben, damit du es dir anschauen kannst.
