### ISSUE TITLE
Lighttp öffnet viele TCP ports...

### ISSUE THREAD

**Issue by SirTwistDo** [alexreinert/debmatic#185]
Hallo,

nach einer Neuinstallation von debmatic auf Debian Buster habe ich mir mit "lsof -i | grep lighttp" angeschaut, auf welchen Ports der Webserver horcht. Über die Datei /etc/debmatic/webui.conf habe ich den Port auf 8040 geändert, aber weiterhin öffnet lighttp noch die Ports 80, 1999, 2000, 2001, 2010, 8181, 9292 und 30080
Was sind das für Ports, und wie kann man das verhindern?
Ich habe im /etc/debmatic/lighttp-Verzeichnis nichts gefunden.

Schöne Grüße,
Sir Twist

**Comment by alexreinert** [comment]
Das sind intern notwendige Ports für die Kommunikation zwsichen den verschiedenen Diensten und externen Lösungen, welche so von eQ-3 vorgegeben sind. Wenn man die versucht zu verhinden, wird das System nicht mehr richtig laufen.

**Comment by SirTwistDo** [comment]
Super, vielen Dank für die schnelle Antwort! Ich habe das jetzt auch in der /etc/lighttp/conf-* gefunden. Mal gucken, was wirklich benötigt wird.
