### ISSUE TITLE
WebUI zeigt Präsenzmelder nicht an

### ISSUE THREAD

**Issue by Gerrni** [alexreinert/debmatic#188]
Debmatic im Docker auf Synology. Andere IP Geräte werden angezeigt allerdings ein Präsenzmelder nicht. Angelernt ist er, er wird auch in iobroker angezeigt inkl. States.

Aufgrund fehlender Anzeige in WebUI kann ich jedoch keine Einstellungen vornehmen.

**Comment by alexreinert** [comment]
Welche Debmatic Version wird eingesetzt?
Welche Funkhardware wird eingesetzt?
Welches OS?
Was liefert `debmatic-info`?
Welcher Browser? Sind irgendwelche Virenscanner, Ad-Remover, etc. installiert?
Wo wird das Gerät nicht angezeigt, in der Systemsteuerung oder bei der Bedienübersicht? Liegt es im Posteingang? Wurde der Browsercache seit dem letzten Update geleert und die Seite mit Strg+F5 neu geladen?

**Comment by Gerrni** [comment]
Welche Debmatic Version wird eingesetzt?
-> Aktuelle Firmwareversion: | 3.53.34.59

Welche Funkhardware wird eingesetzt?
-> Das USB Funkmodul

Welches OS?
-> Docker Image unter DSM7 (Synology)

Was liefert debmatic-info?
-> Weiß ich nicht, was muss ich da tun?

Welcher Browser? Sind irgendwelche Virenscanner, Ad-Remover, etc. installiert?
-> Adblock - für alle Seiten der Homematic Website freigegeben

Wo wird das Gerät nicht angezeigt, in der Systemsteuerung oder bei der Bedienübersicht? Liegt es im Posteingang? Wurde der Browsercache seit dem letzten Update geleert und die Seite mit Strg+F5 neu geladen?
-> Das Gerät wird an KEINER Stelle angezeigt, auch nicht im Posteingang. Browser Cache vollständig geleert und aktualisiert, neu geladen. Chrome.

**Comment by alexreinert** [comment]
"Das USB Funkmodul" ist nicht eindeutig, da gibt es verschiedene, bitte genaue Bezeichnung.
Von debmatic gibt es kein fertiges Docker Image (zumindest kein mir bekanntes), daher, welches Image wird da verwendet?

**Comment by Gerrni** [comment]
Ich habe DEIN Modul gekauft über technikkram. HB-RF-USB
Entschuldige; es läuft in einer ubuntu 15.03 VM, habe ich mich vertippt. Oben aktualisiert. 

Andere Geräte, also nicht IP und auch IP werden dargestellt. Der Präsenzmelder scheint ja auch vorhanden zu sein; sonst wäre er nicht in ioBroker.

**Comment by alexreinert** [comment]
Was jetzt: Docker oder VM, das macht einen riesigen Unterschied.
Über Technikkram gibt es das HB-RF-USB-TK, welches auf meinem Originalmodul basiert, ich gehe davon aus, dass du das meinst. Aber welches Funkmodul hast du da aufgesteckt?

Hast du am Präsenzmeldet mal einen Werksreset gemacht und den neu angelernt? Gibt es Service Meldungen?
Kannst du dich bitte per SSH einloggen und zum einen die Ausgabe von `debmatic-info` posten und zum anderen den Inhalt der Dateien /var/log/messages und /var/log/hmserver.log nach dem erneuten Anlernversuch?

**Comment by Gerrni** [comment]
- VM
- Kann ich nicht genau sagen; auf einer Rechnung stets nicht genauer drauf. Hatte jedenfalls mal ein Post oder Eintrag im Forum von Dir gefunden dass Du einen Weg gefunden hast Deine Lösung zu vertreiben - das hab ich komplett gekauft. Ich meine das waren um die 80€.
- Einen Reset habe ich nicht gemacht, der ist nagelneu. Service Meldungen habe ich keine Einzige. Auch bei erstem Anlernen keinen Eintrag im Posteingang usw. 
- debmatic-info bringt dieses: 
![image](https://user-images.githubusercontent.com/40135870/104470369-ef7a1c00-55b9-11eb-985b-ad4a05aca138.png)

**Comment by Gerrni** [comment]
Warum auch immer taucht er im Posteingang auf. Ein weiterer hat auch funktioniert. Kann also geschlossen werden
