### ISSUE TITLE
Installation auf Ubuntu 19.04 amd64 (sowohl Pentium als auch i3) schlägt fehl

### ISSUE THREAD

**Issue by NestWolfsteiner** [alexreinert/debmatic#19]
Nur zur Information: 
Der Versuch der Installation auf dieser HW/BS Kombi schlägt fehl mit 
"N: Das Laden der konfigurierten Datei »main/binary-i386/Packages« wird übersprungen, da das Depot »https://www.debmatic.de/debmatic stable InRelease« die Architektur »i386« nicht unterstützt.
"
BG 
Frank

**Comment by alexreinert** [comment]
Das hat weniger was mit Ubuntu 19.04 zu tun, als eher mit der Tatsache, dass nur die 64-Bit Version (amd64 Platform) unterstützt wird.

**Comment by NestWolfsteiner** [comment]
Danke Dir für die schnelle Antwort, gleich mal einen weiteren Rechner zusammengebaut.  Die gleiche Fehlermeldung erscheint bei einem i5-3550. 
BG 
Frank

**Comment by NestWolfsteiner** [comment]
PS Ich habe sicher das amd64 image verwendet "ubuntu-19.04-desktop-amd64"

**Comment by NestWolfsteiner** [comment]
PS und auch auf  beiden Rechnern wird "Typ des Betriebssystems: 64 bit" im Info gemeldet

**Comment by NestWolfsteiner** [comment]
Update: Installation mit Debian 9 Lenovo Pentium M73 läuft durch, bin gerade am weiteren testen

**Comment by alexreinert** [comment]
Ich habe gestern die Installation von debmatic auf Ubuntu 19.04 Server durchgeführt.
Die angeführte Fehlermeldung ist eine reine Warnung, weil versucht wird, auch eine Liste von 32-Bit Paketen zu laden, welche nicht vorhanden ist (weil nicht unterstützt).
Für den Kernel 5.0 habe ich noch ein paar Anpassungen machen müssen, die sind aber bereits hochgeladen, abschließend kann ich also sagen, dass die Installation auf Ubuntu 19.04 problemlos möglich ist.
