### ISSUE TITLE
pivccu-rpi-modules.service fails to start

### ISSUE THREAD

**Issue by yellowlexx** [alexreinert/debmatic#190]
Auf meinem frisch aufgesetzten RaspberryPi 4 konnte das Service "pivccu-rpi-modules.service" nicht gestartet werden. Als Konsequenz waren meine HMIP Geräte nicht verfügbar und es konnten auch keine HMIP Geräte angelernt werden (HMIP fehlt im anlernen Menü).

Eine Untersuchtung des Problems hat gezeigt, dass mein Kernel (uname -r) sich als Version "5.10.9-v7l+" meldet, die KERNEL_GIT_VERSION in /var/lib/piVCCU/rpi-modules/ensure_headers.sh aber "5.10.9-v7+" lautet.
Woher der Unterschied kommt ist mir unklar. Durch manuelle Intervention konnte ich das Service zum Laufen bekommen und HMIP funktioniert nun in debmatic.

**Comment by alexreinert** [comment]
64 Bit Kernel und rpi-update verwendet?

**Comment by yellowlexx** [comment]
rpi-update habe ich verwendet, ja. Aber das Problem hatte ich davor schon.
Mein Kernel ist, sowie mein ganzes System, 32bit. Setzt debmatic einen 64bit kernel voraus?
Soweit ich weiss is RaspiOS ja noch nicht offiziell as 64Bit System verfügbar (aber man kann wohl einen 64bit kernel mit 32bit user land betreiben).

**Comment by alexreinert** [comment]
Nein, 64 Bit sind nicht notwendig. Im Gegenteil, bis vor kurzem wurden beim 64 Bit Kernel von Raspbian keine ordentlichen Header ausgeliefert, daher die Frage.
rpi-update installiert einen testing Header, bei welchem die Raspberry Pi Foundation (und auch ich) von der produktiven Mutzung abrät. Wenn das dann nicht ganz sauber läuft, dann ist das leider so.
Mit den offiziellen Kernel Paketen aus den Raspbian Repository kann ich keine Probleme festellen, da bräuchte ich mehr Details.

**Comment by yellowlexx** [comment]
Hallo,

Habe heute nochmal den ganzen Ablauf nachgestellt. Ausgehend von Buster Lite 2020-12-02 (das war auch mein Startpunkt beim ursprünglichen Report) habe ich nochmal Deine Anleitung nachvollzogen. In Schritt 2. macht man ein 'apt update'. In Schritt 3. ein 'apt install raspberrypi-kernel-headers'. Die header sind potentiall neuer als der laufende Kernel. Das habe ich bei meinem ersten Durchlauf übersehen. Diesemal habe ich ein "apt-get upgrade" gefolgt von einem Reboot gemacht. Dann sind Kernel und Header in sync und alles ist gut.
Bei meinem ersten Versuch hat mich Google auf die rpi-update Idee gebracht was nicht ideal war.
Eventuell kannst Du das Kernel upgrade (plus reboot) als Hinweis in Deine Doku mit aufnehmen.

[1] https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2020-12-04/2020-12-02-raspios-buster-armhf-lite.zip

**Comment by yellowlexx** [comment]
Issue resolved.
