### ISSUE TITLE
2 Funkplatinen

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#191]
Hallo ich habe folgenden Platinen HB-RF-USB-TK und  HB-RF-ETH. Beide sind mit Funkmodule bestückt. Nun meine Frage, kann ich die beide gleichzeitig am Intel Nuc unter Debmatic betreiben? Ich wollte eine in der Wohnung und eine im Keller anschließen.
Gruß Heino Gerdes

**Comment by alexreinert** [comment]
Nein, das geht nicht, weil die Binaries von eQ-3 nur ein Funkmodul unterstützen und mangels Zugriff auf den Quellcode kann ich daran leider auch nichts ändern.
Es bleiben nur die Möglichkeiten über LAN GW für BidCos, HmIP-HAP für HmIP Advanced Routing und HmIP Routing per HmIP Zwischensteckdose.
