### ISSUE TITLE
No PRI-RF-MOD detection on RPi4 with RPi OS lite (armhf)

### ISSUE THREAD

**Issue by SMHRambo** [alexreinert/debmatic#193]
engl:
Hi,
I have problems with the detection of the RPI-RF-MOD on my Pi4 with RaspberryPi OS lite.
The led doesn't light up.
The Modul is working the same Pi4 with RaspberryMatic.

any suggestions
thanks in advance

ger:
Hi,
Ich habe ein Problem mit der Erkennung des RPI-RF-MOD auf meinem Pi4 mit RaspberryPi OS lite.
Die LED leuchtet nicht.
Das Modul funktioniert auf dem selben Pi4, wenn RaspberryMatic eingesetzt wird.

Irgendwelche Ideen
Danke schon mal im Voraus

debmatic version: 3.53.34-59
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

**Comment by alexreinert** [comment]
- Ein HM-RF-MOD gibt es nicht, ist damit das RPI-RF-MOD gemeint?
- Welche Version von Raspberry Pi OS wird verwendet?
- Wurden alle Schritte der Anleitung inkl. der dort beschriebenen Reboots befolgt?
- Was liefert `sudo ls -la /dev/raw*`?
- Wie sieht die Datei /boot/config.txt aus?
- Was liefern `sudo strings /proc/device-tree/soc/serial@7e201000/compatible`, `sudo strings /proc/device-tree/aliases/uart0` und `sudo strings /proc/device-tree/aliases/serial0`?
- Was liefert `sudo detect_radio_module --debug /dev/raw-uart`?

**Comment by SMHRambo** [comment]
Danke erstmal für die schnelle Antwort.
bzgl. des HM-RF-MOD, stimmt ist mir auch schon aufgefallen, da war ich irgendwie in gedanken.

- RaspberyPi OS Version: von heute, 2021-01-11-raspios-buster-armhf-lite
- Die Anleitung wurde genau befolgt.
- Das /dev/raw-uart ist vorhanden
pi@raspberrypi:~ $ sudo ls -la /dev/raw*
crw------- 1 root root 235, 0 Jan 28 14:45 /dev/raw-uart
/dev/raw:
insgesamt 0
drwxr-xr-x  2 root root     60 Jan  1  1970 .
drwxr-xr-x 17 root root   3840 Jan 28 14:45 ..
crw-rw----  1 root disk 162, 0 Jan 28 14:45 rawctl

- Das Ende der /boot/config.txt
[all]
#dtoverlay=vc4-fkms-v3d
enable_uart=1
dtoverlay=pivccu-raspberrypi

- sudo strings /proc/device-tree/soc/serial@7e201000/compatible
pivccu,pl011

- sudo strings /proc/device-tree/aliases/uart0
/soc/serial@7e201000

- sudo strings /proc/device-tree/aliases/serial0
/soc/serial@7e215040

- sudo detect_radio_module --debug /dev/raw-uart
Sending HM frame: fd 00 03 fe 00 01 14 1e
Sending HM frame: fd 00 03 00 01 00 9e 03
Sending HM frame: fd 00 03 fe 02 01 98 1d
Sending HM frame: fd 00 03 00 03 00 12 00
Sending HM frame: fd 00 03 fe 04 01 8c 1d
Sending HM frame: fd 00 03 00 05 00 06 00
Error: Radio module was not detected

**Comment by alexreinert** [comment]
Aufgrund der unvollständigen Ausgabe der /boot/config.txt kann ich nicht beurteilen, ob Schritt 5 korrekt ausgeführt wurde. Der Inhalt der /proc/device-tree/aliases/serial0 spricht dafür, dass das nicht der Fall war.

**Comment by SMHRambo** [comment]
Danke für den Tipp mit Schritt 5, 
habe noch mal eine unbearbeitete config.txt rauf kopiert und selbständig angepasst.
In diesem zusammenhang habe ich alle [all] zusammengefasst.
Nun läuft es.
