### ISSUE TITLE
lighttpd: socket failed: Address family not supported by protocol 

### ISSUE THREAD

**Issue by drstil** [alexreinert/debmatic#194]
I installed debmatic on my raspberry pi 2B with debian buster. When trying to start lighttpd, I got the error:
`2021-01-30 11:38:27: (network.c.281) socket failed: Address family not supported by protocol`
This error disappears, when I disable the 20-debmatic.conf file, so it seems to be associated with debmatic configuration. 

lighttpd without debmatic configuration is running without errors. I still changed the port of lighttpd.conf to 81 and also the port of debmatic /etc/debmatic/webui.conf to 81.

Do you have an idea, what could cause the error? Ipv6 is disabled for lighttpd, as written in some issues to this error.

Thank you and best!

**Comment by drstil** [comment]
I removed the ipv6 configuration from 20-debmatic.conf, which solved the issue. 
I'm trying now to find a solution, to get it working with the original configuration and will answer back.

**Comment by drstil** [comment]
In my case, ipv6 as module was enabled successfully. There was only a line `ipv6.disable=1` in /boot/cmdline.txt. I did not add this line, but after removing it, everything worked fine!

Thank you for supporting and providing debmatic! 

Best!

**Comment by bumblebee-tgl** [comment]
Hi,

i´am getting this error today too.
But there is no ipv6 anywere.

I updatet my Pi this week.
Mybe is there the Error?
