### ISSUE TITLE
Gerätekommunikation gestört. Nur Probleme seit HmIP-HAP Installation

### ISSUE THREAD

**Issue by freshwebs** [alexreinert/debmatic#195]
Moin,

Ich betreibe einen RPi4 mit Debmatic. Auf dem RPi ist ein RPI-RF-MOD.

`debmatic version: 3.53.34-59
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993D837
 Radio MAC:     0xFFD837
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993D837
 Radio MAC:     0xB831DE
` 

Ich hatte aus einem eBay Kauf noch einen Homematic IP Access Point (HmIP-HAP) über. Diesen wollte ich als LAN-Router anlernen. Hat auch geklappt. Aber seit dem klappt das Funken so gut wie gar nicht mehr. Woran kann das liegen? Hat jemand eine Idee?

Viele Grüße
Jan

**Comment by alexreinert** [comment]
Raspberry Pi 4 und HmIP ist ein großes Problem, weil der Raspberry Pi 4 ein massiver Störstrahler ist. Kann man hier und im Homematic Forum oft genug lesen. Da hilft es nur das Funkmodul weit genug vom Raspberry Pi 4 entfernt aufzustellen (deutlich >0,5m) und die Spannungsversorgung zu filtern, z.B. per HB-RF-USB-2 oder HB-RF-ETH oder mittels Flachbandkabel und entsprechnder Entstörung der 5V Leitungen.

Die Ausgaben von debmatic-info sehen ansonten gut aus.

**Comment by freshwebs** [comment]
Wie ist es, wenn ich eine externe Antenne an das Modul löte? Würde dies helfen?

**Comment by alexreinert** [comment]
Kann es besser machen, aber das Funkmodul selber nimmt über das Metallgehäuse vom CC1310 einiges an Störstrahlung auf und auch die Filterung der Versorgungsspannung fehlt bei diesem Vorgehen.
Zusätzlich sind 2m Antennenkabel mit entsprechender Güte ziemlich teuer und günstiges Antennenkabel hat eine deutliche Dämpfung des Empfangs- und Sendesignals, was dann anderweitig zu Problemen führen kann.
