### ISSUE TITLE
Update auf die Version 3.55.10 schlägt fehl. Neuinstallation ebenfalls. 

### ISSUE THREAD

**Issue by github6043** [alexreinert/debmatic#198]
Der Upgrade oder die Neuinstallation der aktuellsten DebMatic Version schlägt bei mir fehl. Auf Ubuntu 20.04 hat die Vorgängerversion problemlos funktioniert.
![2021-02-04 10_38_26-Window](https://user-images.githubusercontent.com/40850921/106874417-d3a7f880-66d5-11eb-9bf9-2edd3d0b6a88.png)

**Comment by AndreasBerz** [comment]
Mmhh, habe gerade issue #201 angelegt. Leider ohne vorher die vorhandenen issues durchzuschauen :(
Scheint bei mir ein recht ähnliches Problem mit der neuen Version zu sein.
Bei mir "hängt" der Installationsvorgang kurz vorm Ende fest und hört nicht mehr auf.
Man muss den Vorgang mit kill-command oder reboot abwürgen und danach funktioniert debmatic nicht mehr.

**Comment by alexreinert** [comment]
Es fehlte eine Abhängigkeit zum Paket ifupdown, welche dieses Verhalten hervorrufen könnte. Diese ist nur vorhanden, bitte nochmal updaten.

**Comment by github6043** [comment]
Hi Alex, alles ok, update klappt. Weiter ist auch die LED auf dem RPI Funkmodul nun mit korrektem Status (blau) online. Die HB-RF-ETH Lösung ist super, besten Dank
