### ISSUE TITLE
Frage: Portbelegung und lighttpd

### ISSUE THREAD

**Issue by SMHRambo** [alexreinert/debmatic#199]
Ein tolles Projekt, ohne das ich mein Smarthome nicht so kompakt aufbauen könnte.

Da ich selber programmiere und gerne mal die Software prüfe die ich bei mir einsetze,
habe ich mir dein Projekt/Code etwas angeguckt und habe dazu ein paar Verständnisfragen.

1. Warum sind zum Code vom "eq-3/occu" alle nach aussen nötigen Ports geändert (2000->32000, 2001->32001,...),
nur um sie dann später wieder über lighttpd-proxy zu den original Ports umzuleiten. 
Die einzige Grund der mir einfällt ist der IPv6 Support.
Würde das nicht auch funktionieren, wenn man nur die IPv6 Anfragen auf die IPv4 Ports umlenkt.
Dadurch würden weit aus weniger Ports offen sein und bei der IPTables/Firewall-Konfiguration muss nicht so viel beachtet werden. 
Zudem würde die lighttpd-Config etwas zusammenschrumpfen, da die HMIP Komponenten die auf Java (2010, ...) laufen sowieso schon IPv6 unterstützen.

2. Warum laufen vom lighttpd zwei Instanzen, ich bin zwar kein lighttpd Experte aber im Code von "eq-3/occu" wird, so wie ich es verstanden habe, nur eine Instanz genutzt um sowohl den Proxypart für 8183->8181 als auch die Bereitstellung der Website zu übernehmen.

Danke für die Zeit, die du in dieses Projekt steckst.

**Comment by alexreinert** [comment]
Zu Frage 1: Weil das von der Original CCU auch so gemacht wird. Hat den Hintergrund der Authentifizierung und der SSL Unterstützung, auch wenn das in debmatic noch nicht komplett umgesetzt ist.
Zu Frage 2: Die CGI Scripte müssen teilweise mit root Rechten laufen, ich wollte aber nicht den gesamten front facing lighttpd mit root Rechten laufen lassen.

**Comment by SMHRambo** [comment]
Danke, für die schnelle Antwort.

In die original CCU Firmware habe ich bisher nicht rein geguckt,
da in der Projektbeschreibung von OCCU die rede ist.

Damit sind erstmal alle meine Fragen beantwortet.

Danke nochmal.
