### ISSUE TITLE
Heizungsthermostat Anzeigeprobleme nach Neustart

### ISSUE THREAD

**Issue by mar565** [alexreinert/debmatic#20]
System:
- Gigabyte Brix 3150
- Proxmox -> VM Debian 9.8.0
- RF-MOD

Nach einem Neustart der VM werden mir, im webUI, einige Heizungsthermostate als "OFF" angezeigt. Im ioBroker werden sie mit 23°C angezeigt, am Thermostat selbst sind aber 22°C eingestellt.
Wenn ich den Wert über ioBroker oder am Thermostat ändere, oder versuche ihn im webUI wieder einzustellen, wird der korrekte Wert sofort richtig dargestellt.
![WebUI](https://user-images.githubusercontent.com/49168222/56473754-d9d0d480-646f-11e9-8e33-b581ad920337.JPG)

**Comment by alexreinert** [comment]
Das ist leider ein bekanntes Problem in den Closed Source Binaries von eQ-3 an dem ich mangels Zugriff nichts ändern kann. Es betrifft leider auch alle HmIP Geräte und nicht nur die Heizungsthermostate, da fällt es nur am meisten auf
