### ISSUE TITLE
WebUI Fehler: Geräte in Gewerke und Räume unter Einstellungen werden nicht angezeigt

### ISSUE THREAD

**Issue by SMHRambo** [alexreinert/debmatic#200]
Bei mir lassen sich unter Einstellungen die Geräte in dem Menü für Gewerke und Räume nicht mehr anzeigen, 
wenn man auf das + Zeichen klickt.
Leider weiss ich nicht ob das Problem schon vorher bestand, 
die letzte Änderung war das Update auf "3.55.10.64".

- Das + Zeichen ändert sich zwar zu einem - aber mehr passiert nicht.
- Auch das betätigen der Schaltfläche "Baumstruktur öffen" änder nur das + Zeichen in ein - Zeichen.
- Hinzufügen von Kanälen funktioniert.
- Gewerke-/Raumliste bearbeiten zeigt ein 404 Fehler an.
- Man kann zwar Gewerke/Räume hinzufügen aber nicht wieder entfernen.

Auch eine Neuinstallation (mit apt purge) des Paketes debmatic +lighttpd ergab keine Besserung.

Hardware:
Raspberry Pi 4
RPI-RF-MOD
2021-01-11-raspios-buster-armhf-lite

**Comment by alexreinert** [comment]
Was liefert debmatic-info?

**Comment by SMHRambo** [comment]
debmatic info:
debmatic version: 3.55.10-64
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  5A4993D557
 Radio MAC:     0xFFD557
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F5A4993D557
 Radio MAC:     0xBD30AA

**Comment by j-p-l** [comment]
Ich bekomme: 
`ReGaHss[1035]: CRASH: Could not spawn a new request handler! {"HTTP-Listener"} [ThreadFunction():httpListener.cpp:178]`
in der console ausgespielt. Hängt das zusammen?

**Comment by alexreinert** [comment]
@SMHRambo Kannst du bitte mal den Browsercache löschen und die Seite mit Strg+F5 neu laden.

**Comment by SMHRambo** [comment]
Nachdem ich folgenen Log von lighttpd bekommen habe, 
wenn ich auf das + geklicket hatte.

```
2021-02-05 10:54:10: (http-header-glue.c.1250) read(): Connection reset by peer 21 20
2021-02-05 10:54:10: (gw_backend.c.2154) response already sent out, but backend returned error on socket: tcp:127.0.0.1:8183 for /pages/tabs/admin/views/functionchannels.htm?sid=@SsOjp9wQcq@&id=1223&fTblPos=1&clearSel=true, terminating connection
```

Und es für eine kurze Zeit funktioniert hat, 
wenn ich die IP des Pi geändert habe, 
hatte ich mir sowas schon gedacht.

Leider hat neben dem Cache leeren, 
erst der Neustart des PC den gewünschten Erfolg gebracht.

Danke für die Hilfe,
vielleicht hilft es jemanden in der Zukunft, 
der mit einem ähnlichen Problem zu kämpfen hat.
