### ISSUE TITLE
Latest update 3.55.10.66 of debmatic is "endless"

### ISSUE THREAD

**Issue by AndreasBerz** [alexreinert/debmatic#201]
I have got "deb https://www.debmatic.de/debmatic stable main" within my list of repositories and tried to install the latest update of debmatic. For ex. "sudo apt-get upgrade" or "sudo apt-get install debmatic" or any kind of UI-backend.
The installation starts and is runnig fine for a moment, but then it got stuck and never returns.
Last two lines at command line are:

>Enabling debmatic: ok
>Run "service lighttpd force-reload" to enable changes

![image](https://user-images.githubusercontent.com/72526879/106963204-8b71f000-6740-11eb-8e42-0f037d80baf6.png)

Thats it. Command will not return, no matter how long you are waiting.
Removing package and reinstalling it, will result in exact the same situation.
Debmatic is not working anymore after running in that situation.
Have to use system backup to get back the former version of debmatic.

System is Xubuntu x86_64 on Intel-NUC.
Hardware HB-RF-ETH with  RPI-RF-MOD is used as Transmitter. Package "hb-rf-eth" is installed.
Debmatic is working well for some months in combination with openHAB2 and now openHAB3.

Best regards, Andi.

**Comment by alexreinert** [comment]
There was a missing dependency to the package ifupdown for the ifquery tool. It is now included and should work now.

**Comment by AndreasBerz** [comment]
Yes, approved! Package installation finishes now the regular way.
Debmatic ist working properly afterwards.
Thank you much for correcting the package.
