### ISSUE TITLE
Einige Störungen mit debmatic auf Ubuntu 20.04 und HB-RF-ETH (RPI-RF-MOD)

### ISSUE THREAD

**Issue by github6043** [alexreinert/debmatic#204]
Guten Abend Alex

Folgende Infrastruktur habe ich seit kurzem online 

Ubuntu Server 20.04 LTS als VM auf ESXi mit 2 CPU und 4 GB RAM
HB-RF-ETH Modul mit RPI-RF-MOD (Version 1.2.9)
Debmatic mit der Firmware 3.55.10.66

Was ich feststelle sind folgende Störungen.

1. Auf dem Funkmodul RPI-RF-MOD leuchtet die Status LED blau, in einem Intervall von zirka 95 Sekunden ändert der Status auf rot für 5 Sekunden.
2. Auf der Konsole der VM mit installiertem Debmatic erhalte ich wieder die Buffer Fehlermeldungen die ich in Issue #187 beschrieben habe

Die Bufferfehler sind erst seit kurzen wieder aufgetaucht, kann nicht mit Sicherheit sagen, ob das mit dem Upgrade zusammenhängt. Mit Ubuntu 18 und älterer Debmatic & HB-RF-USB waren die Störungen nicht vorhanden.

**Comment by github6043** [comment]
Duty Cycle auf meiner Debmatic ist konstant zwischen 10-18%
Aktuelle Firmwareversion:  3.55.10.66

**Comment by github6043** [comment]
Hat für mich auch mit der Firmware 3.55.10.66 zu tun. Nach einem Downgrade auf 3.53.34.59 keine Probleme / Unterbrüche mit Debmatic mehr. Auf dem Modul RPI-RF-MOD leuchtet die Status LED nun zwar konstant rot, ich kann jedoch alle meine HM und HM-IP devices erreichen und steuern. Duty Cycle um 3%

**Comment by meier81** [comment]
Das sieht bei dir stark nach dem gleichen Problem wie bei mir aus
[https://github.com/alexreinert/debmatic/issues/202](url)
Macht fast den Eindruck als startet die CCU ständig neu, ich fliege auch alle ca. 30 Sekunden aus der Oberfläche mit Sitzung abgelaufen. Mein Duty Cycle ist auch hoch gegangen, hatte auch so 14-16. Nach Downgrade alles in Ordnung.

**Comment by AndreasBerz** [comment]
Kann dieses issue#204 und auch issue#202 bestätigen.
Debmatic läuft bei mir auf Xubuntu x86_64 auf Intel NUC.
Nach ca. 1,5min. leuchtet die LED kurz für 5 sek. rot dann wieder blau. (HB-RF-ETH+RPI-RF-MOD)
Beim Öffnen von WebUI erscheint öfters nur "Loading", das geht aber nicht mehr weg. Neustart fällig.
Häufiger noch, kann man sich erfolgreich an WebUI anmelden, aber nach weniger als einer Minute ist der Session timeout abgelaufen. Session sollte standardmäßig 5min. bestehen.
Mein Eindruck ist, die Debmatic bleibt zu einem bestimmten Zeitpunkt-X "irgendwie stehen", 
Die Temperaturkurven des angebundenen openHAB3 sind dann nur noch absolut waagrechte Geraden, weil keine Temperaturänderungen mehr von den HmIP-Wandthermostaten durch Debmatic geliefert werden.

**Comment by Goersch** [comment]
Gibt es hierzu was neues? War gerade auf dem Weg mir das HB-RF-ETH zuzulegen; bin jetzt aber nicht sicher, ob das die richtige Lösung ist.

**Comment by meier81** [comment]
@Goersch: Also ich kann über die HB-RF-ETH nichts schlechtes berichten, lief immer zuverlässig und ohne weitere Aussetzer bei mir. Warum es ausgerechnet aktuell hier ein Problem gibt weiß ich nicht, wie gesagt bin eine Version zurück, rennt ohne Probleme. Wäre aber auch interessiert ob Alex hier schon Erkenntnisse hat oder evtl. auch weitere Infos benötigt, falls ja, bitte melde dich.

**Comment by AndreasBerz** [comment]
Habe ebenfalls einen Downgrade von Debmatic auf Vorgängerversion 3.53.34.59 gemacht. (Anregung von @github6043)
In dieser Version läuft die Debmatic seit 6 Tagen stabil. Die Version 3.55.10.66 hatte nach 2-3 Tagen aufgehört zu funktionieren.
Lustigerweise leuchtet die HB-RF-ETH jetzt dauerhaft rot statt blau, so wie es in den alten Firmware-Versionen von HB-RF-ETH der Fall war. Bezüglich des Farbenspiels blicke ich nicht durch....aber das System funktioniert wenigstens.
Ich gehe davon aus, dass Alexreinert es hier mitteilen würde, falls er eine Lösung hätte.

**Comment by github6043** [comment]
Mit der Version 3.53.34.59 und HB-RF-ETH absolut keine Probleme, einzig die LED mit Status rot. HM und HMIP läuft alles. Weiter eine Anbindung mit Node Red (eigene VM). Nichts negatives festgestellt. Gibt also keinen Grund nicht die HB-RF-ETH zu nutzen.

**Comment by alexreinert** [comment]
Ich kann das Problem leider nicht wirklich nachstellen. Wenn man aber über alle Foren schaut, dann tritt dieses Problem vereinzelt auf allen CCU Varianten auf, irgendwas im Closed Source des HMServers scheint sich zu verhaken.
Ich hoffe, dass sich das Problem mit der hoffentlich bald kommenden 3.57.x erledigen wird. Mangels Zugriff auf den Source vom HMServer kann ich leider nicht wirklich mehr machen.

**Comment by meier81** [comment]
Hallo Alex,
mal vielen Dank für deine Rückmeldung. Dann lass ich erstmal die 3.53 drauf und warte mal auf die neue 3.57.
