### ISSUE TITLE
Firmware Upgrade Homematic wired

### ISSUE THREAD

**Issue by herrmie** [alexreinert/debmatic#205]
Hallo,
ich versuche meine Homematic Thermostate auf die neuereVersion zu bringen. Auf der Startseite sehe ich das Firmware Updates verfügbar sind. Gehe dann unter Einstellungen > Geräte-Firmware - Übersicht und dort sehe ich dann meine Thermostate mit der aktuellen Version und die Firmware die auf der CCU verfügbar ist. Mit einem Klick auf Update kommt dann aber: 

![image](https://user-images.githubusercontent.com/45813597/108604037-b8aed700-73ab-11eb-96b9-f2e0b17a6a53.png)

Hat jemand eine Idee an was das liegen kann? Muss ich die Thermostate vielleicht erstmal in einen Upgrade Modus bringen, damit die CCU diese bespielen kann?

Ich habe das ganze auch nochmal anhand folgender Anleitung versucht: https://www.contronics.de/download/Anleitung-Firmwareupdate-HM-Module.pdf aber ich habe den Update Button unter Einstellungen --> Geräte --> Einstellen nicht.

Danke schon mal.

Grüße,
herrmie

**Comment by Goersch** [comment]
Benutzt Du evtl. auch noch HM-CFG-LAN? Damit gehen Firmware updates nicht.

**Comment by Goersch** [comment]
ach, less jetzt "wired" - vergiß meine Antwort - sorry

**Comment by herrmie** [comment]
Hallo Georg,
nee, deine Antwort macht Sinn. Ich habe das Ticket falsch aufgemacht. :)
Ich habe die Homematic Thermostate (nicht IP), die sind ja funk und nicht wired. Mein Fehler. Und tatsächlich habe ich meinen HM-CFG-LAN Gateway noch aktiv. Müsste ich vielleicht mal abstecken. Da ich ja jetzt den USB Stick im Raspi nutze.
Ich versuche es mal, vielleicht liegt es echt daran.

Grüße,
herrmie

**Comment by herrmie** [comment]
ich habe jetzt meinen HM-CFG-LAN abgekoppelt, den raspi mit debmatic neugestartet und versucht die Firmware upgrades meiner Thermostate zu starten. Aber leider der gleiche Fehler wie oben.

Grüße,
herrmie

**Comment by herrmie** [comment]
Hallo,
hat vielleicht jemand eine Idee?

Grüße,
herrmie

**Comment by Goersch** [comment]
Ich weiss nicht, was Du für einen USB Stick hast - Firmware updates geht bei dem alten Homematic nur mit dem Funk-LAN-Gateway (soweit ich weiss)

**Comment by herrmie** [comment]
Hallo,
das ist so nicht ganz richtig. Ich hatte immer den LAN Gateway im Einsatz. Damals habe ich mir den HM-CFG-USB-2 gekauft um Updates auf das Gerät zu spielen. 
Nun wollte ich die Möglichkeit aus debmatic nutzen. Aber leider geht das nicht. Was nutzen denn andere als Schnittstelle? Es muss doch noch andere geben, die den HM-CFG-USB-2 haben, oder nicht?
