### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by rschulz921** [alexreinert/debmatic#206]
Hallo Alex,

ich gebe auf :) Nachdem ich schon bei pivccu aufgegeben habe, habe ich es mit debmatic versucht und bin in den gleichen fehler gelaufen:

Installiert nach Anleitung, System ist ein Raspi 4 mit Openhabian Image, recht frisch installiert mit einem aufgestecktem HM-MOD-RPI-PCB (mit externer Antennenanschluss).

**folgendes Ergebnis:**

`
openhabian@openhabian:~ $ **systemctl status debmatic**
● debmatic.service - debmatic
   Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2021-02-27 02:01:39 CET; 2min 26s ago
  Process: 339 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
 Main PID: 339 (code=exited, status=0/SUCCESS)

Feb 27 02:01:28 openhabian systemd[1]: Starting debmatic...
Feb 27 02:01:28 openhabian initsystem.sh[339]: cat: /sys/class/net/eth0/carrier: Invalid argument
Feb 27 02:01:28 openhabian initsystem.sh[339]: cat: /sys/class/net/wlan0/carrier: Invalid argument
Feb 27 02:01:39 openhabian systemd[1]: Started debmatic.
openhabian@openhabian:~ $ sudo debmatic-info
[sudo] password for openhabian:
debmatic version: 3.55.10-66
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
openhabian@openhabian:~ $ **sudo dpkg-reconfigure pivccu-modules-dkms**

------------------------------
Deleting module version: 1.0.56
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/pivccu/1.0.56/source ->
                 /usr/src/pivccu-1.0.56

DKMS: add completed.
Error! echo
Your kernel headers for kernel 5.10.17-v7l+ cannot be found at
/lib/modules/5.10.17-v7l+/build or /lib/modules/5.10.17-v7l+/source.
`

Im 5.10.17-v7l+Verzeichnis gibt es leider keine _build_ oder _source_ Unterordner mehr, auch nicht wenn ich auf GitHUB schau: https://github.com/raspberrypi/firmware/tree/master/modules

**config.txt ist angepasst:**

`
dtoverlay=pivccu-raspberrypi

enable_uart=1

force_turbo=1

dtoverlay=pi3-disable-bt
`

die WebUi kann ich aufrufen, ist aber natürlich alles leer :/

Ansonsten steht der Raspi nur im WLAN, Kabel habe ich leider keins in der Nähe

Am USB Port hängt noch ein USB Zigbee Stick der mit zigbee2mqtt läuft.

HILFE :)

**Comment by alexreinert** [comment]
Was liefern `uname -a` `ls -la /usr/src`? Welche Anleitung wurde verwendet, es gibt ja mehrere?

**Comment by rschulz921** [comment]
Hallo Alex, zunächst ersteinmal Dank Dir für die viele Arbeit für die Community und die schnelle Antwort !!!!

Das es mehrer Anleitungen gibt, ist mir auch aufgefallen und zum Schluss und mit dem Stunden war es sicher auch ein Mix der Tipps, die man sich ergoogelt hat. Die Hauptanleitung war aber Deine:
[](https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md)

Beim ersten Versuch mit piVCCU und in Verbindung mit dem WiFi Hinweis:
[](https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md)
[](https://github.com/alexreinert/piVCCU/blob/master/docs/setup/wlan.md)

Im Ersten Versuch hatte ich Homegear installiert und auch am Laufen gehabt, inkl. dem Funkmodul (scheint also schon mal zu funktionieren), dann aber festgestelt das meine Devices ja HmIP sind und nicht nur Hm :( also deinstalliert und mit piVCCU angefangen.

Zuvor hatte ich auch moch MQTT mit zigbee2mqtt zum Laufen gebracht, kann sein das diese Anleitungen auch noch Einfluss auf den "jungräulichen" Openhabian hatten: [](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html)

**uname -a:**
Linux openhabian 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

**ls -la /usr/src:**
`openhabian@openhabian:~ $ ls -la /usr/src
total 24
drwxr-xr-x  6 root root 4096 Feb 26 22:14 .
drwxr-xr-x 10 root root 4096 Jan 11 13:50 ..
drwxr-xr-x 23 root root 4096 Feb 27 00:28 linux-headers-5.10.11+
drwxr-xr-x 23 root root 4096 Feb 27 00:28 linux-headers-5.10.11-v7+
drwxr-xr-x 23 root root 4096 Feb 27 00:43 linux-headers-5.10.11-v7l+
drwxr-xr-x  2 root root 4096 Feb 26 22:14 pivccu-1.0.56
`

**im 5.10.17-v7l+Verzeichnis finden sich folgende Inhalte:**
`
openhabian@openhabian:~ $ ls -la /usr/src/linux-headers-5.10.11-v7l+
total 1336
drwxr-xr-x  23 root root   4096 Feb 27 00:43 .
drwxr-xr-x   6 root root   4096 Feb 26 22:14 ..
drwxr-xr-x  26 root root   4096 Feb 27 00:28 arch
drwxr-xr-x   3 root root   4096 Feb 27 00:28 block
drwxr-xr-x   2 root root   4096 Feb 27 00:28 certs
-rw-r--r--   1 root root 202986 Feb  4 13:36 .config
drwxr-xr-x   4 root root   4096 Feb 27 00:28 crypto
drwxr-xr-x   8 root root   4096 Feb 27 00:28 Documentation
drwxr-xr-x 139 root root   4096 Feb 27 00:28 drivers
drwxr-xr-x  79 root root   4096 Feb 27 00:28 fs
drwxr-xr-x  31 root root   4096 Feb 26 22:15 include
drwxr-xr-x   2 root root   4096 Feb 27 00:28 init
drwxr-xr-x   2 root root   4096 Feb 27 00:28 ipc
-rw-r--r--   1 root root    555 Feb  4 11:04 Kconfig
drwxr-xr-x  19 root root   4096 Feb 27 00:28 kernel
drwxr-xr-x  21 root root   4096 Feb 27 00:28 lib
-rw-r--r--   1 root root  64472 Feb  4 11:04 Makefile
drwxr-xr-x   3 root root   4096 Feb 27 00:28 mm
-rw-r--r--   1 root root 981825 Feb  4 13:36 Module.symvers
drwxr-xr-x  73 root root   4096 Feb 27 00:43 net
drwxr-xr-x  31 root root   4096 Feb 27 00:28 samples
drwxr-xr-x  17 root root  20480 Feb 27 00:28 scripts
drwxr-xr-x  13 root root   4096 Feb 27 00:28 security
drwxr-xr-x  26 root root   4096 Feb 27 00:28 sound
drwxr-xr-x  32 root root   4096 Feb 27 00:28 tools
drwxr-xr-x   3 root root   4096 Feb 27 00:28 usr
drwxr-xr-x   4 root root   4096 Feb 27 00:28 virt
`

**Comment by alexreinert** [comment]
Dein laufender Kernel ist aktueller als die installierten Kernel Header (5.10.17 vs. 5.10.11).

Msl ns Blaue geraten: Hast du rpi-update verwendet um den Kernel zu aktualisieren?

**Comment by rschulz921** [comment]
Korrekt, irgendwann und irgendwo beim googeln kam dieser Befehl als Tipp wohl mit dazwischen. Gibt es eine Möglichkeit die beiden Versionen wieder anzugleichen?

**Comment by alexreinert** [comment]
Das ist überholt, rpi-update soll man schon seit Jahren nur in ganz wenigen Fällen auf explizite Anforderung der Raspberry entwicker einsetzen.

```
sudo apt update
sudo apt install --reinstall raspberrypi-bootloader raspberrypi-kernel
```
und ein reboot sollten das Problem beheben. Nach dem Reboot werden die Kernel Module automatisch gebaut, das kann aber etwas dauern. Daher einfach erstmal 10-15 Minuten nichts machen und dann debmatic-info anschauen.

**Comment by rschulz921** [comment]
Hallo Alex, das schaut schon viel viel besser aus und ich erinner mich, gestern deinem Hinweis unter: [https://github.com/alexreinert/debmatic/issues/33](https://github.com/alexreinert/debmatic/issues/33) sochmal gefolgt zu sein, lediglich die 10min Wartezeit habe ich wohl ignoriert :/ Danke für den Tipp!!!

Jetzt schaut debmatic-info so aus:

`
openhabian@openhabian:~ $ sudo debmatic-info
[sudo] password for openhabian:
debmatic version: 3.55.10-66
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  JEQ0240609
 Radio MAC:     0x1C12D3
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7CEE98D13E1
 Radio MAC:     0xB633ED
`
In der Admin UI sehe ich die Geräte:

- HM-RCV-50 BidCoS-RF
- HmIP-RCV-50 HmIP-RCV-1

Das Anlernen des Tasters HmIP-WRC2 hat geklappt.

Leider klappt das Anlernen des Thermostats nicht (auf Geräte anlernen, HmIP anlernen, Thermostat HmIP-WTH-TK resettet und auf anlernen gestellt).

Ich vermut es liegt am Zusatz "TK" weil es aus dem Telekom Sortiment stammt oder? Kennst du da noch einen Trick oder muss ich die Thermostaten tauschen?

**Comment by alexreinert** [comment]
Ich weiß, dass es mit irgendwelchen Telekom Geräten Probleme gab, aber ich habe nicht mehr genau im Kopf, welche das waren.
Du könntest versuchen, die mal mit Eingabe von SGTIN/Key anlernen.

**Comment by rschulz921** [comment]
funktioniert leider nicht, ich werde es wohl einfach mal mit einem Gerät ohne "TK" Zusatz ausprobieren, vielen Dank aber erstmal!!!
