### ISSUE TITLE
debmatic und homematic ip hap

### ISSUE THREAD

**Issue by Checktitek** [alexreinert/debmatic#207]
Hallo Alex,

ich bin ziemlich neu in der Homematic Welt und fange gerade erst an. Mit dem Homatic IP - Hap habe ich angefangen und da ich hier noch ein Raspberry Pi 3b am laufen habe, hab ich mich schnell dazu entschlossen den Pi für Homematic zu benutzen, also habe ich mir noch schnell ein HM-MOD-RPI-PCB gekauft. Da aber noch ADSB (Flugzeugempfang) auf dem Pi läuft, kam auch nur debmatic für mich in Frage. Jetzt zu mein Problem, ich konnte alle Homematic IP Geräte unt debmatic Anlernen, was aber nicht funktioniert ist der Hap, wenn ich auf Access Point hinzufügen klicke, wird der Hintergrund gräulich, aber mehr auch nicht. Ich kann nirgends drauf drücken, egal wie lange ich es „stehen“ lasse, muss immer den Browser schließen und mich neu Anmelden. Ein Deinstallieren aller Komponenten hat leider auch nichts gebracht und im Netz habe ich dazu auch nichts gefunden. Ich würde den Hap gerne als Range Extender benutzen, da im Haus nur mit dem Pi nicht so eine gute Abdeckung ist. Vielleicht haben Sie noch ein Rat für mich. 

Gruss Marco

**Comment by alexreinert** [comment]
Für die Nuzzung des HmIP-HAP und den HmIPW-DRAP ist zwingend das Funkmodul RPI-RF-MOD notwendig, weil dies nicht nur funken kann, sondern auch die gesamten Krxptofunktionen von HmIP durchführt. Für das HM-MOD-RPI-PCB hat eQ-3 kein Firmware Update bereitgestellt, welches die notwendigen Kryptofunktionen bereitstellt.

**Comment by Checktitek** [comment]
Ok das macht Sinn. Danke fürs schnelle Antworten, dann bestelle ich mal ein neues Modul.

Damit sollte der Fehler dann aber Verschwunden sein?

**Comment by alexreinert** [comment]
Ja

**Comment by Goersch** [comment]
Ich häng mich mal hier dran - wahrscheinlich hab ich da was falsch gemacht/verstanden oder nicht genug gelesen. Irgendwie ist das alles ein wenig verwirrend, was die unterschiedlichen Funk-Erweiterung angeht.

Mit dem HmIP-RFUSB kann ich somit keinen HmIP-W DRAP an debmatic/CCU anmelden? Oder ist da ein RPI-RF-MOD drauf? 
Firmware ist 2.8.6. 

Ich kann zwar mit dem HmIP-RFUSB HmIP Geräte anmelden - in der Systemsteuerung wird aber die Funktion zum Anmelden der HmIP HAB / DRAP nicht angezeigt (einzig "Accespoint mit inkompatibler FW", der aber dazu führt, dass der Web-Server hängt)

**Comment by alexreinert** [comment]
Wie geschrieben, du brauchst zwingend das RPI-RF-MOD. Ob das per GPIO Header, per HB-RF-USB oder per HB-RF-ETH angeschlossen ist, ist dabei egal.
Der HmIP-RFUSB ist dafür ungeeignet und auch aus anderen Gründen eine ziemliche Krücke.

**Comment by Goersch** [comment]
Danke für die Klarstellung - jetzt hab ichs verstanden - das HmIP-RFUSB kommt nicht mit einem   RPI-RF-MOD.
