### ISSUE TITLE
Delete broken addons

### ISSUE THREAD

**Issue by salapate** [alexreinert/debmatic#208]
Aus mir unersichtlichen Gründen habe ich bei der Migration von raspberrymatic zu debmatic wohl ein Backup gemacht, bevor ich die Addons entfernt habe... Nun habe ich die diversen stubs für watchdock und einige andere in der GUI und frage mich ob es eine Möglichkeit diese trotzdem zu löschen? Auf der GUI gibt es ja jetzt keine Möglichkeit mehr Addons zu managen.

* Ein MVP wäre ja bereits eine Beschreibung zur manuellen Entfernung.

**Comment by salapate** [comment]
Ich hatte versucht das Backup nach zip umzubenennen und dann in selbigem die Struktur zu durchforsten, es lässt sich aber nicht entpacken. Scheinbar hat sich das Format geändert?

**Comment by alexreinert** [comment]
Ich vermute, du meinst innerhalb der Systemsteuerung? Dann ist die Datei /etc/config/hm_addons.cfg dein Freund.

Das Backup war schon immer kein Zip, sondern ein tar.gz.

**Comment by salapate** [comment]
Danke, Alex! Habe cuxd deinstalliert und das file umbenannt. 
Jetzt habe ich nur noch das Problem, dass "devconfig" nicht richtig funktioniert, bzw. dass ich weder unter devconfig noch über die Geräteansicht die stubs einer vorherigen hue integration gelöscht bekomme. In der Geräteansicht hängt sich das Löschen mit der Meldung "Konfigurationsdaten werden geladen... Bite Warten..." auf. und ich muss die Seite neu laden. Wenn ich es via devconfig versuche kommt "An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root)."

**Comment by salapate** [comment]
Das umbenennen/läöschen des mapdb directories scheint hier Abhilfe zu schaffen.:
https://homematic-forum.de/forum/viewtopic.php?t=41891
