### ISSUE TITLE
Wired-Geräte bleiben im Posteingang

### ISSUE THREAD

**Issue by gwiltschek** [alexreinert/debmatic#21]
Hallo,

Beim Versuch einen HMW_IO_12_Sw7_DR (bzw auch einen Sw2-DR) anzulernen landet dieser im Posteingang, aber es erscheint nie ein Fertig-Button anstelle des Lade-Icons. In der Browserkonsole bekomme ich eine Fehlermeldung, dass device null ist (in der allChannesAvailable-Methode in webui.js, Device.get mit der devID gibt dort immer null zurück). Auch Interface/Kategorie im Posteingang zeigt null, schätze mal da hats irgendwas.

Wenn ich numberOfChannels auf 16 oder sonstwas setze bekomme ich die Buttons und kann die Geräte aus dem Posteingang holen, habe sie aber dann aber nirgendwo mehr in der GUI (schalten geht trotzdem über openHAB, da die Geräte dort schon einmal angelegt waren).

Normale RF-Geräte funktionieren tadellos.

Zum System:
Raspbian 9
Linux 4.14.48-v7+ #1118 SMP Thu Jun 7 16:40:27 BST 2018 armv7l GNU/Linux
debmatic version: 3.45.7-16
Browser am Client: Chrome Version 74.0.3729.108 (Official Build) (64-bit) (aber auch mit FF, Edge, etc getestet)

Lg,
Georg

**Comment by alexreinert** [comment]
Mir fehlen aktuell leider Wired Testgeräte, so dass ich das Problem nicht nachstellen kann.

**Comment by gwiltschek** [comment]
Hi,

ich hab debmatic jetzt auf einem frisch aufgesetzten rasbian neu installiert und da geht alles. Keine Ahnung was es da vorher hatte.

Lg,
Georg

**Comment by gwiltschek** [comment]
Ein kleiner Nachtrag, weil ich das Problem noch ein paar mal hatte und jetzt endlich herausgefunden habe woher es kommt:

Beim Anlernen eines Wired-Gateways bekommt dieses eine DeviceID (zB 123). Sucht man nuch nach Wired-Geräten, sollten diese als InterfaceID ebenfalls die 123 bekommen, allerdings bekamen sie oft eine andere, zB 999. Dadurch ist das Interface im WebUI auch null, weil es kein Interface mit der ID 999 gab. Die CCU speichert die ID unter in /var/HS485D.handlers und holt sie sich auch von dort, allerdings wird die Datei nie gelöscht weswegen es in einigen Fällen (anderes Funkmodul, anderes Gateway, wechsel yahm -> debmatic, keine Ahnung) zu meinem Problem kam. Wenn ich die Datei lösche wird sie beim nächsten Start von debmatic richtig angelegt und alles funktioniert (also scheinbar zumindest) :)

Lg,
Georg
