### ISSUE TITLE
Anbindung HMUARTLGW möglich?

### ISSUE THREAD

**Issue by hvorragend** [alexreinert/debmatic#210]
Hallo, 
kann ich in debmatic einen "HMUARTLGW" (
https://wiki.fhem.de/wiki/HMUARTLGW) einbinden?

Der HM-MOD-UART vom HM-MOD-RPI-PCB wird dabei per esplink über das Wifi eingebunden. Aktuell nutze ich das in FHEM. Würde aber gerne debmatic ausprobieren. 

Danke
Carsten

**Comment by alexreinert** [comment]
HMUARTLGW ist ein Software Modul von FHEM und keine Hardware.
Eine Einbindung des Funkmoduls per WLAN wird nicht unterstützt, weil der Betrieb mit der Dual CoPro Firmware Latenzanforderungen hat, welche per WLAN nicht machbar sind. FHEM nutzt nur die BidCos only Firmware, bei der das weniger problematisch ist.

**Comment by hvorragend** [comment]
Okay. Danke. Ich kannte die Unterschiede nicht. Danke für die Erklärung.
