### ISSUE TITLE
HM-MOD-UART auf MapleCUL nutzbar?

### ISSUE THREAD

**Issue by hvorragend** [alexreinert/debmatic#211]
Hallo,

mich habe einen MapleCUL (https://wiki.fhem.de/wiki/MapleCUN nur per USB und nicht per LAN eingebunden), auf dem ich einen HM-MOD-UART per ttyACM einbinden kann. 

Kann debmatic diesen auch nutzen?
Ich hätte auch einige HM-MOD-UART-USB-Sticks, die ich gerne in debmatic verdrahten würde. Geht das?

Danke
Carsten

**Comment by alexreinert** [comment]
Ein MapleCUL ist kein HM-MOD-UART und kann dieses meines Wissens nach auch nicht vollständig emulieren, daher auch hier ein Nein.

HM-MOD-UART-USB ist mir unbekannt (und auch Google findet dazu nichts), daher kann ich dazu nichts sagen.

Ganz allgemein steht im Readme aber auch drin, welche Funkhardware unterstützt wird.

**Comment by hvorragend** [comment]
Ich habe einen HM-MOD-UART einfach nur auf einem MapleCUL und der wird dann als ttyACM zur Verfügung gestellt. 

Das "HM-MOD-UART-USB" waren von mir zu viele Bindestriche. Ich habe mehrere USB-Stick mit einem HM-MOD-UART-USB. https://forum.fhem.de/index.php/topic,56606.msg757155.html#msg757155

Aber die Antwort wird vermutlich ähnlich sein. 😄

**Comment by alexreinert** [comment]
Ja, sieht leider ähnlich aus. Der verlinkte USB Stick nutzt zwar den gleichen Chip (FT232R) wie die unterstützte HB-RF-USB Platine, allerdings ist er nicht ganz kompatibel verdrahtet und hält sich auch nicht ganz an die USB Vorgaben und die Design Notes von FTDI.

**Comment by hvorragend** [comment]
Okay. Danke.
