### ISSUE TITLE
co-processor device

### ISSUE THREAD

**Issue by ptweety** [alexreinert/debmatic#212]
Hi,

wäre es möglich diesen patch (s.u.) einzupflegen?
(Und ja, mir ist bewusst, dass dies gehen die Philosophie des Projekts verstößt)

``` shell
--- /usr/share/debmatic/bin/start_hmserver.sh.orig
+++ /usr/share/debmatic/bin/start_hmserver.sh
@@ -16,6 +16,11 @@
   sed "s|^Adapter\.1\.Port=.*$|Adapter.1.Port=${HM_HMIP_DEVNODE}|" /etc/crRFD.conf > /var/run/crRFD.conf
   if [[ "${HM_HMIP_DEV}" != "RPI-RF-MOD" ]]; then
     sed -i "s|^Lan\.Routing\.Enabled=.*$|Lan.Routing.Enabled=false|" /var/run/crRFD.conf
+  else
+    # enable Adapter.Local.Device.Enabled in case a RPI-RF-MOD is used. This
+    # will bring up the additional CO-PROCESSOR device which will allow to show
+    # up the DutyCycle and CarrierSense parameters.
+    sed -i "s|^Adapter\.Local\.Device\.Enabled=.*$|Adapter.Local.Device.Enabled=true|" /var/run/crRFD.conf
   fi
 fi
```

**Comment by alexreinert** [comment]
Bei debmatic bin ich da deutlich entspannter mit solchen Anpassungen.
Einzig will ich erst die 3.57.4 im Lauf der Woche in stable übernehmen und nicht kurz vorher noch ein potentielles Problem einbauen.

**Comment by alexreinert** [comment]
Ist jetzt eingebaut, wenn auch etwas abweichend: in der /etc/crRFD.conf ist er per Default aktiviert und wird in der start_hmserver.sh bei Bedarf deaktiviert, falls kein RPI-RF-MOD verwendet wird. Dieses Vorgehen hat den Vorteil, dass der Nutzer die Möglichkeit hat, das auch beim RPI-RF-MOD zu deaktivieren, mit dem Patch oben gäbe es da keine Möglichkeit für.
Ein entsprechendes Update ist im testing APT Repository drin und kommt dann in ca. 2 Wochen in stable.

**Comment by ptweety** [comment]
Ich habe das (wie vorgeschlagen) ausprobiert und mal ein paar Tage so laufen lassen. Sieht alles gut aus ...
