### ISSUE TITLE
Reconnect nach ausschalten von HB-RF-ETH funktioniert nicht.

### ISSUE THREAD

**Issue by hieblmedia** [alexreinert/debmatic#214]
Hallo,
habe seit paar Tagen die HB-RF-ETH Platine mit RPI-RF-MOD im Einsatz. Funktioniert soweit alles problemlos.

Es gibt ein kleines Problem beim wieder verbinden.

- Wenn man nur das Netzwerkkabel zieht und wieder ansteckt, funktioniert das wieder verbinden problemlos.
- Wenn man die Platine aber vom Strom nimmt und wieder einschaltet dann kommt einfach kein reconnect zutande. 
Habe auch versucht das Netzwerkkabel danach aus-/einzustecken. Bringt nichts.  Ich vermute mal das dann irgendeine Initialisierung nicht stattfindet, da die Blaue LED dann auch nicht anspringt.
Man muss daher bei Power-Off der HB-RF-ETH Platine debmatic immer neu starten.

![image](https://user-images.githubusercontent.com/183510/111869262-cd689580-897e-11eb-831b-3529a2596797.png)

**Comment by alexreinert** [comment]
Ja, das ist so By Design.
Durch die Stromunterbrechung ist nicht mehr sichergestellt, dass das Funkmodul korrekt initialisiert ist und eine Reinitialisierung kann man bei den Closed Source Komponenten von eQ-3 nur durch einen Neustart durchführen.

**Comment by hieblmedia** [comment]
Ah ok. Danke für die Info.
