### ISSUE TITLE
Signalstärke ausgeben

### ISSUE THREAD

**Issue by iTobs** [alexreinert/debmatic#215]
Hallo,
wann wird die Signalstärke der Verbindung zu den Geräten gemessen, bzw wie kann ich debmatic dazu bringen diese zu messen. 
Ich habe debmatic zusammen mit openhab im Einsatz. Dort kann ich SIGNAL_STRENGTH der einzelnen verbundenen Geräte auslesen. Zu Beginn wurde mir die Signalstärke bei 2 von 10 Geräten als NULL angezeigt, obwohl die Steuerung der Geräte funktionierte.
Nach Neustart des raspberry zeigt er mir bei allen Verbindungen NULL an. 
In der Web-Oberfläche von debmatic / homematic habe ich auch keinen Menüpunkt gefunden mir dort die Signalstärke anzuzeigen. 
Kann mir jemand weiterhelfen?
Viele Grüße
Tobias

**Comment by alexreinert** [comment]
Ich vermute, dass das in OpenHab aus den RSSI Werten kommt. Diese werden aktualisiert, wenn Signale empfangen und gesendet werden. Wann das passiert, kommt auf das jeweilige Gerät an, bei manchen Batteriegeräten kann das z.B. nur sein, wenn eine Taste gedrückt wird, bei einer Zwischenste kdose mit Messfunktion kann es alle 3 Minuten sein.
Insgesamt sollte man dem Wert aber nicht zuviel Aufmerksamkeit widmen, Signalstärke darf man nicht mit Signalqualität verwechseln.

**Comment by iTobs** [comment]
Ich verwende 9 Funk-Heizkörpertthermostate HM-CC-RT-DN und ein Wandthermosthat HM-TC-IT-WM-W-EU.
Ich habe verschiedene Funktionien durchgesehen-sie melden aber keine Signalstärke mehr.
Ich war darauf gekommen, weil ich den Batteriestand überwachen wollte. Wenn aber Signalstärke nicht so viel aussagt, lass ich es einfach weg. Zeigt denn debmatic irgendwo die Signalqualität an, um einnzuschätzen, wie gut die Übertragung ist?

**Comment by alexreinert** [comment]
Über die versteckte devconfig.cgi der CCU kann man sich die RSSI Werte abrufen (Google hilft, wie man auf die Seite kommt). Damit kann man eine Abschätzung machen, aber wie geschrieben, die Werte muss man mit Vorsicht genießen. Ansonsten liefern die Closed Source Komponenten von eQ-3 leider keine wirklichen Informationen aus. Ggf. helfen dir externe Systeme wie der AskSinAnalyzer.
