### ISSUE TITLE
Homematic-Virtual-Interface & Highchart

### ISSUE THREAD

**Issue by tromanski** [alexreinert/debmatic#216]
Hallo Alex Reinert,

ich würde gerne die Variablen meiner Debmatic Installation mit Highchart visualisieren. Ist es von dir geplant Highchart zu integrieren? Interessant wäre auch das Homematic-Virtual-Interface, da es noch viele weitere Funktionen bietet. Bin mir jedoch nicht sicher, ob es noch gepflegt wird

Vielen Dank im Voraus

**Comment by alexreinert** [comment]
Falls du damit das highchart Addon meinst: Das steht aktuell nicht auf der Agenda, weil es bisher niemand angefragt hat. Vermutlich, weil die meisten Nutzer nicht die stark begrenzten Diagramm Möglichkeiten nutzen, sondern komplett andere Middleware, welche sowas dann aus einem Guß mitbringen.
