### ISSUE TITLE
HM-MOD-RPI-PCB  wird nicht erkannt

### ISSUE THREAD

**Issue by opu1000** [alexreinert/debmatic#217]
Hallo Alex, ich bin neu im debmatic Thema (und github), hatte vorher homegear im Start. Ich haben einen Raspberry 3B im Einsatz.
Mein Modul wird irgendwie nicht erkannt. Ich habe openhabian (neues Version)  installiert und oben drauf debmatic.
die /boot/config.txt sieht so aus:
cat /boot/config.txt

#hdmi_safe=1
#disable_overscan=1
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16
#framebuffer_width=1280
#framebuffer_height=720
#hdmi_force_hotplug=1
#hdmi_group=1
#hdmi_mode=1
#hdmi_drive=2
#config_hdmi_boost=4
#sdtv_mode=2
#arm_freq=800
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

dtparam=audio=on

[pi4]

dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=16

dtoverlay=pivccu-raspberrypi
dtoverlay=pi3-disable-bt

**Die Paket Info ist diese hier:**
pkg -s pivccu-modules-raspberrypi
Package: pivccu-modules-raspberrypi
Status: install ok installed
Priority: extra
Section: kernel
Maintainer: Alexander Reinert <alex@areinert.de>
Architecture: all
Version: 2.0-15
Depends: raspberrypi-kernel-headers | linux-headers-raspi, pivccu-modules-dkms, bc
Pre-Depends: debconf (>= 0.5) | debconf-2.0
Description: Raspberry Pi kernel modules needed for Homematic
  This package contains the Raspberry Pi kernel needed for Homematic.
Homepage: https://github.com/alexreinert/piVCCU

Was könnte das sein?

**Comment by opu1000** [comment]
Dies liefert debmatic-info:
root@openhabian:~# debmatic-info
debmatic version: 3.57.4-68
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

**Comment by opu1000** [comment]
Hallo, knn mal bitte einer helfen. Ich bekomme das Modul einfach nicht zum Laufen.
Gruß

**Comment by 00joshi** [comment]
Ich hatte das Problem auch und nun ist es weg. Leider kann ich nicht genau sagen was das Problem gelöst hat. In raspi-config habe ich das tool geupdatet und "resize partition" angeklickt.

Aus der Bash History:

 ```
sudo dpkg --purge debmatic
cd /media/usb0/
ls
cd ..
sudo apt-get install debmatic
service lighttpd force-reload
sudo dpkg --purge raspberrypi-kernel-headers pivccu-modules-dkms
sudo dpkg --purge pivccu-modules-dkms raspberrypi-kernel-headers
dpkg --purge pivccu-modules-raspberrypi
sudo dpkg --purge pivccu-modules-raspberrypi
sudo dpkg --purge pivccu-modules-dkms
sudo apt install pivccu-modules-dkms
sudo apt install raspberrypi-kernel-headers pivccu-modules-dkms
sudo apt install build-essential bison flex libssl-dev
sudo apt install pivccu-modules-raspberrypi
ls
detect_radio_module
sudo
sudo reboot
raspi-config
sudo raspi-config
sudo reboot
```

**Comment by alexreinert** [comment]
Welches Funkmodul ist im Einsatz? Hat das vorher schon funktioniert oder ist es neu?
Was liefert `sudo detect_radio_module --debug /dev/raw-uart`?

**Comment by opu1000** [comment]
Hallo Alex, ich nutze auf dem Raspi das Modul HM-MOD-RPI-PCB. Es war 3 Jahrelang mit homegear im Einsatz. Dazu hatte ich openHAB als Zentrale. Zur Zeit nutze ich für die "Produktion" einen 2. Raspi mit dem neuen HM-Modul und Raspberrymatic. Ich will aber wieder umsteigen und openHAB nutzen, das dann debmatic als "bridge" nutzt. Mein Ziel ist alles auf einem Gerät zu haben. Das Modul wird nicht erkannt:

 sudo detect_radio_module --debug /dev/raw-uart
Sending HM frame: fd 00 03 fe 00 01 14 1e
Sending HM frame: fd 00 03 00 01 00 9e 03
Received HM frame: fd 00 0d 00 01 04 02 43 6f 5f 43 50 55 5f 42 4c 7f 7b
Sending HM frame: fd 00 03 fe 02 01 98 1d
Sending HM frame: fd 00 03 00 03 00 12 00
Received HM frame: fd 00 0d 00 03 04 02 43 6f 5f 43 50 55 5f 42 4c ff 87
Sending HM frame: fd 00 03 00 04 03 80 09
Received HM frame: fd 00 04 00 04 04 00 99 6b
Sending HM frame: fd 00 03 fe 05 01 0a 1e
Sending HM frame: fd 00 03 00 06 00 0c 00
Received HM frame: fd 00 0d 00 06 04 02 43 6f 5f 43 50 55 5f 42 4c 3e 04
Sending HM frame: fd 00 03 00 07 03 8a 09
Received HM frame: fd 00 04 00 07 04 00 99 57
Sending HM frame: fd 00 03 fe 08 01 a4 1d
Sending HM frame: fd 00 03 00 09 00 2e 00
Received HM frame: fd 00 0d 00 09 04 02 43 6f 5f 43 50 55 5f 42 4c fc 84
Sending HM frame: fd 00 03 00 0a 03 24 0a
Received HM frame: fd 00 04 00 0a 04 00 19 b0
Error: Radio module was not detected

debmatic-info
debmatic version: 3.57.4-69
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

Gruß

**Comment by alexreinert** [comment]
Aktualisier bitte mal manuell die Firmware des Funkmoduls:
`sudo /bin/eq3configcmd update-coprocessor -u -p /dev/raw-uart -c -t HM-MOD-UART -f -d /firmware/HM-MOD-UART`
und führ danach danach den detect_radio_module Befehl nochmal aus.
Ausgabe von beidem bitte hier posten.

**Comment by MiCo2022** [comment]
Danke 1000x! Das Firmwareupdate hat auch mein altes Modul zum  Laufen gebracht!
