### ISSUE TITLE
Konstante CPU Auslastung durch HMIPServer.jar

### ISSUE THREAD

**Issue by fberlakovich** [alexreinert/debmatic#218]
Ich betreibe debmatic in einer Debian VM auf einem QNAP nas (x86_64) zusammen mit einem HMIP-RFUSB:
```
debmatic version: 3.57.4-68
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         3014F711A000041BE99B3957
 Radio MAC:     0xBC5DC9
```
Funktioniert soweit auch alles gut, aber der java Prozess der HMIPServer.jar ausführt verbraucht konstant ca 15% CPU und nach einigen Tagen sogar 100% CPU. Eine kurze Analyse mit jstack verrät, dass folgender Thread für die Auslastung verantwortlich ist:
```
"Thread-5" #48 prio=5 os_prio=0 cpu=1034814.53ms elapsed=6654.87s tid=0x00007efe4402f000 nid=0x3a3 runnable  [0x00007efe4ace5000]
   java.lang.Thread.State: RUNNABLE
        at gnu.io.RXTXPort.eventLoop(Native Method)
        at gnu.io.RXTXPort$MonitorThread.run(RXTXPort.java:1611)
```
Das Problem wirkt auf den ersten Blick wie dieses hier: https://github.com/NeuronRobotics/nrjavaserial/issues/36. Allerdings wurde das Problem in Version 3.12.0 von nrjavaserial behoben und soweit ich das beurteilen kann, ist in HMIPServer.jar Version 3.12.0 von nrjavaserial enthalten (siehe com/neuronrobotics/nrjavaserial/build.properties im jar). Was mich allerdings etwas stutzig macht: im assembly code von native/linux/x86_64/libNRJavaSerial.so wirkt es nicht so als wäre der patch vorhanden. Zumindest wird dort noch die Konstante 1000 und nicht wie zu erwarten 100 * 1000 verwendet.

Mir ist klar, dass das Problem sehr wahrscheinlich nicht an debmatic liegt, aber evt. kann mir jemand einen Hinweis geben wo ich weitersuchen könnte.

**Comment by fberlakovich** [comment]
Ok, ich habe einen workaround gefunden. Ich kann allerdings die Folgen noch nicht abschätzen, insofern kann ich diese Lösung wirklich niemandem empfehlen.
Ich habe ein checkout von https://github.com/NeuronRobotics/nrjavaserial gemacht und die neueste Version (6c54eeb) gebaut und anschließend `build/resources/main/native/linux/x86_64/libNRJavaSerial.so` nach `/usr/share/debmatic/lib/libNRJavaSerial.so` kopiert. Damit die neue library auch verwendet wird, habe ich noch `/usr/share/debmatic/bin/start_hmserver.sh` angepasst:
```
@@ -3,6 +3,12 @@
 if [ -z "$HM_HMIP_DEV" ]; then
   HMSERVER_BIN="HMServer"
   HMSERVER_ARGS="/etc/HMServer.conf"
+  if [ -e /usr/share/debmatic/lib ]; then
+    LIBSERIAL=`find /usr/share/debmatic/lib -name "libNRJavaSerial*.so"`
+    if [ -n "$LIBSERIAL" ]; then
+      JAVA_ARGS="-DlibNRJavaSerial.userlib=$LIBSERIAL"
+    fi
+  fi
 else
   if [ -e /usr/share/debmatic/lib ]; then
     LIBSERIAL=`find /usr/share/debmatic/lib -name "libNRJavaSerial*.so"`
```
Die CPU Auslastung ist verschwunden und auf den ersten Blick scheint alles zu funktionieren. Ich habe allerdings auch nur zwei Geräte.

* Warum habe ich die neueste Version von nrjavaserial genommen anstatt 3.12.0? Version 3.12.0 verwendet lockdev.h, das auf meinem System (Debian stretch) nicht verfügbar ist.
* Warum habe ich keine andere Version von nrjavaserial genommen? Zumindest Version 3.21.0 und 5.2.1 haben bei mir dazu geführt, dass meine beiden Geräte in Homatic nach dem Start deaktiviert waren und sich auch nicht aktivieren ließen. Warum? Keine Ahnung, könnte auch ein Zufall sein bzw. an etwas anderem liegen. Leider ist mir die Zeit ausgegangen das Problem weiter zu untersuchen und ich kenne mich auch überhaupt nicht mit Homatic aus.
* Warum ist diese Lösung eine schlechte Idee? Meine Lösung aktualisiert nicht die zugehörigen Java Klassen von nrjavaserial. Ich habe zwar überblicksmäßig überprüft ob im C code (dh. in der native library) möglicherweise nicht-rückwärtskompatible Änderungen gemacht wurden, aber es ist sehr gut möglich dass ich etwas übersehen habe. 

Möglicherweise hat jemand eine bessere Idee?

**Comment by alexreinert** [comment]
Die beste Idee wäre es, eQ-3 dazu zu bringen, dass sie einfach ein Upgrade auf die neueste Version machen. Ich habe das über alle mir verfügbaren Kanäle bereits versucht, aber je mehr Nutzer dort "nerven", desto höher sehe ich die Chancen, dass es passiert. Einfach weil die Beantwortung der Anfragen zu viel Aufwand verursacht.

**Comment by fberlakovich** [comment]
> Die beste Idee wäre es, eQ-3 dazu zu bringen, dass sie einfach ein Upgrade auf die neueste Version machen. Ich habe das über alle mir verfügbaren Kanäle bereits versucht, aber je mehr Nutzer dort "nerven", desto höher sehe ich die Chancen, dass es passiert. Einfach weil die Beantwortung der Anfragen zu viel Aufwand verursacht.

Alles klar, dann mache ich das mal. Was ist denn der vielversprechendste Weg eQ-3 zu kontaktieren?

**Comment by alexreinert** [comment]
Tja, wenn ich das nur wüsste... :-(

**Comment by fberlakovich** [comment]
Ok, ich denke dann kann man das Ticket schließen. Danke jedenfalls für die Antwort und die tolle Arbeit an debmatic!
