### ISSUE TITLE
SIcherheitsschlüssel // Probeme seit vorletztem Update

### ISSUE THREAD

**Issue by j-p-l** [alexreinert/debmatic#22]
Hallo Alex, 
ich habe seit dem vorletzten Update alle Verbindungen zu Geräten verloren, die mit einem Sicherheitschlüssel verbunden waren. Ich habe nach dem letzten Update alle Geräte geräteseitig zurückgesetzt und neu verbunden, was prinzipiell funktioniert hat. Leider besteht diese Möglichkeit nicht bei allen Geräten, wenn ein Sicherheitsschlüssel gesetzt ist. Diese Geräte bekomme ich jetzt aber auch nicht mehr an die CCU angelernt (obwohl der Sicherheitsschlüssel der selbe ist) und so sind diese momentan nicht mehr nutzbar. 
Bin ich der einzige mit diesem Problem? Hast du eine Idee, was ich machen kann? 

Was ich bis jetzt gemacht habe (leider ohne Erfolg): 
- altes Backup eingespielt
- Ich habe den richtigen Sicherheitsschlüssel verwendet
- versucht die Geräte abzulernen

Besteht die Möglichkeit die alte, letzte bei mir funktionierende Version, einzuspielen um die entsprechenden Geräte zurückzusetzen und diese dann in der aktuellen Version wieder neu anlernen? 

Andere Frage noch, wenn ich die Backups einspiele, sind unter Einstellungen die Buttons CloudMatic und NEOServer sichtbar, die ja bei debmatic keine Funktion haben. Kann ich diese irgendwie entfernen? 

Vielen Dank für deine Hilfe! 
Jannis

**Comment by alexreinert** [comment]
Welche Version meinst du genau mit vorletzte Version?

**Comment by j-p-l** [comment]
Sorry, hätte ich auch gleich schreiben können. Das war, als das Update von der 3.41.11
auf die 3.43.15 kam.

**Comment by j-p-l** [comment]
Ich habe gerade gesehen, dass ich den Status der zwei Dimmer - bei den anderen Geräten handelt es sich um Wandtaster - zumindest auslesen kann. Das Senden von Befehlen jedoch nicht.

**Comment by alexreinert** [comment]
Ich habe das bei mir versucht nachzustellen:
Jungfräuliche CCU3 mit Firmware 3.45.7, Sicherheitsschlüssel gesetzt, HM Gerät angelernt, Backup gemacht, CCU3 runtergefahren, debmatic gestartet, Backup eingespielt mit Eingabe von Sicherheitsschlüssel, Gerät lässt sich schalten.

Die Frage wäre jetzt, wo bei dir der Unterschied ist, welche zu dem Problem führt.

Von welchem System kommst du (bzw. von welchem System ist das Backup). War da vor diesem System ggf. noch irgendwas älteres im Einsatz (also z.B. von CCU1 zu CCU2 zu CCU3 zu debmatic)?

Wie sieht die /etc/config/crypttool.cfg auf dem alten System und auf debmatic aus (bitte hier partiell unkenntlich machen, weil das der Systemschlüssel ist, ich brauche aber die Info, ob die identisch sind).

**Comment by alexreinert** [comment]
Ein Fix ist hochgeladen und kann per apt installiert werden.
Allerdings muss man als Betroffener die Datei /etc/config/ids aus einem alten Backup wiederherstellen. Entweder durch Einspielen des kompletten Backups (mit dem Nachteil, dass dann natürlich alle Änderungen seit dem initialen Einspielen des Backups verloren sind), oder durch ein manuelles Ändern: Die sbk Dateien sind nichts anderes als tar Archive. Diese können z.B. mit 7Zip geöffnet werden. Dann im Archiv die originale ids Datei öffnen und den Inhalt der Datei manuell per SSH in der /etc/config/ids von der debmatic Installation ersetzen.

Sorry für die Umstände, war ein klassischer Bug, weil ich den Edge-Case der abweichende Formatierung von alten CCU2 Installationen übersehen habe und ein neuer Mechanismus damit Probleme hatte.

**Comment by j-p-l** [comment]
Super, vielen Dank! Haben die 'alte' ID eingestellt und neugestartet, die Taster resettet und dann mit der 'neuen' ID wieder angelernt. Geht jetzt wieder alles. 

War ein etwas anderes Topic, aber bekomme ich die Menüpunkte aus dem Backups unter Einstellungen für CloudMatic und den NEOServer entfernt? Die haben ja bei debmatic keine Funktion.

**Comment by alexreinert** [comment]
Du musst dafür die Datei /etc/config/hm_addons.cfg editieren und da die entprechende Punkte rausschmeißen.

**Comment by j-p-l** [comment]
Danke dir!
