### ISSUE TITLE
fehlende Kanäle unter "Startseite > Einstellungen > Geräte" 

### ISSUE THREAD

**Issue by Negruej** [alexreinert/debmatic#221]
Hallo Alex,

in der aktuellen Version 3.57.4.69 werden bei mir nicht alle Kanäle der Aktoren in der WebGui angezeigt.
Nicht angezeigte Kanäle sind dann auch für direkte Verknüpfungen nicht verfügbar.
Als Beispiel:
[Beispiel HMIP-PSM Debmatic.pdf](https://github.com/alexreinert/debmatic/files/6289760/Beispiel.HMIP-PSM.Debmatic.pdf)
bei einem HMIP-PSM gibt es den Kanal 3, 4 und 5 als Schaltkanal, angezeigt wird aber nur Kanal 3.
Vergleiche ich das mit meiner alten RaspiMatic Installation werden dort alle Kanäle angezeigt. 
[Beispiel HMIP-PSM RaspiMatic.pdf](https://github.com/alexreinert/debmatic/files/6289783/Beispiel.HMIP-PSM.RaspiMatic.pdf)
Einen Fehler durch Datenübernahme kann ich ausschließen da alle Aktoren von der alten Zentrale sauber abgelernt und nach reset an Debmatic wieder angelernt wurden.   

Lässt sich das Verhalten der Anzeige steuern oder ist das ein Fehler ?

Gruß,
Jürgen

**Comment by alexreinert** [comment]
Hast du in der Systemsteuerung unter Benutzereinstellungungen für deinen Benutzer die Option "Modus vereinfachte
Verknüpfungskonfiguration aktivieren" deaktiviert (also kein Häkchen drin)? Standardmäßig ist die in der CCU seit einigen Versionen aktiviert und würde dann dein Problem erklären.

**Comment by Negruej** [comment]
ja das wars, nach Ausschalten der Option "Modus für Vereinfachte Verknüpfungskonfiguration aktivieren" beim User in der Benutzerverwaltung sind alle wieder sichtbar.

Danke + schönes WoEnd

**Comment by fermoll2509** [comment]
Hallo Alex

Kann es sein, dass man nach der Umstellung "Vereinfachte Verknüpfungskonfiguration" auch die Aktoren restten und neu anlernen muss? Bei mir ist nur ein Kanal sichtbar.

**Comment by alexreinert** [comment]
Nein, die Geräte müssen nicht neu angelernt werden. Um sicher zu gehen: Die Option muss deaktiviert sein. Und es könnte sein, dass man sich einmal neu bei der CCU anmelden muss.
