### ISSUE TITLE
HM Geräte upgraden

### ISSUE THREAD

**Issue by boennhoff** [alexreinert/debmatic#222]
Hallo zusammen,
ich nutze _debmatic_ mit der CCU Version 3.57.4.69 zusammen mit einem _HM-MOD-RPI-PCB_, nutze bisher ausschließlich _HomeMatic_ Geräte und bin sehr froh alles als deb-package nutzen zu können, danke dafür @alexreinert.

Nun sehe ich in der _Geräte-Firmware - Übersicht_, dass einige Versionen veraltet sind (im Vergleich zu anderen), aber ich finde Online die Firmwaredateien die es wohl hochzuladen gilt nicht, ganz besonders nicht auf der ELV/EQ3 Websites. Andere Beiträge im Netz suggerieren, dass die Changelogs und Firmware über die Oberfläche verfügbar sein könnten und auch dort direkt flashbar sind. Aber nicht bei mir, die Übersicht ist diesbezüglich leer. Wo bekomme ich die Firmwares her?

Generell würde mich interessieren wie das Firmwareupgrade technisch gemacht wird mit der 1% Regel, die DutyCycle ist immer so dermaßen schnell voll, wie soll denn da eine Firmware übertragen werden können bei der mickrigen Datenmenge die zur Verfügung steht?

Wer kann mich erleuchten?

**Comment by alexreinert** [comment]
Früher gab es die Firmware Files mal direkt im Download Bereich von eQ-3, mittlerweile sind diese leider nicht mehr dort verfügbar.
Auf der Startseite wird normalerweise ein Link eingeblendet, wenn veraltete Firmwarestände auf den Geräten festgestellt werden über welche man die Firmware runterladen kann (ggf. die Startseite mal mit Strg+F5 aktualisieren). Mit diesem .tgz geht man dann vor, wie unter https://www.eq-3.de/downloads/faqs/Manuelles_Update_Geraete-Firmware.pdf beschrieben. Das .tgz darf nicht entpackt werden, beim Safari muss man da etwas aufpassen, weil der die standardmäßig entpackt.

**Comment by alexreinert** [comment]
Technisch werden die Updates über 868MHz versendet, damit gilt die 1% Regel des DutyCycles auch dort. Ein Firmware Update dauert daher selbst unter Idealbedingungen gerne mal 8-10 Stunden.

**Comment by boennhoff** [comment]
Danke für die schnellen Antworten! Ich nehme an, die Upgradedauer bezieht sich auf ein einzelnes Gerät... Ich konnte mir das Lachen nicht verkneifen, aber immerhin funktioniert das Upgrade überhaupt :+1:

Auf der Startseite werden bei mir allerdings keine Links zu Upgrades angezeigt, auch nicht nach dem Leeren des Browsercaches. Kommt man irgendwie manuell an die Links?

So sieht es bei mir aus:
![image](https://user-images.githubusercontent.com/6317864/115543965-4d498e80-a2a2-11eb-8589-e654bcee4202.png)
![image](https://user-images.githubusercontent.com/6317864/115544145-85e96800-a2a2-11eb-85a9-a0dc1a5e71b8.png)

**Comment by alexreinert** [comment]
Unter https://ccu3-update.homematic.com/firmware/api/firmware/search/DEVICE?product=HM-CCU3&version=3.57.5 kann man die aktuell verfügbaren Versionen abrufen, für die HM-TC-IT-WM-W-EU bekommt man die Firmware unter https://ccu3-update.homematic.com:8443/firmware/download?cmd=download&serial=0&product=HM-TC-IT-WM-W-EU

**Comment by boennhoff** [comment]
Danke, das war sehr hilfreich: Das erste Upgrade läuft!
