### ISSUE TITLE
Question about Git Workflow

### ISSUE THREAD

**Issue by theimo1221** [alexreinert/debmatic#223]
Hello team,

how could I include a patch like this (https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu/0111-WebUI-Fix-Translation-Performance/occu/WebUI/www/webui)?

As I migrated from Raspberrymatic to Debmatic I'd like to migrate that patch as well.

I have shortly above 100 Devices which results in Device Page needing ~8 seconds to load. With that patch applied it is reduced to ~1s.

Thanks and best regards 

Thiemo

**Comment by ptweety** [comment]
Hi @theimo1221,

es gibt m.E. keine separate patch Infrastruktur für debmatic. @alexreinert pflegt da ein paar Anpassungen, die für das Projekt relevant sind. Aber darüber hinausgehend gibt es nichts, wo du dich einhängen könntest.

Ich habe da vor ein paar Wochen selber mal drauf geschaut und für mich lokal eine Lösung gefunden. Allerdings ist das nicht gut genug für die Allgemeinheit.

Es bräuchte halt etwas mehr, wie etwa einen Maintainer für ein Repository von patches, einen Mechanismus, diese patches auch nach jedem update (oder start) von debmatic anzuwenden und vielleicht sogar eine Darstellung in der UI, welche patches der jeweilige Anwender aktiv hat (Letzteres könnt das Patcher-Addon von hobbyquaker leisten; gibt es aber nicht unter debmatic).

Für den Moment kannst du deinen patch also nur selber Einpflegen, indem du:
- debmatic stoppst
- den patch anpasst (etwa per `curl -s "$URL" | sed "s/\([---|+++] \)occu\/WebUI/\1/g" > "$PATCH"`)
- den patch einspielst (etwa per `patch -p0 -l -d/ -i "$PATCH"`)
- debmatic startest

**Comment by alexreinert** [comment]
Ich kam bis jetzt einfach noch nicht dazu, einen kompletten Workflow aufzusetzen.
Ich nehme gerne Vorschläge entgegen.

**Comment by ptweety** [comment]
Nun, als erstes stellt sich mir die Frage, ob
a) jeder patch ein integraler Bestandteil von debmatic sein soll (und damit per default in den Paketen mit ausgeliefert wird) oder
b) als separates Objekt behandelt wird (wie etwa ein Addon).

**Comment by theimo1221** [comment]
Während manche Patches komplett eigenständig sind, so bauen andere auf vorherigen auf, weswegen im Falle einer eigenen Auswahl an Patches, man dem Nutzer dies darstellen müsste.

Vielleicht reicht es auch die Patches zu Clustern (Bugfixes, Improvements, ...)
