### ISSUE TITLE
usb serial adapter nutzbar?

### ISSUE THREAD

**Issue by WiredLife** [alexreinert/debmatic#224]
Guten Abend, ich habe das HM-MOD-RPI-PCB Modul an einen USB Serial Wandler mit FTDI Chipsatz angeschlossen und diesen als /dev/ttyUSB05 eingebunden.
Kann debmatic das nutzen?
Vielen Dank!

**Comment by alexreinert** [comment]
Nein, weil die normalen USB Serial Wandler eine deutlich höhere Latenz haben, als es beim Funkmodul erlaubt ist.

**Comment by WiredLife** [comment]
Aber da ist doch auch nur ein normaler FT232RL drauf. Wenn man da Ihr Template drauf flasht, sollte das doch gehen oder muss man da vorher noch was anpassen, weil die Powerstrecke beim HB-RF-USB über Transistoren und PWREN geschaltet wird?

**Comment by alexreinert** [comment]
Nein, das ist kein normaler FT232RL. Der ist speziell geflasht und speziell beschaltet, damit die USB Richtlinien eingehalten werden können, was nicht bei den normalen USB Serial Wandlern in Verbindung mit den Funkmodulen regelmäßig nicht der Fall ist, weil dort der maximal erlaubte Stromaufnahme überschritten wird und es keine Entstörung Richtung USB Port gibt.

**Comment by WiredLife** [comment]
Oh, dann hab ich garantiert was falsch verstanden. Ich dachte man kann Ihren HB-RF-USB auch selbst nachbauen.
Gibt es eine Möglichkeit bei Ihnen das fertige PCB zu kaufen? Für SMD löten hab ich zu unruhige Hände.

**Comment by alexreinert** [comment]
Man kann die ja auch selber bauen, die entsprechenden Baupläne sind auf Github verfügbar. Aber eben nicht mittels eine fertigen USB Serial Adapters.
Aufgrund von WEEE und Co. verkaufe ich keine (teil-)bestückten Platinen. smartkram hat die Erlaubnis, diese in eigenem Namen und auf eigene Rechnung zu verkaufen.
