### ISSUE TITLE
Stop debmatic before full system backup

### ISSUE THREAD

**Issue by Alexander060101** [alexreinert/debmatic#225]
Hi,

I want to make weekly full system backups with the tool raspiBackup to my Synology NAS.

I am unsure whether it is enough to stop the "main" debmatic process with "systemctl stop debmatic" before the backup or whether I need to stop all debmatic processes separately.
Debmatic has quite a lot of them.
And if so: In which order should I stop them?

I am looking forward to any help.
Thanks.

Best regards
Alex

**Comment by alexreinert** [comment]
If you use `systemctl start/stop debmatic` it will start/stop all dependent processes in the right order.

**Comment by Alexander060101** [comment]
Thanks for the quick reply!
