### ISSUE TITLE
How to change webui port

### ISSUE THREAD

**Issue by MarpleA** [alexreinert/debmatic#228]
Hi,

this question has been asked a couple of time before but I still don't get it to work.

I'd like to change the webui port from 80 to 8080 and apparently there are three locations to I could change this port.
/etc/debmatic/webui.conf
/etc/lighttpd/lighttpd.conf
/etc/lighttpd/conf-available/20-debmatic.conf

changing number 1 and 2 doesn't work for me in any combination. I, of course, restarted the service after every change.
number 3 has a lot of port redirects but I don't see the port number 80 which I'd like to change. So I don't know what to change in this file.
Can someone shed some light on what has to be changed and how these three configs interact?

thx & best

**Comment by alexreinert** [comment]
Changing the port in /etc/debmatic/webui.conf should be enough to get the WebUI working on a different port.
Lighttpd will listen in that case on port 80 using the default config. Changing the port in /etc/lighttpd/lighttpd.conf will prevent Lighttpd from listining on port 80 anymore.
After the change the Lighttpd service and the debmatic service should be restarted (or just reboot the full system).
The file /etc/lighttpd/conf-available/20-debmatic.conf does not need to be changed as it includes the /etc/debmatic/webui.conf.

**Comment by MarpleA** [comment]
thanks!
