### ISSUE TITLE
HmIP-Mod-TM lässt sich nicht anlernen

### ISSUE THREAD

**Issue by mbuersi** [alexreinert/debmatic#231]
Hallo Alex, ich muss sagen ich bin technisch nicht so richtig drin im Thema, daher hoffe ich, dass ich hier überhaupt richtig bin.
Ich nutze einen Pi4 mit debmatic und einem HM-MOD-RPI-PCB. Bisher habe ich einen Temperatur+Feuchtigkeitssensor eingebunden, der wunderbar funktioniert. An diesem Punkt vielen Dank für deine Arbeit!

Ich wollte nun die Torsteuerung meines Novoferm Garagentors einbinden und nutze dafür das "HmIP-Mod-TM" Modul für dieses Tor. Leider erkennt die CCU das Modul nicht. Laut Anleitung ist das Modul 3min nach einstöpseln fähig eingebunden zu werden, dabei blinkt eine LED alle paar sekunden. Nach 3min muss einmal kurz auf den Knopf gedrückt werden um weiterhin anlernen zu können. Nach längerem Drücken verhält es sich wieder etwas anders, lässt sich aber auch so nicht einbinden.
In der Hm Web Oberfläche verändert sich dann nur plötzlich die Anlernzeit auf ca. 30sek. erkennen tut sie aber leider nichts.

Gibt es eine Lösung für dieses Problem?

**Comment by alexreinert** [comment]
Anlernen von HmIP Geräten funktioniert regelmäßig nur mit diesem Vorgehen:

- Werksreset vom Gerät (auch bei neuen Geräten)
- Stromversorgung vom Gerät trennen
- Anlernmodus in der CCU starten
- Stromversorgung wiederherstellen
- Nichts drücken, weder am Gerät noch in der CCU
- Warten bis die 30sec un der CCU abgelaufen sind

Das Drücken zum wieder aktivieren des Anlernmodus ist zwar in der Doku beschrieben, wirklich zuverlässig habe ich allerdings nie nutzen können.

Zusätzlich kommt hier ggf. noch hinzu, dass du einen RPi 4 hast. Dieser ist für seine massive Störstrahlung u.A. auf 868 MHz bekannt und stört vpr allem HmIP beim Listen before Talk. Da helfen nur mind. 50cm Abstand zwischen Funkmodul und Pi z.B. durch die Platine HB-RF-USB-2.

**Comment by box99h** [comment]
Ich habe gerade ein ähnliches Thema mit einer HMIP-PSM.
Mit meinem RPI4 und RPI-RF-MOD lässt sich die Dose weder anlernen noch schalten.
Meine daraufhin kurzfristig reaktivierte CCU2 schaltet die Dose problemlos und kann diese auch nach Werksreset wieder anlernen. 

Über die Debmatic funktioniert allerdings weder das schalten der Dose (durch Wiederherstellen aus dem CCU2 Backup) noch ein anlernen.
Die oben beschriebenen Punkte habe ich ohne Erfolg versucht.

Wenn noch jemand eine Idee hat wäre ich sehr dankbar.

**Comment by alexreinert** [comment]
Wie geschrieben: Der Raspi 4 ist ein massiver Störstrahler. Sorge für Abstand zwischen dem Pi und dem Funkmodul.

**Comment by box99h** [comment]
Danke.
Ich hab eine HB-RF-USB2 bestellt. 
Muss ich irgendetwas bei meiner bestehenden Installation ändern bzw. beachten, wenn ich auf USB Verbindung gehe? Ich bin damals nach dieser Anleitung vorgegangen [https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md](url).

Wenn das Modul via USB betrieben wird sollte sich auch Bluetooth wieder aktivieren lassen? Nach der Umstellung auf Soft-UART funktioniert der BLE Adapter im IOBroker bei mir nicht mehr.

**Comment by alexreinert** [comment]
Wechsel nur bei ausgeschaltetem System, ansonsten braucht man da nicht wirklich was beachten.
Beim Wechsel des Funkmoduls oder beim Wechsel von einer CCU2 braucht es bei HmIP ein Rekeying, welches zwingend Internetzugriff und etwas Zeit benötigt, daher das System kn dem Fall einfach mal für einige Stunden in Ruhe lassen.
Bluetooth kann bei Verwendung einer HB-RF-USB-2 auch wieder über den Hardware UART genutzt werden, man muss halt die entsprechenden Anpassungen aus der debmatic Anleitung wieder rückgängig machen.

**Comment by box99h** [comment]
Vielen Dank für die Hilfe. Mit den HB-RF-USB-2 funktioniert die Steckdose wieder. 
Kannst du mir vielleicht noch bei den konkreten Schritten helfen, die notwendig sind den Hardware UART zu reaktiveren?

Ich habe aus der /boot/config.txt den gesamten miniuart Block entfernt. dtoverlay=pi3-disable-bt ist nicht eingetragen.
systemctl status hciuart.service liefert:

> ● hciuart.service - Configure Bluetooth Modems connected by UART
   Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

>May 24 14:28:17 raspberrypi systemd[1]: Dependency failed for Configure Bluetooth Modems connected by UART.
>May 24 14:28:17 raspberrypi systemd[1]: hciuart.service: Job hciuart.service/start failed with result 'dependency'.

Danke
