### ISSUE TITLE
why using lighttpd? fixing security flaws

### ISSUE THREAD

**Issue by WiredLife** [alexreinert/debmatic#233]
as i see, lighttpd is only used as proxy
why proxying the ports one to another and not using the java server itself?

**Comment by alexreinert** [comment]
This is mainly because the original CCU3 works like this.

**Comment by alexreinert** [comment]
Unfortunately there is no such option in the closed binaries of eQ-3.

**Comment by WiredLife** [comment]
so this means every ccu is easily attackable by a hacker in the same network of the ccu?
sad life
i'm on the way to find how to fix this and will post it here

**Comment by gstrauss** [comment]
To constrain the exposure, you might configure eQ-3 binaries listen on a specific port, and then configure the host firewall to block all connections to that port except from localhost.
