### ISSUE TITLE
why using ReGaHss.normal instead of ReGaHss.community?

### ISSUE THREAD

**Issue by WiredLife** [alexreinert/debmatic#234]
is there a reason why using ReGaHss.normal instead of the newer ReGaHss.community version?

**Comment by alexreinert** [comment]
As in the CCU3 you can configure in the WebUI which ReGaHss should be used.

**Comment by WiredLife** [comment]
ah i see, so standard is normal and compatibility is the community version?
this description makes no sense for me

**Comment by alexreinert** [comment]
It seems, that there was a little change in the WebUI some versions ago. There were 3 variants: Normal, Legacy and Community, defaulting to Normal.
Right now the Normal was removed and the entry "Standard" is mapped to Community, and compatibility is mapped to "Normal".
But there is a bug in the WebUI, that the wrong drop down entry is selected in case the edition was not configured by the user.

**Comment by alexreinert** [comment]
HTML of the WebUI:
```
<select id="selectedReGaVersion">
  <option value="NORMAL">Kompatibilitätsmodus</option>
  <option value="COMMUNITY">Standard</option>
</select>
```
