### ISSUE TITLE
HB-RF-USB-TK wird in debmatic nach Update nicht mehr erkannt

### ISSUE THREAD

**Issue by iTobs** [alexreinert/debmatic#239]
Hi,

folgendes Problem und ich weiß nicht mehr weiter...
 
Ich habe auf meinem Raspberry pi4 debmatic mit HB-RF-USB-TK und openHAB laufen. 
nach 
sudo apt update && sudo apt upgrade
findet debmatic das Modul nicht mehr. 

lsusb
Bus 001 Device 059: ID 0403:6f70 Future Technology Devices International, Ltd HB-RF-USB

debmatic-info
debmatic version: 3.57.5-71
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

sudo dpkg-reconfigure pivccu-modules-dkms
läuft durch, aber nach dem reboot funktioniert debmatic trotzdem nicht. 

Wo kann ich noch suchen? 

Viele Grüße
Tobias

**Comment by alexreinert** [comment]
Was liefert `ls -la /dev/raw-*`?

**Comment by iTobs** [comment]
ls -la /dev/raw-*
ls: cannot access '/dev/raw-*': No such file or directory

**Comment by alexreinert** [comment]
`lsmod` und `modprobe hb-rf-usb`? (ausgeführt als root)

**Comment by iTobs** [comment]
[20:51:47] openhabian@openhab:~$ sudo lsmod
Module                  Size  Used by
rpi_rf_mod_led         16384  0
overlay               106496  2
8021q                  32768  0
garp                   16384  1 8021q
stp                    16384  1 garp
llc                    16384  2 garp,stp
vc4                   253952  0
cec                    49152  1 vc4
drm_kms_helper        241664  2 vc4
v3d                    73728  0
gpu_sched              45056  1 v3d
brcmfmac              327680  0
brcmutil               20480  1 brcmfmac
drm                   520192  5 v3d,vc4,gpu_sched,drm_kms_helper
sha256_generic         16384  0
drm_panel_orientation_quirks    16384  1 drm
cfg80211              761856  1 brcmfmac
snd_bcm2835            28672  1
rfkill                 32768  4 cfg80211
snd_soc_core          225280  1 vc4
bcm2835_codec          36864  0
bcm2835_isp            32768  0
bcm2835_v4l2           40960  0
snd_compress           20480  1 snd_soc_core
bcm2835_mmal_vchiq     28672  3 bcm2835_isp,bcm2835_codec,bcm2835_v4l2
v4l2_mem2mem           36864  1 bcm2835_codec
videobuf2_vmalloc      16384  1 bcm2835_v4l2
snd_pcm_dmaengine      16384  1 snd_soc_core
rpivid_mem             16384  0
videobuf2_dma_contig    20480  2 bcm2835_isp,bcm2835_codec
snd_pcm               106496  5 snd_compress,vc4,snd_pcm_dmaengine,snd_bcm2835,snd_soc_core
videobuf2_memops       16384  2 videobuf2_dma_contig,videobuf2_vmalloc
videobuf2_v4l2         32768  4 bcm2835_isp,bcm2835_codec,bcm2835_v4l2,v4l2_mem2mem
raspberrypi_hwmon      16384  0
videobuf2_common       61440  5 bcm2835_isp,bcm2835_codec,bcm2835_v4l2,v4l2_mem2mem,videobuf2_v4l2
snd_timer              32768  1 snd_pcm
lz4                    16384  8
lz4_compress           45056  1 lz4
syscopyarea            16384  1 drm_kms_helper
snd                    77824  7 snd_compress,snd_timer,snd_bcm2835,snd_soc_core,snd_pcm
zram                   28672  3
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
videodev              249856  6 bcm2835_isp,bcm2835_codec,videobuf2_common,bcm2835_v4l2,v4l2_mem2mem,videobuf2_v4l2
zsmalloc               28672  1 zram
fb_sys_fops            16384  1 drm_kms_helper
mc                     45056  6 bcm2835_isp,bcm2835_codec,videobuf2_common,videodev,v4l2_mem2mem,videobuf2_v4l2
backlight              20480  1 drm
vc_sm_cma              32768  2 bcm2835_isp,bcm2835_mmal_vchiq
hb_rf_usb              16384  0
generic_raw_uart       24576  1 hb_rf_usb
nvmem_rmem             16384  0
uio_pdrv_genirq        16384  0
uio                    20480  1 uio_pdrv_genirq
ip_tables              28672  0
x_tables               32768  1 ip_tables
ipv6                  495616  91
[20:55:14] openhabian@openhab:~$ sudo modprobe hb-rf-usb
[20:55:38] openhabian@openhab:~$

**Comment by iTobs** [comment]
Heißt das, dass hb_rf_usb geladen ist, aber debmatic es nicht verwendet? 
Fehlt da irgend etwas in der Konfiguration? 
Wäre schön, wenn Du mir weiter helfen könntest

**Comment by alexreinert** [comment]
Sorry für die Verzögerung, habe grade noch ein paar andere Dinge um die Ohren.

Was kommt bei folgenden Befehlen:

```
sudo systemctl stop debmatic
sudo rmmod hb-rf-usb
sudo modprobe hb-rf-usb
dmesg | tail -30
sudo ls -la /dev/raw-*
sudo detect_radio_module --debug /dev/raw-uart
```

**Comment by iTobs** [comment]
Hi,
kein Problem, ich hatte nur gestern noch ein wenig Zeit mir das anzusehen... 

Kann es sein, dass die Stromversorgung Probleme macht? 
Die ersten drei Befehle laufen ohne Meldung durch.
Im log wiederholt sich dann immer die Erkennung: 

```
dmesg | tail -30
[  152.829612] usb 1-1.4: Found HB-RF-USB at usb-0000:01:00.0-1.4
[  152.906929] usb 1-1.4: USB disconnect, device number 20
[  152.907373] usb 1-1.4: bitmode request failed for value 0x00f0: -19
[  153.233985] usb 1-1.4: new full-speed USB device number 21 using xhci_hcd
[  153.390873] usb 1-1.4: New USB device found, idVendor=0403, idProduct=6f70, bcdDevice= 6.00
[  153.390884] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  153.390892] usb 1-1.4: Product: HB-RF-USB
[  153.390900] usb 1-1.4: Manufacturer: Alexander Reinert
[  153.390906] usb 1-1.4: SerialNumber: A94VRFM3
[  153.399822] usb 1-1.4: Found HB-RF-USB at usb-0000:01:00.0-1.4
[  153.622773] usb 1-1.4: USB disconnect, device number 21
[  153.623196] usb 1-1.4: bitmode request failed for value 0x00f0: -19
[  153.953979] usb 1-1.4: new full-speed USB device number 22 using xhci_hcd
[  154.110980] usb 1-1.4: New USB device found, idVendor=0403, idProduct=6f70, bcdDevice= 6.00
[  154.110991] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  154.110998] usb 1-1.4: Product: HB-RF-USB
[  154.111005] usb 1-1.4: Manufacturer: Alexander Reinert
[  154.111012] usb 1-1.4: SerialNumber: A94VRFM3
[  154.119922] usb 1-1.4: Found HB-RF-USB at usb-0000:01:00.0-1.4
[  154.196961] usb 1-1.4: USB disconnect, device number 22
[  154.197387] usb 1-1.4: bitmode request failed for value 0x00f0: -19
[  154.504012] usb 1-1.4: new full-speed USB device number 23 using xhci_hcd
[  154.680942] usb 1-1.4: New USB device found, idVendor=0403, idProduct=6f70, bcdDevice= 6.00
[  154.680953] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  154.680961] usb 1-1.4: Product: HB-RF-USB
[  154.680968] usb 1-1.4: Manufacturer: Alexander Reinert
[  154.680975] usb 1-1.4: SerialNumber: A94VRFM3
[  154.690136] usb 1-1.4: Found HB-RF-USB at usb-0000:01:00.0-1.4
[  154.903532] usb 1-1.4: USB disconnect, device number 23
[  154.903953] usb 1-1.4: bitmode request failed for value 0x00f0: -19
```

**Comment by alexreinert** [comment]
Das sieht nicht nach einem Software Problem aus.
Deine Vermutung könnte hinkommen, könnte auch am Kabel oder der Buchse liegen, an einem falsch aufgestecktem Funkmodul oder an irgendeinem Kurzschluss im Bereich des Funkmoduls.

**Comment by iTobs** [comment]
Was wirklich seltsam ist, das Problem tritt seit einem Update auf...  
Ich werde es checken und berichten.
Danke erst einmal.

**Comment by iTobs** [comment]
Hallo und vielen Dank für die Tipps. 
Ich habe ein anderes USB-Kabel genommen, und die Verbindung hat funktioniert. Ich habe wieder das alte Kabel verwendet und es ging. Nach einem Reboot wieder das selbe Problem. Ab- und neu Angesteckt und dann ging es wieder. Irgendwie ist das seltsam. 
Momentan steckt das Modul am USB2 Anschluss. Ist das OK, oder wäre USB3 besser oder ist es einfach egal? 
Ich werde auch einmal ein Leistungsfähigeres Netzteil testen, irgendwie werde ich den Verdacht nicht los, dass es auch an der Stromversorgung liegen kann...
VG,Tobias

**Comment by alexreinert** [comment]
Das klingt wirklich mysteriös, aber es könnte wirklich am Netzteil liegen.
USB3 braucht es an sich nicht und normalerweise rate ich dazu, lieber den USB2 Anschluss zu nehmen. In deinem Fall würde ich es aber mal ausprobieren, da dann ein eine Controller Chip verwendet wird, der vielleicht etwas anders reagiert.

**Comment by iTobs** [comment]
Ich habe jetzt mein Raspberry an einem original-Netzteil hängen und es hat alles auf Anhieb funktioniert und auch noch dem reboot wird USB ordnungsgemäß erkannt. (immer noch am USB2) 
Ich hoffe, es bleibt dabei. :-) 
Vielen Dank für Deine Hilfe.

**Comment by iTobs** [comment]
Hallo, 
wird dieses Ticket wieder geöffnet, wenn ich etwas schreibe? 
VG, Tobias
