### ISSUE TITLE
Support for cloudmatic

### ISSUE THREAD

**Issue by Goersch** [alexreinert/debmatic#24]
habs hier gelesen, dass Du dran bist: 
[https://homematic-forum.de/forum/viewtopic.php?f=18&t=49029&p=500443&hilit=cloudmatic#p500443](url)
Ohne cloudmatic kann ich nicht umsteigen. Wäre schön, wenn Du hier bekannt geben könntest, wenn es funktioniert.
Danke!
Georg

**Comment by eric2905** [comment]
Bei mir auch.
Sobald das Addon da ist, stelle ich mein produktives System (ca. 90 Geräte) um. Benötige das Addon (noch) für den Remote-Zugriff über Pocket Control.

**Comment by Goersch** [comment]
Bei mir geht es auch um Pocket Control - beinhaltet Geofencing, Push Messages und einfachen Zugriff auf alle Geräte. Dafür gibt es andere Lösungen; ich weiß. Aber nicht in einem Tool über eine abgesicherte Verbindung auf die CCU. Port Forwarding gibts bei mir nicht und IFTTT via iobroker.pro mag ich nicht einsetzen.

**Comment by alexreinert** [comment]
Die komplette Portierung des Addons ist nicht so ganz trivial, die verlassen sich fast noch mehr darauf, dass die Scripts auf einer CCU laufen, als die CCU selbst.
Den VPN Zugang kann man aber relativ einfach manuell konfigurieren, würde euch das reichen?

**Comment by Goersch** [comment]
VPN hilft mir nicht (besteht bereits via FritzBox). Dazu muss ich die VPN Verbindung aber auch immer wieder aktivieren, was für Geofencing „unpraktisch“ ist :)

**Comment by alexreinert** [comment]
Ich meinte damit die reine VPN Verbindung von Cloudmatic.

**Comment by eric2905** [comment]
Der Cloudmatic-VPN-Zugang würde mir persönlich reichen (für Pocket Control).

**Comment by Goersch** [comment]
ah, ok, das würde mir auch (wahrscheinlich) reichen

**Comment by eric2905** [comment]
Hast Du ein grobes Gefühl, wann Du das implementieren kannst?
Das wäre für mich der Zeitpunkt, für den Wechsel von Pi3 / Charly / RaspberryMatic zu NUC / Proxmox / usw. 

Gruß,
Eric

**Comment by alexreinert** [comment]
Sobald es mit easyhome abschließend geklärt ist, dass ich es umsetzen darf.

**Comment by Goersch** [comment]
„Das wäre für mich der Zeitpunkt, für den Wechsel von Pi3 / Charly / RaspberryMatic zu NUC / Proxmox / usw.“

NUC=x86 - hatte verstanden, dass x86 nicht unterstützt wird von debmatic; oder fehlt mir hier „wissen“?

**Comment by alexreinert** [comment]
Stark vereinfacht:
x86 = 32-bit. 
x64 = x86 in 64-bit und das wird unterstützt.
Reine x86 Hardware ist am Narkt nicht mehr zu finden, das ist mittlerweile alles 64-bit (auch die NUCs).

**Comment by Goersch** [comment]
Ok, hab mich falsch ausgedrückt; ich finde den Issue nicht mehr; aber vor kurzem hatte ich noch die Info, dass Linux Kernel 5 und x64 grundsätzlich nicht von debmatic unterstützt wird. Da ich debmatic nun auf dem NUC installieren konnte, scheint sich das geändert zu haben. Danke ! :)

**Comment by alexreinert** [comment]
Du verwechselst das mit piVCCU.

**Comment by Goersch** [comment]
ich brauch glaub ich Urlaub. Danke

**Comment by fubo08** [comment]
Guten Morgen zusammen. Gibt es hier schon was neues? :) Ohne Cloudmatic kann ich leider nicht umsteigen. ;(

**Comment by eric2905** [comment]
Hallo Alex,
kurze vorsichtige Nachfrage wegen Cloudmatic?
Gibt es ein Licht am Horizont?
Gruß,
Eric

**Comment by alexreinert** [comment]
Es gibt Licht, ich habe ein OK, aber mir fehlt grade die Zeit, dass  zu finalisieren. Böser Sommer und so. ;-)

**Comment by eric2905** [comment]
Das ist die einzige Antwort, die ich lesen wollte ;-)
Heute ist ja offiziell der Sommer vorbei - also ran .... LOL ;-)

**Comment by alexreinert** [comment]
Die Funktionalität für Cloudmatic Connect ist so gut wie fertig. Ich warte noch auf eine kleine Zuarbeit von Easy Smarthome, so dass ich aus dem Installer per Benutzername und Passwort an den initialen Schlüssel komme. Wenn man diesen per Hand aus den Downloads extrahiert, funktioniert die Verbindung astrein und auch die Cloudmatic Webansicht funktioniert.

**Comment by eric2905** [comment]
Klasse. Wenn Du Tester brauchst, sag Bescheid.

**Comment by fubo08** [comment]
Sehr geil! Ich bin gespannt wie nen Flitzebogen! Stände natürlich ebenfalls für Tests zur Verfügung. :)

**Comment by alexreinert** [comment]
Paket ist fertig und im apt Repository verfügbar.
Falls das ganze in einem LXC Container läuft, bitte drauf achten, dass im Container ein tun Device verfügbar ist. (Siehe z.B. https://forum.proxmox.com/threads/proxmox-5-and-openvpn.46614/post-220681)

**Comment by MarkSau** [comment]
Hallo Alex...Ich habe debmatic in einem Container laufen und habe nun das Cloudmatic Paket per apt installiert. Auch habe ich die zwei Zeilen aus dem proxmox thread in der .conf hinzugefügt. Die Cloudmatic Schaltfläche war vorher schon da, hat aber jetzt weiterhin keine Funktion. Sie ruft http://192.168.0.10/addons/mh/index.cgi?sid=@G2NGzzgRfl@ auf...was mit einer 404 MEldung ins Leere läuft.

**Comment by alexreinert** [comment]
Die Weboberfläche gibt es noch nicht, im Moment ist das rein der VPN Zugang. Den Status von diesem kannst du per ```sudo systemctl status cloudmatic-openvpn.service``` abrufen.

**Comment by MarkSau** [comment]
> Die Weboberfläche gibt es noch nicht, im Moment ist das rein der VPN Zugang. Den Status von diesem kannst du per `sudo systemctl status cloudmatic-openvpn.service` abrufen.

Verstanden, alles klar...Per APP probiert, funktioniert astrein...Sehr gute Arbeit..Danke

**Comment by MarkSau** [comment]
btw...haben die Fehlermeldungen was zu sagen?

root@MSNUC-CCU:~# sudo systemctl status cloudmatic-openvpn.service
* cloudmatic-openvpn.service - Cloudmatic OpenVPN
   Loaded: loaded (/lib/systemd/system/cloudmatic-openvpn.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-09-06 07:45:46 CEST; 31min ago
 Main PID: 411 (openvpn)
    Tasks: 1 (limit: 4915)
   Memory: 2.8M
   CGroup: /system.slice/cloudmatic-openvpn.service
           `-411 /usr/sbin/openvpn --config /usr/share/cloudmatic/client.conf --cd /usr/share/cloudmatic

Sep 06 07:45:46 MSNUC-CCU systemd[1]: Started Cloudmatic OpenVPN.
Sep 06 07:45:46 MSNUC-CCU openvpn[411]: Fri Sep  6 07:45:46 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Sep 06 07:45:49 MSNUC-CCU openvpn[411]: RTNETLINK answers: File exists
Sep 06 07:45:49 MSNUC-CCU openvpn[411]: Fri Sep  6 07:45:49 2019 ERROR: Linux route add command failed: external program exited with error status: 2
Sep 06 07:45:49 MSNUC-CCU openvpn[411]: Fri Sep  6 07:45:49 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

**Comment by alexreinert** [comment]
> Sep 06 07:45:46 MSNUC-CCU openvpn[411]: Fri Sep 6 07:45:46 2019 WARNING: --ns-cert-type is DEPRECATED. Use --remote-cert-tls instead.

Kommt so aus der automatisch generierten Config von Cloudmatic. Ist aber unkritisch

> Sep 06 07:45:49 MSNUC-CCU openvpn[411]: RTNETLINK answers: File exists
> Sep 06 07:45:49 MSNUC-CCU openvpn[411]: Fri Sep 6 07:45:49 2019 ERROR: Linux route add command failed: external program exited with error status: 2

OpenVPN versucht mehrere Methoden um die Routen vom VPN im System einzutragen. Die erste davon funktioniert auf aktuellen Debian/Ubuntu Systemen nicht mehr und produziert die Fehlermeldung. Danach werden aber weitere Methoden genutzt. Also ebenfalls unkritisch.

> Sep 06 07:45:49 MSNUC-CCU openvpn[411]: Fri Sep 6 07:45:49 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Da keine Passwörter beim VPN Aufbau genutzt werden, sondern Zertifikate, ist das ebenfalls unkritisch. Und bevor die Frage aufkommt: Das Passwort, welches bei der Installation abgefragt wird, wird nicht dauerhaft gespeichert, das dient nur dazu, initial die Keys abzuholen.

**Comment by Goersch** [comment]
super, danke - werde ich auch demnächst ausprobieren. 

Frage: Die VPN-Schlüssel-Datei von Cloudmatic wird mit dem Backup eingespielt? Bin mir nicht mehr sicher, ob man die nicht jedesmal nach einem Backup einspielen muss (lange kein Backup mehr einspielen müssen).

**Comment by alexreinert** [comment]
Nein, die Keys werden nicht über das Backup eingespielt, aber sie werden im Zuge der Installation von den Cloudmatic Server geladen mit Benutzername, Cloudmatic ID und Passwort.

**Comment by Goersch** [comment]
ok, danke

**Comment by eddy-ch** [comment]
Hi Alex

leider bleibt bei meinem P4 mit Buster, die Installation bei 88% stehen und es geht nichts mehr

cloudmatic-openvpn.service is not active, cannot reload.

Progress: [ 88%] [##################################################........]
