### ISSUE TITLE
Debmatic - Eine Komponente der Homematic Zentrale reagiert nicht mehr

### ISSUE THREAD

**Issue by pawael** [alexreinert/debmatic#241]
Hallo zusammen,

ich betreibe eine CCU angeschlossen an eine QNAP TS-473 und reiche diese per USB Platine in eine Ubuntu 20.04 Server VM durch. Leider musste ich die NAS neu aufsetzen. Seitdem habe ich das Problem, dass die o.g. Meldung erscheint. HmIP-RF und VirtualDevices funktionieren nicht mehr. Diese Meldung erscheint direkt bei einer frischen Installation, da wurde noch kein Gerät angelernt. Wenn ich ein Backup zurückspiele, sehe ich unter Einstellungen>Geräte alle meine Geräte, unter Status und Bedienung>Geräte nur meine normalen HM Geräte (sind 2 an der Zahl, welche auch funktionieren). Alle HMIP Geräte werden dort nicht angezeigt. Ich habe HMIP Heizungstermostate, bei denen nach kurzer Zeit das Verbindungssymbol aufhört zu blinken. Ich bekomme das Problem leider nicht gelöst. Es wurde an der Hardware nichts verändert, nur das QTS neu installiert und ein frisches Ubuntu.
Folgendes habe ich bereits gemacht:
- Verschiedene Firmwares installiert
- Anderen USB Port verwendet
- USB Kompatibilität auf 2.0 gesetzt
- Neuere Linux Distribution verwendet

debmatic-info gibt folgendes aus:
debmatic version: 3.57.5-71
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:00:04.0-1 (/dev/raw-uart)
 Board serial:  58A9A71012
 Radio MAC:     0xFF1012
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         3014F711A0001F58A9A71012
 Radio MAC:     0xB2FA2F

Ich habe ein frisches Log einer neuen Maschine vom Start, bis zum erscheinen der Fehlermeldung angehangen
Ich würde mich freuen, wenn mir jemand helfen könnte

Liebe Grüße
PaWäl
[hmserver.log](https://github.com/alexreinert/debmatic/files/6726128/hmserver.log)

**Comment by bjoerns1983** [comment]
Hast du dafür eine Lösung gefunden? Ich musste heute meinen Server neu Aufsetzen (Debian 11) und bekomme auch genau die gleiche Meldung.

**Comment by pawael** [comment]
Leider habe ich keine Lösung dafür gefunden. Irgendwann habe ich es aufgegeben. Ich habe stattdessen ein altes Vollbackup gefunden und die komplette VM wiederhergestellt und dann mein Homematic Backup eingespielt. Das klappte. Seitdem gehe ich an das OS und Homematic nicht mehr dran, ausser Geräte hinzufügen oder einstellen. Aber ich installiere im Moment keine Updates für HM oder Ubuntu. Ferner sichere ich die komplette VM regelmäßig weg, da gezeigt hat, dass der Fehler ja bei der Installation auftritt. Deine Nachfrage zeigt mir, dass ich an der Stelle richtig gehandelt habe ;-) Schade finde ich, dass keine Lösung zu meinem Post kam. Tut mir Leid, dass ich keinen anderen Lösungsansatz anbieten kann
