### ISSUE TITLE
Nur Homematic IP Geräte anlernen möglich

### ISSUE THREAD

**Issue by bkunder** [alexreinert/debmatic#243]
In der WebUI ist es nur möglich die IP Familie anzulernen. Die Variante der älteren Modelle ist dort nicht gegeben, wird aber seitens Hersteller von der CCU3 unterstützt. Handelt es sich hier eventuell nur um eine Einstellung in der WebUi, welche den Zusatz freischaltet? Vielen Dank.

**Comment by alexreinert** [comment]
Welches Funkmodul wird verwendet?

**Comment by bkunder** [comment]
Das ist das verwendete Modul:

HMIP Hardware:  HMIP-RFUSB

**Comment by alexreinert** [comment]
Siehe Readme: Das Funkmodul kann nur HmIP Funk.

**Comment by bkunder** [comment]
Ok Danke
