### ISSUE TITLE
apt update zeigt keine neue version

### ISSUE THREAD

**Issue by Goersch** [alexreinert/debmatic#245]
Hallo,

ich hab schon länger nicht mehr auf meine CCu Firmware Version geschaut, da nach einem "apt update" & "apt upgrade" immer die neueste Version mitinstalliert wurde.

Das scheint nicht mehr zu funktionieren (ich bin auf 3.55.10.66 und will auf 3.59.6.73). "apt update" liefert nur "Alle Pakete sind aktuell". Eintrag in /etc/apt/sources.list.d/de* sieht auch OK aus: 

deb https://www.debmatic.de/debmatic stable main  

Kann ich einfach "drüberinstallieren" (apt upgrade debmatic=version oder so ähnlich)?

Gruss&Danke
Georg

**Comment by alexreinert** [comment]
Bitte mal die Ausgabe von `apt update`, `apt upgrade` und `apt-cache madison debmatic`

**Comment by Goersch** [comment]
Hallo Alex,

hier die Ausgaben:

apt update
`OK:1 http://de.archive.ubuntu.com/ubuntu focal InRelease
OK:2 http://de.archive.ubuntu.com/ubuntu focal-updates InRelease
Holen:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Es wurden 114 kB in 1 s geholt (144 kB/s).
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
`
apt upgrade
`Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  geoip-database gnome-software-common libappstream-glib8 libboost-iostreams1.67.0 libbrlapi0.6 libegl1-mesa libexiv2-14 libffi6 libgutenprint-common libisc-export1100 libisc1100
  liblwres161 libpanel-applet3 libpoppler90 libxml-namespacesupport-perl libxml-sax-base-perl libxml-sax-perl perl-modules-5.28 python3-asn1crypto
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
`
apt-cache madison debmatic -> keine Ausgabe

**Comment by Goersch** [comment]
würde mir "wget -q -O - https://www.debmatic.de/debmatic/public.key | sudo apt-key add" helfen?

**Comment by alexreinert** [comment]
Die Ausgabe von apt update spricht dafür, dass die Datei `/etc/apt/sources.list.d/debmatic.list` nicht vorhanden ist bzw. fehlerhaft ist.
Der Inhalt, den du weiter oben gepostet hast, sieht gut aus, allerdings hast du da nicht genau angegeben, wie die Datei heißt, kannst du da mal nachschauen?
Das mit apt-key wird erstmal nichts bringen, da wäre die Fehlermeldung bei `apt update` eine andere.

**Comment by Goersch** [comment]
debmatic.list:
`# deb https://www.debmatic.de/debmatic stable main # Bei Aktualisierung zu focal
 deaktiviert`

Ich denke, ich muss die Zeile einfach wieder dazunehmen, und dann ist gut?

**Comment by alexreinert** [comment]
Genau. Aber oben sah die Zeile noch anders aus...

Focal ist die Versionsbezeichnung von Ubuntu 20.04. Bei einem Releasewechsel von Ubuntu mit do-release-upgrade werden alle externen APT Repositories deaktiviert. Darauf wird aber auch während des Releasewechsels hingewiesen. Und genau das ist hier passiert.

**Comment by Goersch** [comment]
klappt jetzt :) 

Warum die Zeile anders aussah, ist mir auch nicht klar. Hab die Datei heute das erste Mal editiert. Das upgrade auf 20.04 habe ich letztes Jahr irgendwann gemacht.

Danke :)

**Comment by alexreinert** [comment]
Wie geschrieben, das passiert beim Ubuntu Releasewechsel durch do-release-upgrade.
Wenn man Supportanfragen macht, sollte man versuchen den Supporter nicht mit falschen oder nicht mehr aktuellen Infos auf eine falsche Fährte zu führen, beim nächsten Mal also bitte einfach vorher verifizieren, ob die Aussage noch zutrifft. ;-)

**Comment by Goersch** [comment]
ja, sorry, ich kann es im Moment auch nicht erklären 🥺Ich kann mich daran erinnern, dass da 2 Zeilen drin standen - einmal auskommentiert , einmal ohne „#“
