### ISSUE TITLE
HM-MOD-RPI-PCB wird nicht erkannt

### ISSUE THREAD

**Issue by schup011** [alexreinert/debmatic#247]
Hallo,

ich habe nach der Anleitung debmatic auf einem Pi Zero W installiert und bekomme das HM-MOD-RPI-PCB nicht zum Laufen.

Die Ausgabe von sudo debmatic-info ist:
```
debmatic version: 3.59.6-73
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
```

sudo sudo ls -la /dev/raw* liefert:
```
crw------- 1 root root 240, 0 Aug 24 19:47 /dev/raw-uart

/dev/raw:
total 0
drwxr-xr-x  2 root root     60 Jan  1  1970 .
drwxr-xr-x 15 root root   3340 Aug 24 19:47 ..
crw-rw----  1 root disk 162, 0 Aug 24 19:47 rawctl

```
Außerdem:

```
sudo strings /proc/device-tree/soc/serial@7e201000/compatible
pivccu,pl011

sudo strings /proc/device-tree/aliases/uart0
/soc/serial@7e201000

sudo strings /proc/device-tree/aliases/serial0
/soc/serial@7e201000

```

Ende von /boot/config.txt:
```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=16

dtoverlay=pi3-disable-bt
```

Und jetzt kommts:
```
sudo detect_radio_module --debug /dev/raw-uart
Illegal instruction
```

Die Installation lief nach Anleitung sauber durch. Habe allerdings gleichzeitig openhabian auf dem Raspi OS Lite mit installiert.
Woran könnte das Problem liegen? Wäre für Hilfe sehr dankbar.

**Comment by alexreinert** [comment]
Der Raspberry  Pi Zero W basiert auf der ARMv6 Architektur, diese wird von einigen Binaries nicht unterstützt, es braucht mind. ARM7 Raspberry Pi 2B aufwärts.
Vergleichbar kleine Hardware wäre der Orange Pi Zero, der hat ARMv7 und liegt preislich ähnlich.

**Comment by schup011** [comment]
Herzlichen Dank für die schnelle Info!
Gibt es gar keine Chance? Immerhin lief die Installation bisher problemlos...

**Comment by alexreinert** [comment]
Ich dachte es geht um eine frische Installation?

Eine Möglichkeit für "meine" Binaries gäbe es schon, dafür müsste ich aber die komplette Buildchain austauschen und dann wäre allerdings noch nicht sichergestellt, dass externe Binaries auch dauerhaft laufen. Und Aufwand und Nutzen stehen dafür absolut in keinem Verhältnis.

**Comment by schup011** [comment]
Das verstehe ich absolut. Ich wollte einen Test mit möglichst viel bestehender Hardware, bevor ich in die endgültige Hardware, wo noch 2-3 andere Sachen darauf laufen sollen, investiere. Aber das muss ich halt jetzt. 
Vielen Dank für die tolle schnelle Unterstützung.
