### ISSUE TITLE
HMIP USB wird nicht erkannt

### ISSUE THREAD

**Issue by tidde88** [alexreinert/debmatic#25]
Hallo,

ich habe nun öfters das Problem gehabt, das mein HMIP-USB Stick von ELV nicht erkannt wird, nach einem Update. Nur eine Neuinstallation hilft hier. Ich traue mich schon gar nicht meine VM neuzustarten.

Die Aussage von /var/hm_mode sagt folgendes:

HM_HOST='DEBMATIC'
HM_HOST_RAW_UART=''
HM_HOST_GPIO_UART=''
HM_HOST_GPIO_RESET=''
HM_LED_GREEN=''
HM_LED_RED=''
HM_LED_YELLOW=''
HM_RTC=''
HM_MODE='NORMAL'
HM_HMRF_DEVNODE=''
HM_HMIP_DEVNODE='/dev/ttyUSB0'
HM_HMRF_DEV=''
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMIP_SGTIN='3014f711a000041709adfa00'
HM_HMIP_SERIAL='1709adfa00'
HM_HMIP_VERSION='2.8.6'
HM_HMIP_ADDRESS='0xB27C85'

Nach einem Neustart ist das gerne mal komplett leer.

Was mir noch aufgefallen ist, dass ich wenn ich ein Gerät im Posteingang anklicke, folgendes erscheint:

"Homematic Funk Anlernmodus konnte nicht aktiviert werden."

Aber das Gerät funktioniert einwandfrei.

Kann ich Dir noch mehr Informationen verschaffen ?

Umgebung ist folgende:

Proxmox
Debian 9,9 VM

**Comment by alexreinert** [comment]
Hast du CUxD installiert?

**Comment by tidde88** [comment]
Nein

**Comment by alexreinert** [comment]
Das mit dem Reboot konnte ich jetzt auf einer Debian VM nachvollziehen. Der ModemManager blockiert genau während der Hardware-Erkennung von debmatic den Stick.
Fix dafür kommt im Laufe des Abends.

Das mit dem Update konnte ich jetzt nicht nachvollziehen, kannst du da Details nennen, mit denen ich das nachvollziehen kann?

**Comment by tidde88** [comment]
Durch die Neuinstallation, bin ich ja nun auf der neusten Version.

Ich würde das solange hier "pausieren" bis ein Update auftaucht und ich es
dann nochmal testen kann.

Das mit dem Fix hört sich aber super an.

Ich danke dir vielmals

Mit freundlichen Grüßen

Tobias Tietgen

Alexander Reinert <notifications@github.com> schrieb am Fr., 17. Mai 2019,
18:13:

**Comment by alexreinert** [comment]
Alls du das Problem mit dem Update hattest: Von welcher Version bist du denn auf die aktuelle gegangen?
Und welchen Stick hast du genau: Den Bausatz von elv oder den fertigen von der Telekom?

**Comment by tidde88** [comment]
Ich habe den Bausatz von ELV.

Es war die 3.45.7.16

Mit freundlichen Grüßen

Tobias Tietgen

Alexander Reinert <notifications@github.com> schrieb am Fr., 17. Mai 2019,
18:29:

**Comment by alexreinert** [comment]
Neue Version ist online

**Comment by tidde88** [comment]
Ich werde es mal die Tage testen und gebe dir dann Feedback.

Danke nochmal für den schnellen Fix

Mit freundlichen Grüßen

Tobias Tietgen

Alexander Reinert <notifications@github.com> schrieb am Fr., 17. Mai 2019,
19:23:

**Comment by alexreinert** [comment]
Konntest du bereits testen?

**Comment by tidde88** [comment]
Also mit dem Neustart klappt es nun soweit. Der Stick wird reibungslos
eingebunden.

Mit freundlichen Grüßen

Alexander Reinert <notifications@github.com> schrieb am Mi., 22. Mai 2019,
16:27:
