### ISSUE TITLE
Wäre ein Docker Image mit HB-RF-ETH modul möglich

### ISSUE THREAD

**Issue by cyclemat** [alexreinert/debmatic#250]
bin immernoch auf der suche ob man irgendwie debmatic in Docker ans laufen zu bekommen wäre das mit dem HB-RF-ETH modul möglich oder wird dann auch das Kernel modul genutzt ?

**Comment by alexreinert** [comment]
Auch für die HB-RF-ETH braucht es die extra Kernel Module, das liegt an der Architektur, welche eQ-3 für die parallele Unterstützung von HM und HmIP mit nur einer Funkhardware genutzt hat.

**Comment by cyclemat** [comment]
dann denke ich jetzt mal unkonventionell nehmen wir an wir nutzen nutzen nur ein system also HM classic bzw HM IP könnte man das modul dann umgehen ? denn wenn man jezt das ganze so baut das nur eine familie produkt unterstützt wird isses mir z.b im grunde egal ob ich nur ein oder zwei container laufen lasse 2 Funkmodule wären ja garkein problem kost ja net die welt !
so jedem container ein interface zuweisen und fertig ist die kiste bzw könnte man sogar die mittel FT232 2 Comports realisieren und beides auf eine USB Platine stecken !  usw bzw selbst bei der ethernet Variante könnt man das auch so machen. ist halt nur ne kleine anpassung aber das ist jetzt allese nur so dahin gesagt kenne mich mit dem Kernelmodul zuwenig aus und habe mich damit auch noch nicht beschäftigt

**Comment by alexreinert** [comment]
Nur wenn eQ-3 entsprechende Firmwares für die Funkmodule bereitstellt, mit der verfügbaren Dual CoPro Firmware ist das nicht möglich.
