### ISSUE TITLE
Suche nach Access Point mit inkompatibler FW nach Update nicht möglich

### ISSUE THREAD

**Issue by peterfido** [alexreinert/debmatic#251]
Gestern die Debmatic aktualisiert, da ich ein HAP als zusätzlichen Access-Point einrichten wollte.

Bei der alten Version (3.53.34.55) funktionierte die Suche nach Access-Points mit inkompatibler FW noch. Seit dem Update auf 3.59.6.73 wird das Fenster nur ausgegraut, es fehlt jedoch die "Popup-Box", welche die Suche dann durchführt.

**Comment by alexreinert** [comment]
Welches Funkmodul wird verwendet bzw. was liefert debmatic-info?

**Comment by peterfido** [comment]
Ich nutze das "alte" kleine auf der USB-Platine.

**Comment by alexreinert** [comment]
Für die Einbindung von HAP braucht es zwingend das neue RPI-RF-MOD, weil nur für dieses eine neue entsprechende Firmware von eQ-3 bereitgestellt wurde.

**Comment by peterfido** [comment]
Ja, ok. Jedoch sollte das Fenster mit der Suche nach den Access-Points trotzdem erscheinen.?

**Comment by alexreinert** [comment]
Nö, korrekt wäre es den Punkt komplett aus dem Menü zu entfernen, allerdings kam ich noch nicht dazu. Diese Funktion wird im Closed Source von eQ-3 einfach nicht mehr unterstützt ohne RPI-RF-MOD.

**Comment by peterfido** [comment]
Ah-OK. Danke. 

OT: Der Kantenschutz ist von mir :)

**Comment by alexreinert** [comment]
OT: Danke!

**Comment by peterfido** [comment]
Läuft die RPI-RF-MOD mit "meiner" USB-Platine (HB-RF-USB), oder benötige ich die neuere Version HB-RF-USB-2?

**Comment by alexreinert** [comment]
Die läuft auf der HB-RF-USB allerdings auf der anderen Seite. Ggf. musst du also einen weiteren Pinheader (2x20 Pins) auflöten.

**Comment by peterfido** [comment]
Vielen Dank!

**Comment by peterfido** [comment]
Mit dem neuen Funkmodul RPI-RF-MOD funktioniert die Suche (wieder). Hatte allerdings nichts gefunden, weil:

Das HAP lässt sich mit dem neuen Funkmodul anlernen. Die Firmware scheint es beim zweimaligen Rücksetzen auf Werkseinstellungen selbst aktualisiert zu haben.

Issue kann somit geschlossen werden.
