### ISSUE TITLE
HB-RF-ETH funktioniert nicht mit aktuellem Debian 11

### ISSUE THREAD

**Issue by meier81** [alexreinert/debmatic#252]
Hallo Alex,

habe mich gestern bzw. heute mal drangemacht  und mir eine neue VM mit Debian 11 aufgesetzt. Die bisherige läuft auf Debian 10 problemlos. Habe dann dort soweit alles wieder installiert (debmatic, fhem, influxdb, etc.). Soweit funktioniert auch alles, auch keine Probleme bei der Installation. Lediglich will irgendwas mit der HB-RF-ETH nicht funktionieren, die Weboberfläche zeigt zwar an das sich meine VM mit ihr verbunden hat, in debmatic bekomme ich aber bei Geräten nur das "HM-RCV-50 BidCoS-RF" angezeigt, das Gerät "HmIP-RCV-50 HmIP-RCV-1" fehlt leider. Es kommt auch nach kurzer Zeit eine Fehlermeldung in debmatic das das Gerät nicht erreichbar bzw. vorhanden ist. Ein Neustart bzw. ein reinstall brachte leider auch keinen Erfolg.

Falls du weitere Infos benötigst melde dich.

Gruß Markus

**Comment by alexreinert** [comment]
Siehe https://github.com/alexreinert/debmatic/issues/249#issuecomment-922531691

**Comment by meier81** [comment]
Hallo Alex,

vielen Dank für den Hinweis. Habe da eben auch etwas Zeit mit verbracht, hat leider nicht ganz so einfach funktioniert da ein "java -version" immer die V17 zurückgegeben hat. Nach etwas Recherche habe ich dann hiermit die aktive Java-Version umschalten können:

`sudo update-alternatives --config java`
![switch-java-version-on-debian11](https://user-images.githubusercontent.com/40598096/135419211-b5d756b3-3398-4382-a3e0-8613b4d93b0a.png)

Dann mit der "1" die Version 11 auswählen, Neustart uns alles Super!

Vielleicht hilft das dem ein oder anderen.

Gruß Markus
