### ISSUE TITLE
Cannot install the kernel headers properly

### ISSUE THREAD

**Issue by schup011** [alexreinert/debmatic#253]
Hi,

I am setting up debmatic on a Raspi 4 on top of a openhabian (based on Buster) installation.

When I am installing the kernel headers, it says:
```
Error! echo
Your kernel headers for kernel 5.10.60-v8+ cannot be found at
/lib/modules/5.10.60-v8+/build or /lib/modules/5.10.60-v8+/source.
```
No other error messages, but at the end:
```
debmatic version: 3.59.6-73
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
```

The HM-MOD-RPI-PCB is installed, but not detected.
Do you have any idea?

**Comment by schup011** [comment]
I did everything like described in the installation instructions.

**Comment by alexreinert** [comment]
The Raspbian header package do not provide 64 Bit Kernel Headers, they just include the 32 Bit Kernel Headers. You have to switch to 32 Bit Kernel.

**Comment by schup011** [comment]
Hm.... the openhabian image was said to be 32bit. How can I check?

**Comment by schup011** [comment]
The image was openhabian-pi-raspios32-v1.6.5.img.xz.

**Comment by schup011** [comment]
What I can do is set up a normal Buster or RaspiOS (which one) and then install openhabian on top (not as a preconfigured image).

**Comment by schup011** [comment]
Seems to be 32bit:
```

openhabian@homeCtrl:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

openhabian@homeCtrl:~ $ uname -m
armv7l
```

**Comment by alexreinert** [comment]
The suffix v8+ is only be used on 64 bit kernels. The 64 bit kernel is available on the 32 Bit images, too. Just the "normal" binaries are 32 Bit in this images. Take a look at the /boot/config.txt at the parameter arm_64bit parameter.

**Comment by schup011** [comment]
There is not such a parameter.
See my edited previous post, it is running on armv71.

**Comment by schup011** [comment]
For some reasons, under /lib/modules there is the -v8, but also the -v7+:

```
openhabian@homeCtrl:/lib/modules $ ls
5.10.60+  5.10.60-v7+  5.10.60-v7l+  5.10.60-v8+
```

**Comment by schup011** [comment]
Here is the complete content of /boot/config.txt:
```

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=16
#enable_uart=1

dtoverlay=pi3-disable-bt
dtoverlay=disable-bt

dtoverlay=pivccu-raspberrypi

```

**Comment by schup011** [comment]
I am doing a fresh install. During the kernel headers install, I get something similar:

```
Error! echo
Your kernel headers for kernel 5.10.17-v7l+ cannot be found at
/lib/modules/5.10.17-v7l+/build or /lib/modules/5.10.17-v7l+/source.

```
Can this be ignored?

**Comment by schup011** [comment]
Obviously, it can be ignored. I did the install, and strangely, debmatic-info first did not tell that it hat found a radio module, but after the first start it worked. I successfully added one HM device. Now I will put the openhabian on top of it, and hopefully that works.

**Comment by schup011** [comment]
Unfortunately, with the openhabian installed later, openhabian does not work because it is not able to get the openJDK 11 running.
So I am back to the first problem. With using the openhabian distro (preconfigured system based on Raspi-OS), it results in this (all steps made exactly identical):

```
debmatic version: 3.59.6-73
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown
```

Can you provide some hints what could be going wrong? What could I check? The error during kernel headers installation can't be it, because it occurred also during the installation on the clean Raspi OS which was successful.

**Comment by alexreinert** [comment]
It is the error this the kernel headers. The kernel headers cannot be built without the kernel headers and without kernel modules no communication can be established.
When you used Raspberry Pi OS I assume, that you updated kernel and headers, so there was a mismatch between running kernel and (new) kernel headers. After a reboot, they matched and the kernel modules are built automatically.

So: Please reboot your system and run `sudo dpkg-reconfigure pivccu-modules-dkms` and provide the full output here.

**Comment by schup011** [comment]
I got it working by updating kernel and bootloader and reinstalling debmatic.

**Comment by schup011** [comment]
Seems to be critical which kernel version is used. What I did (not sure whether everything was needed) is:

```
sudo apt install raspberrypi-kernel raspberrypi-kernel-headers raspberrypi-bootloader
sudo apt remove raspberrypi-kernel-headers raspberrypi-bootloader 
sudo apt install raspberrypi-kernel-headers raspberrypi-bootloader pivccu-modules-raspberrypi
sudo apt remove debmatic
sudo reboot 
sudo apt install debmatic

```
