### ISSUE TITLE
nach Update kein Anlernen mehr möglich

### ISSUE THREAD

**Issue by WiredLife** [alexreinert/debmatic#254]
Hallo,
seit dem Update auf die aktuelle 3.59.6.73 Firmware, kann ich keine Homematic (BidCos-RF) Geräte mehr anlernen (Homematic IP nicht getestet).
Wenn das Pairing bei debmatic nicht aktiviert ist, blinken die Geräte im Anlernmodus gelb und dann rot, bei aktiviertem Pairing gelb und dann grün, was für ein erfolgreiches Pairing sprechen würde.
Allerdings taucht im Posteingang nichts auf.

Jemand eine Idee was ich machen könnte?

Habe das HM-MOD-RPI-PCB schon vom HB-RF-USB-TK abgezogen und direkt auf den Pi 4 gesteckt.
Die angelernten Aktoren usw. funktionieren nach wie vor.

**Comment by alexreinert** [comment]
Sind die Geräte möglicherweise schonmal angelernt gewesen?

**Comment by meier81** [comment]
Hallo,

habe eventuell das gleiche Problem, zumindest sieht es danach aus.
Ich wollte heute meine neuen HB-Sec-RHS-3 Sensoren in Betrieb nehmen. Sketch habe ich draufgespielt, Seriallog sieht auch gut aus. Nun gehe ich auf HM Gerät anlernen, die Zeit fängt an zu laufen. Jetzt drücke ich am Gerät den Config-Taster, es gehen beide LED´s an, die rote blinkt einmal während die grüne weiterhin leuchtet, dann gehen beide wieder aus. Im Seriallog bekomme ich dann auch 4 Einträge, denke die sind bezüglich des Anlernens. Hatte vorher nämlich ein Frequenzproblem, da haben die LED´s nämlich weitergeblinkt und im Log war nur eine Zeile, wahrscheinlich nur die Anfrage von Gerät.

Habe aber anschließend auch kein Gerät im Posteingang. Mehrfach probiert, leider kein Erfolg.

**Comment by WiredLife** [comment]
> Sind die Geräte möglicherweise schonmal angelernt gewesen?

Ja in Homegear, habe sie dort aber per pup unpaired, gewartet bis sie raus waren und dann noch die Geräte einzeln per langen Druck auf den Anlerntaster auf Werk zurückgesetzt. Kurz vor dem Update hab ich ein identisches Gerät genau so in debmatic einbinden können.

**Comment by meier81** [comment]
Also ich habe eben nochmal den Log der CCU umgestellt und einen Anlernversuch gestartet, einziger Eintrag hier lautet:

`Oct  1 21:18:03 debian rfd: Peering with RHS300A101 failed`

Also sollte ja mein Sender korrekt funktionieren, hab aber keine Idee mehr wo es jetzt noch liegen könnte. Hab auch schon debmatic gedowngraded, auch keine Besserung.

**Comment by WiredLife** [comment]
Ich hab mal ein Log angefertigt (die letzten 4 Ziffern der Seriennummern geXt)
`Oct  3 21:07:24 openHABianPi rfd: Entering install mode for 60 s
Oct  3 21:07:30 openHABianPi rfd: NEQ068XXXX's type is HM-RC-Key4-2
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:30 openHABianPi rfd: (REQ091XXXX) Response status: OK.
Oct  3 21:07:30 openHABianPi rfd: Device firmware version is 1.2
Oct  3 21:07:30 openHABianPi rfd: TX:  @1200478505 0xF8780D -> 0x4B8264 CONFIG_START [REQ091XXXX]:#012  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01#012  CONFIG_CHANNEL = 0#012  CONFIG_PEER_ADDRESS = 0x000000#012  CONFIG_PEER_CHANNEL = 0#012  CONFIG_PARAM_LIST = 0
Oct  3 21:07:32 openHABianPi rfd: (REQ091XXXX) Response status: Authentication failed..
Oct  3 21:07:32 openHABianPi rfd: (REQ091XXXX) Response status: Send failed.
Oct  3 21:07:32 openHABianPi rfd: SendFrame failed 1 times:  @1200478505 0xF8780D -> 0x4B8264 CONFIG_START [REQ091XXXX]:#012  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01#012  CONFIG_CHANNEL = 0#012  CONFIG_PEER_ADDRESS = 0x000000#012  CONFIG_PEER_CHANNEL = 0#012  CONFIG_PARAM_LIST = 0
Oct  3 21:07:32 openHABianPi rfd: Peering with NEQ068XXXX failed
Oct  3 21:07:32 openHABianPi rfd: (REQ091XXXX) Response status: OK, Data.
Oct  3 21:07:32 openHABianPi rfd: Deleting persistent data for device NEQ068XXXX
Oct  3 21:07:32 openHABianPi rfd: Could not determine 's type`
