### ISSUE TITLE
Anlernen von AskSinPP-Geräten funktioniert nicht

### ISSUE THREAD

**Issue by meier81** [alexreinert/debmatic#255]
Hab jetzt hier mal einen eigenen Issue aufgemacht, denke das war in dem anderen nicht wirklich gut. Hier nochmal zum Problem:

Ich wollte meine neuen HB-Sec-RHS-3 Sensoren in Betrieb nehmen. Sketch habe ich draufgespielt, Seriallog sieht auch gut aus (denke ich). Nun gehe ich auf HM Gerät anlernen, die Zeit fängt an zu laufen. Jetzt drücke ich am Gerät den Config-Taster, es gehen beide LED´s an, die rote blinkt einmal während die grüne weiterhin leuchtet, dann gehen beide wieder aus. Im Seriallog bekomme ich dann auch 4 Einträge, denke die sind bezüglich des Anlernens. Hatte vorher nämlich ein Frequenzproblem, da haben die LED´s nämlich weitergeblinkt und im Log war nur eine Zeile, wahrscheinlich nur die Anfrage von Gerät. Hier der Serial-Log:

`AskSin OTA Bootloader V0.7.0

Start App
AskSin++ v5.0.0 (Oct  1 2021 17:46:58)
Address Space: 32 - 103
CC init1
CC Version: 04
 - ready
Config Freq: 0x2165EA
Pins: 110
Activate Cycle Msg
<- 0F 01 86 10 00A101 000000 06 01 C8 00 00 2D  - 2861
 debounce
 pressed
 released
<- 1A 02 84 00 00A101 000000 10 F2 09 52 48 53 33 30 30 41 31 30 31 80 01 01 00  - 15106

-> 10 01 A0 01 73AFEC 00A101 00 05 00 00 00 00 00  - 15290
<- 0A 01 80 02 00A101 73AFEC 00  - 15564
-> 10 01 A0 01 73AFEC 00A101 00 05 00 00 00 00 00  - 15839
<- 0A 01 80 02 00A101 73AFEC 00  - 16115`

Habe aber anschließend auch kein Gerät im Posteingang. Mehrfach probiert, leider kein Erfolg.

Zudem hatte ich den Log der CCU umgestellt und einen Anlernversuch gestartet, einziger Eintrag hier lautet:

`Oct 1 21:18:03 debian rfd: Peering with RHS300A101 failed`

Also sollte ja mein Sender korrekt funktionieren (denke ich), hab aber keine Idee mehr wo es jetzt noch liegen könnte. Hab auch zum testen schon debmatic gedowngraded, brachte aber auch keine Besserung.

**Comment by alexreinert** [comment]
Ist die Seriennummer (00A101) doppelt vergeben?

**Comment by meier81** [comment]
Hallo Alex,

nein, darauf habe ich geachtet. Ich habe bislang nur originale Homematic Geräte verbaut, davon alles IP-Devices bis auf eines, das ist noch ein BidCoS-Gerät.

Habe wie gesagt mehrfach probiert das Gerät anzulernen, vom Gerät her würde ich sagen sieht alles gut aus, auch was die LES´s und den Log angeht. Nur scheint ihn die CCU abzulehnen.
Ich kann aber nochmal einen flashen mit einer ganz anderen Seriennummer und nochmal probieren.

**Comment by meier81** [comment]
So,

eben nochmals probiert, habe mir mit random die Serial und die ID erzeugen für den OTA Bootloader erzeugen lassen, auf den Sensor hochgeladen, dieser startet mit folgenden Log:

`AskSin OTA Bootloader V0.7.0

Start App
AskSin++ v5.0.0 (Oct  1 2021 17:52:21)
Address Space: 32 - 103
CC init1
CC Version: 04
 - ready
Config Freq: 0x2165EA
Pins: 110
Activate Cycle Msg
<- 0F 01 86 10 3D8E2C 000000 06 01 C8 00 00 2F  - 1689`

Dann CCU in Anlernmodus versetzt und den Config-Taster auf dem Device gedrückt, folgendes kommt im Log:

` debounce
 pressed
 released
<- 1A 02 84 00 3D8E2C 000000 10 F2 09 55 48 55 38 32 37 30 33 33 39 80 01 01 00  - 15095

-> 10 01 A0 01 73AFEC 3D8E2C 00 05 00 00 00 00 00  - 15278
<- 0A 01 80 02 3D8E2C 73AFEC 00  - 15554
-> 10 01 A0 01 73AFEC 3D8E2C 00 05 00 00 00 00 00  - 15824
<- 0A 01 80 02 3D8E2C 73AFEC 00  - 16095`

In der CCU läuft die Zeit runter, kein neues Device im Posteingang. Das message-Log ergibt wieder nur eine Zeile:

`Oct  2 17:41:04 debian rfd: Peering with UHU8270339 failed`

Als Device Modell habe ich `F209` eingetragen, das sollte ja aber soweit passen.

Debmatic läuft bei mir auf meinem QNAP-NAS in einer Debian 11 VM in Version 3.59.6.73, als Funkmodul habe ich ein HM-MOD-RPI-PCB in Kombination mit der HB-RF-ETH Platine.

Gibt es die Möglichkeit hier noch mehr zu loggen um den Fehler einzugrenzen?

Gruß Markus

**Comment by meier81** [comment]
Hat sich erledigt, das Problem hat sich gefunden, liegt irgendwo in der AskSinPP-Bibliothek.

Werden wir noch eingrenzen und beheben, auf jeden Fall kein Punkt in debmatic.

Gruß Markus
