### ISSUE TITLE
Keine Verbindung mit Node-Red

### ISSUE THREAD

**Issue by Der-Schubi** [alexreinert/debmatic#257]
Hallo!

Ich bin gerade von RaspberryMatic auf debmatic umgestiegen.
Meine debmatic Istallation läuft auf Debian Buster als virtuelle Maschine (qemu) unter proxmox.
So weit scheint alles zu funktionieren. Gerätekommunikation ist ok.
Nun komme ich leider mit Node-Red nicht auf die CCU. Erst hatte ich Node-Red auf einem lxc Container laufen, da aber keine Verbindung zustande kam, habe ich Node-Red jetzt direkt in der VM von debmatic mit drin. Ergebnis ist das gleiche.
Mit den Einstellungen für die ccu-connection bin ich mir unsicher, was sind die richtigen Ports für BINRPC und XMLRPC? 2000/2001? 2047/2048 habe ich aber auch schon probiert.

Ein paar Infos:
Node-Red Version: v2.1.3
Node.js Version: v12.22.5
node-red-contrib-ccu version: 3.4.2

debmatic-info:
debmatic version: 3.59.6-78
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: HB-RF-USB-2@usb-0000:00:1d.0-1 (/dev/raw-uart)
 Board serial:  OEQ0308361
 Radio MAC:     0x583C68
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D7098E1C89
 Radio MAC:     0xBE0904

systemctl list-dependencies debmatic:
Alles läuft, bis auf debmatic-hs485d.service, debmatic-monitor-hb-rf-eth.service und pivccu-dkms.service

Einstellungen für den ccu-connection node:
CCU address: 10.0.0.5
Listen address: 10.0.0.6 (bzw. .5 bei lokalem Node-Red)
Init address: 10.0.0.6 (dito ^^)
BINRPC listening port: 2000
XMLRPC listening port: 2001
Angehakt sind ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices und CUxD
Authentifictation ist an und Username und Passwort korrekt gesetzt.

Startup von Node-Red:
[info] [ccu-connection:3014F711A061A7D7098E1C89] paramsets loaded from /home/schubi/.node-red/paramsets.json
[warn] [ccu-connection:3014F711A061A7D7098E1C89] metadata new empty
[info] [ccu-connection:3014F711A061A7D7098E1C89] regadata loaded from /home/schubi/.node-red/ccu_rega_10.0.0.5 3014F711A061A7D7098E1C89.json
[info] [ccu-connection:3014F711A061A7D7098E1C89] values loaded from /home/schubi/.node-red/ccu_values_10.0.0.5 3014F711A061A7D7098E1C89.json
[error] [ccu-connection:38263145.35ea0e] Error: Invalid property expression: unexpected ' ' at position 12
[info] Started flows
[info] [mqtt-broker:ServDroid] Connected to broker: mqtt://10.0.0.3:1883

Woran kann es liegen?

Grüße,
Schubi

**Comment by alexreinert** [comment]
Die Scnittstellen sind schon ziemlich lange auf XmlRPC, nur CUxD läuft noch mit BinRPC. (analog zur Original CCU3).

**Comment by Der-Schubi** [comment]
Das dachte ich mir von dem, was ich gelesen habe schon.
Sieht der Rest so weit richtig aus? Was ist der richtige XMLRPC-Port?

**Comment by alexreinert** [comment]
Ich kenne Node Red nicht im Detail, daher ist das schwer zu sagen. Ports sind 2000, 2001, 2010 (analog zur CCU3)

**Comment by Der-Schubi** [comment]
OK, danke Dir schon mal, dann frag ich mal Hobbyquaker.

**Comment by Der-Schubi** [comment]
Eine Frage noch: Ist es normal, dass ich keinen Button mehr für die Firewall-Einstellungen habe?

**Comment by Der-Schubi** [comment]
Ich habe den Fehler, ohne ihn wirklich gefunden zu haben, beseitigen können. Ich habe die debmatic noch einmal resettet und die Daten aus der Raspberrymatic neu importiert. Danach funktionierte es auf Anhieb.
Danke für die Hilfe und entschuldigung, dass ich hier die Hühner scheu gemacht habe.

Grüße,
Schubi
