### ISSUE TITLE
The repository 'https://www.debmatic.de/debmatic stable Release' does not have a Release File.

### ISSUE THREAD

**Issue by searbea** [alexreinert/debmatic#258]
Guten Tag,

Leider kommt bei mir nach dem  Update der repository dieser Error.

**The repository 'https://www.debmatic.de/debmatic stable Release' does not have a Release File.**

Hab es schon mehrmals versucht, nur immer wieder mit dem gleichen Ergebnis.

Habe persönlich Debmatic schon länger in einem Proxmox container am laufen. Damals lief die Installation wie beschrieben problemlos durch.

Viele Dank für diese super Arbeit

Beste Grüße

Uwe

**Comment by alexreinert** [comment]
Dir fehlt das aktuelle Root Zertifikat von Let's Encrypt.

Welches OS ist installiert, je nachdem ist der Weg unterschiedlich.

**Comment by searbea** [comment]
Guten Abend,

Vielen dank für die rasche Antwort.
Tatsächlich habe ich aus reiner Bequemlichkeit ein vorhandenes Template auf dem Proxmox-Server genommen

**Ubuntu 18.04**

habe es soeben mit einem **Ubuntu 20.04** probiert und ist problemlos durchgelaufen.

Vielen Dank nochmal 

Beste Grüße 

Uwe
