### ISSUE TITLE
Ersetzen des internen Tcl 8.2 durch debian Paket tcl möglich?

### ISSUE THREAD

**Issue by ecky-l** [alexreinert/debmatic#26]
Hallo,

Debmatic bringt sein eigenes Tcl in der Uralt-Version 8.2 mit (die ist von Ende der 90er!). Da Tcl, soweit ich verstanden habe, in der CCU v.a. für die CGI Scripte nötig ist, sollte es möglich sein, statt des eingebauten Interpreters /bin/tclsh das Debian Paket (tcl, derzeit Version 8.6) zu verwenden. Die Sprache ist sehr abwärtskompatibel, ich _könnte_ mir daher vorstellen, dass keine Anpassungen am CCU Code nötig sind (beschwören würde ich es allerdings nicht und wenn, dann wäre das wahrscheinlich ein Killerargument). Die Abhängigkeiten aus der tcllib in /lib/tcl8.2/ könnten dann auch raus, davon gibt es aktuellere Versionen im Paket tcllib.

Vorteil wäre: debmatic wird um den Tcl Interpreter kleiner und es gäbe keine Konflikte mit einem anderweitig installierten Tcl auf der Kiste. Tcl und die tcllib selbst würden sich mit "apt upgrade" einfacher aktualisieren lassen, und die Maintenance des Interpreters innerhalb von debmatic entfällt. Und evtl. fällt das Entwickeln von Erweiterungen mit der neuen Tcl Version leichter...
Man müsste dann im debmatic Paket nur eine Abhängigkeit auf tcl und tcllib setzen.

**Comment by alexreinert** [comment]
Es ist kein eigenes tcl, sondern das tcl aus dem OCCU Projekt. Neben den Problemen, dass ich nicht abschätzen kann, ob es aufgrund des Versionsunterschieds zu Problemen kommt, ist es auf jeden Fall so, dass es sich um eine von eQ-3 erweiterte Version handelt und ya müsste erst geprüft werden, wie man die in das Standardpaket bekommt.
Insgesamt also eine größere Aktion, welche sicherlich sinnvoll ist, aber noch gibt es da wichtigere Baustellen.

**Comment by ecky-l** [comment]
Hm ja, [dieses Repository](https://github.com/eq-3/occu) hier, oder? Das Tcl ist Standard 8.2.3, zumindest unterscheidet sich das Archiv in CCU2/download/tcl-eQ-3.tar.gz nicht von den [Originalsourcen auf Sourceforge](https://sourceforge.net/projects/tcl/files/Tcl/8.2.3/) (bis auf die "RCS:" Zeilen, die haben es offenbar bei sich irgendwo eingecheckt). Also ist das Binary selbst schonmal wahrscheinlich nicht modifiziert.

Aber die relevante Logik ist offenbar in einer C Extension tclrega.so und dazu gibt es noch ein paar weitere Libs daneben, z.B. in arm-gnueabihf/packages/WebUI/lib - libelvutils.so und libeq2udss.so sehen so aus als ob sie OCCU spezifische Funktionalität enthalten. Die anderen sehen eher nach Standard-Extensions aus die man aus anderer Quelle bekommt. Und für tclrega.so gibt es leider keine Sourcen :/. Damit kann man auch nicht rausfinden, ob sie z.B. gegen die tclstubs Library gelinkt sind oder direkt gegen libtcl.so. Wenn sie gegen die tclstubs gelinkt sind, stehen die Chancen sehr gut, dass sie mit einem neueren Tcl einfach so funktionieren. Anderenfalls stehen die Chancen eher schlecht. Es sei denn man hätte die Sourcen und könnte sie anpassen und neu linken... schade dass die nicht dabei sind.

Naja. Ich kann mir auch vorstellen, dass es wichtigere Baustellen gibt.
