### ISSUE TITLE
OpenHAB2 Homematic binding vs. debmatic

### ISSUE THREAD

**Issue by djnzde** [alexreinert/debmatic#261]
Hallo,
ich habe OpenHAB2 und debmatic zusammen auf einem System laufen. Wollte nun das Homematic Binding in OH2 aktivieren, es findet auch allein das HM-Gateway, aber es geht nicht weiter.
Im events.log von OH2 steht
2021-11-20 16:45:38.662 [hingStatusInfoChangedEvent] - 'homematic:bridge:DEB9929463' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): org.xml.sax.SAXException: Unknown XML-RPC tag: title
Laut bisheriger Recherche könnte das ein CCU-Firewall-Problem sein, aber wie könnte ich das in debmatic kontrollieren/konfigurieren?
Danke für einen kurzen Hinweis, VG djnzde

**Comment by alexreinert** [comment]
Welche Funkhardware wird verwendet und was liefert debmatic-info?

**Comment by djnzde** [comment]
Debmatic benutzt nur einen CUL über cuxd. Es sol erst mal nur einige FHT80-Thermostate ans OH2 durchreichen. Die FHT-Geräte sind im debmatic schon eingerichtet und funktionieren soweit.
debmatic-info
debmatic version: 3.59.6-78
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
 Board serial:  unknown
 Radio MAC:     unknown
HMIP Hardware:  unknown
 SGTIN:         unknown
 Radio MAC:     unknown

cuxd
USB 1-3 - {CUX} NANO CUL [FF] - /dev/ttyUSB0 {:50s} - V 1.67 nanoCUL868 - Fri Nov 19 22:10:28 2021
  USB 1-5 - (0aa7) [WIRELESS] - Fri Nov 19 22:10:28 2021

  Erfolgreich mit HomeMatic-CCU 127.0.0.1:8183 verbunden!

  als RPC-Server(INIT) von HomeMatic-CCU (1032) angefordert!

VG djnzde

**Comment by alexreinert** [comment]
In dem Fall wird dann au ch keine XmlRPC Schnittstelle für HM oder HmIP gestartet und das entsprdchend in OpenHAB konfiguriert werden.

**Comment by djnzde** [comment]
OpenHAB hat beim Installieren automatisch die CCU von debmatic gefunden:
  "homematic:bridge:DEB9929463": {
    "class": "org.eclipse.smarthome.core.thing.internal.BridgeImpl",
    "value": {
      "label": "eQ3-HmIP-CCU3-App - 192.168.168.33",
      "channels": [
        {
          "acceptedItemType": "Number",
          "kind": "STATE",
          "uid": {
            "segments": [
              "homematic",
              "bridge",
              "DEB9929463",
              "DUTY_CYCLE_RATIO"
            ]
          },
          "channelTypeUID": {
            "segments": [
              "homematic",
              "DUTY_CYCLE_RATIO"
            ]
          },
          "label": "Duty Cycle",
          "description": "Current duty cycle usage",
          "configuration": {
            "properties": {}
          },
          "properties": {},
          "defaultTags": []
        }
      ],
      "configuration": {
        "properties": {
          "cuxdPort": 8701,
          "socketMaxAlive": 900,
          "installModeDuration": 60,
          "timeout": 15,
          "hmIpPort": 2010,
          "factoryResetOnDeletion": false,
          "discoveryTimeToLive": -1,
          "wiredPort": 2000,
          "gatewayType": "auto",
          "groupPort": 9292,
          "gatewayAddress": "192.168.168.33",
          "unpairOnDeletion": false,
          "rfPort": 2001
        }
      },
      "properties": {},
      "uid": {
        "segments": [
          "homematic",
          "bridge",
          "DEB9929463"
        ]
      },
      "thingTypeUID": {
        "segments": [
          "homematic",
          "bridge"
        ]
      }
    }
  },

Kann ich durch manuelle Config  die CCU als Bridge einbinden oder wird sie die Geräte überhaupt nicht für OpenHAB bereitstellen?

**Comment by alexreinert** [comment]
Solche Detailfragen zu OpenHAB kann ich leider nicht beantworten.

**Comment by djnzde** [comment]
Der lighttpd liefert 503 beim Versuch, auf die Ports 2000, 2001 zuzugreifen. Die ANtwort des Webservers sieht in diesem Fall so aus
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>503 Service Not Available</title>
 </head>
 <body>
  <h1>503 Service Not Available</h1>
 </body>
</html>
und OpenHAB versucht das zu parsen, meckert dabei als erstes das <title> Tag an, weil es da nicht erwartet wird.
Dann liegt der Fehler wohl daran, dass für die einzelnen Dienste (HM, HMIP) keine Server/Schnittstellen auf der CCU gestartet sind? Müsste ich zwingend ein Funkmodul dran haben, nur damit die CCU die entsprechenden Schnittstellen startet? Was wäre, wenn ich nur Wired-Komponenten hätte?
Danke aber schon mal für die bisherigen Infos.

**Comment by alexreinert** [comment]
Es werden nur die RPC Dienste gestartet, für welche auch die entsprechende Hardware vorhanden ist.

**Comment by djnzde** [comment]
Mein debmatic läuft zuammen mit openHAB auf einer Beebox. Ein HM-USB-Funkstick (HmIP-RFUSB oder HM-CFG-USB2) an dem Gerät würde also dazu führen, dass der entsprechende RPC-Server gestartet wird? Im Moment hängt ein nanoCUL an einer der USB-Schnittstellen, der den Zugriff auf die FHT-Komponenten abwickelt.
Danke & Gruß

**Comment by alexreinert** [comment]
Blöde Frage: Warum nimmst du nicht einfach das FHT Binding von OpenHab anstatt der Verrenkung über eine CCU mit CuXD, bei welcher die CCU an sich gar nicht als CCU genutzt wird?

Zu deiner Frage: Mit einem angeschlossenen HM-CFG-USB2 wird der BidCos RPC Server gestartet, mit einem HmIP-RFUSB wird aktuell der HmIP RPC Server gestartet (in Zukunft vermutlich BidCos und HmIP, da eQ-3 eine neue Firmware für den Stick rausgebracht hat, die möglicherweise beides gleichzeitig unterstützt), mit einem per HB-RF-USB-2 oder HM-RF-ETH angeschlossenem HM-MOD-RPI-PCB oder RPI-RF-MOD werden die BidCos und HmIP RPC Server gestartet.

**Comment by djnzde** [comment]
Das Problem ist, dass das FHT-Binding seit openHAB2 nicht mehr ordentlich läuft. Mit openHAB v1 war die Welt noch schön und das CUL- und das FHT-Binding haben super funktioniert.
Die beiden Bindings sind aber nicht nach openHAB2 migriert worden, man kann sie zwar als v1-Bindings auch in OH2 aktivieren, aber sie laufen bei mir zumindest nicht richtig. Ich habe mir schon die letzten Quellen geholt und eigene Debug-Infos eingefügt usw., aber es wird einfach nicht. 
Daher tatsächlich der Umweg über HM-CCU, obwohl es unwahrscheinlich ist, dass wirklich HM-Komponenten in dieses System kommen (ich habe einiges an KNX, etliche Geräte über MQTT und eben die alten FHT80).
Die direkte EInbindung über das CUL und FHT-Binding in OH2 wären mir am liebsten, an OH3 wagre ich noch gar nicht zu denken.

**Comment by djnzde** [comment]
FYI: nachdem ich den HMIP-RFUSB angeschlossen hatte, ging der Status der HM-Bridge im openHAB auf "online" und es wurden entsprechende Geräte (THings) erkannt. Trotzdem ist die Anzahl der steuerbaren Parameter eher überschaubar und so habe ich mir überlegt, HMIP-RFUSB und debmatic-CCU nicht bloß als Gateway für den alten FHT-Kram zu benutzen, sondern wirklich für etwas Homematic (IP)-Stoff. Habe WTH2 und 2 Thermostate Compact drangehängt, die relativ problemfrei (nur bei der Gruppenerstellung hats einmal gehakt) einzurichten waren. 
Es wird wohl daraus hinauslaufen, dass ich (wie viele vor mir) FHT80 rauswerfe und statt dessen HMIP einsetze. Ein Argument für die FHT waren die Ventilantriebe, andere passen bei mir aufgrund der baulichen Situation nicht rein, aber die HMIP-eTRV-C haben praktisch das gleiche Format wie FHT8 und so wird halt alles mal erneuert.
