### ISSUE TITLE
VM Proxmox 7.1-5 (Alles funktioniert, Blaues Blinken)

### ISSUE THREAD

**Issue by trevon88** [alexreinert/debmatic#262]
Hallo Alexander,
Ich habe von Raspberry auf das aktuelle Proxmox umgestellt, alles hat funktioniert und läuft mit dem Backup vom Raspberry einwandfrei! :-)

Jetzt habe ich ein blaues Blinken auf dem Modul. Irgendwo meine ich gelesen zu haben, das dies die Meldung für eine gestörte Internetverbindung ist?

Gibt es hierfür eine Workaround?

Vielen Dank für deine tolle Arbeit :-)

**Comment by alexreinert** [comment]
Hat die VM denn Internet? Was liefert `ping www.google.com` innerhalb der VM? Welche OS ist im Einsatz (inkl. Version)?

**Comment by trevon88** [comment]
Hallo, Alexander, ja die VM hat Internet und ich kann auch alles Updaten.

`
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
`
`
PING www.google.com (172.217.168.4) 56(84) bytes of data.
64 bytes from zrh11s03-in-f4.1e100.net (172.217.168.4): icmp_seq=1 ttl=113 time=                                            15.2 ms
64 bytes from zrh11s03-in-f4.1e100.net (172.217.168.4): icmp_seq=2 ttl=113 time=                                            14.1 ms
64 bytes from zrh11s03-in-f4.1e100.net (172.217.168.4): icmp_seq=3 ttl=113 time=                                            15.0 ms
64 bytes from zrh11s03-in-f4.1e100.net (172.217.168.4): icmp_seq=4 ttl=113 time=                                            14.6 ms
64 bytes from zrh11s03-in-f4.1e100.net (172.217.168.4): icmp_seq=5 ttl=113 time= `


Danke für die schnelle Antwort :-)

**Comment by alexreinert** [comment]
Was liefern folgende Befehle?
```
ls -la /var/status/has*
ip -o -4 addr show
```

**Comment by trevon88** [comment]
Hallo Alex

Ich war "ausser gefecht", möchte dir aber für deine Antwort danken.
Ich habe alles geupdatet, seitdem funktioniert alles.

Danke und ein hoffentlich gutes 2022

Gruss

Am Mo., 22. Nov. 2021 um 13:35 Uhr schrieb Alexander Reinert <
***@***.***>:
