### ISSUE TITLE
nach update von Proxmox Kernel 5.13.19 und update vom DKMS Modul Fehler.

### ISSUE THREAD

**Issue by MarkSau** [alexreinert/debmatic#263]
nach update von Proxmox Kernel 5.13.19 und update vom DKMS Modul Fehler.
versuch eines Reinstall:

`root@MSNUC:~# sudo apt reinstall pivccu-modules-dkms debmatic-lxc-host
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 43.0 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://www.debmatic.de/debmatic testing/main amd64 pivccu-modules-dkms all 1.0.68 [41.1 kB]
Get:2 https://www.debmatic.de/debmatic testing/main amd64 debmatic-lxc-host all 1.0.5 [1,872 B]
Fetched 43.0 kB in 0s (145 kB/s)
Preconfiguring packages ...
(Reading database ... 87298 files and directories currently installed.)
Preparing to unpack .../pivccu-modules-dkms_1.0.68_all.deb ...
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.

Deleting module version: 1.0.68
completely from the DKMS tree.

Done.
Unpacking pivccu-modules-dkms (1.0.68) over (1.0.68) ...
Preparing to unpack .../debmatic-lxc-host_1.0.5_all.deb ...
Unpacking debmatic-lxc-host (1.0.5) over (1.0.5) ...
Setting up pivccu-modules-dkms (1.0.68) ...
Error! The module/version combo: pivccu-1.0.68
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.68/source ->
                 /usr/src/pivccu-1.0.68

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.13.19-1-pve ARCH=x86 all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.19-1-pve (x86_64)
Consult /var/lib/dkms/pivccu/1.0.68/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Setting up debmatic-lxc-host (1.0.5) ...
`

**Comment by alexreinert** [comment]
Wie ist der Inhalt der Datei /var/lib/dkms/pivccu/1.0.68/build/make.log?

**Comment by MarkSau** [comment]
DKMS make.log for pivccu-1.0.68 for kernel 5.13.19-1-pve (x86_64)
Sun 21 Nov 2021 12:01:51 PM CET
make -C /lib/modules/5.13.19-1-pve/build M=/var/lib/dkms/pivccu/1.0.68/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.19-1-pve'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[1]: *** [Makefile:753: include/config/auto.conf] Error 1
make[1]: Leaving directory '/usr/src/linux-headers-5.13.19-1-pve'
make: *** [Makefile:30: all] Error 2

**Comment by MarkSau** [comment]
auto.conf existiert

**Comment by alexreinert** [comment]
Dem Log nach ist das ein Problem von den Proxmox Kernel Headern, welches generell alle DKMS basierten Kernel Module betreffen wird. Da werde ich vermutlich nicht wirklich etwas machen können.

**Comment by MarkSau** [comment]
apt reinstall pve-headers-`uname -r` pve-headers war in dem Fall die Lösung...Danach ging auch der reinstall von den pivccu modulen.
Danke für den Hinweis...
