### ISSUE TITLE
Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by cocoon77** [alexreinert/debmatic#264]
Hallo,

ich wollte mich bzgl. der Verwendung von debmatic mit Raspberry Pi OS Bullseye erkundigen, da in deiner Beschreibung diese Version nicht offiziell unterstützt wird.
Ich habe zum Testen eine Installation mit den selben Schritten wie üblich versucht und sieht auf den ersten Blick im Log so aus als ob alles ok ist. Dienst ist gestartet und keine Fehler im Log - Hardwarelicht ist Blau ... Jedoch bekomme ich die WebUI nicht zum laufen. Bei der Eingabe der Adresse kommt keine Antwort. Ich habe dann noch ioBroker installiert der mit Port 8081 normal im Browser zum die das WebUI zeigt.
Vielen Dank für dieses Projekt!
Martin

**Comment by alexreinert** [comment]
Bullseye läuft, das ist in der Doku noch nicht angepasst.

Wegen der nicht erreichbaren WebUI: Welche IP rufst du auf, die vom Container oder die vom Pi? Was liefert `sudo pivccu-info`?

**Comment by cocoon77** [comment]
Die WebUI ist die IP des Pi die ich versuche zu erreichen und ist statisch gesetzt.
pivccu-info scheint bei mir nicht zu exisiteren.
Das einzige was bei der Installation nicht lt. Anleitung funktionierte ist `wget -q -O - https://www.debmatic.de/debmatic/public.key | sudo apt-key add -` da diese anscheinend nun anders gemacht werden muss.

**Comment by alexreinert** [comment]
Mein Fehler, bin im Kopf von piVCCU ausgegangen.

Was liefern

```
sudo debmatic-info
sudo systemctl status lighttpd.service
sudo systemctl status debmatic.service
sudo systemctl list-dependencies debmatic.service # Bitte inkl. Info über Farben der Punkte
sudo systemctl status debmatic-lighttpd.service
```

**Comment by cocoon77** [comment]
Hallo vielen Dank, das hat mir bei der Fehlersuche schon mal weitergeholfen um bei beiden Systemen vergleichen zu können:

`sudo debmatic-info`

debmatic version: 3.59.6-78
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:01:00.0-1.4 (/dev/raw-uart)
 Board serial:  XXXXXXX
 Radio MAC:   XXXXXXX
HMIP Hardware:  RPI-RF-MOD
 SGTIN:         XXXXXXXXXXXXXXXXXXX
 Radio MAC:   XXXXX


`sudo systemctl status lighttpd.service` Und hier scheint nun das Problem zu sein:

● lighttpd.service - Lighttpd Daemon
     Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-11-22 14:04:11 GMT; 12min ago
    Process: 709 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
    Process: 715 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)
   Main PID: 715 (code=exited, status=255/EXCEPTION)
        CPU: 913ms

Nov 22 14:04:11 SmartHome systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Nov 22 14:04:11 SmartHome systemd[1]: Stopped Lighttpd Daemon.
Nov 22 14:04:11 SmartHome systemd[1]: lighttpd.service: Start request repeated too quickly.
Nov 22 14:04:11 SmartHome systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Nov 22 14:04:11 SmartHome systemd[1]: Failed to start Lighttpd Daemon.


`sudo systemctl status debmatic.service`

● debmatic.service - debmatic
     Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
     Active: active (exited) since Mon 2021-11-22 14:04:16 GMT; 18min ago
    Process: 519 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
   Main PID: 519 (code=exited, status=0/SUCCESS)
        CPU: 2.174s

Nov 22 14:04:04 SmartHome systemd[1]: Starting debmatic...
Nov 22 14:04:16 SmartHome systemd[1]: Finished debmatic.


`sudo systemctl list-dependencies debmatic.service`

● ├─debmatic-eq3configd.service
● ├─debmatic-hmserver.service
grau ├─debmatic-hs485d.service
● ├─debmatic-hssled.service
grau ├─debmatic-lighttpd.service
grau ├─debmatic-monitor-hb-rf-eth.service
● ├─debmatic-multimacd.service
● ├─debmatic-prepareinterfaceslist.service
● ├─debmatic-rega.service
● ├─debmatic-rfd.service
● ├─debmatic-setinterfaceclock.timer
● ├─debmatic-ssdpd.service
● ├─debmatic-startupfinished.service
● ├─debmatic-updatelgwfirmware.service
● ├─debmatic-updatelgwkey.service
● ├─debmatic-updaterffirmware.service
grau ├─pivccu-dkms.service
● ├─system.slice
● └─sysinit.target
grau   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─fake-hwclock.service
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─sys-kernel-tracing.mount
●   ├─systemd-ask-password-console.path
grau   ├─systemd-binfmt.service
grau   ├─systemd-boot-system-token.service
grau   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
grau   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
grau   ├─systemd-pstore.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot.mount
●   │ ├─systemd-fsck-root.service
●   │ └─systemd-remount-fs.service
●   └─swap.target


`sudo systemctl status debmatic-lighttpd.service`

● debmatic-lighttpd.service - debmatic lighttpd
     Loaded: loaded (/lib/systemd/system/debmatic-lighttpd.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

Nov 22 14:04:11 SmartHome systemd[1]: Dependency failed for debmatic lighttpd.
Nov 22 14:04:11 SmartHome systemd[1]: debmatic-lighttpd.service: Job debmatic-lighttpd.service/start failed with result 'dependency'.

**Comment by alexreinert** [comment]
Was liefert `cat /var/log/lighttpd/error.log`

**Comment by cocoon77** [comment]
`sudo cat /var/log/lighttpd/error.log`

2021-11-22 13:42:15: server.c.1513) server started (lighttpd/1.4.59)
2021-11-22 13:42:43: server.c.949) [note] graceful shutdown started
2021-11-22 13:42:43: server.c.1976) server stopped by UID = 0 PID = 2615

**Comment by alexreinert** [comment]
ok, dann `/usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf`

**Comment by cocoon77** [comment]
`sudo /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf`

2021-11-22 16:09:22: network.c.337) socket: Address family not supported by protocol

**Comment by alexreinert** [comment]
Hast du IPv6 deaktiviert?

**Comment by alexreinert** [comment]
Wann ja: Bitte aktivieren, Link-Local reicht dabei vollkommen aus.

**Comment by cocoon77** [comment]
Ok, ich hatte ipv6.disable=1 in der /boot/cmdline.txt eingetragen da ich gerne IPv6 deaktivieren wollte.
Wenn ich diesen Eintrag entferne funktioniert es korrekt.

Im aktiven System habe ich die IPv6 auch deaktiviert, wohl aber anders.

Vielen Dank für deine Zeit und die Hilfe!
