### ISSUE TITLE
Nach Update keine IP Geräte mehr

### ISSUE THREAD

**Issue by MisterBJ** [alexreinert/debmatic#265]
Hallo,

nachdem gestern mein Pi4 mit openhab 3.2 (als Docker Container) und debmatic (mit HM-MOD-RPI-PCB) nur noch verzögert reagierte habe ich einen Neustart vom Pi gemacht. Als das nicht half ging ich per SSH auf Ursachenprüfung. Es hatte sich herausgestellt das der Docker Container von openhab eine riesige Log-Datei mit über 100GB erstellt hatte. Der kleine Rechner war voll da ging gar nix mehr...keine Weboberfläche von openhab und auch nicht die CCU. Nachdem ich die Log-Datei gelöscht und den Pi neugestartet habe lief reagierte der Pi auch wieder normal.
Das aber nicht ging war unter der CCU Weboberfläche...es waren keine HM IP Geräte zu sehen. Also habe ich erstmal ein Backup eingespielt. Gleiche Problem, neustart, keine Änderung. Dann habe ich mir gesagt ich mach mal ein Update vom System und somit auch ein Update von Debamtic auf die Version 3.61.5.81. Backup eingespielt, Neustart vom Pi, keine Änderung. Ich habe keine IP-Geräte mehr, siehe Screenshot.
Mir gehen die Ideen aus was ich noch machen bzw. überprüfen könnte.

Was ich vergessen habe, unter Openhab werden weiterhin Daten geliefert und auch Änderungen sind möglich.

debmatic-info:
debmatic version: 3.61.5-81
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  NEQ0230770
 Radio MAC:     0x470549
HMIP Hardware:  HM-MOD-RPI-PCB
 SGTIN:         3014F711A061A7D5698CED72
 Radio MAC:     0xBC9AB0

cat /etc/debian_version: 10.11
uname -a: Linux smartpi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

Gruß,
Björn
<img width="365" alt="screenshot_65" src="https://user-images.githubusercontent.com/43717268/143744189-589794e3-3c3e-42ba-b547-e471936f65c0.png">

**Comment by alexreinert** [comment]
Ich fürchte, dass ReGaDom wg. Platzmangel nicht sauber gespeichert werden konnte. Spätestens durch das Einspielen des Backups kommt man dann auch nicht mehr an alte Fragmente ran.
Du könntest mir das Backup per Mail zusenden, dann kann ich schauen, ob ich noch was machen kann.
Ein möglicher Versuch wäre es auch, die Geräte erneut anzulernen, bei HM Geräten funktioniert das recht gut, bei HmIP Geräten sehe ich die Chancen aber leider überschaubar.

**Comment by MisterBJ** [comment]
Gerne sende ich dir das Backup zu bzw. ich bin dir dankbar wenn du dir die Zeit dafür nimmst..
Was mich verwirrt ist das ich mit openHAB weiterhin die Geräte steuern kann und gerade eben zeigt die CCU mir neue Geräte-Updates für die HMIP-PSM an. Wenn er ein Update anzeigt sollte das Gerät der CCU doch bekannt sein oder nicht?
Neuanlernen würde ich sehr gerne umgehen da ich einige HMIP-Geräte besitze und diese müssten, glaube ich, in OH ja auch dann wieder neu integriert werden.
Ich suche das File heraus und sende es demnächst per Mail.

Danke im voraus,
Björn

**Comment by alexreinert** [comment]
Es gibt nicht nur ein Config File auf der CCU, sondern mehrere. Die Anzeige auf der Weboberfläche kommt u.A. von der RegaDom, Openhab greift direkt per XmlaRPC auf den HMServer zu, welcher eine eigene Config hat.

**Comment by MisterBJ** [comment]
Okay, bin von nur einer Config ausgegangen.

**Comment by MisterBJ** [comment]
Hallo Alex,

ich wollte nur nachfragen ob meine E-Mail mit der Backup Datei angekommen ist.

Gruß,
Björn

**Comment by alexreinert** [comment]
Ja, kam an, ich bin noch am Auseinandernehmen

**Comment by MisterBJ** [comment]
Servus Alex,
das scheint ja doch kompliizerter zu sein. Ist zwar Blöd aber ich würde Morgen meinen Feiertag dazu nutzen um die Geräte neu zu connecten. Hatte jetzt schon das Problem das Batterie von einem Heizungsregler leer ware und ich keine Meldung bekommen habe. Was ich mir als Frage stelle, bzw. stelle ich dir ist es vielleicht Sinnvoller von DebMatic auf piVCCU im Docker umzusteigen? Ich stelle mir vor das ich einfach regelmäßig ein Backup vom Container auf mein NAS ablege...Sinnvoll?

Gruß,
Björn

**Comment by MisterBJ** [comment]
Hallo zusammen,

wie ich bereits geschrieben habe habe ich den Pi neu aufgesetzt da ich keine Geräte mehr steuern konnte.
Ich bin auch bei debMatic geblieben und nicht auf piVCCU umgestiegen.
Ich habe jetzt das gleiche Problem das ich keine Geräte anlernen kann, auch nach einer Werkszurückstellung (4sek + 4 sek).
Es wird das letzte PiOS verwendet und die aktuellste debmatic. Ich habe auch kein Backup geladen um Fehler vorzubeugen.
So langsam...nein...ich bin am verzweifeln.

debmatic-info:
`debmatic version: 3.61.7-88
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  NEQ0230770
 Radio MAC:     0x470549
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 SGTIN:         3014F711A061A7D5698CED72
 Radio MAC:     0xBC9AB0`

cat /etc/debian_version: 11.1
uname -a: Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux


Gruß,
Björn

**Comment by alexreinert** [comment]
Die Kernel Version sieht nach Raspberry Pi 4 aus? Der ist leider ein massiver Störsender, welcher vor allem HmIP stört, vor allem (aber nicht nur dann), wenn etwas an USB3 und/oder HDMI hängt. Einzige zuverlässige Lösung dafür ist es, dass gesamte Funkmodul mind. 0,5m besser 1m entfernt vom Pi aufzustellen (per HB-RF-USB-2 oder GPIO Verlängerung)

**Comment by MisterBJ** [comment]
Das ist ja Blöd, komisch nur das es bis zu dem Log-Datei (docker) es einwandfrei funktioniert hat.
Aber das kann schon Möglich sein da ich ein Wandthermostat mal direkt daneben und mal einen Meter entfernt aufgestellt habe.
Auf den USB-Anschluss kann ich nicht verzichten da ich eine M-SSD verwende.
Danke dir für die schnelle Antwort, schönen Sonntag noch.

**Comment by MisterBJ** [comment]
So, ich habe jetzt die HB-RF-USB-2 gejauft und installiert und jetzt funktioniert alle einwandfrei.
Aber eine Frage hätte ich noch zum Backup.
Ich hatte die HM-MOD-RPI-PCB mit debmatic zum testen auf einen Pi3 installiert um sicher zu gehen das die HM-MOD-RPI-PCB noch in Ordnung ist. Habe über die Web-UI ein Backup erstellt und dann mit deiner Platine auf den Pi4 gewechselt. Aber nachdem ich das Backup eingespielt habe waren zwar die Geräte und die Direktverknüpfungen noch/wieder da aber die Gruppen nicht.
Weist du vielleicht ob eine Doku existiert wo genau drin steht was wirklich gesichert wird? Oder gibt es noch bessere Lösungen?

Gruß und Danke,
Björn
