### ISSUE TITLE
Proxmox 7.1-7 Fehler beim Erstellen der Kernel Module

### ISSUE THREAD

**Issue by bepat** [alexreinert/debmatic#266]
Hallo,

ich kann unter Proxmox 7.1-7 mit Kernel Version 5.13.19-1 leider die Kernel Module nicht erstellen.
Die Log Datei `/var/lib/dkms/pivccu/1.0.68/build/make.log` enthält folgenden Inhalt:
```
DKMS make.log for pivccu-1.0.68 for kernel 5.13.19-1-pve (x86_64)
Wed 01 Dec 2021 07:49:13 AM CET
make -C /lib/modules/5.13.19-1-pve/build M=/var/lib/dkms/pivccu/1.0.68/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.19-1-pve'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[1]: *** [Makefile:753: include/config/auto.conf] Error 1
make[1]: Leaving directory '/usr/src/linux-headers-5.13.19-1-pve'
make: *** [Makefile:30: all] Error 2
```

Das vorgeschlagene `make oldconfig` bzw.  `make prepare` bringt folgenden Fehler:
```
lib/Kconfig.debug:2603: can't open file "Documentation/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:77: oldconfig] Error 1
make: *** [Makefile:635: oldconfig] Error 2
```

Die Kernel Header habe ich schon entfernt und neu installiert. Leider ohne Erfolg.

Hat vielleicht Jemand einen Tipp für mich?
Vielen Dank!

Gruß
Benedikt

**Comment by alexreinert** [comment]
Das ist ein fehlerhaftes Kernel Header Paket von Proxmox, welches leider nur durch Proxmox gefixt werden kann.

**Comment by bepat** [comment]
Ich hatte sowas schon befürchtet.
Aber vielen Dank für die schnelle Antwort!

**Comment by bepat** [comment]
Ich habe jetzt den fehlenden Documentation Ordner aus den Kernel Quellen manuell auf mein System kopiert und war so in der Lage, das Modul zu erstellen.

**Comment by Spezialtrick** [comment]
@bepat 

Könntest du dein Vorgehen genauer beschreiben? Stehe vor dem gleichen Problem und weiß nicht so recht, was ich nun machen soll.

**Comment by bepat** [comment]
Mit dem Kernel 5.13.19-2-pve aus dem no-subscription Repository hat sich das Problem erledigt. Damit werden die Module ohne weitere Anpassungen gebaut.
