### ISSUE TITLE
Installation raspberrypi-kernel-headers in LXC container (ohne Proxmox)

### ISSUE THREAD

**Issue by uli-rpi** [alexreinert/debmatic#267]
Die Installation der raspberrypi-kernel-headers in einem LXC container schlägt fehl

(Paket raspberrypi-kernel-headers ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. )
Pi 4B, Buster, 32bit

**Comment by alexreinert** [comment]
Ja, normal, weil ein LXC Container nicht die notwendigen Rechte hat. Die ganzen Sachen für Kernel Module müssen im Host gemacht werden und dann die entsprechenden Geräte in den Container reingereicht werden.

**Comment by uli-rpi** [comment]
Hallo Alex,
ja danke, gibt es eine Doku für das "reinreichen"

**Comment by alexreinert** [comment]
Nicht wirklich, weil das je nach OS und Funkmodul komplett unterschiedlich sein kann.
Ggf. ist aber piVCCU3 genau was du suchst, da läuft die CCU in einem Container, aber der ganze Prozess mit dem reinreichen ist komplett in einen eigenen systemd Service verpackt.

**Comment by uli-rpi** [comment]
ich habe eine piVCCU3 produktiv auf einem anderen Raspberry am Laufen, wollte die debmatic mal ausprobieren. 

Danke für deine schnelle Antwort. 
Du kannst das issue schließen.
