### ISSUE TITLE
Anlernen nicht möglich

### ISSUE THREAD

**Issue by caveman2003** [alexreinert/debmatic#27]
Hi all, 
z.Z. teste ich den CCU3 (3.45.7.22) auf Docker / Kubernetes (https://github.com/angelnu/docker-ccu), dabei sollten keine hat's oder funkmodule (wie  HM-MOD-RPI-PCB) verwendet werden sondern Gateways (wie Wired Access Point DRAP und HomeMatic RF-LAN). Dabei ist es nicht möglich Geräte anzulernen. (siehe Bild).
Alternativ habe ich debmatic (3.45.7.22) auf ein RasPi 3B+ native (ohne Docker) installiert und ich habe das gleiche Problem: es nicht möglich Geräte anzulernen. 
![Auswahl_013](https://user-images.githubusercontent.com/35966082/58544668-052ea800-8202-11e9-83d3-81d1b650fbb1.png)

Auf eine CCU2 (YAHM) ist das kein Problem...

**Comment by caveman2003** [comment]
Gibt es ein Problem mit der Firmware? oder gibt es ideen dazu ?

**Comment by alexreinert** [comment]
Ich kann nur zu debmatic antworten mit dem Docker System von angelnu habe ich nichts am Hut.

Der Anlerndialog zeigt immer nur die Protokolle zum Anlernen an, für welche auch Hardware vorhanden ist, d.h. es muss entweder ein HmRF kompatibles Funkmodul angeschlossen sein oder ein LAN-GW korrekt eingerichtet sein, damit HmRF angelernt werden kann.

Der HmIPW-DRAP kann nur eingerichtet werden, wenn ein RPI-RF-MOD angeschlossen ist (entweder direkt oder über eine HB-RF-USB), da dies im Closed Source von eQ-3 so vorgesehen ist. Ich vermute, dass das RPI-RF-MOD an der Stelle für die Verschlüsselung des Protokolls notwendig ist.

**Comment by caveman2003** [comment]
Danke für die Aufklärung. Ich habe ein LAN GW angeschlossen aber es wird nicht als "activ" angezeigt. Das LAN GW wird noch von meine (produktive) CCU2 verwendet. Ist es möglich eine LAN GW von zwei CCU's anzusteuern ? (mehrere LAN GW an eine CCU schon gesehen :-) ).
Schade dass ich für HmIPW-DRAP ein Stück Hardware brauche... das macht es schwierig in einem Kubernetes zu betreiben... was mein Ziel eigentlich ist. ...

**Comment by alexreinert** [comment]
Ein LAN GW kann immer nur an einer CCU betrieben werden.

**Comment by caveman2003** [comment]
Danke sehr !
