### ISSUE TITLE
log4j version

### ISSUE THREAD

**Issue by ruN86** [alexreinert/debmatic#272]
Ist debmatic betroffen von der aktuellen log4j Lücke?

Beim Start von HMIPServer.jar wird wohl auch log4j verwendet. Ich kann aber nicht sehen oder sagen welche Version und in wie fern debmatic von der Lücke betroffen ist.

**Comment by ruN86** [comment]
Mal abgesehen davon dass die CCU nicht nach außen hin erreichbar sein sollte hat das BSI mittlerweile ja auch die 1.x Versionen als angreifbar deklariert, 

Zitat:"Update 4:
Inzwischen wurde die Liste mit der Informationssammlung durch NCSC-NL [NCSC2021] veröffentlicht.
Entgegen der anderslautenden ursprünglichen Annahme ist Berichten zufolge die Programmbibliothek auch
in den Versionen 1.x verwundbar. In diesen Fällen sei die Verwundbarkeit jedoch nur über eine schadhafte
Programmkonfiguration ausnutzbar, sodass eine Ausnutzung weit weniger wahrscheinlich erscheint. [GIT2021d]".

Und auch das hier hinterlässt in diesem Zusammenhang einen faden Beigeschmack:
"Die Log4J Versionen 1.x sind von der aktuellen Schwachstelle nach aktueller Kenntnis nicht betroffen [GIT2021d]. Die
Version 1.x wird, auch wenn sie noch in diversen Produkten eingesetzt wird, nicht mehr vom Hersteller unterstützt. Sie
ist End-of-Life und durch andere Schwachstellen verwundbar. Daher sollten auch noch eingesetzte Log4J Versionen 1.x
ebenfalls auf eine nicht-verwundbare Version 2.x aktualisiert werden."

Ich weiß auch, dass hier nicht die richtige Stelle für HMIPSERVER.jar Fragen ist aber welche Stelle könnte hier denn tätig werden bzw. wer ist verantwortlich für die Pflege oder das Produkt, eq3 selbst?

**Comment by alexreinert** [comment]
Die Versionen 1.x sind aber nur bedingt angreifbar wie du selbst geschrieben hast und die meines Wissens nach ist die Konfig, so wie ich ausliefere damit nicht betroffen.
Der HMIPServer wird Closed Source von eQ-3 bereitgestellt, Ansprechpartner wären diese. Allerdings ist die Reaktionszeit nicht unbedingt das, was man gerne hätte, auch bei den restlichen Software-Komponenten der CCU Firmware sollte mal lieber nicht zu genau drauf schauen, von wann diese sind, log4j ist hier leider nicht die Spitze des Eisbergs.

**Comment by ruN86** [comment]
Alles klar, danke für die schnellen Antworten.
