### ISSUE TITLE
3.61.7: combination of HmIP-RFUSB and HM-CFG-USB-2 not working

### ISSUE THREAD

**Issue by disaster123** [alexreinert/debmatic#273]
Hi,

3.61.7-86 does not show any hardware devices.

root@debmatic:~# debmatic-info 
debmatic version: 3.61.7-86
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown

After installing a vm backup:
root@debmatic:~# debmatic-info 
debmatic version: 3.59.6-78
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  HM-CFG-USB-2
 Board serial:  KEQ111XXXX
 Radio MAC:     unknown
HMIP Hardware:  HMIP-RFUSB
 SGTIN:         3014F711A000041BE9XXXX
 Radio MAC:     0xBEDXXX

Greets,
Stefan

**Comment by alexreinert** [comment]
Did you reboot the VM after the update?

**Comment by disaster123** [comment]
yes - sure

**Comment by disaster123** [comment]
i also tried todo the upgrade again after installing the vm backup - still failing

**Comment by alexreinert** [comment]
Can you please provide the output of lsusb inside the vm?
And for clarification: What type of VM are you using?

**Comment by disaster123** [comment]
sure:
```
root@debmatic:~# lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 003: ID 1b1f:c00f eQ-3 Entwicklung GmbH HM-CFG-USB/HM-CFG-USB-2 [HomeMatic Configuration adapter]
Bus 002 Device 002: ID 1b1f:c020 eQ-3 Entwicklung GmbH 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd 
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

VM Type is: Qemu / KVM

**Comment by claymore666** [comment]
Hi Alex,

for what it's worth and maybe it helps to narrow it down, it works with the HB-RF-ETH (on QEMU/ Proxmox):

`root@debmatic:/# debmatic-info`
`debmatic version: 3.61.7-86`
`Kernel modules: Available`
`Raw UART dev:   Available`
`HMRF Hardware:  RPI-RF-MOD`
` Connected via: HB-RF-ETH@10.2.6.234 (/dev/raw-uart)`
` Board serial:  5A4993DD65`
` Radio MAC:     0xFFDD65`
`HMIP Hardware:  RPI-RF-MOD`
` Connected via: HB-RF-ETH@10.2.6.234 (/dev/raw-uart)`
` SGTIN:         3014F711A0001F5A4993DD65`
` Radio MAC:     0xB696A2`

obviously, no usb devices...:
`root@debmatic:/# lsusb`
`Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub`

Cheers,

Chris

**Comment by alexreinert** [comment]
Please provide the output of `detect_radio_module --debug /dev/raw-uart` and `dmesg | grep usb`

**Comment by disaster123** [comment]
Did you mean @disaster123 or @claymore666 ?

For me /dev/raw-uart does not exist on both versions (working and not working one)

**Comment by alexreinert** [comment]
Of course I mean you, @disaster123, debugging a working installation is not worth the time.
In 3.59.6 it is normal, that there is not raw-uart available when using the HMIP-RFUSB.. In 3.61.7 it should be available, as there is now support for BidCos/HMIP dual mode using the HMIP-RFUSB.

**Comment by disaster123** [comment]
@alexreinert here we go:
```
root@debmatic:~# detect_radio_module --debug /dev/raw-uart
10:28:29.617286 Sending HM frame:  fd 00 03 fe 00 01 14 1e
10:28:29.621222 Received HM frame: fd 00 10 fe 00 05 01 48 4d 49 50 5f 54 52 58 5f 41 70 70 cc e0
10:28:29.621306 Sending HM frame:  fd 00 03 fe 01 02 92 17
10:28:29.623636 Received HM frame: fd 00 04 fe 01 05 01 07 02
10:28:29.826249 Received HM frame: fd 00 0e fe 00 00 48 4d 49 50 5f 54 52 58 5f 42 6c f4 c2
10:28:29.826397 Sending HM frame:  fd 00 03 fe 02 01 98 1d
10:28:29.830360 Received HM frame: fd 00 0f fe 02 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ea c6
10:28:29.830433 Sending HM frame:  fd 00 03 fe 03 03 9e 11
10:28:30.270206 Received HM frame: fd 00 04 fe 03 05 01 87 29
10:28:30.289115 Received HM frame: fd 00 0f fe 01 00 48 4d 49 50 5f 54 52 58 5f 41 70 70 0e 20
10:28:30.289180 Sending HM frame:  fd 00 03 01 04 09 00 22
10:28:30.390332 Received HM frame: fd 00 05 01 04 04 01 01 16 28
10:28:30.390409 Sending HM frame:  fd 00 03 01 05 02 06 18
10:28:30.492850 Received HM frame: fd 00 0d 01 05 04 01 02 08 06 01 00 0c 01 14 03 7e 6a
10:28:30.492934 Sending HM frame:  fd 00 03 02 06 01 0c 2e
10:28:30.495684 Received HM frame: fd 00 07 02 06 06 01 be d3 9e c7 7b
10:28:30.495759 Sending HM frame:  fd 00 03 fe 07 04 86 03
10:28:30.499665 Received HM frame: fd 00 10 fe 07 05 01 30 14 f7 11 a0 00 04 1b e9 9b 3a 7b 94 2a
HMIP-RFUSB 1BE99B3A7B 3014F711A000041BE99B3A7B 0x000000 0xBED39E 2.8.6
```

```
root@debmatic:~# dmesg | grep -i usb
[    0.402734] pci 0000:00:01.2: quirk_usb_early_handoff+0x0/0x6d0 took 23715 usecs
[    0.439547] pci 0000:01:1b.0: quirk_usb_early_handoff+0x0/0x6d0 took 35885 usecs
[    0.973488] ACPI: bus type USB registered
[    0.973505] usbcore: registered new interface driver usbfs
[    0.973591] usbcore: registered new interface driver hub
[    0.973598] usbcore: registered new device driver usb
[    0.976825] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.978201] uhci_hcd: USB Universal Host Controller Interface driver
[    1.019718] uhci_hcd 0000:00:01.2: new USB bus registered, assigned bus number 1
[    1.019932] usb usb1: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 4.19
[    1.019933] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.019934] usb usb1: Product: UHCI Host Controller
[    1.019935] usb usb1: Manufacturer: Linux 4.19.0-18-amd64 uhci_hcd
[    1.019936] usb usb1: SerialNumber: 0000:00:01.2
[    1.028278] hub 1-0:1.0: USB hub found
[    1.028599] xhci_hcd 0000:01:1b.0: new USB bus registered, assigned bus number 2
[    1.029258] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    1.029260] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.029261] usb usb2: Product: xHCI Host Controller
[    1.029261] usb usb2: Manufacturer: Linux 4.19.0-18-amd64 xhci-hcd
[    1.029262] usb usb2: SerialNumber: 0000:01:1b.0
[    1.029411] hub 2-0:1.0: USB hub found
[    1.029669] xhci_hcd 0000:01:1b.0: new USB bus registered, assigned bus number 3
[    1.029671] xhci_hcd 0000:01:1b.0: Host supports USB 3.0 SuperSpeed
[    1.029699] usb usb3: We don't know the algorithms for LPM for this host, disabling LPM.
[    1.029713] usb usb3: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.19
[    1.029714] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.029715] usb usb3: Product: xHCI Host Controller
[    1.029715] usb usb3: Manufacturer: Linux 4.19.0-18-amd64 xhci-hcd
[    1.029716] usb usb3: SerialNumber: 0000:01:1b.0
[    1.029854] hub 3-0:1.0: USB hub found
[    1.488308] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    1.560249] usb 2-1: new full-speed USB device number 2 using xhci_hcd
[    1.645280] usb 1-1: not running at top speed; connect to a high speed hub
[    1.678504] usb 1-1: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[    1.678506] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=10
[    1.678507] usb 1-1: Product: QEMU USB Tablet
[    1.678507] usb 1-1: Manufacturer: QEMU
[    1.678508] usb 1-1: SerialNumber: 28754-0000:00:01.2-1
[    1.691692] usbcore: registered new interface driver usbhid
[    1.691692] usbhid: USB HID core driver
[    1.692657] input: QEMU QEMU USB Tablet as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/0003:0627:0001.0001/input/input4
[    1.692699] hid-generic 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Mouse [QEMU QEMU USB Tablet] on usb-0000:00:01.2-1/input0
[    1.754101] usb 2-1: New USB device found, idVendor=1b1f, idProduct=c020, bcdDevice= 1.00
[    1.754103] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.754104] usb 2-1: Product: eQ-3 HmIP-RFUSB
[    1.754104] usb 2-1: Manufacturer: Silicon Labs
[    1.754105] usb 2-1: SerialNumber: 3014F711A000041BE99B3A7B
[    2.116285] usb 2-2: new full-speed USB device number 3 using xhci_hcd
[    2.344216] usb 2-2: New USB device found, idVendor=1b1f, idProduct=c00f, bcdDevice= 9.67
[    2.344218] usb 2-2: New USB device strings: Mfr=4, Product=14, SerialNumber=36
[    2.344218] usb 2-2: Product: HM-CFG-USB
[    2.344219] usb 2-2: Manufacturer: eQ-3
[    2.344220] usb 2-2: SerialNumber: KEQ1111109
[    2.380403] hid-generic 0003:1B1F:C00F.0002: hiddev0,hidraw1: USB HID v1.10 Device [eQ-3 HM-CFG-USB] on usb-0000:01:1b.0-2/input0
[    2.479246] usb 2-1: Found eQ-3 HmIP-RFUSB with serial 3014F711A000041BE99B3A7B at usb-0000:01:1b.0-1
[    2.491230] usbcore: registered new interface driver hb_rf_usb_2
```

**Comment by alexreinert** [comment]
Please remove the HM-CFG-USB-2, while the HmIP-RFUSB is still connected, reboot the VM and wait about 5 to 10 minutes. Then provide the output of debmatic-info.
Maybe there is some incompatibility, if both sticks are connected, but I'm currently I have no access to my tests systems, to check that.

**Comment by alexreinert** [comment]
As the HmIP-RFUSB supports now HM and HmIP, the HM-CFG-USB-2 is now not needed anymore for HM communication.

**Comment by disaster123** [comment]
If i remove the HM-CFG-USB-2 i get:
```
root@debmatic:~# debmatic-info 
debmatic version: 3.61.7-86
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:01:1b.0-1 (/dev/raw-uart)
 Board serial:  1BE99B3A7B
 Radio MAC:     0x4effc9
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:01:1b.0-1 (/dev/raw-uart)
 SGTIN:         3014F711A000041BE99B3A7B
 Radio MAC:     0xBED39E
```

**Comment by disaster123** [comment]
So i need to repair all my devices??

**Comment by disaster123** [comment]
Mhm seems it just works without the 2nd stick - could this be? No repair needed? Just put the CFG2 stick to trash?

**Comment by alexreinert** [comment]
As said: The HmIP-RFUSB supports now BidCos (=HM) and HmIP dual support. So yes, this could (and should) be, that you are needing the second stick anymore and any old BidCos devices work without re-pairing, just as it would be, if you would replace a defective HM-CFG-USB-2 this an other one.
And before you put the stick to trash: For me that would be still a needful test device. :wink:

**Comment by disaster123** [comment]
Please send me your adress ;-) I'll send you the stick.

One remaining issue - each Firmware Update adds 35% duty cycle - until whole ccu stops working. So i can Update 2 devices - ccu needs reboot - update again 2 devices... ccu needs reboot.

**Comment by alexreinert** [comment]
Do you mean firmware update of a device?

**Comment by alexreinert** [comment]
And thanks for the offer with the stick. Can you send me a mail to alex@areinert.de as Github hides your address and I do not want post my full address here in public.

**Comment by disaster123** [comment]
> Do you mean firmware update of a device?

Device firmware

**Comment by alexreinert** [comment]
Device firmware updates take up to 50% DC and do not run in parallel, but sequential. Per device it takes about 8-24 hours, as there is a sending limit to 1% in the 868MHz band (which means 3.6sec per hour). If you reboot the CCU, the current update will start at the beginning, even if it was at 99%. The DC itself is the rolling value of the last hour. So it will fall, the the updates are finished.
This is normal and not a new behavior and I cannot change anything on it, as this is part of the closed source binaries of eQ-3 (and european laws).

**Comment by disaster123** [comment]
Mhm it just takes 2-3 min then reboots and shows current firmware...

Will hopefully send you an email soon - i've currently some reachability problems and need to move the stick to another location - but need to find a way to put the stick far away from the server first. Only LAN and power available.

**Comment by alexreinert** [comment]
Dual usage of HmIP-RFUSB andHM-CFG-USB-2 should work now again.
