### ISSUE TITLE
No CCU firmware version shown 

### ISSUE THREAD

**Issue by tuxianerDE** [alexreinert/debmatic#274]
Hi,

hope you had a nice christmas break. First I would like to express my gratitude for debmatic and how well it works together with the homematic installation here. 

I just wondered about one thing and I was not sure if the problem sits infront of the screen (most probably) or there is an issue I have overlooked. With the latest release I was curious if there a new firmware I have to install to the devices. When I look into the menu however, the current device firmware is shown but the column with CCU Firmware is empty, see attached, is that correct or what did I possibly do wrong?

Cheers & thanks

![debmatic_firmware](https://user-images.githubusercontent.com/47778296/147479428-313ca396-8f42-43c0-b9af-1f1426e5fc7e.PNG)

**Comment by alexreinert** [comment]
Der Einfachheit halber antworte ich mal auf deutsch.
Wenn es für die Geräte neue Firmware Versionen gibt, dann wird das auf der Startseite angezeigt. Dannuss man diese als tgz über den dort angezeigten Limk downloaden und auf die CCU hochladen auf der Seite "Einstellungen" / "Geräte Firmware Übersicht" und dann tauchen in der Liste vom Screenshot auf.
Keine Ahnung, warum eQ-3 sich das so kompliziert ausgedacht hat, ich kam bisher leider noch nicht dazu, das zu vereinfachen.

**Comment by tuxianerDE** [comment]
Hi, vielen Dank! Der Prozess ist in der Tat spannend :)

Auf der Startseite wird nun in der Tat der Hinweis "CCU-Update: | Firmware 3.61.7.87 ist verfügbar" eingeblendet. Wenn ich auf den Link der Firmware Klicke kommt allerdings nur ein Fenster welches mich zu einer Spende ermutigt, dem ich gerne noch nachkomme :) 

Im Download Bereich von Eq3 gibt es keine Firmware mit 3.61.7.87 auch die Google Suche zeigt mal nix dazu an. Gibt es eine eigene Download Seite (ich schaue hier: https://www.eq-3.de/service/downloads.html)

**Comment by alexreinert** [comment]
Ok, ich habe mich mißverständlich ausgedrückt:

Den Link, den du gesehen hast, ist für die eigentliche debmatic Version. Die kann man per apt auf der Shell aktualisieren.

Den Link, welchen ich meinte, sieht man nur, wenn mind. eine Firmware für Geräte runtergeladen werden kann.

**Comment by tuxianerDE** [comment]
Ahh verstanden. Vielen lieben Dank! :)
