### ISSUE TITLE
Update to 3.61.7-88 - HM* Hardware unknown

### ISSUE THREAD

**Issue by appcoders** [alexreinert/debmatic#277]
Update von 3.59.6-78 auf 3.61.7-88 Installation ist kaputt.

Aktueller Status:
```
root@ccu:/# debmatic-info
debmatic version: 3.61.7-88
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
```
```
root@ccu:/# detect_radio_module --debug /dev/raw-uart
18:57:34.716211 Sending HM frame:  fd 00 03 fe 00 01 14 1e
18:57:34.720098 Received HM frame: fd 00 0f fe 00 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c 68 c7
18:57:34.721203 Sending HM frame:  fd 00 03 fe 01 01 92 1d
18:57:34.725036 Received HM frame: fd 00 0f fe 01 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c e9 c5
18:57:34.725641 Sending HM frame:  fd 00 03 fe 02 03 18 12
18:57:34.920237 Received HM frame: fd 00 04 fe 02 05 00 87 3b
18:57:37.721416 Sending HM frame:  fd 00 03 00 03 00 12 00
18:57:37.723588 Received HM frame: fd 00 04 00 03 04 03 19 0e
18:57:40.721679 Sending HM frame:  fd 00 03 fe 04 01 8c 1d
18:57:40.725064 Received HM frame: fd 00 0f fe 04 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ec c0
18:57:40.725187 Sending HM frame:  fd 00 03 fe 05 03 8a 11
18:57:40.919056 Received HM frame: fd 00 04 fe 05 05 00 07 54

```

```
root@ccu:/# lsusb
Bus 001 Device 004: ID 0403:6f70 Future Technology Devices International, Ltd HB-RF-USB
```

```
● debmatic-rfd.service - debmatic rfd
   Loaded: loaded (/lib/systemd/system/debmatic-rfd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Fri 2021-12-31 18:35:09 CET; 28min ago
           └─ ConditionPathExists=!/var/status/debmatic_avoid_rfd was not met

Dec 31 18:35:09 ccu systemd[1]: Condition check resulted in debmatic rfd being skipped.
```

```
dkms status
pivccu, 1.0.70, 5.10.63-v7l+, armv7l: installed
```

Hatte bereits dpkg-reconfigure pivccu-modules-dkms ausgeführt und rebootet. 

Eine Idee @alexreinert ? Danke und gutes neues Jahr :-)

**Comment by appcoders** [comment]
Downgrade auf komplettes Systembackup auf Stand von November 2021 (3.59.6-78) hat keine Besserung gebracht. Ist das Funkmodul kaputt?

**Comment by appcoders** [comment]
Hab jetzt nochmal ein ganz kurzes USB Kabel verwendet. Keine Verbesserung. Das Haus steht still, gut ist ja auch Feiertag :-)

**Comment by djusHa** [comment]
@appcoders 
Hast du versucht den Debmatic Service im nachhinein neu zu starten?
```service debmatic stop``` und ```service debmatic start```

Bei mir hat Debmatic nach einem neustart das Device nicht schnell genug erkannt.

**Comment by alexreinert** [comment]
Es sieht so aus, als wäre das Funkmodul fehlerhaft geflasht. Meistens kann man es durch ein explizites Flashen wieder zum Laufen bringen, die Befehle unterscheiden sich aber je nach genutztem Funkmodul. Welches Funkmodul hast du genau?

**Comment by appcoders** [comment]
Hallo @alexreinert es handelt sich um dieses hier:

https://smartkram.de/shop/produkte/bauteile-zentralen/neues-homematic-funkmodul-fuer-ccu3-fertig-aufgebaut-fuer-raspberrymatic-pivccu/

**Comment by alexreinert** [comment]
Dann bitte als root ausführen:
```
java -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.4.12.eq3
```
und danach nochmal den Befehl mit detect_radio_module.
Wenn es da dann erkannt wird, einen Reboot, sonst mit der Ausgabe von allen Befehlen hier wieder melden.

**Comment by appcoders** [comment]
Vielen herzlichen Dank. 
Sieht wieder gut aus :-)  
Kann das am USB Kabel gelegen haben bezüglich fehlgeschlagenem Flash?

```
10:53:59.710949 Sending HM frame:  fd 00 03 fe 00 01 14 1e
10:53:59.715245 Received HM frame: fd 00 11 fe 00 05 01 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 a2 21
10:53:59.715479 Sending HM frame:  fd 00 03 fe 01 02 92 17
10:53:59.718231 Received HM frame: fd 00 04 fe 01 05 01 07 02
10:53:59.824172 Received HM frame: fd 00 0e fe 00 00 48 4d 49 50 5f 54 52 58 5f 42 6c f4 c2
10:53:59.824326 Sending HM frame:  fd 00 03 fe 02 01 98 1d
10:53:59.828162 Received HM frame: fd 00 0f fe 02 05 01 48 4d 49 50 5f 54 52 58 5f 42 6c ea c6
10:53:59.828262 Sending HM frame:  fd 00 03 fe 03 03 9e 11
10:54:00.022043 Received HM frame: fd 00 04 fe 03 05 01 87 29
10:54:01.924883 Received HM frame: fd 00 10 fe 01 00 44 75 61 6c 43 6f 50 72 6f 5f 41 70 70 b7 36
10:54:01.925093 Sending HM frame:  fd 00 03 01 04 09 00 22
10:54:02.027839 Received HM frame: fd 00 05 01 04 04 01 04 16 36
10:54:02.028003 Sending HM frame:  fd 00 03 01 05 02 06 18
10:54:02.131804 Received HM frame: fd 00 0d 01 05 04 01 04 04 0c 01 00 01 01 3c 00 35 ab
10:54:02.131974 Sending HM frame:  fd 00 03 02 06 01 0c 2e
10:54:02.134814 Received HM frame: fd 00 07 02 06 06 01 1b 67 a5 f7 2c
10:54:02.134949 Sending HM frame:  fd 00 03 fe 07 04 86 03
10:54:02.138795 Received HM frame: fd 00 10 fe 07 05 01 30 14 f7 11 a0 00 1f 58 a9 a7 0b c6 e4 1a
10:54:02.138946 Sending HM frame:  fd 00 03 03 08 08 28 0c
10:54:02.141817 Received HM frame: fd 00 07 03 08 01 01 00 00 00 77 5c
RPI-RF-MOD 58A9A70BC6 3014F711A0001F58A9A70BC6 0xFF0BC6 0x1B67A5 4.4.12
```
```
debmatic version: 3.61.7-88
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:01:00.0-1.4 (/dev/raw-uart)
 Board serial:  58A9A70BC6
 Radio MAC:     0xFF0BC6
HMIP Hardware:  RPI-RF-MOD
 Connected via: HB-RF-USB@usb-0000:01:00.0-1.4 (/dev/raw-uart)
 SGTIN:         3014F711A0001F58A9A70BC6
 Radio MAC:     0x1B67A5
```

**Comment by alexreinert** [comment]
Das kann möglich sein, beim Flashen braucht das Funkmodul sehr viel Strom, was bei schlechten Kabeln die Spannung einbrechen lässt. Aber es kann auch vieles anderes gewesen sein. Nachträglich lässt sich das aber nicht wirklich sagen.

**Comment by appcoders** [comment]
Gut für die nächsten Updates verwende ich dann das kurze Kabel :-) Vielen Dank nochmal.

**Comment by appcoders** [comment]
@alexreinert Leider wieder der gleiche Zustand wie vor zwei Wochen.
Programmierung geht nicht, bleibt einfach stehen. Via dmesg sehe ich folgende Meldung:

gpio gpiochip2: gpiod_set_raw_value: backing chip is gone

kaputt 😞?

**Comment by alexreinert** [comment]
Steht da zufällig auch was von Undervoltage? Zeig mal die gesamte Ausgabe.

**Comment by appcoders** [comment]
Danke für deine schnelle Antwort.
Nein, keinerlei Einträge mit *voltage* in irgendeinem Log File. Ich habe noch gesehen, dass ReGaHss Prozesse sehr viel CPU benötigt haben. Hab den debmatic service gestoppt und danach die Programmierung gestartet. Dann ging es wieder. Ich werd mal das Netzteil auswechseln.
