### ISSUE TITLE
Thread has been blocked

### ISSUE THREAD

**Issue by tuxianerDE** [alexreinert/debmatic#278]
Guten Morgen,

wünsche ein frohes Neues Jahr 2022! Habe einmal das Update von debmatic auf Version 3.61.7.88. Wenn ich das Update eingespielt habe, und in die WebUI wieder gehe, kann ich dort keine Geräte sehen, das System lädt konstant aber schließt dies nicht ab.

Im Syslog, sehe ich folgende Fehlermeldung:```

Jan  1 12:17:44 HOST start_hmserver.sh[20453]: Jan 01, 2022 12:17:44 PM io.vertx.core.impl.BlockedThreadChecker
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: WARNUNG: Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 6260 ms, time limit is 2000
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: io.vertx.core.VertxException: Thread blocked
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at sun.misc.Unsafe.park(Native Method)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$18/15471193.handle(Unknown Source)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.vertx.core.impl.ContextImpl$$Lambda$10/948649.run(Unknown Source)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Jan  1 12:17:44 HOST start_hmserver.sh[20453]: #011at java.lang.Thread.run(Thread.java:748)
Jan  1 12:17:45 HOST start_hmserver.sh[20453]: Jan 01, 2022 12:17:45 PM io.vertx.core.impl.BlockedThreadChecker

```

Lösen konnte ich Problem nur mit einem Downgrade auf meine aktuelle version 3.61.7.86 und dem wieder einspielen des Backups. Muss ich zusätzlich noch einen Java Cache leeren oder ähnliches?

Lg & Danke
Torsten

**Comment by alexreinert** [comment]
Welches Hardware wird verwendet (Funkhardware und System)? Welches OS wird verwendet? Was liefert `debmatic-info`?

**Comment by tuxianerDE** [comment]
Hardware: Raspberry Pi 4 & HM-MOD-RPI-PCB Funkmodul

OS: 
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

debmatic-info kann habe ich einmal laufen gelassen bevor ich das Downgrade durchgeführt habe.
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  REQ0911681
 Radio MAC:     0x71D3E6
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 SGTIN:         3014F711A061A7DBE9975141
 Radio MAC:     0xB63DAE

**Comment by alexreinert** [comment]
Dann brauch ich die vollständigen Logfiles /var/log/syslog und /var/log/hmserver.log und die Datei /var/hm_mode

**Comment by tuxianerDE** [comment]
Ich nehme an, dass ich dafür wieder auf die aktuelle debmatic version upgraden muss, korrekt?

**Comment by alexreinert** [comment]
Ja

**Comment by tuxianerDE** [comment]
issue resolved in latest Version 3.61.7.88
