### ISSUE TITLE
Fehlerhafte Gerätenummer (SGTIN)

### ISSUE THREAD

**Issue by juangamnik** [alexreinert/debmatic#281]
Wenn ich versuche über die Homematic IP App von eQ-3 AG die debmatic-Installation anzubinden über die SGTIN aus `debmatic-info` (respektive aus `/var/hm_mode`), bekomme ich in der App die Fehlermeldung siehe Titel. Raspberry Pi mit debmatic und Handy mit App sind im gleichen Netzwerk.

**Comment by alexreinert** [comment]
Die Homematic IP App funktioniert nur mit der HmIP Cloud und nicht mit einer CCU (egal ob Original CCU3, debmatic, piVCCU oder RasperryMatic).
Es gibt alternative Apps, idealweise mal im Homematic Forum danach suchen, dort kommt die Frage öfter auf.

**Comment by juangamnik** [comment]
Danke!
