### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by 63chris** [alexreinert/debmatic#284]
Hallo,

erst mal Dank und Respekt für die tolle Arbeit.

Musste heute Debmatic neu installieren und bekomme diese Fehlermeldung. Das Zertifikat scheint abgelaufen zu sein.
MfG, Christian

Fehl:8 https://www.debmatic.de/debmatic stable Release                                     
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Fehler bei der Verifizierung des Zertifikats. [IP: 2a01:4f9:2a:da0:7::8 443]
Paketlisten werden gelesen... Fertig                     
E: Das Depot »https://www.debmatic.de/debmatic stable Release« enthält keine Release-Datei.

**Comment by alexreinert** [comment]
Nein, ist es nicht, siehe z.B. #260

**Comment by 63chris** [comment]
that's it. Da muss man erst mal drauf kommen :-)

Herzlichen Dank für die light-speed Hilfe

Christian
