### ISSUE TITLE
HM-MOD-RPI-PCB + HB-RF-USB-2 | RGB Led leuchtet nur Orange

### ISSUE THREAD

**Issue by Kebehsenuef** [alexreinert/debmatic#285]
Huhu Alex

Hab da mal ne Frage.

DietPi: 8.0.2
Debmatic: 3.61.7-88
Angeschlossen ist ein HM-MOD-RPI-PCB über die HB-RF-USB-2 Platine.
System läuft stabil.

Jetzt habe ich Spaßenshalber mal an der USB Platine eine RGB Led angeschlossen.

Diese leuchtet konstant Orange. Sollte die LED nicht angesteuert werden? Oder macht das Debmatic nur wenn es die Charly Platine erkennt. Wenn dem So ist währe es cool wenn man das  Implementieren könnte , das sie die Pins auch bei HM-MOD-RPI-PCB angesteuert werden.

LG Steve

**Comment by alexreinert** [comment]
Die LED wird über das Closed Source Programm von eQ-3 angesteuert, welches die LEDs leider nur ansteuert, wenn ein RPI-RF-MOD angeschlossen ist.

**Comment by Kebehsenuef** [comment]
Ah ok. Danke für die schnelle Antwort. Aber die RGB wird laut Schaltplan von der Pi bedient, diese Befehle müssten dann ja über die USB2 Weitergeleitet werden. Ich nam an des es über die Treiber gehen würde.

Kann man den Extern die Zustände "Standardbetrieb", "Service-Meldung" und "Alarm-Meldung" abrufen? um dann eventuell an der Pi die RGB anzusteuern?

**Comment by alexreinert** [comment]
Sowohl beim Pi, als auch bei der HB-RF-USB-2 werden die LEDs technisch gesehen per GPIO Subsystem vom Linux Kernel angesprochen. Aber das Programm, welches das macht (hss_led), spricht die GPIOs eben nur an, wenn es ein RPI-RF-MOD findet.
Die Zustände kann man per Rega Script abrufen, allerdings scheint das hss_led Programm noch einige Dinge mehr zu prüfen, wie z.B. Internet Connectivity und Verbindungsstatus zu HM Wired oder LAN Gateways.

**Comment by Kebehsenuef** [comment]
Ok dann suche ich mal in richtung regascript. Und ja es kann 11 Zustände anzeigen. Aber Startvorgang,Update und RescueSystem ist eigentlich Irrelevant. Die 3 Zustände wie oben würden mir ausreichen. Danke für die Hilfe, ich such mal ob ich was dazu finde.
