### ISSUE TITLE
Port geändert, seitdem wird die webui fehlerhaft angezeigt und ein anmelden nicht möglich 

### ISSUE THREAD

**Issue by jojojo20104** [alexreinert/debmatic#286]
Hallo,
ich habe auf meinem Raspberry OpenHAB, Phoscon und Debmatic laufen.
Da Poco auf Port :80 läuft habe ich den Port von debmatic auf :8183 in /etc/debmatic/webui.conf geändert.

Seitdem kann ich mich nicht mehr anmelden und sehe nur diese Oberfläche.
![image](https://user-images.githubusercontent.com/98183957/150583575-3ffb2c4c-c233-433e-9e27-033d92da3fcc.png)

Über Hilfe wäre ich sehr dankbar.
Gruß
Jo

**Comment by alexreinert** [comment]
Port 8183 wird intern in debmatic verwendet und sollte daher nicht für die WebUI verwendet werden.

**Comment by jojojo20104** [comment]
Welcher Port wäre den frei?

**Comment by alexreinert** [comment]
8000, 8880, 880, 800.
Wobei ich nicht weiß, ob sich da einer von mit Phoscon beißt. Und ich weiß nicht, ob OpenHAB die WebUI zwingend auf Port 80 erwartet.

**Comment by jojojo20104** [comment]
Es bleibt verzwickt. Leider bekomm ich nur über Port :8183 überhaupt eine Rückmeldung (siehe Bild oben). Über die anderen bekomme ich Browser unabhängig die Rückmeldung, dass "diese Seite ist leider nicht erreichbar"

Kann ich durch die Rückgabe auf Port :8183 auf irgendetwas schließen? Zum Beispiel das Debmatic normal läuft?
oder einen Befehl anhand dessen ich dies überprüfen kann?

debmatic-info gibt mir folgendes zurück
![image](https://user-images.githubusercontent.com/98183957/150590950-ca64dd7e-9400-4d45-9d08-a6cea053c03c.png)

**Comment by alexreinert** [comment]
Neustart nach der Anpassung der Datei hast du gemacht?

**Comment by jojojo20104** [comment]
Ja mehrmals
