### ISSUE TITLE
Firmware Update für HmIP-DLD mir nicht möglich

### ISSUE THREAD

**Issue by juangamnik** [alexreinert/debmatic#288]
Firmware-Version: 3.61.7.89

Auf der Hauptseite wird angezeigt, dass es ein Firmware-Update für ein Gerät gibt. Das kann ich dort als tar-file auch herunterladen:

![image](https://user-images.githubusercontent.com/2939856/153668328-10733a6a-8d3c-48b7-a01b-d038db731fe3.png)

Aber wenn ich unter "Einstellungen -> Geräte Firmware - Überisicht" schaue ist dort keine neuere Firmware auf der CCU:

![image](https://user-images.githubusercontent.com/2939856/153668610-8bf135cf-5583-419a-92da-89f72ae3378a.png)

Den zuvor genannten tar-File unter "Geräte-Firmware -> Neu" hochzuladen führt nur zu einer Fehlermeldung (auch wenn ich es mit der .efw-Datei in dem Tarball versuche):

![image](https://user-images.githubusercontent.com/2939856/153668830-eb18d358-f7f3-4861-a7ba-82c9ec3ca296.png)

Mache ich etwas falsch?

**Comment by alexreinert** [comment]
Das ist keine .tar Datei, sondern .tar.gz bzw. .tgz
Diese darf nicht entpackt werden vor dem Hochladen. Vermutlich nutzt du einen Safari Browser, welcher standardmäsig ohne Nachfrage die Dateien entpackt, diese Funktion muss deaktivert werden.

**Comment by juangamnik** [comment]
Ja das siehst du richtig :). Ich habe mal via `tar -czf HmIP-DLD.tar.gz HmIp-DLD/` wieder alles gepackt (habe auch die Endung tgz versucht) aber er akzeptiert es dennoch nicht.

**Comment by juangamnik** [comment]
Habe es noch mal mit dem Chrome versucht... klappt. Ist das der normale Weg für die Updates? Download->Upload->Update? Also man geht immer den "Umweg" über den Download auf den lokalen Rechner?

**Comment by juangamnik** [comment]
Wie bei meinem letzten Problem: Super schnell, super Service. Ich donate again!

**Comment by alexreinert** [comment]
> Habe es noch mal mit dem Chrome versucht... klappt. Ist das der normale Weg für die Updates? Download->Upload->Update? Also man geht immer den "Umweg" über den Download auf den lokalen Rechner?

Aktuell ja, das ist der Weg, wie eQ-3 das in der CCU3 vorgesehen hat und ich habe bisher noch nicht die Zeit gefunden, das in debmatic umzubauen.

**Comment by juangamnik** [comment]
Ah, ok. Danke @alexreinert.
