### ISSUE TITLE
Kein löschen/bearbeiten von Homematic geräten

### ISSUE THREAD

**Issue by neodata83** [alexreinert/debmatic#29]
Wie im Titel beschrieben habe ich Probleme mit dem Bearbeiten/löschen von normalen Homematic Geräten z.B. HM-PBI-4-FM. beim bearbeiten kommt immer 

`Das Gerät mit der Seriennummer 'OEQXXXXXXX' vom Interface 'RemoteApi' konnte nicht abgefragt werden! `

debmatic läuft in einer VM mit debian 9.9 x86 und HB-RF-USBmit dem Funkmodul RPI-RF-MOD

edit

Hab auch ein form post im Homematicforum

https://homematic-forum.de/forum/viewtopic.php?f=81&t=51667

und hier nochmal der link zu den log dateien

https://share.mailbox.org/ajax/share/0d27a71a039d114dd57b36239d1148f48f95b28e3eebd843/1/8/NTk 

pw: debmatic1973

**Comment by alexreinert** [comment]
Ich kann im Log leider nur erkennen, dass es ein Problem gibt, aber nicht woher es genau kommt. Wurden die Geräte innerhalb von debmatic angelernt, oder wurde ein Backup aus einem anderen System eingespielt? Wenn ja, aus welchem System kam das Backup? Könnte ich das Backup ggf. haben um da mal reinzuschauen?

**Comment by neodata83** [comment]
Geräte wurden neu angelernt da ich vorher ne Raspmatic im einsatz hatte und kein einspielen des Backups möglich war. Link für das Backup ist im email Postfach.
