### ISSUE TITLE
debmatic restarts with actors in OFF position

### ISSUE THREAD

**Issue by raidboy** [alexreinert/debmatic#290]
Debian 11 (bullseye) on NUC style x86/amd64 system. Debmatic 3.61.7-89, HMIP-RFUSB 4.4.16.
Installed according to doc for devmatic.
Installed few HmIP-eTRV-2, HmIP-WTH-2 and HmIP-eTRV-B. Configured them to operate in "Manu Mode".

a) Restarting debmatic: "systemctl stop debmatic ; systemctl start debmatic"

or:

b) Reboot system

or

c) Creating backup (while devices are in Manu mode), and then restoring this backup)

Results in all devices to show up in CCU as being in "Off" status.

I think this is a bug because i have not experienced the same with RaspberryMatic.
But i am a CCU novice, so maybe there is something simple i am overlooking.

**Comment by alexreinert** [comment]
Reicht es dir nicht, wenn ich das einmal beantworte? Siehe: https://homematic-forum.de/forum/viewtopic.php?f=81&t=72720#p706360
