### ISSUE TITLE
Debmatic in LXC

### ISSUE THREAD

**Issue by AFPass** [alexreinert/debmatic#291]
Hallo,

ich bekomme leider mein Debmatic leider nicht zum laufen im LXC Container.
Das Modul HB-RF-USB wird nicht gefunden.

Bei der Installation von den Host Paketen im Proxmox bekomme ich einen Fehler:
`root@pve:~# apt install pivccu-modules-dkms debmatic-lxc-host --reinstall 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 43.5 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://www.debmatic.de/debmatic stable/main amd64 pivccu-modules-dkms all 1.0.71 [41.7 kB]
Get:2 https://www.debmatic.de/debmatic stable/main amd64 debmatic-lxc-host all 1.0.5 [1,872 B]
Fetched 43.5 kB in 0s (152 kB/s)              
Preconfiguring packages ...
(Reading database ... 113445 files and directories currently installed.)
Preparing to unpack .../pivccu-modules-dkms_1.0.71_all.deb ...
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

------------------------------
Deleting module version: 1.0.71
completely from the DKMS tree.
------------------------------
Done.
Unpacking pivccu-modules-dkms (1.0.71) over (1.0.71) ...
Preparing to unpack .../debmatic-lxc-host_1.0.5_all.deb ...
Unpacking debmatic-lxc-host (1.0.5) over (1.0.5) ...
Setting up pivccu-modules-dkms (1.0.71) ...
Error! The module/version combo: pivccu-1.0.71
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.71/source ->
                 /usr/src/pivccu-1.0.71

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.13.19-4-pve ARCH=x86 all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.19-4-pve (x86_64)
Consult /var/lib/dkms/pivccu/1.0.71/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Setting up debmatic-lxc-host (1.0.5) ...
root@pve:~#`

Liegt es daran?
Error! The module/version combo: pivccu-1.0.71
is not located in the DKMS tree.

**Comment by AlexanderS** [comment]
Das hier ist der Fehler:

```
make -j4 KERNELRELEASE=5.13.19-4-pve ARCH=x86 all...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.19-4-pve (x86_64)
```

aus irgendeinem Grund können die Kernelmodule nicht compiliert werden. Du kannst mal in `/var/lib/dkms/pivccu/1.0.71/build/make.log` gucken was der Fehler ist.
