### ISSUE TITLE
Proxmox Kernel Problem LXC Container

### ISSUE THREAD

**Issue by hail0** [alexreinert/debmatic#296]
Hallo zusammen,

ich bekomme bei der Installation von Debmatic in einem Proxmox LXC eine Fehlermeldung.
Hat jemand ähnliche Probleme und falls ja, wie habt Ihr Sie gelöst.

Proxmoxversion:
![grafik](https://user-images.githubusercontent.com/26676301/161422290-44f0afd1-a45b-4b9d-8d7c-f497c1b84e4a.png)

Fehlermeldung Debmatic:
![grafik](https://user-images.githubusercontent.com/26676301/161422259-93894059-444d-4f70-ad7d-3ef95702dd56.png)

Grüße hail0

**Comment by claymore666** [comment]
bei einem LXE Container wird der Kernel des Hosts verwendet. Hast du das [hier] befolgt? (https://github.com/alexreinert/debmatic/blob/master/docs/setup/proxmox.md)

Die Kernelmodule (pve-headers) müsse auf dem Host (Proxmox) installiert werden, nicht im Container!
Siehe auch [hier ](https://homematic-forum.de/forum/viewtopic.php?t=52710)Alex Kommentar.

**Comment by mackshot** [comment]
@hail0 Schau mal hier rein #300 . Möglicherweise ist das bei Dir ja auch das Problem!

**Comment by Tuxtom007** [comment]
Hallo,

ich habe derzeit das selbe Problem:
Die Kernel-Header werden nicht gefunden - ich Proxmox Version 7.2

`DKMS: add completed.
Error! Your kernel headers for kernel 5.15.30-2-pve cannot be found.
Please install the linux-headers-5.15.30-2-pve package,`

Bin gerade schon soweit, das ich wieder von debmativ weg zu Rapsmatic gehen will und das Funkmodul versuche, wieder per USB zum laufen zu bekommen.

**Comment by Tuxtom007** [comment]
Schon klar, RaspberryMatic hatte ich vorher schon als fertiges Proxmox-VM-Image genutzt, allerdings hab ich die Hardware des Proxmox-Server ausgetauscht und danach keine Verbindung mehr zum externe USB-Modul bekommen, obwohl das Modul im Proxmox erkannt und der VM zugewiesen war.
Evtl. ein Problem mit USB3.0, aber weiss ich noch nicht.

Debmatic in einer VM zu nutzen währe aber noch eine gute Option, das hab ich noch nicht probiert, werde ich mal testen. Wenns Ethernet-Modul dann geht, sogar die bessere Lösung.
