### ISSUE TITLE
callback in debmatic-rfd funktioniert nicht, wenn man als Adresse einen Hostnamen angibt

### ISSUE THREAD

**Issue by FernetMenta** [alexreinert/debmatic#297]
Hallo,

ich habe eine frische Installation von debmatic auf Raspberry Pi mit Bullseye. Dazu habe ich iobroker installiert. 2 Versuche, einmal mit Docker auf dem Pi, einmal auf einem anderen System: gleiches Verhalten.
Wenn ich im hm-rpc Adapter als Callback den Namen des Host angebe, z.B. "pi-home" oder "nuc8", funktioniert der rpc Call von debmatic zu iobroker nicht. Wenn ich die ipv4 Adresse des Adapters angebe, z.B. 127.0.0.1, funktioniert es.

Sieht für mich so aus, als kommt da was mit ipv4 / ipv6 durcheinander. 

Gruß,
Rainer

**Comment by alexreinert** [comment]
Der rfd ist Closed Source von eQ-3. Da kann ich leider nichts dran ändern.

**Comment by FernetMenta** [comment]
Schade, trotzdem danke für die schnelle Antwort. Zum Glück gibt es ja einen Workaround.
