### ISSUE TITLE
HM-MOD-RPI-PCB mit Rock PI 4B funktioniert unter Armbian nicht 

### ISSUE THREAD

**Issue by J108560** [alexreinert/debmatic#298]
Hallo Alex,

auf meinem Rock PI 4B wird das "kleine" Funkmodul nicht erkannt. Defekt ist es nicht, im Raspi funktioniert es. Die Installation erfolgt unter Armbian 22.05.0  with Linux 5.15.25-rockchip64. Das "große" RPI-RF-MOD wird hingegen problemlos eingebunden und ist auch funktional. Die Installation scheint somit OK zu sein. Ich habe auch verschiedene Images (Buster, Focal) ausprobiert, das Verhalten ist überall gleich.

debmatic version: 3.63.8-91
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown

Eventuell kannst Du mir ja einen Tip geben?

Gruß Sven

**Comment by J108560** [comment]
Hi,

alle Armbian Kernel nach 5.10. funktionieren nicht. Da scheint sich was im Aufbau geändert zu haben. Ich habe jetzt die Kernelversion eingefroren. Ist aber auf Dauer sicherlich keine Lösung.
Update bzgl. RPI-RF-MOD: Wird zwar mit Kernel 5.15. erkannt (in der WEB Oberfläche ist der Balken da). es funktioniert aber nicht. Anlernen und Statusupdate der Komponenten tun nicht.

**Comment by J108560** [comment]
Hallo,

kann ich denn noch mit Hilfe rechnen? Hat jemand Debmatic auf einem RockPI 4/Rockchip3399 mit dem HM-MOD-RPI-PCB auf der GPIO Leiste am laufen?

**Comment by J108560** [comment]
Hi, kann geschlossen werden, Ich habe nun selbst die Module RPI-RF-MOD und HM-MOD-RPI-PCB auf dem Rock 4 und dem Rock 3A ans laufen gebracht.

**Comment by drschnalli** [comment]
Wie hast du es zum laufen bekommen? Ich hab mir grad auch eines geordert... und hab angst, dass es nicht funktioniert... So wie bei mir auch OLED Displays und so weiter nicht funktionieren an der Pinleiste...  Bin mittlerweile auf Armbian Bullseye. 

Grüße

**Comment by J108560** [comment]
Problem ist, dass ab Kernel 5.15 die I2S1 Schnittstelle (2CH Audio) den Reset-PIN des Moduls blockiert. Ich habe das so gelöst, dass ich mir ein eigenes Paket pivccu-devicetree-armbian gebastelt habe und i2s@ff890000 deaktiviert habe.

**Comment by huwi** [comment]
hallo zusammen.

dank dem tipp von J108560 mit dem i2s1 konnte ich das hm-mod-rpi-pcb zu laufen bringen.

installiertes armbian auf rockpi4b:
_VERSION_ID="11"
VERSION="11 (bullseye)"_
uname -a
_**Linux hostname 5.15.48-rockchip64 #22.05.3 SMP PREEMPT Wed Jun 22 07:27:54 UTC 2022 aarch64 GNU/Linux**_

ich habe folgendes gemacht:
0. debmatic stoppen
_systemctl stop debmatic_
2. getty abschalten ttyS2:
_systemctl --now disable serial-getty@ttyS2
systemctl mask serial-getty_

3. i2s1 deaktivieren
_cd /var/lib/piVCCU/dts_
datei rockpi4.dts.include anpassen -> 

  i2s@ff890000 {
    status = "disabled";
  };

dann die scripts aufrufen:
_./revert_dts.sh
./patch_dts.sh_
4. testen
_detect_radio_module --debug /dev/raw-uart_
das board antwortet jetzt.
5. debmatic wieder starten (und 1-2 minuten warten)
systemctl start debmatic
6. noch ein test
_debmatic-info_
die board-daten sind jetzt abrufbar.

schoene gruesse, hubert

**Comment by J108560** [comment]
Nachdem mir monatelang keiner geholfen hat und jetzt die Lösung auf dem Silbertablett liegt, ist sie nun bereits in die DTS des Installationspakets integriert. War mir eine  Ehre zu helfen....

**Comment by drschnalli** [comment]
Ich hoffe ich bekomme es auch irgendwie hin... weiß gar nicht welche Sources ich nehmen soll usw :( bin da total überfordert.

**Comment by drschnalli** [comment]
Wie bewerkstellige ich das mit dem i2s? Ich denke, dass das damals auch der Grund war... weshalb mein Mysensors Modul nicht funktioniert hat. Und ebenfalls auch nicht das Oled Display... weil dort schlichtweg was blockiert ist.

**Comment by huwi** [comment]
Hallo drschnalli.

Es geht darum, die I2S1 Schnittstelle zu deaktivieren. 

Ich habe meine Beschreibung wohl doch etwas zu kurz gehalten:-(
Auf meinem System ist in der Datei **/var/lib/piVCCU/dts/rockpi4.dts.include** der Block bereits enthalten.

_i2s@ff890000 { status = "enabled"; };_

dieser muss einfach auf disabled geändert werden.
Wenn der Block fehlt, dann den Block am Ende der Datei ergaenzen.

Schöne Grüße und viel Erfolg, Hubert

**Comment by drschnalli** [comment]
Hallo Hubert, ich hab nun alles gemacht was du beschrieben hast. 

`root@rockpi-4b:~# detect_radio_module --debug /dev/raw-uart
15:01:45.451173 Sending HM frame:  fd 00 03 fe 00 01 14 1e
15:01:48.451527 Sending HM frame:  fd 00 03 00 01 00 9e 03
15:01:51.451809 Sending HM frame:  fd 00 03 fe 02 01 98 1d
^C
root@rockpi-4b:~# systemctl start debmatic
root@rockpi-4b:~# debmatic-info
debmatic version: 3.63.9-93
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
`

Heißt denn "Sending HM frame", dass das Modul denn erkannt wird und etwas sendet?

**Comment by huwi** [comment]
hallo drschnalli!

es freut mich dass du es geschafft hast. du kannst auch einfach die neueste version von pivccu-devicetree-armbian installieren. da wurde die aenderung beeits eingebaut.

ich habe keine spenden-adresse. schicke doch lieber was an das dembatic-team. die haben es wirklich verdient. 

ich denke dein erster test hat vielleicht nicht funktioniert, da ev. noch debmatic nach einem reboot gelaufen ist. das habe ich in der beschreibung vergessen. denn wenn debmatic daemons (multimacd) aktiv sind, dann fressen die die received-frames weg. vor detect... immer zuerst "systemctl stop debmatic" machen.

mit folgenden befehl kannst du ueberpruefen, ob noch ein anderes programm mit dem modul schwaetzt:

> fuser /dev/raw-tty

wenn eine nummer zurückkommt, dann ist noch ein programm am laufen. dann mit:

> ps -fp <nummer>

kannst du nachschauen, welches programm noch läuft.


viel spass mit deiner home-matic installation.

schöne grüße, hubert

**Comment by drschnalli** [comment]
Seit heute funktioniert mein HM-MOD-RPI-PCB seltsamerweise nicht mehr... ich musste den Rock Pi 4B eben mal vom Strom trennen.. danach fiel mir auf, dass es im bei debmatic-info das Modul nicht mehr anzeigt... Wie kann ich dessen Funktion noch auf anderem Wege testen? Durchaus habe ich in letzter Zeit Updates installiert..
