### ISSUE TITLE
Fehlermeldung apt-get update

### ISSUE THREAD

**Issue by Goersch** [alexreinert/debmatic#30]
Hallo,

was mach ich mit so einer Fehlermeldung von apt-get update? (ubuntu 19.04)

> E: Repository 'https://www.debmatic.de/debmatic stable InRelease' changed its 'Origin' value from 'piVCCU stable' to 'Alexander Reinert'
> E: Repository 'https://www.debmatic.de/debmatic stable InRelease' changed its 'Label' value from 'piVCCU stable' to 'smarthome'

Danke 
Georg

**Comment by alexreinert** [comment]
Hi,

öfter updaten, die Anpassung ist echt scho  lange her. ;-)

Einfach mit Yes bestätigen, kommt nur einmal. Und idealerweise apt statt apt-get nutzen, das macht ein paar Dinge besser, wenn es um Auflösung von Abhängikeiten geht.

Viele Grüße
Alex

**Comment by Goersch** [comment]
Danke - das ist die Installation die auf die cloudmatic VPN Anbindung wartet ;) Werd ich wohl auch mal öfter aktualisieren müssen.
