### ISSUE TITLE
Problem installing debmatic on RPI4, 64Bit

### ISSUE THREAD

**Issue by huwi** [alexreinert/debmatic#301]
Hi Alex.
Installing debmatic in RPI4 64Bit:

dpkg: error processing archive debmatic_3.63.8-91_arm64.deb (--install):
 trying to overwrite '/lib/ld-linux-armhf.so.3', which is also in package libc6:armhf 2.31-13+rpt2+rpi1+deb11u2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 debmatic_3.63.8-91_arm64.deb

Kind Regards, Hubert

**Comment by huwi** [comment]
Hi Alex.
I have traced the startup routines.
So i find the following behavor:

---
<style>
body { font-family: Courier; font-size: 0.3cm }
</style>
cd /usr/share/debmatic/bin
bash -x initsystem.sh -> ifup.sh -> hangs ->
IFACE=eth0 bash -x ifup.sh ->  eq3configcmd netconfigcmd ... -> hangs.
strace  eq3configcmd netconfigcmd -i 192.168.42.74 -g 192.168.42.4 -n 255.255.255.0 -d1 '' -d2 ''
-> here we can see the systemcall:
futex(0xf7db2564, FUTEX_LOCK_PI_PRIVATE, NULL) = -1 EDEADLK (Resource deadlock avoided)
futex(0xffcdb950, FUTEX_WAIT_PRIVATE, 0, NULL^C) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
---

Can you work with this informations?
Kind Regards, Hubert

**Comment by huwi** [comment]
thank you, no problem anymore ....

**Comment by mayonezo** [comment]
What did you do to fix it?
