### ISSUE TITLE
cuxd: missing update to current version 2.9

### ISSUE THREAD

**Issue by disaster123** [alexreinert/debmatic#303]
Current version is 2.9: https://homematic-forum.de/forum/viewtopic.php?f=37&t=15298

debmatic still provides 2.6

Would be great to get an update.

**Comment by disaster123** [comment]
Still valid

**Comment by disaster123** [comment]
Wrongly closed

**Comment by disaster123** [comment]
Still valid

**Comment by alexreinert** [comment]
I release an update with version 2.10 in the testing respository, see also commit 55dc40e.
