### ISSUE TITLE
Option "Authentifizierung Aktiv" funktioniert anscheinend nicht.

### ISSUE THREAD

**Issue by Thuffir** [alexreinert/debmatic#304]
Aktuelle Software-Version:3.65.6.94
Ich habe diese Option eingeschaltet, kann aber trotzdem weiterhin mit FHEM ohne Angabe von User / Passwort zugreifen.

**Comment by alexreinert** [comment]
Lokal oder remote? Der lokale Zugriff kann nicht verhindert werden bei der Architektur der CCU3 Software, kann aber auch weitgehend unkritisch angesehen werden.

**Comment by Thuffir** [comment]
Lokal. Danke das erklärt alles.
