### ISSUE TITLE
Kein Zugriff auf Weboberfläche - A dependency job for debmatic-lighttpd.service failed

### ISSUE THREAD

**Issue by mstreng411** [alexreinert/debmatic#305]
System:
Raspberry Pi 4
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian

Nach einem Update bekomme ich keinen Zugriff auf die Weboberfläche mehr. Bei debmatic-lighttpd.service kommt die Fehlermeldung: : Job debmatic-lighttpd.service/start failed with result 'dependency

list-dependencies ergibt folgendes:

● ├─debmatic-eq3configd.service
ROT ● ├─debmatic-hmserver.service ROT
● ├─debmatic-hs485d.service
● ├─debmatic-hssled.service
● ├─debmatic-lighttpd.service
● ├─debmatic-monitor-hb-rf-eth.service
● ├─debmatic-multimacd.service
● ├─debmatic-prepareinterfaceslist.service
● ├─debmatic-rega.service
ROT ● ├─debmatic-rfd.service ROT
● ├─debmatic-setinterfaceclock.timer
● ├─debmatic-ssdpd.service
● ├─debmatic-startupfinished.service
● ├─debmatic-updatelgwfirmware.service
● ├─debmatic-updatelgwkey.service
● ├─debmatic-updaterffirmware.service
● ├─pivccu-dkms.service
● ├─system.slice
● └─sysinit.target
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─fake-hwclock.service
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─plymouth-read-write.service
●   ├─plymouth-start.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
ROT ●   ├─systemd-modules-load.service ROT
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot.mount
●   │ ├─systemd-fsck-root.service
●   │ └─systemd-remount-fs.service
●   └─swap.target

journalctl -xe:

Aug 19 13:08:55 kali-smartcontrol systemd[1]: debmatic-hmserver.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd

--
-- The unit debmatic-hmserver.service has entered the 'failed' state with result 'exit-code'.
Aug 19 13:08:55 kali-smartcontrol systemd[1]: Failed to start debmatic hmserver.
-- Subject: A start job for unit debmatic-hmserver.service has failed
-- Defined-By: systemd

--
-- A start job for unit debmatic-hmserver.service has finished with a failure.
--
-- The job identifier is 130750 and the job result is failed.
Aug 19 13:08:55 kali-smartcontrol systemd[1]: Starting debmatic rega...
-- Subject: A start job for unit debmatic-rega.service has begun execution
-- Defined-By: systemd

--
-- A start job for unit debmatic-rega.service has begun execution.
--
-- The job identifier is 130686.
Aug 19 13:08:56 kali-smartcontrol add_fw_block.sh[5772]: iptables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol add_fw_block.sh[5772]: ip6tables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol add_fw_block.sh[5772]: iptables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol add_fw_block.sh[5772]: ip6tables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol systemd[1]: debmatic-rega.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd

--
-- An ExecStartPre= process belonging to unit debmatic-rega.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Aug 19 13:08:56 kali-smartcontrol delete_fw_block.sh[5791]: iptables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol delete_fw_block.sh[5791]: ip6tables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol delete_fw_block.sh[5791]: iptables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol delete_fw_block.sh[5791]: ip6tables/1.8.2 Failed to initialize nft: Protocol not supported
Aug 19 13:08:56 kali-smartcontrol systemd[1]: debmatic-rega.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd

-- An ExecStopPost= process belonging to unit debmatic-rega.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Aug 19 13:08:56 kali-smartcontrol systemd[1]: debmatic-rega.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd

--
-- The unit debmatic-rega.service has entered the 'failed' state with result 'exit-code'.
Aug 19 13:08:56 kali-smartcontrol systemd[1]: Failed to start debmatic rega.
-- Subject: A start job for unit debmatic-rega.service has failed
-- Defined-By: systemd

--
-- A start job for unit debmatic-rega.service has finished with a failure.
--
-- The job identifier is 130686 and the job result is failed.
Aug 19 13:08:59 kali-smartcontrol sudo[5857]: openhabian : TTY=pts/0 ; PWD=/home/openhabian ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Aug 19 13:08:59 kali-smartcontrol sudo[5857]: pam_unix(sudo:session): session opened for user root by openhabian(uid=0)

 **lighttpd.service - Lighttpd Daemon**
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2022-08-19 13:12:03 CEST; 58ms ago
  Process: 11667 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
  Process: 11673 ExecStart=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf (code=exited, status=255/EXCEPTION)
 Main PID: 11673 (code=exited, status=255/EXCEPTION)

**Die Debmatic Weboberfläche läuft bei mir wegen Deconz auf Port 8085, das war aber bisher kein Problem. Mir fehlt gerade der Ansatz wo ich nach Fehlern suchen kann. Gruß Micha**

**Comment by alexreinert** [comment]
IPv6 wieder aktivieren

**Comment by mstreng411** [comment]
Generell, oder in den configs von lighttpd?
Ich habe nichts deaktiviert, daher weiß ich nicht wo ich wieder was aktivieren muss. 
Woran hast Du das erkannt? Sorry für die dummen Fragen…
Gruß Micha

**Comment by alexreinert** [comment]
Generell z.b. per Eintrag in den Kernel Boot Parametern in der /boot/cmdline.txt.
Ich habe den Verdacht aufgrund der nftables Fehlermeldungen.
