### ISSUE TITLE
Fehlermeldung nach aktuellem Update

### ISSUE THREAD

**Issue by meier81** [alexreinert/debmatic#306]
Hallo Alex,

ich bekomme leider beim heutigen Update eine Fehlermeldung vom dpkg. Hier mal der Shell-Auszug:

`Vorbereitung zum Entpacken von .../debmatic_3.65.8-95_amd64.deb ...
Removed /etc/systemd/system/debmatic.service.wants/debmatic-setinterfaceclock.timer.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-eq3configd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-eq3configd.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hmserver.service.
Removed /etc/systemd/system/debmatic-rega.service.wants/debmatic-hmserver.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-hmserver.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hs485d.service.
Removed /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-hs485d.service.
Removed /etc/systemd/system/debmatic-rega.service.wants/debmatic-hs485d.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-hs485d.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hssled.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-hssled.service.
Removed /etc/systemd/system/debmatic-hs485d.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic-rfd.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic-rega.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-lighttpd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-monitor-hb-rf-eth.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-multimacd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-multimacd.service.
Removed /etc/systemd/system/debmatic-rfd.service.requires/debmatic-multimacd.service.
Removed /etc/systemd/system/debmatic-lighttpd.service.wants/debmatic-prepareinterfaceslist.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-prepareinterfaceslist.service.
Removed /etc/systemd/system/debmatic-updatelgwfirmware.service.wants/debmatic-prepareinterfaceslist.service.
Removed /etc/systemd/system/debmatic-rega.service.wants/debmatic-prepareinterfaceslist.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-prepareinterfaceslist.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-rega.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-rega.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-rfd.service.
Removed /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-rfd.service.
Removed /etc/systemd/system/debmatic-rega.service.wants/debmatic-rfd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-rfd.service.
Removed /etc/systemd/system/multi-user.target.wants/debmatic.service.
Removed /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-ssdpd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-ssdpd.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-startupfinished.service.
Removed /etc/systemd/system/debmatic-rfd.service.wants/debmatic-updatelgwfirmware.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-updatelgwfirmware.service.
Removed /etc/systemd/system/debmatic-updatelgwkey.service.wants/debmatic-updatelgwfirmware.service.
Removed /etc/systemd/system/debmatic-rfd.service.wants/debmatic-updatelgwkey.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-updatelgwkey.service.
Removed /etc/systemd/system/debmatic.service.wants/debmatic-updaterffirmware.service.
Removed /etc/systemd/system/debmatic-multimacd.service.wants/debmatic-updaterffirmware.service.
Disabling debmatic
Run "service lighttpd force-reload" to enable changes
Entpacken von debmatic (3.65.8-95) über (3.65.6-94) ...
Vorbereitung zum Entpacken von .../pivccu-modules-dkms_1.0.78_all.deb ...
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.77
Kernel:  5.10.0-16-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb_2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-16-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  pivccu
Version: 1.0.77
Kernel:  5.10.0-17-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb_2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.10.0-17-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod......

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.77
completely from the DKMS tree.
------------------------------
Done.
Entpacken von pivccu-modules-dkms (1.0.78) über (1.0.77) ...
debmatic (3.65.8-95) wird eingerichtet ...
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-eq3configd.service → /lib/systemd/system/debmatic-eq3configd.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-eq3configd.service → /lib/systemd/system/debmatic-eq3configd.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-hmserver.service → /lib/systemd/system/debmatic-hmserver.service.
Created symlink /etc/systemd/system/debmatic-rega.service.wants/debmatic-hmserver.service → /lib/systemd/system/debmatic-hmserver.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hmserver.service → /lib/systemd/system/debmatic-hmserver.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-hs485d.service → /lib/systemd/system/debmatic-hs485d.service.
Created symlink /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-hs485d.service → /lib/systemd/system/debmatic-hs485d.service.
Created symlink /etc/systemd/system/debmatic-rega.service.wants/debmatic-hs485d.service → /lib/systemd/system/debmatic-hs485d.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hs485d.service → /lib/systemd/system/debmatic-hs485d.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-hssled.service → /lib/systemd/system/debmatic-hssled.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-hssled.service → /lib/systemd/system/debmatic-hssled.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic-rfd.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic-hs485d.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic-rega.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-lighttpd.service → /lib/systemd/system/debmatic-lighttpd.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-monitor-hb-rf-eth.service → /lib/systemd/system/debmatic-monitor-hb-rf-eth.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-multimacd.service → /lib/systemd/system/debmatic-multimacd.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-multimacd.service → /lib/systemd/system/debmatic-multimacd.service.
Created symlink /etc/systemd/system/debmatic-rfd.service.requires/debmatic-multimacd.service → /lib/systemd/system/debmatic-multimacd.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-prepareinterfaceslist.service → /lib/systemd/system/debmatic-prepareinterfaceslist.service.
Created symlink /etc/systemd/system/debmatic-lighttpd.service.wants/debmatic-prepareinterfaceslist.service → /lib/systemd/system/debmatic-prepareinterfaceslist.service.
Created symlink /etc/systemd/system/debmatic-rega.service.wants/debmatic-prepareinterfaceslist.service → /lib/systemd/system/debmatic-prepareinterfaceslist.service.
Created symlink /etc/systemd/system/debmatic-updatelgwfirmware.service.wants/debmatic-prepareinterfaceslist.service → /lib/systemd/system/debmatic-prepareinterfaceslist.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-prepareinterfaceslist.service → /lib/systemd/system/debmatic-prepareinterfaceslist.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-rega.service → /lib/systemd/system/debmatic-rega.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-rega.service → /lib/systemd/system/debmatic-rega.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-rfd.service → /lib/systemd/system/debmatic-rfd.service.
Created symlink /etc/systemd/system/debmatic-hmserver.service.wants/debmatic-rfd.service → /lib/systemd/system/debmatic-rfd.service.
Created symlink /etc/systemd/system/debmatic-rega.service.wants/debmatic-rfd.service → /lib/systemd/system/debmatic-rfd.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-rfd.service → /lib/systemd/system/debmatic-rfd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/debmatic.service → /lib/systemd/system/debmatic.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-ssdpd.service → /lib/systemd/system/debmatic-ssdpd.service.
Created symlink /etc/systemd/system/debmatic-startupfinished.service.wants/debmatic-ssdpd.service → /lib/systemd/system/debmatic-ssdpd.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-startupfinished.service → /lib/systemd/system/debmatic-startupfinished.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-updatelgwfirmware.service → /lib/systemd/system/debmatic-updatelgwfirmware.service.
Created symlink /etc/systemd/system/debmatic-updatelgwkey.service.wants/debmatic-updatelgwfirmware.service → /lib/systemd/system/debmatic-updatelgwfirmware.service.
Created symlink /etc/systemd/system/debmatic-rfd.service.wants/debmatic-updatelgwfirmware.service → /lib/systemd/system/debmatic-updatelgwfirmware.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-updatelgwkey.service → /lib/systemd/system/debmatic-updatelgwkey.service.
Created symlink /etc/systemd/system/debmatic-rfd.service.wants/debmatic-updatelgwkey.service → /lib/systemd/system/debmatic-updatelgwkey.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-updaterffirmware.service → /lib/systemd/system/debmatic-updaterffirmware.service.
Created symlink /etc/systemd/system/debmatic-multimacd.service.wants/debmatic-updaterffirmware.service → /lib/systemd/system/debmatic-updaterffirmware.service.
Created symlink /etc/systemd/system/debmatic.service.wants/debmatic-setinterfaceclock.timer → /lib/systemd/system/debmatic-setinterfaceclock.timer.
Enabling debmatic: ok
Run "service lighttpd force-reload" to enable changes
Job for debmatic.service failed because a fatal signal was delivered to the control process.
See "systemctl status debmatic.service" and "journalctl -xe" for details.
dpkg: Fehler beim Bearbeiten des Paketes debmatic (--configure):
 »installiertes debmatic-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
pivccu-modules-dkms (1.0.78) wird eingerichtet ...
Error! The module/version combo: pivccu-1.0.78
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.78/source ->
                 /usr/src/pivccu-1.0.78

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j2 KERNELRELEASE=5.10.0-17-amd64 ARCH=x86 all........
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

hb_rf_usb_2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-17-amd64/updates/dkms/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Fehler traten auf beim Bearbeiten von:
 debmatic
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by meier81** [comment]
Hallo Alex,

hast du eine Idee bezüglich dem Fehler?
Die Meldung kommt bei jeden Update und ich habe leider aktuell keine Idee mehr wo ich noch schauen könnte, vielleicht könntest du mir hier etwas weiterhelfen.

Gruß Markus

**Comment by peterfido** [comment]
Steht ja dort, wo Du gucken könntest:
`Run "service lighttpd force-reload" to enable changes
Job for debmatic.service failed because a fatal signal was delivered to the control process.
See "systemctl status debmatic.service" and "journalctl -xe" for details.
dpkg: Fehler beim Bearbeiten des Paketes debmatic (--configure):`

**Comment by meier81** [comment]
Gelesen habe ich das ja auch, ich finde dort aber nichts. Hier die Ausgabe vom systemctl status debmatic.service:

`admin@debian:~$ systemctl status debmatic.service
● debmatic.service - debmatic
     Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
     Active: active (exited) since Thu 2022-11-03 16:27:05 CET; 3 weeks 2 days ago
   Main PID: 481 (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 2340)
     Memory: 0B
        CPU: 0
     CGroup: /system.slice/debmatic.service

Warning: some journal files were not opened due to insufficient permissions.`

Und bei sudo journalctl -xe bekomme ich folgendes:

`admin@debian:~$ sudo journalctl -xe
Nov 27 10:57:25 debian influxd-systemd-start.sh[437]: ts=2022-11-27T09:57:25.502789Z lvl=info msg="Retention policy deletion check (start)" log_id=0dwXU_Dl000 service=retention>
Nov 27 10:57:25 debian influxd-systemd-start.sh[437]: ts=2022-11-27T09:57:25.503107Z lvl=info msg="Retention policy deletion check (end)" log_id=0dwXU_Dl000 service=retention o>
Nov 27 10:58:06 debian sudo[734422]:    admin : TTY=pts/0 ; PWD=/home/fhem ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Nov 27 10:58:06 debian sudo[734422]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
Nov 27 10:58:32 debian sudo[734422]: pam_unix(sudo:session): session closed for user root
Nov 27 10:58:40 debian sudo[734439]:    admin : TTY=pts/0 ; PWD=/home/fhem ; USER=root ; COMMAND=/usr/bin/apt full-upgrade
Nov 27 10:58:40 debian sudo[734439]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
Nov 27 10:58:46 debian systemd[1]: Reloading.
Nov 27 10:58:46 debian systemd-udevd[734482]: Using default interface naming scheme 'v247'.
Nov 27 10:58:46 debian systemd-logind[424]: Watching system buttons on /dev/input/event4 (Power Button)
Nov 27 10:58:47 debian systemd-logind[424]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
Nov 27 10:58:47 debian systemd[1]: Reloading.
Nov 27 10:58:47 debian systemd[1]: Reloading.
Nov 27 10:58:48 debian systemd[1]: Reloading.
Nov 27 10:58:48 debian systemd[1]: Reloading.
Nov 27 10:58:48 debian systemd[1]: Reloading.
Nov 27 10:58:49 debian systemd[1]: Reloading.
Nov 27 10:58:49 debian systemd[1]: Reloading.
Nov 27 10:58:50 debian systemd[1]: Reloading.
Nov 27 10:58:50 debian systemd[1]: Reloading.
Nov 27 10:58:50 debian systemd[1]: Reloading.
Nov 27 10:58:51 debian systemd[1]: Reloading.
Nov 27 10:58:51 debian systemd[1]: Reloading.
Nov 27 10:58:51 debian systemd[1]: Reloading.
Nov 27 10:58:52 debian systemd[1]: Reloading.
Nov 27 10:58:52 debian systemd[1]: Reloading.
Nov 27 10:58:53 debian systemd[1]: Reloading.
Nov 27 10:58:53 debian systemd[1]: Reloading.
Nov 27 10:58:55 debian sudo[734439]: pam_unix(sudo:session): session closed for user root
Nov 27 10:58:57 debian sudo[734788]:    admin : TTY=pts/0 ; PWD=/home/fhem ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Nov 27 10:58:57 debian sudo[734788]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
Nov 27 11:00:03 debian systemd[1]: Starting debmatic set interface clock...
░░ Subject: A start job for unit debmatic-setinterfaceclock.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit debmatic-setinterfaceclock.service has begun execution.
░░
░░ The job identifier is 65964.
Nov 27 11:00:03 debian systemd[1]: debmatic-setinterfaceclock.service: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit debmatic-setinterfaceclock.service has successfully entered the 'dead' state.
Nov 27 11:00:03 debian systemd[1]: Finished debmatic set interface clock.
░░ Subject: A start job for unit debmatic-setinterfaceclock.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit debmatic-setinterfaceclock.service has finished successfully.
░░
░░ The job identifier is 65964.
Nov 27 11:00:22 debian influxd-systemd-start.sh[437]: ts=2022-11-27T10:00:22.983430Z lvl=info msg="Cache snapshot (start)" log_id=0dwXU_Dl000 service=storage-engine engine=tsm1>
Nov 27 11:00:23 debian influxd-systemd-start.sh[437]: ts=2022-11-27T10:00:23.160027Z lvl=info msg="Snapshot for path written" log_id=0dwXU_Dl000 service=storage-engine engine=t>
Nov 27 11:00:23 debian influxd-systemd-start.sh[437]: ts=2022-11-27T10:00:23.160117Z lvl=info msg="Cache snapshot (end)" log_id=0dwXU_Dl000 service=storage-engine engine=tsm1 o>
Nov 27 11:00:34 debian sudo[734788]: pam_unix(sudo:session): session closed for user root
Nov 27 11:00:36 debian sudo[734816]:    admin : TTY=pts/0 ; PWD=/home/fhem ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Nov 27 11:00:36 debian sudo[734816]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
`

**Comment by meier81** [comment]
Kurze Info: Das Problem hat sich mit dem aktuellen Update erledigt, es gibt keine Fehlermeldung mehr.

Gruß Markus
