### ISSUE TITLE
HB-RF-USB / 0x6F70 unter Windows erneut flashen ?

### ISSUE THREAD

**Issue by Newbie-2** [alexreinert/debmatic#307]
Sorry falsches Projekt

**Comment by alexreinert** [comment]
Was hat das mit debmatic zu tun?

**Comment by Newbie-2** [comment]
Der Post "306/Fehlermeldung nach aktuellem Update" bezog sich ja auch auf einen Fehler. 
Und ich habe auch ein Problem. Deshalb wollte ich wissen, wie ein unter Windows angemeldetes Modul mit falschen Einstellungen ein weiteres mal mit der korrekten Datei HB-RF-USB_FT232R.xml beschrieben werden kann ? Oder funktioniert das nur erneute flashen unter einem Linux System und nicht unter Windows ?
