### ISSUE TITLE
HM-MOD-RPI-PCB & Bluetooth (RPi3B+)

### ISSUE THREAD

**Issue by eiGelbGeek** [alexreinert/debmatic#31]
To get Bluetooth and the RPi module running, I still had to set core_freq = 250 in the config.txt. Without this entry the Bluetooth module will not be found on a Raspberry 3B +.

`sudo bash -c 'cat << EOT >> /boot/config.txt
dtoverlay=pi3-miniuart-bt
enable_uart=1
force_turbo=1
core_freq=250
EOT'`

**Comment by alexreinert** [comment]
Thanks for the hint, I fixed it in the documentation
