### ISSUE TITLE
Debmatic nach Installation: "Homematic Funk Anlernmodus konnte nicht aktiviert werden."

### ISSUE THREAD

**Issue by OpenDave-2022** [alexreinert/debmatic#311]
Guten Abend,

nach der Installation von Debmatic gemäß Anleitung funktioniert die Funkschnittstelle nicht.
Folgende Fehler sind mir aufgefallen:

In der WebUi erhalte ich den Fehler: "Homematic Funk Anlernmodus konnte nicht aktiviert werden."
Während der Installation kam "Echo Error! ", "Your kernel headers for kernel 5.15.61-v7l+ cannot be found"

dematic-Info ergibt die folgende Ausgabe:
debmatic version: 3.65.8-95
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown

Zum Einsatz kommt bei mir ein Pi4B und ein Homematic IP RF-USB-Stick. Als Betriebssystem OpenHabian mit OpenHAB 3.0.
Daneben läuft auch FHEM mit einem DUO-Fern USB-Stick von Rademacher.

Leider konnte ich auch nach langer Suche keine Lösung finden.

Zu Ergänzung sei noch erwähnt, dass ich zum Test ein weiteren Pi4B mit RaspberryMatic aufgesetzt habe, wo der Stick von Anfang an eingebunden wurde und verfügbar ist.

**Comment by alexreinert** [comment]
Das Problem ist, dass die Kernel Header nicht verfügbar sind für den aktuell laufenden Kernel. Ich krnne das aktuelle OpenHabian Image nicht und weiß nicht, ob da ggf. ein anderer Kernel zum Einsatz kommt zu dem es keine Header gibt, werde ich am Wochenende mal durchtesten.

**Comment by OpenDave-2022** [comment]
> Das Problem ist, dass die Kernel Header nicht verfügbar sind für den aktuell laufenden Kernel. Ich krnne das aktuelle OpenHabian Image nicht und weiß nicht, ob da ggf. ein anderer Kernel zum Einsatz kommt zu dem es keine Header gibt, werde ich am Wochenende mal durchtesten.

Hallo Alex, vielen Dank für deine Rückmeldung! Um erste Erfahrungen mit HomeMatic zu machen, werde ich zunächst den zweiten Pi mit RaspberrryMatic betreiben. Grundsätzlich wäre es natürlich Klasse alles auf einem Gerät zu laufen zu haben.
Wenn du von mir weitere Info benötigst, meld dich gern! Beste Grüße!

**Comment by yasars** [comment]
gibt es eine lösung? finde nix ... bekomme meine antenne auch nicht zum laufen ... pi os 


danke

**Comment by moranaga** [comment]
Probiert bitte nach SSH-Login auf der Konsole als nichtprivilegierte Nutzer _sinngemäß_:

```
$ uname -r
5.15.61
$ dpkg -l | grep linux-image
ii  linux-image-<kernel_name>            5.15.61
$ apt-cache search linux-headers-<kernel_name>
linux-headers-<kernel_name>
$ sudo apt install linux-headers-<kernel_name>
```

Das sind folgende Schritte:

1. Version des laufenden Kernels herausfinden
2. Name des Installierten Kernel-Pakets herausfinden (kann sein, dass mehr als eins installiert ist, auf Version achten)
3. Nach dem zugehörigen Paket mit den Headern suchen (bei Funden erneut auf Version achten)
4. Fall das passende gefunden wurde, installieren

Wenn das soweit geklappt hat, muss der Modulbau erneut angetriggert werden. 
Dazu einfach das Paket erneut installieren, die Skripte darin erledigen den Rest:

`$ sudo apt reinstall pivccu-modules-dkms`

Diese Vorgehensweise ist beispielhaft und ungetestet. Dennoch, HTH
