### ISSUE TITLE
Download link for create_cuxd.sh broken

### ISSUE THREAD

**Issue by alexirion** [alexreinert/debmatic#316]
The download link "https://homematic-forum.de/forum/download/file.php?id=${architectures[$ARCH]}" does not work:

wget -O cuxd.tar.gz https://homematic-forum.de/forum/download/file.php?id=87961
--2022-11-05 22:08:43--  https://homematic-forum.de/forum/download/file.php?id=87961
Auflösen des Hostnamens homematic-forum.de (homematic-forum.de) … 78.46.177.218
Verbindungsaufbau zu homematic-forum.de (homematic-forum.de)|78.46.177.218|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2022-11-05 22:08:43 FEHLER 404: Not Found.

**Comment by alexreinert** [comment]
I release an update with version 2.10 in the testing respository, see also commit 55dc40e.
