### ISSUE TITLE
Homematig IP Basic Heizthermostat nicht anlernbar (Raspberry PI 4 B 4 GB)

### ISSUE THREAD

**Issue by derDennis99** [alexreinert/debmatic#317]
Hallo lieber Entwickler,

ich kann seit der neuen Version keinen Heizthermostat mehr anlernen. Ich habe schon 3 Geräte getestet und es funktioniert leider nicht :(

kann das mit den Bugs zusammenhängen, wie in dem Forum geschrieben?:
_"Wenn man den Thread zur Original CCU verfolgt, dann kann man sagen, dass es Probleme gibt. EQ-3 hat zwar Sachen mit den Thermostaten gefixt, aber gleichzeitig an der Stelle neue (imho schlimmere) Bugs aufgemacht. Da abgesehen davon nur überschaubar viel geändert wurde, habe ich das Update noch nicht in stable übernommen und hoffe, dass kurzfristig eine 3.65.13? rauskommt."_

Macht es Sinn die Version zu "Downgraden"? Momentan habe ich die Version 3.65.8.95 bei mir installiert.

Gruß und danke
Dennis

**Comment by alexreinert** [comment]
Es ging dort um die Version 3.65.11.

**Comment by derDennis99** [comment]
oh ja das stimmt. Hast du iene Idee, woran das leigen könnte? ich bekomme auch keinen Fensterkontakt mehr angelernt. Die Geräte kann ich aber noch steuern das funktioniert alles. Gibt es eine Maximalanzahl an Geräten pro ccu?

**Comment by alexreinert** [comment]
Welches Funkmodul? Welche Rechnerhardware? Welche Geräte genau? Bei den Geräten vorher einen Werksreset am Gerät gemacht? Hat debmatic ungestörten Internet Zugang? Wie versuchst du Schritt für Schritt das Anlernen?

**Comment by derDennis99** [comment]
-Funkmodul: Raspberry Pi HM-MOD-RPI-PCB 
-Hardware ist ein Raspberry Pi 4 B (4 GB)
-Geräte, welche ich versuche anzulernen: Homematic IP Smart Home Heizkörperthermostat – Basic HmIP-eTRV-B-2 und den Homematic IP Smart Home Fenster- und Türkontakt mit Magnet HmIP-SWDM 
-Ich habe die Geräte mehrfach auf Werkseinstellungen zurückgesetzt. Ich habe verschiedene Neue Geräte getestet. (Nur Thermostate) Das Direkte anlernen der Geräte funktioniert. Aber nicht das anlernen an die CCU.
-Wie kann ich den Internetzugang von Debmatic prüfen?

Anlernen:
1. Anlernmodus an ccu einschalten dann Batterien in das Gerät stecken.
2. Anlernmodus an ccu einschalten dann bei dem Gerät nochmal auf die Anlerntaste drücken (Blauetaste)
3. Direktes anlernen KEY und SGTIN in der GUI eingegeben auch hier keinen Erfolg.
4. Raspi heruntergefahren und vom Strom getrennt. Geräte in Werkseinstellungen zurückgesetzt. Raspi wieder hochgefahren und nochmal versucht das Gerät anzulernen.

Als ich das Update auf die Version 3.65.8.95 gemacht hatte, konnte ich danach einen Thermostat anlernen. Jetzt keinen mehr. Ic habe auch sonst keine weiteren Updates gemacht. Das einzige, was ich noch geändert habe ist, dass ich bei zwei Homematic Steckdosen das Häckchen bei "Gerät dient als Router" gesetzt habe. Aber damit kann das nicht zusamen hängen oder?

**Comment by alexreinert** [comment]
Der Raspberry Pi 4 ist ein massiver Störsender auf 868MHz, siehe auch diverse Einträge im HM Forum. Einzige zuverlässige Lösung ist mind. 1m Abstand zwischen Funkmodul und Raspberry Pi.

**Comment by derDennis99** [comment]
Das hatte ich auch schon gelesen. Aber den 4er habe ich schon seit dem er zuverkaufen ist im Betrieb und habe bis jetzt so ca. 10 Geräte ohne Probleme angelernt bekommen. Ich habe für das Modul auch eine extra Antenne drangebaut aber das wird wascheinlich nix bringen... Bleibt wohl nur noch den alten 3er ausm Schrank zu räumen und das mit dem nochmal zu testen.

**Comment by derDennis99** [comment]
Alte Geräte, welche schon in Betrib sind, lassen sich auch wieder neu anlernen ohne Probleme...

**Comment by naresh97** [comment]
Ich habe auch das gleiche Problem, auch mit einem RPi 4. Alte Geräte funktionieren mit dem Anlernen immer noch. Neues HmIP-eTRV-B-2 allerdings nicht. Ich habe auch versucht mit Werksreset, mit KEY/SGTIN, mit dem Gerät direkt neben der Antenna. Leider alles ohne Erfolg.

**Comment by naresh97** [comment]
Also ich habe gerade mit einem neuen HmIP-STHD Wandthermostat, und das konnte ich problemlos anlernen lassen. Scheint nur ein problem mit den neuen HmIP-eTRV-B-2 zu sein... Vielleicht hilft da die Homematic Forum weiter 🤷🏾‍♂️

**Comment by naresh97** [comment]
Upgrade auf 3.65.11 hat mir geholfen (https://homematic-forum.de/forum/viewtopic.php?f=81&t=76482)

**Comment by VMicha** [comment]
Hallo, ich habe ein ähnlich gelagertes Problem. In meinem Setup ist ebenfalls der pi4 mit Debmatic und Funkmodul mit externer Antenne am Gehäuse. Es ist auch ein HAP als AP verbunden. Ich habe 8 Hmip STHD-Raumthermostate erfolgreich über Direktverbindungen zu Fußbodenheizungssteuerungen (FBH) (je 4) laufen, die ich über die Zentrale anlegen konnte. Neue Thermostate lassen sich jetzt leider nur genau 1x anlernen. Der Versuch dann eine Direktverbindung zur FBH einzurichten klappt nicht, weil eine Übertragung zum STHD fehlschlägt. Nach Zurücksetzen des STHD per Werkreset lässt sich dieser nun nicht mehr anlernen. 4 Stück STHD habe ich jetzt in diesem Zustand - 1 STHD habe ich noch OVP.  Ich glaube nicht, dass es die Funkprobleme vom pi4 sind. Ich kann die Geräte auch nicht mehr an einem HAP anlernen. Für Hilfe bedanke ich mich im Voraus. Viele Grüße
