### ISSUE TITLE
Installation unter Debian 

### ISSUE THREAD

**Issue by bjoerneman** [alexreinert/debmatic#319]
sudo apt-key add - funktioniert nicht mehr. könntest du bzw. jemand die installationsanweisung an aktuelle gegebenheiten anpassen. bitte weiterso. 

LG

**Comment by phrozen77** [comment]
Funktionieren tut es noch - es kommt aber ein Warning:

```
root@hm:~# wget -q -O - https://www.debmatic.de/debmatic/public.key | apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

**Comment by J-Feiler** [comment]
Hallo phrozen77

sorry das ich mich einmische, aber das hat weder mit der debmatic noch mit Alex etwas zu tun.
debian speichert die Schlüssel jetzt nur anders.

Abhilfe schafft dieser Artikel:
https://www.techrepublic.com/article/how-to-fix-the-apt-key-deprecated-warning-in-ubuntu/#:~:text=One%20of%20the%20reasons%20why,have%20a%20signed%2Dby%20option.

ich hoffe Dir damit geholfen zu haben.
mfg, Josef

**Comment by mschlenstedt** [comment]
Mit Alex und Debmatic hat das nix zu tu, aber mit der Beschreibungen unter https://github.com/alexreinert/debmatic/tree/master/docs/setup :-)

apt-key ist deprecated und in Debian 12 nicht mehr enthalten. Der korrekte Befehl lautet nun:

```
curl -sL https://www.debmatic.de/debmatic/public.key | gpg --dearmor | tee /usr/share/keyrings/debmatic.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/debmatic.gpg] https://www.debmatic.de/debmatic stable main" | tee /etc/apt/sources.list.d/debmatic.list
```
