### ISSUE TITLE
Automatische Bestätigung der Servicemeldung "Gerätekommunikation gestört" funktioniert nicht

### ISSUE THREAD

**Issue by muchul** [alexreinert/debmatic#321]
hallo,

ich habe in der Benutzerverwaltung die "Automatische Bestätigung der Servicemeldung "Gerätekommunikation gestört"" aktiviert.
Leider funktioniert dies nicht richtig. 
Ich habe genau ein Gerät, das sich alle 2-3 Wochen meldet, vermutlich weil ein 433MHz Sender in der nähe ist, oder immer Personen zwischen Sender und CCU Stehen.

Die gelbe LED Blinkt, obwohl der Haken gesetzt ist.
Wenn ich in die GUI gehe, wird jedoch keine Fehlermeldung angezeigt und die LED hört auf zu blinken.

Das ist auch in den vorhergehenden Versionen schon so gewesen.
Nur, wenn ich in die GUI gehen muss damit das Blinken aufhört, kann ich die Meldung auch selber wegklicken. Ich denke nicht das das so gewollt ist.
Allerdings bin ich mir auch nicht sicher, ob das mit Debmatic was zu tun hat, oder von EQ3 gelöst werden müsste.

PS: Mir ist klar, das es besser wäre, die Störung selber zu lokalisieren und zu beheben, aber wenn eine Funktion angeboten wird, sollte diese auch funktionieren, daher bitte keine Diskussionen darüber das der Fehler gefunden und gelöst werden muss.

Vielen Dank für Debmatic und den Support der hier geleistet wird.

**Comment by alexreinert** [comment]
Das funktioniert genau so, wie eQ-3 die Funktion vorgesehen und implementiert hat. Ein direktes Bestätigen, sobald es auftritt, wäre absolut sinnvoll, aber leider kann man das nur im Closed Source anpassen, also leider nichts, was ich in debmatic implementieren könnte.

**Comment by muchul** [comment]
Danke, irgendwie habe ich mir das gedacht.
