### ISSUE TITLE
Kompatibilität zu HMIP-HAP

### ISSUE THREAD

**Issue by Develeon64** [alexreinert/debmatic#323]
Hallo zusammen,

ich habe nun seit einiger Zeit DebMatic auf einem Raspberry Pi 3 B laufen zusammen mit dem HM-MOD-RPI-PCB. Von ein paar kleineren Schwierigkeiten abgesehen, läuft das ziemlich gut.
Nun habe ich aber ein schwerwiegender es Problem, da ich das System um einen HMIP-HAP erweitern wollte. Weder mit der ausgelieferten Firmware, noch der Aktuellen (2.4.28) [ausnahmslos sämtliche beteiligte Softwares sind -Stand heute- auf aktuellster Version] konnte ich erfolgreich eine Verbindung herstellen. Im Internet las ich dann einen Artikel, dass das mit dem HM-MOD-RPI-PCB auch gar nicht möglich sei und dafür ein RPI-RF-MOD her müsste.
Mein Problem daran ist, dass ich im Schaltschrank keinen Platz für die aufgetragene breite dieses Moduls habe.

Nun habe ich also über Lösungsansätze nachgedacht:
Ich könnte das Modul vielleicht per IDE-Kabel an einem anderen Ort in dem Schrank unterbringen. Ist aber glaube ich eine blöde Lösung.

Dann fand ich das HB-RF-USB und war direkt begeistert davon. Damit könnte ich das zweite im Schrank verbaute Raspberry Pi 2 B komplett entfernen, da ich die Relais dann mit den freigewordenen Pinnen des anderen Pis ansteuern kann, wo jetzt die Antenne draufsteckt, und den so freigewordenen Platz dafür verwenden. Die Version 2 davon fällt ja leider auch wieder raus, weil die Kombination ja wieder breiter wäre. Bei dem HB-RF-ETH ja dasselbe, richtig?
Jetzt wäre meine erste Frage:
_**Ändert das USB-Board (oder ggf. das ETH-Board) etwas an der Kompatibilität, oder kann ich so den HAP ins System integrieren?**_

Während meiner versuchten Recherche bin ich dann auch noch über den HMIP-RF-USB gestolpert. Ob der HAP mit diesem im Grundsatz kompatibel ist, habe ich leider nicht rausfinden können. Deshalb wäre meine zweite Frage hier:
_**Ist der HAP mit dem RF-USB unter DebMatic kompatibel?**_

Im Schaltschrank befinden sich Netzwerkkabel, die theoretisch auch mit PoE befeuert werden können. Außerdem befindet sich ein 5V-Netzteil mit mehr als ausreichend Leistung darin, womit alle möglichen Platinen versorgt werden können, die mit 5V laufen.
_**Gibt es also unter diesen Vorraussetzungen noch weitere Ideen, auf die ich selbst noch nicht gekommen bin?**_

Auf Wunsch kann ich selbstverständlich weitere Infos oder Fotos zur Einbausituation bereitstellen.

Ich bedanke mich im Voraus für Ideen und Infos!
Und ebenfalls auch einen großen Dank an @alexreinert für die Bereitstellung sowohl der Software, als auch der Erweiterungs-Boards, wirklich großartig!

Mit freundlichen Grüßen
Develeon

Hier noch ein Bild des Schaltschrankes:
![20221201_134717.jpg](https://user-images.githubusercontent.com/14893682/205057079-91196be8-992c-4dfd-9ec7-4a20a55de3af.jpg)

**Comment by alexreinert** [comment]
An sich hast du ja fast alle Möglichkeiten selbst genannt: Es braucht entweder das RPI-RF-MOD oder den HmIP-RFUSB um den AP anzusteuern, meine persönliche Empfehlung wäre klar das RPI-RF-MOD.
RPI-RF-MOD kann man per GPIO, HB-RF-USB, HB-RF-USB-2 oder HB-RF-ETH anschließen, für deine Einbausituation würde sich da entweder die HB-RF-USB (ohne -2) im Schaltschrank oder die anderen Platinen außerhalb des Schaltschranks anbieten: Beim HB-RF-ETH direkt per Netzwerk angeschlossen, beim HB-RF-USB-2 mittels USB over CAT Extender irgendwo angeschlossen, wo man mit den Netzwerkkabeln hinkommt. Ich persönliche würde auch versuchen, das außerhalb des Schrankes zu positionieren, weil Funk und Metalschrank keine optimale Kombi ist, ggf. kann man dadurch sogar die Notwendigkeit für den AP eliminieren.

**Comment by Develeon64** [comment]
Danke für deine ultra schnelle Antwort!
Dann wird es vermutlich entweder HB-RF-USB + HM-RF-MOD, oder direkt der HM-RF-USB. Aber wenn deine Empfehlung eher auf ersteres geht, höchstwahrscheinlich diese, wenn das dann eh alles kompatibel ist.

Der Schaltschrank an sich ist hier auch nicht das Problem. Der ist, bis auf die Befestigungsplatte, hinter sich räumlich nichts befindet, aus Kunststoff. Das Problem ist hier, dass durch die Kohle, die beim Bau des Hauses vor 120 Jahren in den Decken verbaut wurde, fast kein Funk etagenübergreifend funktionieren kann. Deshalb passt es schon für diese Etage die Antenne im Schrank zu lassen und unten den AP hinzustellen.

Danke dir für deine zahlreichen Tipps!
Du hast mir sehr damit geholfen!
