### ISSUE TITLE
CCU-Jack als Debian package?

### ISSUE THREAD

**Issue by ptweety** [alexreinert/debmatic#324]
Hallo Alex,

bisher hat hier noch niemand nachgefragt, also übernehme ich das mal:
- besteht die Möglichkeit den CCU-Jack als Debian Packet für DebMatic zu bauen?

Aus meiner Sicht sollte das ähnlich gehen, wie beim CUxD, denn der CCU-Jack stellt u.a. ein eigenes Interface für virtuelle Geräte bereit.

Siehe auch: https://github.com/mdzio/ccu-jack/issues/109

**Comment by 63chris** [comment]
gibt es eine Chance, diesen zu implementieren?

viele Grüße

**Comment by 63chris** [comment]
über eine kurze Rückmeldung, ob das möglich wäre würde ich mich freuen

Grüße

**Comment by 63chris** [comment]
btw - mdzio hatte auch angeboten, das Paket zu bauen, wenn die Anpassungen "überschaubar" sind.
https://github.com/mdzio/ccu-jack/issues/109


Wäre toll, wenn es dieses add-on auch für Debmatic geben könnte, damit alle Funktionen von CCU-Jack nutzbar sind

Grüße
