### ISSUE TITLE
install debmatic on raspberry OS end with an error (/lib/ld-linux-armhf.so.3)

### ISSUE THREAD

**Issue by sean1587** [alexreinert/debmatic#325]
Ja ich weis, es gibt bereits ähnliche issues, aber keine Lösungen.
Ich habe versucht debmatic auf meinem RP4 mit Raspberry OS 64bit zu installieren.
Leider bekomme ich folgende Fehlermeldung:
```
pi@home:~ $ sudo apt install debmatic
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut... Fertig
Statusinformationen werden eingelesen... Fertig
Die folgenden NEUEN Pakete werden installiert:
  debmatic
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 53,9 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Vorkonfiguration der Pakete ...
(Lese Datenbank ... 124555 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../debmatic_3.65.8-95_arm64.deb ...
Entpacken von debmatic (3.65.8-95) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/debmatic_3.65.8-95_arm64.deb (--unpack):
 Versuch, »/lib/ld-linux-armhf.so.3« zu überschreiben, welches auch in Paket libc6:armhf 2.31-13+rpt2+rpi1+deb11u5 ist
dpkg-deb: Fehler: »einfügen«-Unterprozess wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/debmatic_3.65.8-95_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Ich hab mal neu aufgesetzt mit dem 64-Bit-Image(hatte ich übrigens zuvor auch schon drauf gehabt), aber debmatic funktioniert nicht zusammen mit anydesk und anderer Software, die auf das libc6-armhf Paket angewiesen sind.
Wenn ich debmatic zuerst installiere, kann ich anydesk usw. nicht mehr installieren und umgekehrt.
Wenn man die Fehlermeldung genauer betrachtet, bedeutet das in etwa, dass ein Teil des Paketes der libc6-armhf mit debmatic mitgeliefert wird, dieser Teil jedoch nicht kopiert wird, weil schon das eigentliche Paket installiert ist.
Ich bin kein Programmierer und weiß auch nicht wie aufwendig es wäre, aber vielleicht ist das ein nicht ganz so dummer Vorschlag:
Der/Die Programmierer/Entwickler von debmatic müssten anstatt einen Teil des Paketes der libc6-armhf mit zu liefern, die libc6-armhf als Abhängigkeit hinzufügen, damit bei der installation von debmatic die gesamte lib installiert wird, falls diese noch nicht installiert ist.

Yes, I know there are already similar issues, but no solutions.
I tried to install debmatic on my RP4 with Raspberry OS 64bit.
Unfortunately I get the following error message:
```
pi@home:~ $ sudo apt install debmatic
Reading package lists... Done
Building dependency tree... Done
Status information is being read... Done
The following NEW packages will be installed:
  debmatic
0 updated, 1 newly installed, 0 to remove and 0 not updated.
There are 0 B of 53.9 MB of archives left to download.
After this operation, 0 B additional disk space is used.
Preconfiguration of the packages ...
(Reading database... 124555 files and directories are currently installed.)
Preparing to unpack .../debmatic_3.65.8-95_arm64.deb ...
Unpacking debmatic (3.65.8-95) ...
dpkg: error processing archive /var/cache/apt/archives/debmatic_3.65.8-95_arm64.deb (--unpack):
 Attempt to overwrite "/lib/ld-linux-armhf.so.3" which is also in package libc6:armhf 2.31-13+rpt2+rpi1+deb11u5
dpkg-deb: error: 'insert' subprocess was killed by signal (broken pipe).
Errors occurred while editing:
 /var/cache/apt/archives/debmatic_3.65.8-95_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I reinstalled with the 64-bit image (I had it before, by the way), but debmatic doesn't work with anydesk and other software that rely on the libc6-armhf package.
If I install debmatic first I can no longer install anydesk etc and vice versa.
If you take a closer look at the error message, it means something like that part of the libc6-armhf package is supplied with debmatic, but this part is not copied because the actual package is already installed.
I'm not a programmer and I don't know how complicated it would be, but maybe this is a not so stupid suggestion:
The debmatic programmer/developer would need to add the libc6-armhf as a dependency instead of providing part of the libc6-armhf package so that when debmatic is installed the entire lib is installed if it is not already installed.

**Comment by mayonezo** [comment]
Das andere issue wurde jetzt automatisch als stale markiert.

**Comment by alexreinert** [comment]
Sollte mit den letzten beiden Commits erledigt sein. Ein entsprechender Build ist im testing APT Repository verfügbar.
