### ISSUE TITLE
Debmatic auf ubuntu 22.04 ohne swap.img dependency Problem?

### ISSUE THREAD

**Issue by J-Feiler** [alexreinert/debmatic#327]
Hallo Alex
Ich habe auf meinem debmatic host (Intel NUC mit Ubuntu-Server 22.04) vor ein paar tagen wie auf meinen anderen Rechnern das swapping deaktiviert. 
Mit 8GB RAM funktioniert das normalerweise sehr gut. Die debmatic läuft ja auch schon seit einem Jahr auf diesem Rechner, ich hatte nur vergessen das swapping zu deaktivieren.

Danach hatte ich jedoch das Problem das die debmatic nur noch bei jedem 3 oder 4 Boot funktioniert hat.
Wenn sie mal gelaufen ist war alles soweit ok. Wenn nicht... lag es am debmatic rfd service das nicht starten konnte.
(dependency error)
Seit dem reaktivieren des swap-Speichers ist der Fehler weg. 8x neu gestartet, immer alles ok.

Ich möchte jetzt gar nicht hinterfragen warum das rfd.service den swap-Speicher braucht...... ist eben so.
Es wäre aber evtl. super wenn in der install-Anleitung ein Hinweis wäre das "swappen" nicht abzuschalten.

Das würde ein aus meiner Sicht sehr gutes Produkt noch ein wenig perfekter machen und evtl. anderen helfen diese Situation zu vermeiden.

Mit Freundlichen Grüßen aus Wien

Josef Feiler

**Comment by alexreinert** [comment]
Kann ich nicht nachvollziehen, ich habe es hier auf mehreren Testsystemen ausprobiert und bei keiner hatte ich Probleme nach dem Deaktivirrrn der Swap Partition, nicht mal bei den Systemen mit nur 2GB RAM. Läuft da parallel noch andere Software? Wieviele Geräte sind angelernt? Steht irgendwas im syslog oder bei dmesg?

**Comment by J-Feiler** [comment]
Auf diesem Rechner läuft ausser der debmatic noch mein Slave-IoBroker. 
Dieser hat nur die Rega und RPC-Adapter für die debmatic installiert. 
Mit dem Broker dann noch der Redis-Server.

Angelernt sind:
1 x keymatic incl. 2 Fernbedienungen
4 x fensterkontakt
4 x Heizkörperventil
1 x Wndthermostat
alles HmIP Geräte, also nichts wirklich wildes.

Ich suche morgen die Log-einträge aus dem Syslog und hmserver-log.
Die einzige aussagekräftige Meldung für mich war die dependency Fehlermeldung die jetzt weg ist.
lt. debmatic-info war/ist alles OK, 
uart war/ist alles OK 

rfd-service startet wieder:
● debmatic-rfd.service - debmatic rfd
     Loaded: loaded (/lib/systemd/system/debmatic-rfd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-02-04 18:48:53 CET; 4h 31min ago
    Process: 1592 ExecStartPre=/usr/share/debmatic/bin/add_fw_block.sh debmatic_rfd 32001 (code=exited, status=0/SUCCESS)
    Process: 1610 ExecStart=/usr/share/debmatic/bin/start_rfd.sh (code=exited, status=0/SUCCESS)
   Main PID: 1620 (rfd)
      Tasks: 6 (limit: 9315)
     Memory: 21.0M
        CPU: 6.804s
     CGroup: /system.slice/debmatic-rfd.service
             └─1620 /bin/rfd -l 1 -f /etc/config/rfd.conf -d

Feb 04 18:49:41 debmatic rfd[1620]: rcux support getDeviceDescription
Feb 04 18:49:41 debmatic rfd[1620]: rcux support getParamsetDescription
Feb 04 18:49:41 debmatic rfd[1620]: rcux support getParamset
Feb 04 18:49:41 debmatic rfd[1620]: rcux support putParamset
Feb 04 18:49:41 debmatic rfd[1620]: rcux support getValue
Feb 04 18:49:41 debmatic rfd[1620]: rcux support setValue
Feb 04 18:49:41 debmatic rfd[1620]: rcux support reportValueUsage
Feb 04 18:49:41 debmatic rfd[1620]: rcux support listReplaceableDevices
Feb 04 18:49:41 debmatic rfd[1620]: rcux support ping
Feb 04 18:49:41 debmatic rfd[1620]: GetAvailableFirmware for HM-RCV-50

Wie gesagt, ich durchforste morgen nochmal alle Logs die ich habe.

Danke schon mal dafür.
