### ISSUE TITLE
HM-MOD-RPI-PCB anlernen nicht möglich

### ISSUE THREAD

**Issue by UncleCCC** [alexreinert/debmatic#33]
Hallo :)
Da ich meinen Raspi gerne noch für andere zwecke nutzen möchte, würde ich gerne von Raspmatic auf Debmatic wechseln.
Installation hat nach Anleitung super funktioniert.
Nur kann ich keine Geräte anlernen, anscheinend wird das HM-MOD-RPI-PCB Modul nicht erkannt?
![Screenshot (38)](https://user-images.githubusercontent.com/53874047/63631407-70ccb980-c627-11e9-87b5-2257670643f9.png)
Wie gesagt mit Raspmatic lief alles wunderbar

**Comment by alexreinert** [comment]
Was kommt per SSH bei debmatic-info?

**Comment by UncleCCC** [comment]
Guten morgen

pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.47.15-31
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
pi@raspberrypi:~ $

Sieht nicht gut aus 😀

**Comment by alexreinert** [comment]
Wurde der Reboot gemacht, welcher in der Anleitung steht?

**Comment by UncleCCC** [comment]
Ja habe ich jetz mehrmals gemacht, könnte es daran liegen das ich während der Installation das Modul noch nicht aufgesteckt hatte? Ich habe statt dem reboot den raspi runter gefahren, das Modul aufgesteckt und dann wieder gestartet

**Comment by alexreinert** [comment]
Nein, die Kernel Module fehlen.
Was kommt bei ```sudo dpkg-reconfigure pivccu-modules-dkms```?

**Comment by UncleCCC** [comment]
Die Ausgabe habe ich als Screenshot angehängt..
Es wurde ein Neustart verlangt, bringt aber keine Besserung, 
Geräte anlernen sieht immer noch aus wie im ersten Beitrag

![Auswahl_087](https://user-images.githubusercontent.com/53874047/63636132-92e82b00-c66b-11e9-871e-dfd961f1b524.png)

**Comment by alexreinert** [comment]
Die Kernel Header sind nicht bzw. in der falschen Version installiert.
Was kommt bei
```
sudo dpkg -s raspberrypi-kernel
sudo dpkg -s raspberrypi-kernel-headers
```

**Comment by UncleCCC** [comment]
Wieder als Screenshot.
Hab nix anderes gemacht als die letzte 
Raspbian Buster Lite installiert und dann nach deiner Anleitung vorgegangen
![Auswahl_088](https://user-images.githubusercontent.com/53874047/63648227-e3738d00-c72c-11e9-8654-2279946a131a.png)

**Comment by alexreinert** [comment]
Wie vermutet, Kernel und Header passen nicht zusammen.
```sudo apt update && sudo apt upgrade```
Danach ein Reboot, 10 Minuten warten und dann nochmal pivccu-info.

**Comment by UncleCCC** [comment]
Jetzt läufts :)
Vielen Dank für deine Hilfe :)
Aber wie gesagt, der Raspy war frisch aufgesetzt und dann hab ich nach Anleitung installiert..
