### ISSUE TITLE
Proxmox      /etc/pve/lxc/XXX.conf: Permission denied

### ISSUE THREAD

**Issue by keksn** [alexreinert/debmatic#330]
kann die manuelle Konfiguration im Server für den Container nicht durchführen

**Comment by alexreinert** [comment]
Mit root editiert?

**Comment by keksn** [comment]
Hallo, ich bin mit root angemeldet. Muss ich zusätzlich noch etwas machen? Danke !! Lg

**Comment by keksn** [comment]
> Mit root editiert?

Hallo, ich bin mit root angemeldet. Muss ich zusätzlich noch etwas machen? Danke !! Lg

**Comment by keksn** [comment]
Habe die Datei über cyberduck über ssh editiert ...das hat geklappt.
