### ISSUE TITLE
Bekomme HmIP-RFUSB unter Ubuntu nicht zum laufen

### ISSUE THREAD

**Issue by FlexFlix** [alexreinert/debmatic#331]
Ich habe auch einen anderen schon unter einem Identischen System funktinierenden RFUSB nicht zum laufen bekommen..

Ich glaube ich stehe auf dem Schlauch.

Intel NUC
Ubuntu 22.04.1 LTS
Eigentlich alles nach Anleitung gemacht. :(

lsusb ergibt: Bus 001 Device 002: ID 1b1f:c020 eQ-3 Entwicklung GmbH HmIP-RFUSB

Lötstellen hab ich eben mal durchgepiept, da aber ein anderer Stick ja auch nicht funktioniert, denke ich an Software Problem..
hab aber alles noch mal neu aufgesetzt ohne Erfolg.

`nuc@nuc-NUC11ATKC4:~$ sudo debmatic-info 
debmatic version: 3.67.10-99
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown

nuc@nuc-NUC11ATKC4:~$ sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Module pivccu-1.0.78 for kernel 5.19.0-32-generic (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.

dummy_rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

dw_apb_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

eq3_char_loop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

fake_hmrf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

generic_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_eth.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb_2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

hb_rf_usb.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

led_trigger_timer.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

meson_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

pl011_raw_uart.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

plat_eq3ccu2.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rpi_rf_mod_led.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

rtc-rx8130.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.19.0-32-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....
Deleting module pivccu-1.0.78 completely from the DKMS tree.
Error! The module/version combo: pivccu-1.0.78 is not located in the DKMS tree.
Creating symlink /var/lib/dkms/pivccu/1.0.78/source -> /usr/src/pivccu-1.0.78

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.19.0-32-generic ARCH=x86 all....
Signing module:
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/plat_eq3ccu2.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/hb_rf_eth.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/rtc-rx8130.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/fake_hmrf.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/dummy_rx8130.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/pl011_raw_uart.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/hb_rf_usb_2.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/meson_raw_uart.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/dw_apb_raw_uart.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/hb_rf_usb.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/rpi_rf_mod_led.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/eq3_char_loop.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/generic_raw_uart.ko
 - /var/lib/dkms/pivccu/1.0.78/5.19.0-32-generic/x86_64/module/led_trigger_timer.ko
Secure Boot not enabled on this system.
cleaning build area...

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

hb_rf_usb_2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-32-generic/updates/dkms/

depmod...
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Unit /lib/systemd/system/pivccu-dkms.service is added as a dependency to a non-existent unit pivccu.service.
`

Vielen Dank
Felix

**Comment by alexreinert** [comment]
Was liefert `modprobe eq3_char_loop`?

**Comment by FlexFlix** [comment]
Hallo,
danke für die Antwort :)

sudo modprobe eq3_char_loop
modprobe: ERROR: could not insert 'eq3_char_loop': Exec format error

**Comment by alexreinert** [comment]
ok, dann ist es was ich vermute habe, die Kernel Header sind eingerichtet für Signing, der Kernel läuft aber ohne Signing.
Das ist leider ein typisches Verhalten, wenn die Kernel Header bereits während der Installation installiert werden, aber man kann es einfach fixen:
```
sudo apt install --reinstall linux-headers-$(uname -r)
sudo sudo dpkg-reconfigure pivccu-modules-dkms
sudo apt-mark auto linux-headers-$(uname -r)
sudo reboot
```

**Comment by FlexFlix** [comment]
Vielen Dank! :)

sudo debmatic-info 

debmatic version: 3.67.10-102
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:00:14.0-7 (/dev/raw-uart)
 Board serial:  1F299ED144
 Radio MAC:     0xFF7BDA
HMIP Hardware:  HMIP-RFUSB
 Connected via: eQ-3 HmIP-RFUSB@usb-0000:00:14.0-7 (/dev/raw-uart)
 SGTIN:         3014F711A000041F299ED144
 Radio MAC:     0xB7E366
