### ISSUE TITLE
Upgrade auf Ubuntu Server 20.04.5 LTS schlägt fehl

### ISSUE THREAD

**Issue by MalteHillmann** [alexreinert/debmatic#332]
Hallo!

Die aktuelle Version lässt sich auf Ubuntu Server 20.04.5 LTS nicht mehr updaten.
dpkg stoppt während des postinst scripts /var/lib/dpkg/info/debmatic.postinst in Zeile 12 mit dem Fehler: `[: too many arguments`

https://github.com/alexreinert/debmatic/blob/45a9e037a898426ac98452ee2e7d87c9040e7953/debmatic/DEBIAN/postinst#L12

Habe das mal kurz in der Server bash (5.0.17(1)-release) getestet:
```if [ -d /lib/tcl8.2 ] && [ ! `ls -A /lib/tcl8.2/` ]; then``` -> Fehler: `[: too many arguments`
`if [ -d /lib/tcl8.2 ]; then` -> kein Fehler
```if [ ! `ls -A /lib/tcl8.2/` ]; then``` -> Fehler: `[: too many arguments`

Als schnellen (temporären) fix habe ich die Zeilen 12-15 im postinst Script komplett auskommentiert, da auf meiner Installation der Symlink sowieso bereits korrekt existiert. Damit funktioniert dann das Upgrade. Ist aber ja keine Dauerlösung.

Viele Grüße
Malte

**Comment by alexreinert** [comment]
Kannst du bitte mal die Ausgabe von `ls -la /lib/tcl8.2/` posten?

**Comment by alexreinert** [comment]
Sollte in Version 3.67.10-102 gefixt sein.
