### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by T1mey** [alexreinert/debmatic#333]
Was bedeutet denn der Schritt 5 der Anleitung (https://github.com/alexreinert/debmatic/blob/master/docs/setup/otheros.md)

`Installation der Kernel Header (dieser Schritt ist abhängig von Distribution und verwendetem Kernel, bitte in der Hilfe der Distribution nachschlagen)`

für einen Ubuntu 22.04 server (Proxmox VM) ?

Sind die ggf. schon installiert?

![image](https://user-images.githubusercontent.com/10464878/228751619-aecf4f20-72ea-4ec3-a975-80d60ae3c050.png)

**Comment by alexreinert** [comment]
Der Screenshot sieht danach aus, dass diese bereits installiert sind.
Ansonsten: https://letmegooglethat.com/?q=install+kernel+header+ubuntu

**Comment by T1mey** [comment]
Bekomme aber bei der Installation folgenden Fehler

![image](https://user-images.githubusercontent.com/10464878/228753216-1e4a6d97-270a-4323-ba65-85b55cc6d5a8.png)

**Comment by alexreinert** [comment]
In der unteren Hälfte des Screenshots werden die Kernel Module korrekt gebaut, das sollte also kein Problem sein.

**Comment by T1mey** [comment]
Leider bekomme ich beim Anlernen

![image](https://user-images.githubusercontent.com/10464878/228758747-af07a081-9518-4fd0-b3f3-a820b978210b.png)



![image](https://user-images.githubusercontent.com/10464878/228758535-55372cc2-0675-4392-bed2-b1a65ae21f0e.png)

**Comment by alexreinert** [comment]
```
sudo apt install --reinstall linux-headers-`uname -r`
sudo dpkg-reconfigure pivccu-modules-dkms
sudo reboot
```

**Comment by T1mey** [comment]
Hat leider nicht geholfen. Ggf. noch eine Idee?

**Comment by T1mey** [comment]
Liefert das hier 

crw------- 1 root root 236, 0 Mär 30 07:31 /dev/raw-uart

Funkmodul sieht so aus 

![image](https://user-images.githubusercontent.com/10464878/228766236-b440b6fc-4eb6-4ba4-8582-302a44321946.png)

**Comment by alexreinert** [comment]
Da haben ein paar Pins Potential für eine kalte Lötstelle, insbesondere 2, 9 und 10.

**Comment by T1mey** [comment]
Hab gerade die 12 Pins nachgelötet um eine kalte Lötstelle auszuschließen.
Funktioniert aber immer noch nicht.

**Comment by alexreinert** [comment]
Bitte nochmal ein Bild und nochmal `sudo systemctl stop debmatic` ausführen und dann die Ausgabe von sudo `detect_radio_module --debug /dev/raw-uart` posten.

**Comment by T1mey** [comment]
Hab es nochmal ausgeführt

![image](https://user-images.githubusercontent.com/10464878/228780404-36d62061-b0fd-4f07-9db4-0fbc4fe98509.png)

**Comment by T1mey** [comment]
Also ich habe das ganze nun mal an meine RPI 3 gehangen und dieser verhält sich genauso (auf dem UI) wie der Proxmox Container mit Debmatic.

**Comment by alexreinert** [comment]
Was weiterhin für ein Hardware Problem spricht, aber meine Bitte nach einem neuen Foto ignorierst du ja.

**Comment by T1mey** [comment]
> Was weiterhin für ein Hardware Problem spricht, aber meine Bitte nach einem neuen Foto ignorierst du ja.

Sry hatte ich wohl überlesen

![image](https://user-images.githubusercontent.com/10464878/229036526-503ae57b-8a2b-4d5a-ba5e-6b3e7015c849.png)

**Comment by alexreinert** [comment]
Ich erkenne es leider nicht richtig, aber Pin 9 (Gnd) sieht immer noch leicht nach einer Lötkugel aus.

**Comment by T1mey** [comment]
Aber Pin 9 wird doch von dem kleinen Modul gar nicht belegt

**Comment by alexreinert** [comment]
Es werden Pins 1-12 belegt.

**Comment by T1mey** [comment]
Also eben gerade ist mein RPI-RF-MOD gekommen. Gerade gelötet & angeschlossen ... Funktioniert auf anhieb.

**Comment by alexreinert** [comment]
Und das hat im Gegensatz zum HM-MOD-RPI-PCB nicht nur Pin 9 als Masse, sondern auch noch weitere.
