### ISSUE TITLE
Einzeiler zur Installation Kernel-Header funktioniert nicht unter Linux Mint und Armbian (amd64)

### ISSUE THREAD

**Issue by mschlenstedt** [alexreinert/debmatic#334]
Der folgende Einzeiler zur Installation aus den Setup-Anleitungen zur Installation der Kernel-Header funktioniert in Linux Mint (Debian Bookworm) und DietPi (basiert auf Armbian, Debian Bullseye) nicht.

```
dpkg --get-selections | grep 'linux-image-' | grep '\sinstall' | sed -e 's/linux-image-\([a-z0-9-]\+\).*/linux-headers-\1/'
```

`dpkg --get-selections | grep 'linux-image-'` zeigt bei diesen Systemen folgendes:

linux-image-5.10.0-21-amd64			install
linux-image-amd64				install

Der folgende Einzeiler funktioniert:

```
dpkg --get-selections | grep 'linux-image-' | grep '\sinstall' | sed -e 's/linux-image-\([a-z0-9\.-]\+\).*/linux-headers-\1/'

**Comment by alexreinert** [comment]
Dieser Einzeiler steht bewusst nur in der Anleitung zu Armbian, weil er nur da funktioniert. Weder Mint noch DientPi basieren auf Armbian und auch wenn der gepostete Befehl dort funktionieren mag, allgemein gültig ist er (leider) nicht.

**Comment by mschlenstedt** [comment]
Zumindest die Odroid-Version von DietPi ist ein Armbian in der Basis. DietPi an sich ist ja keine eigene Distribution, sondern nimmt als Basis immer eine vorhandene Distribution. Daher hatte ich die Anleitung gewählt - und sie funktioniert letztendlich auch ;-)

Mein modifizierter Einzeiler fügt im Oder-Regex ja nur den Punkt hinzu: [a-z0-9\.-]

Er dürfte also auf Armbian weiter laufen (weil ODER) und zusätzlich eben auf den Standard-Architekturen ebenfalls funktionieren - zumindest hier auf Mint und der VM von DietPi.

Aber ja: Ein reines Armbian habe ich nicht ;-)
