### ISSUE TITLE
Update von 3.65.8.95 auf 3.67.10.99 schlägt fehl

### ISSUE THREAD

**Issue by Develeon64** [alexreinert/debmatic#336]
Ich kann mein Debmatic nicht updaten. `apt Upgrade debmatic` schreibt dazu folgendes:
```
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 debmatic : Hängt ab von (vorher): libc6 (>= 2.29) aber 2.28-10+rpt2+rpi1+deb10u1 soll installiert werden
E: Beschädigte Pakete
```

`apt list libc6 -a` ergibt:
```
libc6/oldstable,now 2.28-10+rpt2+rpi1+deb10u1 armhf  [installiert]
libc6/oldstable 2.28-10+rpi1+deb10u2 armhf
```

`apt upgrade libc6` sagt:
```
libc6 ist schon die neueste Version (2.28-10+rpt2+rpi1+deb10u1).
```

Das Ganze läuft auf einem Rpi 3 mit HM-MOD-RPI-PCB auf Raspbian 10 (buster).

**Comment by alexreinert** [comment]
Debian Buster bzw. Raspbian Buster ist EOL und wird mit der neuen Version nicht mehr unterstützt. Es bräuchte daher ein Update auf Bullseye.

**Comment by Fabi0220** [comment]
Hey habe das gleiche Problem.

Ich nutze jedoch Ubuntu 18.04.6 LTS

Erhalte beim Updateversuch diese Fehlermeldung. 

`debmatic : Hängt ab von (vorher): libc6-i386 (>= 2.29) aber 2.27-3ubuntu1.6 soll installiert werden`

`
libc6/bionic-updates,now 2.27-3ubuntu1.6 amd64  [installiert]
libc6/bionic-security 2.27-3ubuntu1.5 amd64
libc6/bionic 2.27-3ubuntu1 amd64
`

`libc6 ist schon die neueste Version (2.27-3ubuntu1.6).`

Muss ich auf eine neuere Ubuntu Version wechseln oder gibt es eine Möglichkeit dies per Befehl zu beheben

**Comment by alexreinert** [comment]
Ja, du brauchst eine neuere Ubuntu Version, Bionic hat über 5 Jahre auf dem Buckel, da kann man schon mal langsam an ein Update denken.
