### ISSUE TITLE
Fehlermeldung: Homematic Funk Anlernmodus konnte nicht aktiviert werden.

### ISSUE THREAD

**Issue by jojojo20104** [alexreinert/debmatic#337]
Ich bekomme seit einem Debmatic Update immer folgende Fehlermeldung wenn ich neue Geräte anlernen möchte "Homematic Funk Anlernmodus konnte nicht aktiviert werden.". Eine Verbindung zu den Sensoren und Aktoren ist seit dem auch nicht mehr vorhanden. Ein Zurückspielen eines Backups bringt leider auch keine Lösung. Ich habe inzwischen auf einem neuen RPi debmatic komplett neu installiert und bekomme das selbe Problem.

Folgende Ausgabe erhalte ich bei `sudo debmatic-info`

> debmatic version: 3.67.10-102 
> Kernel modules: Not available
> Raw UART dev:   Not available
> HMRF Hardware:  unknown
> HMIP Hardware:  unknown 
> 

Meine Vermutung ist das etwas mein Funkmodul (HB-RF-USB-2 + RPI-RF-MOD) nicht korrekt erkannt wird. Die LED leuchtet allerdings Grün und bis vor dem Update hat alles funktioniert. Ich weiß aktuell nicht weiter wie ich diesen Fehler lösen kann?

**Comment by alexreinert** [comment]
Die Kernel Module sind nicht vorhanden. Kann es sein, dass durch das Update auch Kernel und die Raspberry Firmware aktualisiert wurde und jetzt der 64 Bit Kernel auf einem 32 Bit System aktiv ist? Dann bitte in der /boot/config.txt dafür sorgen, dass der 32 Bit Kernel geladen wird, ein 32/64 Bit Mischbetrieb wird nicht unterstützt.

**Comment by jojojo20104** [comment]
Mit der Abfrage ` uname -m` bekomme ich `armv7l` als Antwort. Das dürfte dann doch nicht das Problem sein?

**Comment by alexreinert** [comment]
Was liefert `sudo dpkg-reconfigure pivccu-modules-dkms`?

**Comment by alexreinert** [comment]
Das Problem kommt, weil die zum Kernel gehörigen Kernel Header nicht auf dem System vorhanden sind. Daher können die Kernel Module nicht gebaut werden und ohne diese ist keine Kommunikation mit dem Funkmodul möglich.
Welches genaue OS wird verwendet?

**Comment by jojojo20104** [comment]
Ich habe die SD Karte mit dem 32Bit Image von OpenHAB geflasht. 

> openhabian-pi-raspios32-202212201337-gitb2e396e-crc9e18ad69.img

**Comment by 63chris** [comment]
gleiches Problem bei mir auf einen frisch aufgesetzten RPi4 mit 32bit OS lite. Nichts anderes wurde installiert, nur ein apt update/upgrade gemacht. Ich nutze ein HB-RF-USB

debmatic version: 3.69.7-104
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown

output von sudo dpkg-reconfigure pivccu-modules-dkms

pi@BauligHA:~ $ sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

------------------------------
Deleting module version: 1.0.80
completely from the DKMS tree.
------------------------------
Done.
Error! The module/version combo: pivccu-1.0.80
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.80/source ->
                 /usr/src/pivccu-1.0.80

DKMS: add completed.
Error! echo
Your kernel headers for kernel 6.1.21-v8+ cannot be found at
/lib/modules/6.1.21-v8+/build or /lib/modules/6.1.21-v8+/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.

Gruß
chris

**Comment by 63chris** [comment]
@jojojo20104 

wegen dem Fenster, wenn das so aussieht heisst das, dass die CCU kein Funkmodul ansprechen kann, passt also zu dem software problem, das hier diskutiert wird

**Comment by alexreinert** [comment]
Siehe alexreinert/piVCCU#484

**Comment by 63chris** [comment]
Danke, hat letztlich funktioniert, nachdem ich zuerst in der /boot/config.txt folgende Zeile hinzugefügt hatte arm_64bit=0 und - nachdem ich wieder u.a. Meldung bekommen habe - zusätzlich noch diesen befehl gesetzt habe
sudo dpkg-reconfigure pivccu-modules-dkms.

vorher
pi@homeserver:~ $ sudo debmatic-info
debmatic version: 3.69.7-104
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  unknown
HMIP Hardware:  unknown


nachher
pi@homeserver:~ $ sudo debmatic-info
debmatic version: 3.69.7-104
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: HB-RF-USB@usb-0000:01:00.0-1.3 (/dev/raw-uart)
 Board serial:  NEQ13320xx
 Radio MAC:     0x4F608D
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: HB-RF-USB@usb-0000:01:00.0-1.3 (/dev/raw-uart)
 SGTIN:       xxxxxxxxxxxxxxxx
 Radio MAC:     0xB878F9
