### ISSUE TITLE
Kanaleinstellungen nach update "kastriert" 

### ISSUE THREAD

**Issue by 63chris** [alexreinert/debmatic#339]
Hallo,

angefangen hat es mit dieser Beobachtung
[https://github.com/jp112sdl/JP-HB-Devices-addon/issues/70](url)

Normalerweise sieht das Fenster z.B. für die LED Einstellung so aus
![grafik](https://user-images.githubusercontent.com/34574073/233061593-c4ecfa42-9efa-451f-a1d4-a78a8320b7ee.png)

Seit kurzen dann so 
![Screenshot 2023-04-19 01](https://user-images.githubusercontent.com/34574073/233061706-d2ae8e70-f330-4249-8e83-9a6ee2a986f5.png)

das einzige, was ich seit der letzten Änderung am CCU Program für die LED Anzeigen gemacht habe, war den update auf Version 3.67.10-102 durchzuführen.

wie kann man dem Problem auf den Grund gehen?

Gruß
Chris

**Comment by alexreinert** [comment]
Ist das Problem auch in der heute erschienenen Version 3.69.7-104 vorhanden?

**Comment by 63chris** [comment]
gerade einen update gemacht. Jetzt ist es wieder wie es soll. Vielen Dank

**Comment by 63chris** [comment]
closed

**Comment by 63chris** [comment]
.
