### ISSUE TITLE
Debmatic 3.69.7.105

### ISSUE THREAD

**Issue by T1mey** [alexreinert/debmatic#340]
Hallo,

seit dem Update (Debmatic 3.69.7.105) keine Verbindung mehr von Homeassistant und noder ed zur CCU.
Schon irgendwas bekannt?

NodeRed meldet

`"    < BidCos-RF init Error: Unknown XML-RPC tag 'TITLE'"`

**Comment by alexreinert** [comment]
Nein, nichts bekannt.
Die Fehlermeldung klingt aber leicht danach, dass Nodered zu früh versucht auf die RPC Schnittstelle zuzugreifen.

**Comment by T1mey** [comment]
Ah ... nach dem Update sind keine Gerätemehrbedienbar. Sehr spät gesehen.

```
debmatic version: 3.69.7-105
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
```

`sudo dpkg-reconfigure pivccu-modules-dkms
` + reboot hat leider nicht geholfen 
`

**Comment by yagona** [comment]
Ich hatte das gleiche Problem nach einem Upgrade-Versuch des Raspi von "buster" auf "bullseye". Ein neues Image mit anschließendem Einspielen des letzten Backups war letztlich die Lösung.

**Comment by alexreinert** [comment]
Welche Hardware? Welches OS? Ausgabe vom dpkg-reconfigure?

**Comment by alexreinert** [comment]
Buster ist letztem Jahr EoL und wird nicht mehr unterstützt.

**Comment by Doreinie** [comment]
Hallo,
auch ich bekomme seit letztem update / upgrade die Fehlermeldung in iobroker: 

Cannot call init: [http://192.168.178.38:2010, ""] Unknown XML-RPC tag 'TITLE'

![image](https://user-images.githubusercontent.com/57943613/234195709-9cb42702-c0cb-4a8d-8284-4b5d48a48e0f.png)

gibt es da einen Befehl mit dem ich zur letzen funktionierenden Version zurück gehen kann?
Auch meine Installation ist noch auf Buster.

**Comment by Alex18081** [comment]
Auch nach der update, starte debmatic nicht mehr(
sudo dpkg-reconfigure pivccu-modules-dkms geht durch, meldet das reboot soll durch geführt werden, aber nach dem neustart das gleiche problem. (Linux Mint 19.3 Tricia/bionic)

**Comment by alexreinert** [comment]
Was liefert debmatic-info?

**Comment by alexreinert** [comment]
Und welches OS und welche Hardware?

**Comment by Alex18081** [comment]
> debmatic-info

debmatic-info
debmatic-info: Befehl nicht gefunden.

Bei versuch debmatic zu installieren bekomme ich
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 debmatic : Hängt ab von (vorher): libc6-i386 (>= 2.29) aber 2.27-3ubuntu1.6 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

OS Linux Mint 19.3, Hardware ein PC mit hb-rf-usb

**Comment by alexreinert** [comment]
Linux Mint 19.3 basiert auf Ubuntu 18.04 und das hat eine zu alte libc6 Version, welche nicht mehr unterstützt wird.

**Comment by alexreinert** [comment]
Version 3.67.10-99 ist die letzte debmatic Version, die dort noch funktionieren wird.

**Comment by Alex18081** [comment]
> Version 3.67.10-99 ist die letzte debmatic Version, die dort noch funktionieren wird.

Wie kriege ich die wieder darauf?
Gibst Möglichkeit CCU Einstellungen noch irgendwie rausholen? Dann konnte ich RPi mit neue System einschmeißen.. Ganze Fußbodenheizung wurde über homematic gesteuert

**Comment by Alex18081** [comment]
> 
Danke!  Habe jetzt Aktualisierung auf neue System gewagt. Ich Hofe es geht durch. Falls nicht, dann zurück zum Widerherstellung punkt und werde mit debmatic=3.68.10-99 versuchen.

**Comment by alexreinert** [comment]
Sorry, Tippo.
`sudo apt install debmatic=3.67.10-99`

**Comment by Alex18081** [comment]
> Sorry, Tippo. `sudo apt install debmatic=3.67.10-99`

kann das sein das wurde auch Firmware vom modul mit überschrieben? 
Habe jtzt bei ioBroker meldung
 Init not possible, going to stop: write EPROTO  140202233939904:error:1408F10B:SSL routines:ssl3_get_record:wrong  version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332

Und im log vom debmatic

2023-04-25 17:19:15,601 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 18 out of 23 
2023-04-25 17:19:15,665 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
2023-04-25 17:19:15,665 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
2023-04-25 17:19:15,669 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LegacyBackendNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
2023-04-25 17:19:15,675 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-5] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
2023-04-25 17:19:15,681 de.eq3.vertx.manager.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [legacy.api.worker][connector.open])

**Comment by alexreinert** [comment]
Ggf. wird auch die Firmware des Moduls überschrieben, je nachdem von welcher Version man kam und welches Funkmodul man hat.

**Comment by Alex18081** [comment]
> Hallo,
> 
> seit dem Update (Debmatic 3.69.7.105) keine Verbindung mehr von Homeassistant und noder ed zur CCU. Schon irgendwas bekannt?
> 
> NodeRed meldet
> 
> `" < BidCos-RF init Error: Unknown XML-RPC tag 'TITLE'"`

 Init not possible, going to stop: Unknown XML-RPC tag 'TITLE'

Ich bekomme diese meldung sobald Authentifizierung (XML-RPC) deaktiviere

**Comment by Alex18081** [comment]
> Ggf. wird auch die Firmware des Moduls überschrieben, je nachdem von welcher Version man kam und welches Funkmodul man hat.

also ich bin jetzt vom 3.69.7.105 auf 3.67.10-99 zurück. (System update leider nicht geklappt)

debmatic version: 3.67.10-99
Kernel modules: Not available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: HB-RF-USB@usb-0000:00:14.0-5 (/dev/raw-uart)
 Board serial:  PEQ017XXX
 Radio MAC:     0x67XXXX
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: HB-RF-USB@usb-0000:00:14.0-5 (/dev/raw-uart)
 SGTIN:         3014F711A061A7D8XXXXXXXX
 Radio MAC:     0xBEXXXX

**Comment by T1mey** [comment]
Hallo @all,

also mein OS ist ein debian bookworm. 
Hardware ist ein HB-RF-USB-2 + RPI-RF-MOD

Bin gerade auf 3.67.10-99 zurück aber dort funktioniert aktuell nichts mehr.

**Comment by T1mey** [comment]
weiss nicht genau welche logs ich anschauen muss aber in hmserver.log steht folgendes:

```
io.vertx.core.VertxException: Thread blocked
        at sun.misc.Unsafe.park(Native Method) ~[?:1.8.0_362]
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) ~[?:1.8.0_362]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078) ~[?:1.8.0_362]
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) ~[?:1.8.0_362]
        at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99) ~[HMServer.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80) ~[HMServer.jar:?]
        at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70) ~[HMServer.jar:?]
        at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24) ~[HMServer.jar:?]
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMServer.jar:?]
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:187) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:162) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$83/1918327665.run(Unknown Source) ~[?:?]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$82/1409319019.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMServer.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[HMServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMServer.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMServer.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMServer.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
```

**Comment by alexreinert** [comment]
@T1mey 
Welches OS hast du jetzt genau? Erst schreibst du Debian Bookworm (welches noch gar nicht released ist), dann änderst du auf Ubuntu 22.04. Welche Hardware hast du genau? (Nicht nur Funkmodul, sondern auf der SBC oder PC)
Bei Ubunutu 22.04 brauchst du nicht auf die 3.67 zurück, da es da eine aktuelle libc6 gibt.
Was liefert debmatic-info? Was liefert lsusb?

**Comment by T1mey** [comment]
> @T1mey Welches OS hast du jetzt genau? Erst schreibst du Debian Bookworm (welches noch gar nicht released ist), dann änderst du auf Ubuntu 22.04. Welche Hardware hast du genau? (Nicht nur Funkmodul, sondern auf der SBC oder PC) Bei Ubunutu 22.04 brauchst du nicht auf die 3.67 zurück, da es da eine aktuelle libc6 gibt. Was liefert debmatic-info? Was liefert lsusb?

Hi... ja hatte mich vertan

Also es ist ein Fujitsu Futro s740. Darauf läuft ein Proxmox und darin eine VM mit 

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

debmatic-info

```
debmatic version: 3.69.7-105
Kernel modules: Not available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
```

lsusb
```
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 10c4:8c07 Silicon Labs HB-RF-USB-2
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd QEMU USB Tablet
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

**Comment by alexreinert** [comment]
@T1mey Was liefert `dpkg-reconfigure pivccu-modules-dkms`

**Comment by T1mey** [comment]
> @T1mey Was liefert `dpkg-reconfigure pivccu-modules-dkms`

/usr/sbin/dpkg-reconfigure: pivccu-modules-dkms ist kaputt oder nicht komplett installiert

**Comment by alexreinert** [comment]
@T1mey Dann bitte `apt install pivccu-modules-dkms` und ggf- `dpkg --configure -a` falls das entsprechend angezeigt wird und von beidem bitte die vollständige Ausgabe.

**Comment by T1mey** [comment]
> apt install pivccu-modules-dkms

```
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benöti                                                                                                         gt:
  dfu-programmer digitemp etherwake linux-image-5.15.0-69-generic
  linux-modules-5.15.0-69-generic linux-modules-extra-5.15.0-69-generic socat
  wakeonlan
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden NEUEN Pakete werden installiert:
  pivccu-modules-dkms
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Es müssen 43,0 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Holen:1 https://www.debmatic.de/debmatic stable/main amd64 pivccu-modules-dkms a                                                                                                         ll 1.0.81 [43,0 kB]
Es wurden 43,0 kB in 0 s geholt (137 kB/s).
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket pivccu-modules-dkms wird gewählt.
(Lese Datenbank ... 157791 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../pivccu-modules-dkms_1.0.81_all.deb ...
Entpacken von pivccu-modules-dkms (1.0.81) ...
pivccu-modules-dkms (1.0.81) wird eingerichtet ...
Create kernel modules ... Done
Enable DKMS service ... Done
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

zweiter Befehl wird nicht gefordert.

**Comment by alexreinert** [comment]
@T1mey ok, dann bitte Reboot, 10 Minuten warten und dann debmatic-info
Und es ist für mich ein Rätsel, wieso du das Paket pivccu-modules-dkms deinstalliert hast.

**Comment by T1mey** [comment]
Hab ich eigentlich nicht getan...

Nach 10 min liefert debmatic-info leider immer noch 

```
debmatic version: 3.69.7-105
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
```

**Comment by alexreinert** [comment]
Dann bitte mal die Ausgabe von `modprobe hb_rf_usb_2` und `dmesg | grep usb`

**Comment by T1mey** [comment]
`modprobe: ERROR: could not insert 'hb_rf_usb_2': Exec format error`

**Comment by T1mey** [comment]
`modprobe: ERROR: could not insert 'hb_rf_usb_2': Exec format error`

```
[    0.551071] usbcore: registered new interface driver usbfs
[    0.551095] usbcore: registered new interface driver hub
[    0.551120] usbcore: registered new device driver usb
[    0.741412] pci 0000:00:01.2: quirk_usb_early_handoff+0x0/0x160 took 80796 us                                                                                                         ecs
[    0.866939] pci 0000:02:1b.0: quirk_usb_early_handoff+0x0/0x160 took 122321 u                                                                                                         secs
[    1.513541] usb usb1: New USB device found, idVendor=1d6b, idProduct=0001, bc                                                                                                         dDevice= 5.15
[    1.513550] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                                                                         1
[    1.513555] usb usb1: Product: UHCI Host Controller
[    1.513559] usb usb1: Manufacturer: Linux 5.15.0-71-generic uhci_hcd
[    1.513563] usb usb1: SerialNumber: 0000:00:01.2
[    1.849517] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    2.035699] usb 1-1: New USB device found, idVendor=0627, idProduct=0001, bcd                                                                                                         Device= 0.00
[    2.035770] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=1                                                                                                         0
[    2.035821] usb 1-1: Product: QEMU USB Tablet
[    2.036858] usb 1-1: Manufacturer: QEMU
[    2.037857] usb 1-1: SerialNumber: 28754-0000:00:01.2-1
[    3.196640] usbcore: registered new interface driver usbhid
[    3.197620] usbhid: USB HID core driver
[    3.444699] input: QEMU QEMU USB Tablet as /devices/pci0000:00/0000:00:01.2/u                                                                                                         sb1/1-1/1-1:1.0/0003:0627:0001.0001/input/input5
[    3.486306] hid-generic 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Mou                                                                                                         se [QEMU QEMU USB Tablet] on usb-0000:00:01.2-1/input0
[    3.555290] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bc                                                                                                         dDevice= 5.15
[    3.555294] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                                                                         1
[    3.555296] usb usb2: Product: xHCI Host Controller
[    3.555298] usb usb2: Manufacturer: Linux 5.15.0-71-generic xhci-hcd
[    3.555300] usb usb2: SerialNumber: 0000:02:1b.0
[    3.570940] usb usb3: We don't know the algorithms for LPM for this host, dis                                                                                                         abling LPM.
[    3.571062] usb usb3: New USB device found, idVendor=1d6b, idProduct=0003, bc                                                                                                         dDevice= 5.15
[    3.571108] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                                                                         1
[    3.571147] usb usb3: Product: xHCI Host Controller
[    3.571174] usb usb3: Manufacturer: Linux 5.15.0-71-generic xhci-hcd
[    3.571209] usb usb3: SerialNumber: 0000:02:1b.0
[    4.085328] usb 2-1: new full-speed USB device number 2 using xhci_hcd
[    4.241654] usb 2-1: New USB device found, idVendor=10c4, idProduct=8c07, bcd                                                                                                         Device= 1.01
[    4.242899] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.244137] usb 2-1: Product: HB-RF-USB-2
[    4.245409] usb 2-1: Manufacturer: Alexander Reinert
[    4.246664] usb 2-1: SerialNumber: 0001
```

**Comment by alexreinert** [comment]
@T1mey Deine Kernel Header sind vermutlich auf Module signing konfiguriert. Das kenne ich nur, wenn die Header über den Installer frisch installiert sind und nicht im laufenden Betrieb. Daher explizit die Frage: Ist das eine alte Installation oder ist die VM frisch installiert?
Bei einer frischen Installation hilft (bei x64) `apt install --reinstall linux-headers-$(uname -r) && dpkg-reconfigure pivccu-modules-dkms`. Sollte danach der modprobe Befehl ohne Fehler laufen, dann braucht es noch einen Reboot.

**Comment by T1mey** [comment]
Das war eine Installation die ein wenig mehr als 1 Monat her ist.
Die lief bis die Tage problemlos und also ich auf die neue ccu version gehen wollte (apt update & upgrade) ging nichts mehr.

Jetzt funktioniert es wieder! Vielen lieben Dank!!!

**Comment by Doreinie** [comment]
Hatte ein ähnliches Problem mit pivccu was ich gestern beheben konnte. Vielleicht passt es hier auch.
`sudo rpi-update 
sudo Reboot
sudo apt reinstall pivccu-modules-raspberrypi raspberrypi-kernel`

Dann funktionierte alles wieder

**Comment by alexreinert** [comment]
@Doreinie Bitte nicht rpi-update verwenden, selbst die Raspberry Pi Foundation rät davon ab. Das hat man früher gebraucht, bevor sie den Kernel und die Firmware sauber in deb Pakete verpackt hatten.
