### ISSUE TITLE
HmIP-RFUSB nicht erkannt

### ISSUE THREAD

**Issue by MubiTec** [alexreinert/debmatic#342]
Hallo,
Ich krieg meinen Stick einfach nicht verbunden.
Hab debian 11 als lxc container in proxmox und die Installation von debmatic  nach der Anleitung erfolgreich durchgeführt.
Ich hab auf dem Host cp210x aktiviert, per udev rule den symlink auf ttyHMIP erstellt und ttyHMIP an den Container übergeben.
Wie im Screenshot zu sehen ist im Container der Stick übe lsusb sichtbar und auch ttyHMIP da.
sudo detect_radio_module --debug /dev/ttyHMIP meldet aber, dass der Stick keine Funktion hat.
Was kann ich tun? Bin gerade mit meinem Wissen am Ende 
![Screenshot_20230505_213946_Termius](https://user-images.githubusercontent.com/44448393/236555864-e2b343f8-f35c-4524-aaab-6b240fe9f43f.jpg)

**Comment by alexreinert** [comment]
Meine Empfehlung: Nicht Container, sondern VM nehmen.

Ansonsten darf nicht der cp210x Treiber genutzt werden, sondern es muss der raw-uart Kernel Module auf dem Host installiert und genutzt werden und die entsprechenden cgroups gesetzt werden, damit der Container Rechte für den Zugriff hat, was mit Proxmox 7 und cgroup2 deutlich schwieriger geworden ist.

**Comment by MubiTec** [comment]
Treiber ist deinstalliert. Gebracht hat es nix.
Jetzt gibt's doch die VM 👍
Gibt's Richtwerte mit welchen Ressourcen diese dimensioniert werden sollte? Speicher, RAM etc?
Danke schon mal für die Hilfe!

**Comment by alexreinert** [comment]
Mind. 2 CPU Kerne
Mind. 512 MB RAM fest zugewiesen, Mind. 2GB RAM Ballooning
Mind. 10GB HDD, Virtio
Virtio Netzwerkkarte
Funkstick als USB2 Gerät (nicht als USB3)

**Comment by MubiTec** [comment]
Danke!
