### ISSUE TITLE
debmatic auf neuem rpi nicht erreichbar

### ISSUE THREAD

**Issue by SpRiNgToIfEl** [alexreinert/debmatic#343]
Hallo,

ich habe für einen Kollegen einen neuen RPI 4 mit Debian Bullseye 64-bit und Debmatic aufgesetzt. Die Installation verlief unauffällig und ohne Probleme.

Leider lässt sich Debmatic nicht unter der IP des RPI erreichen, Bild anbei.

Anscheinend ist keine "Startseite" hinterlegt?
Wie kann hier das Problem gelöst werden?

Besten Dank für die Hilfe!

Gruß
Stefan

![Screenshot_20230511-190357_Chrome~2](https://github.com/alexreinert/debmatic/assets/64694788/642cee2d-2127-45a0-97aa-d0e45873e9bf)

**Comment by SpRiNgToIfEl** [comment]
Also nach dem aufrufen der IP im Browser erscheint das obere Bild. Oder meinst du eine log?

**Comment by alexreinert** [comment]
Das ist ein Befehl in der Konsole.

**Comment by SpRiNgToIfEl** [comment]
achja, hier ein Bild dazu

![screen](https://github.com/alexreinert/debmatic/assets/64694788/1250fa23-3c1d-4630-9b1e-e89450eaa78d)

**Comment by alexreinert** [comment]
Dann bitte einmal die Ausgabe von
`sudo apt install --reinstall debmatic` und die Info, ob es danach läuft.

**Comment by SpRiNgToIfEl** [comment]
...es funktioniert nun. Hast du etwas geändert?

**Comment by SpRiNgToIfEl** [comment]
kann man evtl bei einer neuinstallstion gleich im voraus einen anderen port angeben?

wäre hilfreich falls neben debmatic auch z.b. iobroker, octopi (mehrere 3d-drucker instanzen) und andere sachen auf den RPI installiert werden sollten...

**Comment by alexreinert** [comment]
Nein, ich vermute, das sich bei ersten Installation irgendwas verschluckt hat bei Aktivieren der Lighttpd Config.

**Comment by alexreinert** [comment]
Automatisch ist da aktuell nichts vorgesehen, es geht da im Moment nur die Anpassung nach der Installation.

**Comment by SpRiNgToIfEl** [comment]
alles klar, danke für die info und die hilfe.

bzgl. den ports: vielleicht wäre was man zukünftig mit einbinden könnte. eine abfrage ob standard oder ob ein besonderer port genutzt werden soll. dieses wird auch bei octopi abgefragt (mehrere instanzen).
