### ISSUE TITLE
HmIP-HAP als LAN-Router einbinden (Advanced Routing) ?

### ISSUE THREAD

**Issue by AndreasBerz** [alexreinert/debmatic#344]
Kann man einen HmIP-HAP als LAN-Router in der Debmatic einbinden (Advanced Routing) ?
Ich bin da nicht so optimistisch, weil schon der Button "Access Points mit inkompatibler FW" in der Systemsteuerung fehlt.

Ich war dann mal neugierig und habe es einfach ausprobiert. Aber weder Anlernen mit Internetzugang, noch Anlernen ohne Internetzugang konnte den HmIP-HAP finden.

Den HmIP-HAP hatte ich zuvor zweimalig auf Werkseinstellungen zurückgesetzt.
Debmatic läuft in der neusten Version unter Xubuntu 20.04 auf Intel-NUC.
Als Funkmodul wird HB-RF-ETH mit RPI-RF-MOD eingesetzt.

**Comment by alexreinert** [comment]
Doch das geht.
Der Button ist in der letzten CCU Version seitens eQ-3 entfernt worden.
Welche Farbe hat die LED vom HmIP-HAP?

**Comment by AndreasBerz** [comment]
Der Button leuchtet Blau.
Der Bootvorgang des HmIP-HAP läuft ungefähr so ab: erst orange, dann gelb, dann blau blinken, dann blau konstant.
Wenn ich den Tutorial-Videos glauben darf, dann sollte ein HmIP-HAP im Router-Betrieb türkis leuchten.
Jetzt kommt mir ein Gedanke!
Muss der HmIP-HAP per Funk an die Debmatik-CCU angelernt werden, oder geht das per LAN ?
Ich sitze hier im Dachgeschoss und das HB-RF-ETH ist zwei Etagen weiter unten im EG.
Ich habe auch zwei HmIP-Devices hier oben, die konnte ich problemlos anlernen und funktionieren im Normalbetrieb trotz halber/mittlerer Empfangsstärke sehr gut. Aber Firmware-Update dieser beiden Devices geht definitiv über diese Distanz nicht. 
Ich musste dazu das HB-RF-ETH ins Dachgeschoss holen dort ans LAN anschließen.

**Comment by alexreinert** [comment]
Wie lernst du genau an? Der richtige Vorgang wäre HAP vom Strom trennen, Anlernmodus in der CCU starten und dann den HAP wieder am Strom anschließen ohne dabei den Button zu drücken.
Türkis leuchtet er erst, wenn er mit der CCU gekoppelt ist.

**Comment by AndreasBerz** [comment]
Ich habe sämtliche Varianten durchgeprobt:
-Erst Anlernen und dann Strom
-Erst Strom, dann Anlernen, dann den Button auf HAP
-Anlernen am gleichen Switch
-Anlernen bei gesperrter Interverbindung in Fritzbox
-Anlernen in der Nähe von HB-RF-ETH
...geht alles nicht, also nichts im Posteingang.
Vielleicht verträgt sich der HmIP-HAP innerhalb der Debmatic nicht mit einem bereits vorhanden Homatic-Wired-Gateway  (altes Gateway, nicht DRAP).
Den HAP kann ich aber über die Homatic-App für Android ansprechen.
Dort steht er hätte Firmware 2.4.48 und es gibt keine weiteren Firmware Updates.

**Comment by alexreinert** [comment]
Wenn du ihn über die ansprechen kannst, dann ist er mit der App gekoppelt und kann nicht an die CCU angelernt werden.

**Comment by AndreasBerz** [comment]
Die Kopplung mit der App habe ich erst ausprobiert, nachdem alle Versuche des Anlernens an der Debmatic-CCU gescheitert sind.
Ich wollte einfach mal sehen, ob der HAP prinzipiell funktioniert und welchen Firmwarestand er hat.
Zwischen den Anlernversuchen an der Debmatic-CCU habe ich auch öfters mal einen Werksreset gemacht.
Vielleicht ist ja ein Wired-Hm-LAN-Gateway und ein HmIP-HAP als LAN-Router innerhalb einer CCU zu viel gewollt.
