### ISSUE TITLE
Installationsprobleme

### ISSUE THREAD

**Issue by derderneburger** [alexreinert/debmatic#345]
Hi Alex,

ich habe leider schon ein Problem bei der Installation auf meinem Raspberry Pi 4 mit dem aktuellsten Raspberry Os.

Anleitung: https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md

Schon bei Punkt 1 bekomme ich folgende Meldung am Ende:

> W: Fehlschlag beim Holen von https://apt.debmatic.de/debmatic/dists/stable/InRelease Verbindung mit apt.debmatic.de:443 nicht möglich (65.108.197.112) - connect (111: Verbindungsaufbau abgelehnt) Verbindung mit apt.debmatic.de:443 kann nicht aufgebaut werden (2a01:4f9:1a:9956:7::8). - connect (101: Das Netzwerk ist nicht erreichbar)
> W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

Demenstprechend geht beim 2. Punkt nur der Erste Teil. Beim 2. bekomme ich wieder eine Fehlermeldung.

> E: Paket pivccu-modules-dkms kann nicht gefunden werden.

dementsprechend kann ich den letzten Punkt ja auch vergessen. Also die installation an sich. Die Schritt dazwischen benötige ich ja nicht, da ich die Platine von dir habe und den RF-Mod nicht an den GPIO Pins habe.

**Comment by alexreinert** [comment]
Die Schritte bauen aufeinander auf, wenn der erste fehlschlägt, kann man nicht einfach mit den anderen weitermachen.

Ich vermute, dass das Problemvon einen Reboot der APT Servers kommt, den ich vorhin im Zuge von Wartungsarbeiten durchgeführt habe. Bitte nochmal probieren.

**Comment by derderneburger** [comment]
Sry für die späte Antwort. Jetzt hat alles funktioniert.
