### ISSUE TITLE
Lost connection to HMIP-RFIP on 3.69.7-108

### ISSUE THREAD

**Issue by WallyDW** [alexreinert/debmatic#346]
I updated my Debmatic to newest version and then lost access to the USB stick.
I could not find any errors and then tried to install RaspberryMatic instead to see if that worked.
It did not, but in the logs this line occurred.

Updating Homematic RF-Hardware: HMIP-RFUSB: =>4.4.18, ERROR ( != 4.4.18)

I then found a thread on the RaspberryMatic GitHub page about a similar issue.
https://github.com/jens-maus/RaspberryMatic/issues/1516

Is this the same issue with a new version and what info can I give you to help in debugging?

```
root@ha:/# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1b1f:c020 eQ-3 Entwicklung GmbH HmIP-RFUSB
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

My stick is bought directly from ELV, so it is not a Telekom stick and Debmatic have been running for nearly 2 years with that stick and Debmatic.

**Comment by alexreinert** [comment]
Please describe your hardware setup and pprovide the output of `debmatic-info`

**Comment by WallyDW** [comment]
Setup is a Debian 11 running on a HP fanless laptop with a HMIP-RFUSB stick connected by a short extension cable.
The Debian 11 is fully updated and with the update to 108 of Debmatic I also got like 17 other packages updated, so it might not be Debmatic at all.
I have tried to install version 105, but I get a fail on the apt command for that version saying it is not available.

I probably made the error of uninstalling Debmatic and then reinstall it, because there is no hardware info in the outputs anymore.

```
root@ha:/# debmatic-info
debmatic version: 3.69.7-108
OS:               Debian GNU/Linux 11 (bullseye)
Kernel:           5.10.0-23-amd64 x86_64
Service Status:   Running
Kernel modules:   Not available
Raw UART dev:     Not available
HMRF Hardware:    unknown
HMIP Hardware:    unknown
```

```
root@ha:/# cat /var/hm_mode
HM_HOST='debmatic'
HM_MODE='NORMAL'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='none'
HM_LED_RED=''
HM_LED_RED_MODE1='none'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_HOST_GPIO_UART=''
HM_HOST_GPIO_RESET=''
HM_RTC=''
HM_HMIP_DEV=''
HM_HMIP_DEVNODE=''
HM_HMIP_SERIAL=''
HM_HMIP_VERSION=''
HM_HMIP_SGTIN=''
HM_HMIP_ADDRESS=''
HM_HMIP_ADDRESS_ACTIVE=''
HM_HMIP_DEVTYPE=''
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HMRF_ADDRESS=''
HM_HMRF_ADDRESS_ACTIVE=''
HM_HMRF_DEVTYPE=''
```

**Comment by WallyDW** [comment]
apt-transport-https/stable,stable,now 2.2.4 all [Installeret]
build-essential/stable,stable,now 12.9 amd64 [Installeret]
bison/stable,stable,now 2:3.7.5+dfsg-1 amd64 [Installeret]
flex/stable,stable,now 2.6.4-8 amd64 [Installeret]
libssl-dev/stable-security,stable-security,now 1.1.1n-0+deb11u5 amd64 [Installeret]
pivccu-modules-dkms/stable,stable,now 1.0.82 all [Installeret]
debmatic/stable,stable,now 3.69.7-108 amd64 [Installeret]

**Comment by alexreinert** [comment]
The kernel modules are missing.
Please provide output of `dpkg-reconfigure pivccu-modules-dkms` (If there is an error message pointing to a logfile, please provide contents of that file, too)

**Comment by WallyDW** [comment]
running `dpkg-reconfigure pivccu-modules-dkms`  seems to have solved it.
Thanks for the help!
