### ISSUE TITLE
Entfernung zwischen Debmatic Host und Funkmodul

### ISSUE THREAD

**Issue by markusklein01** [alexreinert/debmatic#347]
Ich betreibe meine CCU3 mit +80 HMIP Geräten und habe leider alle 9-12 Monate eine defekte SD Card im System. Daher die Idee stattdessen auf DebMatic zu switchen. Problemstellung: der bereits existente Proxmox Server ist außerhalb des Hauses, die HMIP logischerweise alle im Haus. Gibt es eine Möglichkeit das Funkmodul im LAN zu platzieren und trotzdem von Seiten DebMatic anzusteuern? Danke.

**Comment by alexreinert** [comment]
Was heißt außerhalb des Hauses? Grundsätzlich gibt es die Platine HB-RF-ETH, aber die muss sich im gleichen LAN befinden (aufgrund der Anforderungen an die maximalen Latenzen).

**Comment by alexreinert** [comment]
Auf die HB-RF-ETH wird das eigentliche Funkmodul aufgesteckt und diese ist dann per Ethernet (daher der Name) mit debmatic verbunden. Ob debmatic dabei auf Bare Metal läuft oder innerhalb einer Proxmox VM ist egal. Einzig sollte man bei Proxmox die Firewall für diese VM deaktivieren, weil die einiges an zusätzliches Latenz bringt.
