### ISSUE TITLE
Nach update auf 3.69.7.108 ist "Status und Bedienung" fast leer

### ISSUE THREAD

**Issue by pinsel2006** [alexreinert/debmatic#348]
Hallo!

Nach dem update und dem reboot zeigt die Liste unter "Status und Bedienung" nur noch meine Gruppen (Heizgruppen => Thermostate, Heizkörperregler und Fensterkontakte), aber alle anderen Geräte sind weg. Unter "Einstellungen" habe ich noch alles, aber es ist nichts bedienbar und auch Funktionstests laufen nicht.

Hardware ist ein Raspberry 4 mit RPI-RF-Mod.
Debian Version ist die 11.7.

**Comment by pinsel2006** [comment]
Fast vergessen, die Bridge im Openhab meldet jetzt auch:
COMMUNICATION_ERROR
org.xml.sax.SAXException: Unknown XML-RPC tag: title

**Comment by alexreinert** [comment]
Was liefert debmatic-info auf der Konsole?

**Comment by pinsel2006** [comment]
debmatic version: 3.69.7-108
OS:               Debian GNU/Linux 11 (bullseye)
Kernel:           6.1.21-v8+ aarch64
Service Status:   Running
Kernel modules:   Not available
Raw UART dev:     Not available
Rasp.Pi UART:     Assigned to GPIO pins
HMRF Hardware:    unknown
HMIP Hardware:    unknown

**Comment by alexreinert** [comment]
Ich sehe es grade im Text im initialen Text.

Was liefert `sudo dpkg-reconfigure pivccu-modules-dkms`?
Handelt es sich um ein 64 Bit Image oder um ein 32 Bit Image,bei dem nur der Kernel auf 64 Bit gestellt wurde?

**Comment by pinsel2006** [comment]
Ja, genau, wurde durchgeführt, da es durch das popup ja gefordert war.

Das liefert das reconfigure:
Disabled DKMS service ... Done
Remove obsolete kernel modules ... Done
Ensure non mixed processor architecure ... Done
Create kernel modules ... Done
Enable DKMS service ... Done

Mit der Forderung nach einem weiteren Neustart.
.
Welcher jetzt auch wirklich das Problem gelöst hat.
debmatic-info liefert jetzt:
`
debmatic version: 3.69.7-108
OS:               Debian GNU/Linux 11 (bullseye)
Kernel:           6.1.21-v8+ aarch64
Service Status:   Running
Kernel modules:   Available
Raw UART dev:     Available
Rasp.Pi UART:     Assigned to GPIO pins
HMRF Hardware:    RPI-RF-MOD
 Connected via:   GPIO@fe201000.serial (/dev/raw-uart)
 Board serial:    5A4993F334
 Radio MAC:       0xFFF334
HMIP Hardware:    RPI-RF-MOD
 Connected via:   GPIO@fe201000.serial (/dev/raw-uart)
 SGTIN:           3014F711A0001F5A4993F334
 Radio MAC:       0xBB3E0F
`

Alles ist wieder da und auch die Deviceliste in openhab ist wieder durchgehend grün.
DANKE!
