### ISSUE TITLE
Status-LED des RPI-RF-MOD bleibt dunkel

### ISSUE THREAD

**Issue by tzdisco4** [alexreinert/debmatic#349]
Hallo Alex,

ich habe seit langem debmatic und FHEM auf einem ASUS Tinkerboard-S laufen. Vor zwei Tagen wurde von einem Elektriker an der Hausverteilung gearbeitet. Es war zu einem Fehler gekommen, der eine Überspannung hätte erzeugen können. Nach den Arbeiten wollte ich beide Dienste neue starten (funktioniert wohl wg. timing nach dem Reboot nicht automatisch, keine Verbindung). Das schien auch zu funktionieren, jedoch war das WebUI der Debmatic nicht zu erreichen. Ich habe dann nachgeschaut und die Signal-Led des RPI-RF-MOD oben auf dem ELV-Gehäuse war dunkel. Wg. des Verdachts der Überspannung dachte ich, es wäre defekt und habe ein neues bestellt, das hat aber nichts geändert.

Heute habe ich die logfiles genauer analysiert und schlussendlich gefunden, dass der lighttpd nicht lief, weil er die Datei /var/log/lighttpd/error.log wg. permissions nicht öffnen konnte. Vielleicht  lag's an mehrfachem Strom-aus und wieder -an.

Nun läuft alles wieder, aber die LED bleibt dunkel. Und ich bin mir nicht sicher, ob es nicht vor den Elektrikerarbeiten auch so war. Ich habe vor ein paar Wochen nach längerer Zeit mal wieder ein apt update/upgrade gemacht, aber es hakte, wenn ich mich recht erinnere, bei debmatic irgendwie an einer nicht verfügbaren C++-Lib. Bin mir aber nicht sicher.

Der aktuelle Status ist:
`
root@tinkerboard:~# debmatic-info 
debmatic version: 3.61.7-90
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
 Connected via: GPIO@ff190000.serial (/dev/raw-uart)
 Board serial:  5A499401F3
 Radio MAC:     0xFF01F3
HMIP Hardware:  RPI-RF-MOD
 Connected via: GPIO@ff190000.serial (/dev/raw-uart)
 SGTIN:         3014F711A0001F5A499401F3
 Radio MAC:     0xB659E9
`
Und bezüglich upgrade:

root@tinkerboard:~# apt list -a --upgradable
Listing... Done
debmatic/stable 3.69.7-108 armhf [upgradable from: 3.61.7-90]
debmatic/stable 3.67.10-102 armhf
debmatic/stable 3.67.10-99 armhf
debmatic/stable 3.65.11-97 armhf
debmatic/stable 3.65.8-95 armhf
debmatic/stable 3.63.9-93 armhf
debmatic/stable,now 3.61.7-90 armhf [installed,upgradable to: 3.69.7-108]
debmatic/stable 3.59.6-78 armhf
debmatic/stable 3.57.5-71 armhf
debmatic/stable 3.55.10-66 armhf
debmatic/stable 3.53.34-59 armhf
debmatic/stable 3.51.6-47 armhf
debmatic/stable 3.49.17-41 armhf
debmatic/stable 3.47.22-39 armhf
debmatic/stable 3.45.7-27 armhf
debmatic/stable 3.43.15-15 armhf
debmatic/stable 3.41.11-5 armhf

pivccu-modules-dkms/stable 1.0.82 all [upgradable from: 1.0.71]
pivccu-modules-dkms/stable 1.0.80 all
pivccu-modules-dkms/now 1.0.71 all [installed,upgradable to: 1.0.82]
pivccu-modules-dkms/stable 1.0.68 all
`
Aber apt upgrade liefert:

root@tinkerboard:~# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  pivccu-modules-dkms
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Ich habe nun den Verdacht, dass mit den neuen Kernel-Modulen funktionieren würde. Wäre das möglich?

Danke

Thomas

**Comment by alexreinert** [comment]
Gut möglich, dass das an der Version liegt, die mittlerweile gut 2,5 Jahre alt ist, in der Zeit hat sich eine Menge in den Kernel Modulen, in den Device Tree Patches und auch in Armbian getan, kann sehr gut sein, dass da jetzt irgendwas auf deinem System auseinanderläuft.

**Comment by tzdisco4** [comment]
Danke für Deine Einschätzung! Ich habe gerade mal versucht, etwas neuere debmatic-Versionen zu installieren. Dabei bin ich erfolgreich bis zur Version 3.67.10-99 gekommen. Bei der Version 3.67.10-102 gibt es dann folgende Fehlermeldung:
`root@tinkerboard:~# apt upgrade debmatic=3.67.10-102
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 debmatic : PreDepends: libc6 (>= 2.29) but 2.28-10+deb10u2 is to be installed
E: Broken packages
`
Und die dependencies für libc6 sehen seltsam aus:
root@tinkerboard:~# apt depends libc6
libc6
  Depends: libgcc1
  Conflicts: openrc (<< 0.27-2~)
  Breaks: <hurd> (<< 1:0.5.git20140203-1)
  Breaks: <libtirpc1> (<< 0.2.3)
  Breaks: locales (<< 2.28)
  Breaks: locales-all (<< 2.28)
  Breaks: nocache (<< 1.1-1~)
  Breaks: nscd (<< 2.28)
  Breaks: r-cran-later (<< 0.7.5+dfsg-2)
  Recommends: libidn2-0 (>= 2.0.5~)
  Suggests: glibc-doc
 |Suggests: debconf
  Suggests: <debconf-2.0>
    cdebconf
    debconf
  Suggests: libc-l10n
  Suggests: locales

Da werde ich noch etwas forschen müssen ...

Version 3.67.10-99 läuft, aber die LED ist erwartungsgemäß immer noch dunkel.

**Comment by alexreinert** [comment]
Das Forschen kann ich dir vermutlich abnehmen: Es braucht auch ein aktuelles Debian (Bullseye oder Bookworm) bzw. ein aktuelles Ubuntu (>= 22.04).

**Comment by tzdisco4** [comment]
Danke schön für diesen Hinweis! Da werde ich erstmal meinen Forschungsschwerpunkt auf den Update des Kernels legen. Ich werden berichten.

**Comment by tzdisco4** [comment]
Zur Vorbereitung des Upgrades auf Bullseye wollte ich die aktuelle Installation "bereinigen". Als Empfehlung gab es u. a. den Hinweis, Pakete aus dem "Hold" zu holen. Das ist mir letztlich auch mit "apt-get install pivccu-modules-dkms" gelungen (installierte die Version 1.0.82), führte allerdings zur Deinstallation von debmatic.

Die zuletzt erfolgreich installierbare debmatic-Version 3.67.10-99 habe ich dann wieder installiert, die lief aber mit dem pivccu...-Paket nicht mehr, weil das RPI-RF-MOD nicht mehr anzusprechen war. Ich habe dann einfach mal pivccu-modules-dkms Version 1.0.80 installiert. Damit lief debmatic wieder und im Halbdunkel so gegen 22:00 Uhr leuchtete mit die LED auch plötzlich entgegen. Diese beiden Versionen funktionieren offensichtlich zusammen noch mit buster.

Ich bin allerdings verwundert, dass der apt-Mechanismus bei der ersten Installation von debmatic 3.67.10-99 nicht auch automatisch pivccu.. 1.0.80 ( 1.0.71 war zu dem Zeitpunkt installiert) mit installiert hat. Ich dachte, solche Zusammenhänge würde apt erkennen können.

Das System läuft nun wieder, aber trotzdem werde ich nun bald das Upgrade auf bullseye versuchen. Mal schauen, ob mir das gelingt.

Danke nochmal für Deine Hinweise!
