### ISSUE TITLE
Support for HM-Print AddOn

### ISSUE THREAD

**Issue by schmimat** [alexreinert/debmatic#35]
Hallo,

ein AddOn das mir noch fehlt zum Wechsel von pivccu auf debmatic ist HM-Print.
Wir dieses Addon kommen?

Vielen Dank für deine Bemühungen

mfG Matthias

**Comment by alexreinert** [comment]
Ich muss hier erst noch die Lizenz klären

**Comment by 63chris** [comment]
ist zwar schon etwas älter, aber auch mir fehlt dieses sehr hilfreiche add-on
