### ISSUE TITLE
HB-RF-ETHmPoe als Fertigmodul

### ISSUE THREAD

**Issue by markusklein01** [alexreinert/debmatic#350]
Hallo!

Ich suche das o.g. Modul entweder als Fertigmodul oder jemanden, der mir das Modul zusammenlötet. Mir fehlt leider das erforderliche Werkzeug.

Danke und viele Grüße 
Markus

**Comment by alexreinert** [comment]
Hier ist der falsche Ort um danach zu suchen, das hier ist ein Issue Tracker für debmatic.
