### ISSUE TITLE
Apt Repo TLS failure

### ISSUE THREAD

**Issue by bjoerns1983** [alexreinert/debmatic#353]
I am seeing a fatal TLS Issue when i try to update throught https://apt.debmatic.de/debmatic
I am using Debian 11

Tried it with a browser an have the same problem.
Could some please double check that?

**Comment by bjoerns1983** [comment]
Fehl:2 https://apt.debmatic.de/debmatic stable InRelease                                                                                                                                   
  Could not handshake: Ein fataler TLS-Alarm wurde empfangen. [IP: 94.130.64.242 443]

**Comment by alexreinert** [comment]
I cannot see any issue on different clients/browsers and different source ips.

**Comment by bjoerns1983** [comment]
Seems to work again, at least the TLS error disappeared.
Another strange thing: shouldnt the Repo be at CCU3 FW 3.71?

My apt shows me 3.69 as newest version.

**Comment by alexreinert** [comment]
3.69.7 is the current stable version. 3.71.12 is currently only available in the testing repository.
See https://homematic-forum.de/forum/viewtopic.php?f=69&t=79574 (german language)

**Comment by bjoerns1983** [comment]
Thanks for the explanation
