### ISSUE TITLE
Debmatic, HB-RF-USB und Hifiberry (GPIOs nutzen)

### ISSUE THREAD

**Issue by mschlenstedt** [alexreinert/debmatic#355]
Hallo Alex,

ich habe ein RPI-RF-MOD auf einem HB-RF-USB. Ich dachte, dass ich so die GPIOs frei habe für andere Anwendungen. Ich habe auf der GPIO-Leiste ein Hifiberry Miniamp sitzen. Laut Doku benötigt der Hifberry folgende GPIOs:

`GPIOs 18-21 (pins 12, 35, 38 and 40) are used for the sound interface. GPIO16 can be used to mute the power stage. GPIO26 shuts down the power stage. You can’t use these GPIOs for any other purpose.`

Leider funktioniert der Hifberry nur, wenn ich den Debmatic-Service deaktiviere (systemctl disable debmatic). Sobald Debmatic läuft, funktioniert der Hifiberry nicht mehr.

Nutzt irgendetwas von Homematic / Debmatic trotzdem GPIOs, obwohl ich das HB-RF-USB nutze?

```
root@loxberry:~# debmatic-info
debmatic version: 3.71.12-109
OS:               Debian GNU/Linux 11 (bullseye)
Kernel:           6.1.21-v8+ aarch64
Service Status:   Running
Kernel modules:   Available
Raw UART dev:     Available
Rasp.Pi UART:     Assigned to GPIO pins
HMRF Hardware:    RPI-RF-MOD
 Connected via:   HB-RF-USB@usb-0000:01:00.0-1.4 (/dev/raw-uart1)
 Board serial:    58A9A71099
 Radio MAC:       0xFF1099
HMIP Hardware:    RPI-RF-MOD
 Connected via:   HB-RF-USB@usb-0000:01:00.0-1.4 (/dev/raw-uart1)
 SGTIN:           3014F711A0001F58A9A71099
 Radio MAC:       0xB67997
root@loxberry:~#


```

**Comment by alexreinert** [comment]
Ist das Paket pivccu-modulrs-raspberrypi installiert? Wenn ja, deinstallieren und neu starten.
Bitte aber auf keinen Fall das Paket pivccu-modules-dkms deinstallieren.

**Comment by mschlenstedt** [comment]
Das war's! 1000 Dank!
