### ISSUE TITLE
Nach Update, Funkmodul wird nicht erkannt

### ISSUE THREAD

**Issue by eapel** [alexreinert/debmatic#357]
Ich betreibe debmatic auf dem Asus Thinkerboard S.
Nach dem Update auf jammy startet homematic zwar, aber leider ohne das Funkmodul.
` sudo debmatic-info
debmatic version: 3.71.12-109
OS:               Armbian 23.8.3 jammy
Kernel:           6.1.50-current-rockchip armv7l
Service Status:   Running
Kernel modules:   Not available
Raw UART dev:     Not available
HMRF Hardware:    unknown
HMIP Hardware:    unknown`

`sudo dpkg-reconfigure pivccu-modules-dkms
[sudo] password for enrico:
Disabled DKMS service ... Done
Remove obsolete kernel modules ... Done
Create kernel modules ... FAILED
Remove DKMS package ... FAILED
Error! There is no instance of pivccu 1.0.84 for kernel 6.1.50-current-rockchip (armv7l) located in the DKMS tree.
Enable DKMS service ... Done`

Offenbar fehlen die Kernel Module.
Also sudo apt install --reinstall pivccu-modules-raspberrypi
Am Ende kommt es aber zu einer Fehlermeldung

`sudo apt install --reinstall pivccu-modules-raspberrypi
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  liblxc-common liblxc1 libpam-cgfs lxc lxc-utils lxcfs uidmap
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden zusätzlichen Pakete werden installiert:
  linux-headers-5.15.0-1041-raspi linux-headers-raspi linux-raspi-headers-5.15.0-1041
Die folgenden NEUEN Pakete werden installiert:
  linux-headers-5.15.0-1041-raspi linux-headers-raspi linux-raspi-headers-5.15.0-1041 pivccu-modules-raspberrypi
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 13,4 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 84,2 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
Holen:1 http://ports.ubuntu.com jammy-security/main armhf linux-raspi-headers-5.15.0-1041 armhf 5.15.0-1041.44 [12,3 MB]
Holen:2 https://apt.debmatic.de/debmatic stable/main armhf pivccu-modules-raspberrypi all 2.0-18 [2.940 B]
Holen:3 http://ports.ubuntu.com jammy-security/main armhf linux-headers-5.15.0-1041-raspi armhf 5.15.0-1041.44 [1.032 kB]
Holen:4 http://ports.ubuntu.com jammy-security/main armhf linux-headers-raspi armhf 5.15.0.1041.39 [2.308 B]
Es wurden 13,4 MB in 1 s geholt (10,3 MB/s).
Preconfiguring packages ...
Vormals nicht ausgewähltes Paket linux-raspi-headers-5.15.0-1041 wird gewählt.
(Lese Datenbank ... 65172 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../linux-raspi-headers-5.15.0-1041_5.15.0-1041.44_armhf.deb ...
Entpacken von linux-raspi-headers-5.15.0-1041 (5.15.0-1041.44) ...
Vormals nicht ausgewähltes Paket linux-headers-5.15.0-1041-raspi wird gewählt.
Vorbereitung zum Entpacken von .../linux-headers-5.15.0-1041-raspi_5.15.0-1041.44_armhf.deb ...
Entpacken von linux-headers-5.15.0-1041-raspi (5.15.0-1041.44) ...
Vormals nicht ausgewähltes Paket linux-headers-raspi wird gewählt.
Vorbereitung zum Entpacken von .../linux-headers-raspi_5.15.0.1041.39_armhf.deb ...
Entpacken von linux-headers-raspi (5.15.0.1041.39) ...
Vormals nicht ausgewähltes Paket pivccu-modules-raspberrypi wird gewählt.
Vorbereitung zum Entpacken von .../pivccu-modules-raspberrypi_2.0-18_all.deb ...
dpkg-divert: Warnung: Bitte geben Sie »--no-rename« explizit an, die Vorgabe wird in 1.20.x
auf »--rename« geändert werden
»Umleitung von /var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo zu /usr/share/rpikernelhack/overlays/pivccu-raspberr
ypi.dtbo durch rpikernelhack« wird hinzugefügt
Entpacken von pivccu-modules-raspberrypi (2.0-18) ...
linux-raspi-headers-5.15.0-1041 (5.15.0-1041.44) wird eingerichtet ...
linux-headers-5.15.0-1041-raspi (5.15.0-1041.44) wird eingerichtet ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.15.0-1041-raspi

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.0-1041-raspi ARCH=arm all.......
cleaning build area...

dummy_rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

dw_apb_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

eq3_char_loop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

fake_hmrf.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

generic_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

hb_rf_eth.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

hb_rf_usb.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

hb_rf_usb_2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

led_trigger_timer.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

meson_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

pl011_raw_uart.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

plat_eq3ccu2.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

rpi_rf_mod_led.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

rtc-rx8130.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-1041-raspi/updates/dkms/

depmod...
   ...done.
linux-headers-raspi (5.15.0.1041.39) wird eingerichtet ...
pivccu-modules-raspberrypi (2.0-18) wird eingerichtet ...
»Umleitung von /var/lib/piVCCU/dtb/overlays/pivccu-raspberrypi.dtbo zu /usr/share/rpikernelhack/overlays/pivccu-raspberrypi.dtbo durch rpikernelhack« wird entfernt
sed: can't read /var/lib/piVCCU/dtb/config.txt: No such file or directory
dpkg: Fehler beim Bearbeiten des Paketes pivccu-modules-raspberrypi (--configure):
 »installiertes pivccu-modules-raspberrypi-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 2 zurüc
k
Fehler traten auf beim Bearbeiten von:
 pivccu-modules-raspberrypi
piVCCU: DTB rk3288-tinker.dtb was already patched
piVCCU: DTB rk3288-tinker-s.dtb was already patched
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Wo muss ich denn weiter machen?

**Comment by alexreinert** [comment]
Wie der Name vermuten lässt, ist das Paket pivccu-modules-raspberrypi für den Raspberry Pi gemacht und nicht für das Tinkerboard.
Es braucht einfach die richtigen Kernel Module, die entsprechenden Befehle stehen sowohl in der Armbian Doku, wie auch in der debmatic Doku.

**Comment by eapel** [comment]
Oh, stimmt natürlich.

Allerdings lässt sich dies nicht entfernen
`sudo apt remove pivccu-modules-raspberrypi
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden Pakete werden ENTFERNT:
  pivccu-modules-raspberrypi
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
(Lese Datenbank ... 92227 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von pivccu-modules-raspberrypi (2.0-18) ...
sed: can't read /var/lib/piVCCU/dtb/config.txt: No such file or directory
dpkg: Fehler beim Bearbeiten des Paketes pivccu-modules-raspberrypi (--remove):
 »installiertes pivccu-modules-raspberrypi-Skript des Paketes post-removal«-Unterprozess gab den Fehlerwert 2 zurück
dpkg: Zu viele Fehler, Abbruch
Fehler traten auf beim Bearbeiten von:
 pivccu-modules-raspberrypi
Bearbeitung wurde angehalten, da zu viele Fehler auftraten.
piVCCU: DTB rk3288-tinker.dtb was already patched
piVCCU: DTB rk3288-tinker-s.dtb was already patched
E: Sub-process /usr/bin/dpkg returned an error code (1`

Wie komme ich hier weiter?

**Comment by eapel** [comment]
Armbian auf dem Tinkerboard neu aufgesetzt, debmatic installiert, Backup eingespielt.
Alles läuft wieder.
