### ISSUE TITLE
Support for hm_email AddOn

### ISSUE THREAD

**Issue by schmimat** [alexreinert/debmatic#36]
Hallo,

ein AddOn das mir noch fehlt zum Wechsel von pivccu auf debmatic ist hm_email.
Wir dieses Addon kommen?

Vielen Dank für deine Bemühungen

mfG Matthias

**Comment by alexreinert** [comment]
Ich muss hier erst noch die Lizenz klären

**Comment by alexreinert** [comment]
Es sei hier zusätzlich aber auch erwähnt: Da debmatic auf Debian bzw. Ubuntu aufsetzt, kann man per system.Exec auch problemlos direkt Mails versenden, da braucht es nicht zwingend ein Addon für.
