### ISSUE TITLE
debmatic backup/restore armv7l/x86_64

### ISSUE THREAD

**Issue by hoggle64** [alexreinert/debmatic#364]
Hallo,

ich versuche gerade debmatic umzuziehen von einem Pi4 auf eine VM(Ubuntu 22.04).

Beim Einspielen des Backups(was fehlerfrei durchläuft) sehe ich kein einziges Gerät in der neuen Umgebung.

Kann es sein dass das Backup nicht Architektur übergreifend funktioniert ?

**Comment by alexreinert** [comment]
Doch, das funktioniert. Was liefert den debmatic-info?

**Comment by hoggle64** [comment]
sorry das war offensichtlich mein Fehler.
Nach einem nochmaligen apt-get update && apt-get upgrade wurden irgendwelche Kernel Header nachinstalliert.
Nach einem Reboot erscheinen nun alle Geräte.

Danke dennoch für die prompte Reaktion.
