### ISSUE TITLE
Update aus Rasperry matic erzeugt fehler 

### ISSUE THREAD

**Issue by B4unty** [alexreinert/debmatic#366]
Hallo ich habe die debmatic mit allen nötigen plugin aufgesetzt, danach das backup aus der rasperrymatic eingespielt. Dabei bekomme ich dann diese meldung 

`Eine Komponente der Homematic Zentrale reagiert nicht mehr.
Hierfür kann es eine Reihe von Ursachen geben:

es besteht keine Netzwerk-Verbindung
die Stromversorung der HomeMatic Zentrale wurde unterbrochen
mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt
Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.`

**Comment by alexreinert** [comment]
Welche Hardware wird eingesetzt? Was liefert debmatic-info?

**Comment by B4unty** [comment]
Eine VM Debian auf Proxmox.  Hardware hat die VM gerade nicht da ich die Platine am Raspy brauche.

`debmatic version: 3.73.9-112
OS:               Debian GNU/Linux 12 (bookworm)
Kernel:           6.1.0-17-amd64 x86_64
Service Status:   Starting
Kernel modules:   Available
Raw UART dev:     Available
HMRF Hardware:    unknown
HMIP Hardware:    unknown`

**Comment by alexreinert** [comment]
Ohne Hardware können die notwendigen Dienste nicht starten und dann kommt die entsprechende Fehlermeldung, dass eben diese Dienste nicht laufen.

**Comment by B4unty** [comment]
Danke das war die Lösung.
