### ISSUE TITLE
Installation auf RPi 5B unter Bookworm schlägt fehl

### ISSUE THREAD

**Issue by fakenius** [alexreinert/debmatic#367]
Habe gemäß Anleitung auf neuem RPi unter Bookworm installiert. Installation ging ohne Probleme durch, aber debmatic startet nicht.
"systemctl restart debmatic" liefert:

● debmatic.service - debmatic
     Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; preset: enabled)
     Active: active (exited) since Thu 2024-01-25 19:48:55 CET; 4s ago
    Process: 56009 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
   Main PID: 56009 (code=exited, status=0/SUCCESS)
        CPU: 406ms

Jan 25 19:48:33 raspberry4 systemd[1]: Starting debmatic.service - debmatic...
Jan 25 19:48:55 raspberry4 initsystem.sh[56117]: eq3configcmd: error while loading shared libraries: libpthread.so.0: ELF load command address/offset not page-aligned
Jan 25 19:48:55 raspberry4 systemd[1]: Finished debmatic.service - debmatic.

Was kann ich tun? Danke.

**Comment by alexreinert** [comment]
Was für ein Pi? Welches genaue OS Image?

**Comment by alexreinert** [comment]
Und was liefert debmatic-info?

**Comment by fakenius** [comment]
-> Raspberry Pi 5 Model B Rev 1.0

Danke für die Antwort. Habe es heute mit dem aktuellen (Stand heute) Raspbian 64-bit (Bookworm) problemlos installieren können.
Der o.g. genannte Fehler trat mit der Lite-Version auf (Raspbian 64-bit).
