### ISSUE TITLE
[DOC] Geänderter Pfad in neuem Raspberry Pi OS

### ISSUE THREAD

**Issue by 00joshi** [alexreinert/debmatic#368]
Die Befehle in der Anleitung zur Installtion auf einem Raspberry Pi sollten berücksichtigen, dass die Datei /boot/config.txt sich nun unter /boot/firmware/config.txt befindet

**Comment by alexreinert** [comment]
Ich habe die Doku entsprechend angepasst, bis vor kurzem waren da zumindest noch passende Symlinks, aber scheinbar wurden die jetzt entfernt.
