### ISSUE TITLE
Debmatic als VM mit HB-RF-USB

### ISSUE THREAD

**Issue by michaelerbach** [alexreinert/debmatic#37]
Ich habe auf meinem Intel NUC eine VM mit Linux, auf der ich Debmatic erfolgreich installiert habe.

Nun wird leider mein Funkmodul nicht erkannt, welches ich über HB-RF-USB einbinden möchte.

Danke für jeden Hinweis!

**Comment by alexreinert** [comment]
USB Gerät in die VM durchgereicht? Was kommt bei debmatic-info? Was kommt bei lsusb im Host und in der VM?

**Comment by michaelerbach** [comment]
Ich habe generell den USB Port weiter gereicht, allerdings habe ich inzwischen gesehen, dass mein HB-RF-USB gar nicht vom Intel NUC erkannt wird. Auf dem NUC läuft Ubuntu 18.04.3 >müssen hier womöglich noch Treiber installiert werden?

**Comment by alexreinert** [comment]
Ich fange mal weiter vorne an: Was für eine Virtualisierungslösung wird verwendet? Falls Proxmox: VM oder Container? Und nochmal die Frage: Was kommt bei debmatic-info und bei lsusb?
Falls es eine echte VM ist (also nicht LXC Container), braucht es keine Treiber im Host.

**Comment by michaelerbach** [comment]
Also auf dem NUC läuft VirtualBox und hierin habe ich die VM angelegt.

Hier die Ergebnisse der Aufrufe:

serverhomematic@serverhomematic:~$ sudo debmatic-info
[sudo] Passwort für serverhomematic: 
debmatic version: 3.47.15-32
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown


serverhomematic@serverhomematic:~$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

**Comment by alexreinert** [comment]
Sind hier noch Fragen offen? Sonst mache ich zu.

**Comment by michaelerbach** [comment]
Nein keine Fragen offen, muss schauen warum meine USB Gerät nicht durchgereicht wird.
