### ISSUE TITLE
Firmware 3.79.6.118 im Nov.2024 kann nicht installiert werden

### ISSUE THREAD

**Issue by Berli1960** [alexreinert/debmatic#386]
debmatic Vers.: 3.77.7.117 = aktuelle Version
VM auf Proxmox Vers.: 8.2.4
Konsolenbefehl: apt update && apt upgrade  
bringt nachstehenden Fehler:

root@debmatic:~# apt update
OK:1 http://deb.debian.org/debian bookworm InRelease
OK:2 http://security.debian.org/debian-security bookworm-security  InRelease
OK:3 http://deb.debian.org/debian bookworm-updates InRelease
Ign: 4 https://apt.debmatic.de/debmatic stabel InRelease
Fehl:5 https://apt.debmatic.de/debmatic stabel Release
  404   Not Found [IP: 94.130.64.242 443]
Paketlisten werden gelesen....   Fertig
E: Das Depot >>https://apt.debmatic.de/debmatic stabel Release<< enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weiter Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

Die Buchstaben E: und N: sind in rot/braun.

apt upgrade  läuft ohne Fehler durch jedoch führt es das Update nicht durch.

Bitte um Prüfung bzw. korrektur.
Danke für die lfd. Verbesserungen und Upgrades.

**Comment by alexreinert** [comment]
In der /etc/apt/sources.list.de/debmatic.list muss es ```stable``` heißen und nicht ```stabel```.

**Comment by Berli1960** [comment]
Vielen Dank das wars ich habs ja nicht kopieren können sondern abgeschrieben und da ist mir das auch nicht aufgefallen.
Nochmals Danke fürs drüberschauen.

LG
Heinz
