### ISSUE TITLE
Bad Request after install

### ISSUE THREAD

**Issue by DenisMtfl** [alexreinert/debmatic#39]
Ich habe nun OMV auf 88 gemacht debmatic neuinstalliert und nun
Kommt kurz die Seite "Homematic wird vorbereitet..." und danach:

400 Bad Request
(http://192.168.1.158/pages/index.htm?sid=@gBMcgA8QRL@)

**Comment by alexreinert** [comment]
Da leider keine Rückmeldung mehr kam und ich es mit aktuellen Versionen nicht reproduzieren kann, mache ich hier zu.
Falls das Problem noch besteht, bitte wieder aufmachen inkl. der angeforderten Infos.
