### ISSUE TITLE
Geräte Firmware Update übertragen wird nicht fertig

### ISSUE THREAD

**Issue by SkeeveKlah** [alexreinert/debmatic#390]
Hi Alex,
Aus #387 habe ich mir die Seriennummer für den Download der FWs stibitzt, aber das Übertragen der FW an die Geräte wird nicht fertig, seit Tagen steht der Dutycycle auf ca 50%, aber das wars.
Haben die bei HomeMatic noch mehr gemacht um uns Debmatic User aus zu sperren?

Grüße Marc

**Comment by droppar** [comment]
Moin,
ich hab hier 13x HmIP-eTRV-E und 10x (HmIP-SWDO-I, HmIP-SWDO-PL-2) mit debmatic (aktuell: v3.79.6.118 + vorversionen) über die letzten 3 Wochen geupdated - manche Updates mit Übertragung der Firmware zogen sich fast 48h, manche nur paar Stunden.

**Comment by SkeeveKlah** [comment]
Ok, dann muss das Problem wohl wo anders liegen. Dauert jetzt schon Tage…

**Comment by alexreinert** [comment]
Unter absoluten idealbedingungen dauert die Übertragung ca. 8h. Allerdings fängt die Übertragung gefühlt bei jedem fehlerhaft übermittelten Funktelegram komplett von vorne an und das ggf. für jedes einzelne Gerät.
Zusätzlich wird nur so viel übertragen, dass der DC insgesamt nicht über 50% geht, wenn der normal schon z.B. bei 45% liegt, bleibt nicht viel übrig für die Übertragung.
Da das ganze im Closed Source von eQ-3 ist, habe ich da leider auch keine Möglichkeit irgendetwas dran  zu ändern.

**Comment by SkeeveKlah** [comment]
Laut ioBroker habe ich üblicher Weise im Schnitt knapp unter 20%, seit den Updates vor einer Woche an die 50%. Kann ich den jetzt irgendwas machen das positiven Einfluss hat oder einfach warten?
Gab eigentlich noch nie Probleme mit den Updates, die letzten sind nur schon etwas her.
Dank dir auch für die Ausführungen.

**Comment by SkeeveKlah** [comment]
So, ich ich habe die FW Files noch mal gelöscht, alle Geräte einmal stromlos gemacht bzw. neu gestartet und nur eine FW für ein einzelnes Gerät neu hochgeladen. Nach knapp 16 Stunden war dann der Update Button da ;-) Bin gespannt wie lange es bei den nächsten dauert. Ich nehme dann erstmal die zwei 2 STHD und dann kommen die 12 Heizungsthermostate noch mal dran ;-)
Anscheinend muss manN doch einfach nur SEHR viel Geduld haben.
