### ISSUE TITLE
Menüpunk "Systemsteuerung -> Zusatzsoftware" nicht verfügbar

### ISSUE THREAD

**Issue by Ho-Ecker** [alexreinert/debmatic#40]
Hallo,
ich habe Debmatic auf einem frischen Raspbian (Buster) System installiert und möchte das CCU Add-On Redmatic installieren. Leider ist der Menüpunkt "Systemsteuerung -> Zusatzsoftware" nicht verfügbar um das Modul zu laden. Habe ich etwas falsch gemacht? Muss ich Debmatic evtl. anders konfigurieren?

**Comment by alexreinert** [comment]
Siehe Doku: https://github.com/alexreinert/debmatic#addons
