### ISSUE TITLE
Verzögerter Systemstart durch debmatic Skript in /etc/network/if-up.d

### ISSUE THREAD

**Issue by michaelwingender** [alexreinert/debmatic#41]
Hallo,
ich habe auf meinem Router (läuft unter Ubuntu 18.04) debmatic installiert. Funktioniert auch soweit ganz gut. Das einzige was mir aufgefallen ist, ist der ein Reboot seit debmatic deutlich länger braucht. Da es sich um einen Router handelt, hat das Gerät natürlich auch mehrere Netzwerkinterfaces, ein paar physikalische und ein paar VLAN-Interfaces. Da kann auch schon mal ein Interface dabei sein, das keine IP hat und die Internet-Verbindung, die überprüft wird, wird auch erst hergestellt, wenn das letzte VLAN-Interface initialisiert wurde, da es sich erst hier um das Interface handelt, das dann für die pppoe-Verbindung verwendet wird. Da ist also tatsächlich reichlich Potential für eine Verzögerung. Ich bin zwar jetzt froh, dass ich weiß woran es liegt und nichts defekt ist, frage mich aber, ob man das nicht etwas optimieren kann. Ich habe im Moment als Quick-and-Dirty-Lösung den größten Teil der Überprüfungen auskommentiert und lass die Dateien in /var/status ohne Überprüfung anlegen. Das ist aber sicherlich nicht die Königslösung.

Weiterhin frage ich mich was der letzte Teil des Skripts machen soll. Er gibt dem Kommando eq3configcmd anscheinend Informationen zur Default-Route. Leider sind die Infos im Bezug auf die Default Route, die auf meinem System nach dem Neustart vorliegt so aber nicht ganz richtig berechnet. Das was für die Netzmaske rauskommt ist nämlich eine Klasse C-Maske. Das Interface hat aber nur eine Maske für einen einzelnen Host, da es sich um eine ppp-Verbindung handelt (Default Route zeigt in Richtung Internet). Was genau muss hier eq3configcmd mitgeteilt werden? Kann man sich das nicht einfach sparen und sich auf die Routing-Informationen verlassen, die das Betriebssystem bereits hat?

Gruß

**Comment by alexreinert** [comment]
Kannst du mir deine Netzkonfig mal im Detail geben, dann schaue ich mir das nochmal an.
Den Aufruf vom eq3configcmd braucht es für ein paar CCU Dienste. Da diese Close Sotce sind, kann ich leider nicht sagen, warum die nicht einfach über die Routen direkt gehen.

**Comment by michaelwingender** [comment]
Aber klar. Hier das Auszug aus /etc/network/interfaces

auto lo
iface lo inet loopback

auto wlp1s0 <--WLAN Adapter im Moment nicht in Benutzung
iface wlp1s0 inet manual

auto enp2s0 <--LAN
iface enp2s0 inet static
    address 192.168.x.1
    netmask 255.255.255.0
iface enp2s0 inet static <--LAN-Secondary IP für NAT
    address 192.168.x.254
    netmask 255.255.255.0
auto enp2s0.101 <--Media-Netz
iface enp2s0.101 inet static
    address 192.168.y.1
    netmask 255.255.255.0
    vlan-raw-device enp2s0
auto enp2s0.200 <--Gast-Netz
iface enp2s0.200 inet static
    address 192.168.z.1
    netmask 255.255.255.0
    vlan-raw-device enp2s0

auto enp4s0 <--WAN
iface enp4s0 inet static
    address 192.168.a.2
    netmask 255.255.255.252
auto enp4s0.7 <--Tagged WAN
iface enp4s0.7 inet manual
    vlan-raw-device enp4s0

Bis gestern hatte ich dann noch ein Interface für PPPoE mit in der Interfaces-Datei. Den Verbindungsaufbau habe ich im Moment in einen Dienst ausgelagert. Es kommt aber beim Aufbau der Internet-Verbindung am Ende auch noch das PPP Interface dazu mit dazu. Debmatic läuft auf dem Gerät selber, würde also somit alle Interfaces sehen. Es sind keine besonderen Routen gesetzt. Die Default-Route wird über das PPP-Interface beim Verbindungsaufbau zum Provider gelernt. Bevor die PPP-Verbindung steht gibt es nur lokale Routen (alle durch die connected Interfaces).
Die Interfaces fahren beim Booten natürlich alle nacheinander hoch, zuerst die physikalischen wlp1s0, enp2s0, enp4s0 und dann auch jeweils die getaggten.

Hilft das so?

**Comment by alexreinert** [comment]
In der 3.47.22 habe ich eine Optimierung für die Netzwerkerkennung eingebaut, damit sollte das Problem behoben sein. Bitte mal testen.

**Comment by alexreinert** [comment]
Leider keine Rückmeldung, daher Closed. Falls es doch noch ein Problem gibt, bitte wieder aufmachen.

**Comment by michaelwingender** [comment]
Sorry konnte erst heute testen, da ich nicht so häufig Boote. Das Problem ist aus  einer Sicht behoben. Schließen des Tickets also natürlich OK.
