### ISSUE TITLE
Nur mit DEBUG log level erscheint Anlern-Fenster korrekt

### ISSUE THREAD

**Issue by neiser** [alexreinert/debmatic#42]
Ich habe debmatic nach Anleitung in einer Proxmox VM (Debian 10) installiert. Soweit klappte alles auf Anhieb und ich konnte das Webinterface soweit benutzen. Nachträglich habe ich dann das HmIP-RFUSB Modul in die VM weitergeleitet. 

Mit den Standardeinstellung erschien dann beim Button "TeachIn-Devices" im Webinterface interessanterweise nur ein leerer Dialog, obwohl unter "Devices" der HmIP-RFUSB aufgelistet wurde. Wenn ich unter `/etc/config/log4j.xml` alles auf `DEBUG` ändere, wie folgt,
```
        <category name="de.eq3">
                <priority value="DEBUG" />
        </category>
        <category name="org">
                <priority value="DEBUG" />
        </category>
        <category name="com">
                <priority value="DEBUG" />
        </category>
```
und die VM neu starte, dann bekomme ich das übliche Fenster, wo ich erfolgreich Devices anlernen kann im Webinterface. Eigentlich wollte ich das `DEBUG` level nur anmachen, um den Fehler zu suchen, aber jetzt ist ja der Fehler einfach verschwunden. Ist also ein typischer Heisen-Bug, verschwindet bei Beobachtung... :confused: 

Hat jemand eine Idee, wie man das weiter untersuchen kann? Ich befürchte, das ist ein subtiles Timing Problem beim Erkennen des Funkempfängers. Ich habe übrigens noch zwei weitere USB Geräte in die VM durchgereicht in Proxmox, die als `/dev/ttyUSB0` und `/dev/ttyUSB1` erkannt werden (die VM soll auch andere Dinge neben Homematic auslesen). Kann das vielleicht eine Rolle spielen?

Meine Version ist 3.47.15.32, ich könnte ein Update auf 3.47.15.33 machen, aber das traue ich mich nicht ganz, weil es ja recht fragil scheint mit diesem Anlern-Modus. 

Wenn man mir sagt, welche Logs von meiner VM interessant sind, poste ich diese gerne hier.

**Comment by alexreinert** [comment]
Ich glaube nicht, dass das Umstellen auf Debug den entscheidenden Unterschied macht, ich vermute, dass das eher Zufall war. Sofern da keine weitere Fehlermeldung in der WebUI war, wird die Entscheidung für die Anzeige des Anlerndialogs an komplett anderer Stelle getroffen.
Interessant wäre die Ausgabe von ```debmatic-info```, ```lsusb``` und ```ls -la /dev/ttyU*``` wenn das Problem besteht.
Wichtige Frage noch: VM oder Container? Falls Container: Priviligiert oder Unpriviligiert?

**Comment by neiser** [comment]
Hallo Alex,

erstmal vielen Dank für deine super schnelle Antwort!

ich nutze eine "echte" VM, also kein Container in Proxmox. 1 CPU, 2GB RAM. Ich sollte vielleicht noch erwähnen, dass mit dem Boot auch ein recht resourcenintensive WEM Portal Scraper Script hochfährt (Details siehe https://github.com/neiser/wemportal-scripts), welches ein Chromium Headless startet. Vielleicht trägt das auch zu einem "ungünstigen" Timing bei...

ich habe jetzt 10 Geräte erstmal erfolgreich angelernt (HmIP-BWTH) und es scheint soweit alles zu klappen im "DEBUG" Zustand, obwohl nach dem "Teach-In with Internet connection" und dann ein kurzer Druck auf die Homematic Taste vom Thermostat immer ein Fehler-Popup kommt im Webinterface, dass der Teach-In Mode nicht aktiviert werden konnte, sobald ich von dem "Teach-In" Dialog auf den "Inbox (1)" Button klicke (der mir dann das gerade neu angelernte Gerät zeigt, was ich dann mit Klick auf "Done" bestätige). Dieses Fehler Popup hab ich jetzt einfach mal ignoriert. Ich kann die Thermostate jetzt auslesen und bin eigentlich zufrieden. 

Trotzdem fände ich es toll, wenn wir den Bug weiter untersuchen. Die Ausgaben habe ich einmal im Zustand "DEBUG" (wo es funktioniert) und einmal im Zustand "INFO". Ich musste nach dem Umschalten auf "INFO" auch zweimal rebooten, damit ich den Fehler reproduziert bekomme. 

### Ausgaben im "DEBUG" (Teach-In Dialog wird angezeigt)
```
root@homematic:~# debmatic-info
debmatic version: 3.47.15-32
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  HMIP-RFUSB
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          3014F711A000041709ADFBEA
root@homematic:~# lsusb
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 002: ID 1b1f:c020 eQ-3 Entwicklung GmbH 
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 003: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP2102/CP2109 UART Bridge Controller [CP210x family]
Bus 003 Device 002: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP2102/CP2109 UART Bridge Controller [CP210x family]
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd 
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@homematic:~# ls -la /dev/ttyU*
crw-rw---- 1 root dialout 188, 0 Sep 22 10:41 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 Sep 22 10:41 /dev/ttyUSB1
crw-rw---- 1 root dialout 188, 2 Sep 22 11:28 /dev/ttyUSB2
```

### Ausgaben im "INFO" (Teach-In Dialog "leer")

```
root@homematic:/home/homematic# debmatic-info
debmatic version: 3.47.15-32
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
root@homematic:/home/homematic# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 002: ID 1b1f:c020 eQ-3 Entwicklung GmbH 
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 003: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP2102/CP2109 UART Bridge Controller [CP210x family]
Bus 003 Device 002: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP2102/CP2109 UART Bridge Controller [CP210x family]
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 0627:0001 Adomax Technology Co., Ltd 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@homematic:/home/homematic# ls -la /dev/ttyU*
crw-rw---- 1 root dialout 188, 0 Sep 22 11:37 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 Sep 22 11:37 /dev/ttyUSB1
```
Ich hab mir auch mal `dmesg` angeschaut, und man sieht, dass im Fehlerfall garkein `/dev/ttyUSB2` angelegt wird, nachdem der Kernel das Funkmodul sieht:
```
[    7.611673] audit: type=1400 audit(1569145054.684:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=288 comm="apparmor_parser"
[    7.611679] audit: type=1400 audit(1569145054.684:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=288 comm="apparmor_parser"
[    7.611682] audit: type=1400 audit(1569145054.684:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=288 comm="apparmor_parser"
[    7.618835] audit: type=1400 audit(1569145054.692:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=289 comm="apparmor_parser"
[    7.618840] audit: type=1400 audit(1569145054.692:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=289 comm="apparmor_parser"
[    7.699773] usb 3-2: new full-speed USB device number 3 using uhci_hcd
[    8.147069] usb 3-2: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[    8.147073] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    8.147075] usb 3-2: Product: CP2104 USB to UART Bridge Controller
[    8.147076] usb 3-2: Manufacturer: Silicon Labs
[    8.147078] usb 3-2: SerialNumber: 01A61C3A
[    8.157387] cp210x 3-2:1.0: cp210x converter detected
[    8.444372] usb 3-2: cp210x converter now attached to ttyUSB1
[    8.873027] random: crng init done
[    8.873030] random: 7 urandom warning(s) missed due to ratelimiting
[   10.264191] rpi_rf_mod_led: loading out-of-tree module taints kernel.
[   10.264235] rpi_rf_mod_led: module verification failed: signature and/or required key missing - tainting kernel
[   10.580019] usb 4-1: new full-speed USB device number 2 using uhci_hcd
[   11.062719] usb 4-1: New USB device found, idVendor=1b1f, idProduct=c020, bcdDevice= 1.00
[   11.062722] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   11.062724] usb 4-1: Product: eQ-3 HmIP-RFUSB
[   11.062726] usb 4-1: Manufacturer: Silicon Labs
[   11.062727] usb 4-1: SerialNumber: 3014F711A061A7C00010CECF
```

**Comment by neiser** [comment]
Also ich gebe dir recht, dass es nix mit dem Log Level zu tun hat. Eher mit dem durcheinander der drei USB Geräte. Ich glaube, ich werde mein Setup überdenken und diesen anderen USB Geräten einfach eine andere VM spendieren. Das ist sauberer.
