### ISSUE TITLE
Homematic CCU is not ready yet

### ISSUE THREAD

**Issue by naimo84** [alexreinert/debmatic#43]
Hallo zusammen,

ich hab gestern ein Update von debmatic auf 3.47.15-33 gemacht. Heute ist mir aufgefallen, dass die Oberfläche nicht mehr lädt (siehe unten).

Kann mir jemand helfen, wie ich herausfinde, woran das liegen könnte?

Die Verbindung über RPC und node-red funktioniert noch einwandfrei. Ich kann sowohl senden, als auch empfangen.

Danke für eure Hilfe schon einmal im Voraus

Grüße,
Benjamin 

In der hmserver.log steht folgendes:

```
Sep 26 19:46:01 de.eq3.cbcs.server.core.otau.util.FirmwareLoaderFileSystem INFO  [vert.x-worker-thread-3] SYSTEM: Firmware update directory is set to /etc/config/firmware

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-5] SYSTEM: start of FirmwareLoaderFileSystem succeeded (b544ae5a-ec9a-4f99-a114-1bfc6f7a7507)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-1] SYSTEM: start of DeviceInclusionAcceptHandler succeeded (2fc219d4-b6be-4198-a437-802f567780bf)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-7] SYSTEM: start of IncomingHMIPFrameHandler succeeded (20affedf-ec66-4814-b17f-0c11b05e59ac)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-7] SYSTEM: start of WebSocketManager succeeded (ce9a577e-d562-4115-aedb-d625b72e6038)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-2] SYSTEM: start of AccessPointAuthorisationHandler succeeded (5b625591-7e1a-46bc-8f9c-ec27482d05c1)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-1] SYSTEM: start of RemoteCommAdapterInitialization succeeded (e89a986f-c9ce-4745-8bf5-54500d6ca25a)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-0] SYSTEM: start of BackendCommandHandler succeeded (5acae2c7-152f-4c1b-be33-48700615f8b8)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-3] SYSTEM: start of AccessPointMessageDispatcher succeeded (37dd23c0-0b7f-40bd-9f18-68f7bcf4bbf0)

Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-5] SYSTEM: start of AccessPointWatchdog succeeded (5c504d54-0ef9-419a-8b7b-2cdf5240e4cd)

Sep 26 19:46:01 de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-0] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip':
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:105)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:727)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:98)
        at de.eq3.cbcs.server.local.base.internal.ShareableHomeMaticIPTRXCommAdapter.<init>(ShareableHomeMaticIPTRXCommAdapter.java:20)
        at de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization.start(LocalServerAdapterInitialization.java:177)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: gnu.io.NoSuchPortException
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:294)
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:96)
        ... 12 more
		
Sep 26 19:46:01 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-7] SYSTEM: start of LocalServerAdapterInitialization succeeded (fa34ca4c-0e6c-4c26-bd0f-afa9862216c9)

Sep 26 19:46:02 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-1] SYSTEM: start of AccessPointCommDevice succeeded (7ab5c469-0cfb-425d-aadd-bee92a4cfcd7)

Sep 26 19:46:04 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-3] SYSTEM: start of RemoteCommAdapterFinalization succeeded (64054205-5069-4fcf-9c28-dbf3d108fd7c)

Sep 26 19:46:04 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO  [vert.x-eventloop-thread-2] SYSTEM: Started Access Point WebSocket server with port 9293

Sep 26 19:46:04 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO  [vert.x-eventloop-thread-2] SYSTEM: connector open
```

![image](https://user-images.githubusercontent.com/11535502/65713025-899e1400-e098-11e9-80a2-2eefcc5c3852.png)

**Comment by alexreinert** [comment]
Was kommt bei ```debmatic-info```? Was kommt bei ```systemctl status debmatic-multimacd```? Welche Hardware wird genutzt, welches Funkmodul?

**Comment by naimo84** [comment]
Danke für die schnelle Rückmeldung :)

`debmatic-info: `
debmatic version: 3.47.15-33
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0607329
Radio MAC:      0x59d981
SGTIN:          unknown

`systemctl status debmatic-multimacd`

 debmatic-multimacd.service - debmatic multimacd
   Loaded: loaded (/lib/systemd/system/debmatic-multimacd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-26 19:44:56 CEST; 1h 4min ago
  Process: 23631 ExecStart=/usr/share/debmatic/bin/start_multimacd.sh (code=exited, status=0/SUCCESS)
 Main PID: 23640 (multimacd)
    Tasks: 6 (limit: 4236)
   Memory: 1.8M
   CGroup: /system.slice/debmatic-multimacd.service
           └─23640 /bin/multimacd -l 5 -f /var/run/multimacd.conf -d

Sep 26 19:44:34 rooter systemd[1]: Starting debmatic multimacd...
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: kernel.sched_rt_runtime_us = -1
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: cat: /sys/devices/virtual/eq3loop/eq3loop/dev: No such file or directory
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: mknod: missing operand after ‘c’
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: Special files require major and minor device numbers.
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: Try 'mknod --help' for more information.
Sep 26 19:44:34 rooter start_multimacd.sh[23631]: Daemonizing to background
Sep 26 19:44:56 rooter systemd[1]: Started debmatic multimacd.


`Hardware`:

asrock j4105b mit 4GB RAM

OS: Debian 9

`Funkmodul`:

HM-MOD-RPI-PCB auf deiner HB-RF-USB Platine ;)

**Comment by alexreinert** [comment]
Läuft das ganze in einer Virtualisierungslösung?

**Comment by alexreinert** [comment]
Ansonsten: Es gab vor einiger Zeit Anpassungen an den Kernel Modulen. Ich war der Meinung, dass ich die Non-Breaking gemacht hätte, aber zur Sicherheit bitte mal einen Reboot machen und dann die Ausgabe der Befehle nochmal posten.

**Comment by naimo84** [comment]
Nach dem Neustart:

`debmatic version: 3.47.15-33`
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   OEQ0607329
Radio MAC:      0x59d981
SGTIN:          unknown



` debmatic-multimacd.service - debmatic multimacd`
   Loaded: loaded (/lib/systemd/system/debmatic-multimacd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-26 21:40:51 CEST; 12min ago
 Main PID: 8463 (multimacd)
    Tasks: 8 (limit: 4274)
   Memory: 2.0M
   CGroup: /system.slice/debmatic-multimacd.service
           └─8463 /bin/multimacd -l 5 -f /var/run/multimacd.conf -d

Sep 26 21:40:49 rooter systemd[1]: Starting debmatic multimacd...
Sep 26 21:40:49 rooter start_multimacd.sh[8427]: kernel.sched_rt_runtime_us = -1
Sep 26 21:40:49 rooter start_multimacd.sh[8427]: Daemonizing to background
Sep 26 21:40:51 rooter systemd[1]: Started debmatic multimacd.


Virtualisierung wird keine eingesetzt

**Comment by alexreinert** [comment]
Und läuft die Weboberfläche jetzt, nachdem die Fehlermeldung beim multimacd jetzt weg ist?

**Comment by naimo84** [comment]
Lustigerweise geht's nun im Chrome, im Firefox noch immer nicht. Aber das ist eher ein Cache Problem, denk ich ;)

Vielen vielen Dank für deine Unterstüztung 👍 


![image](https://user-images.githubusercontent.com/11535502/65720913-3e403180-e0a9-11e9-960d-8d80a5818936.png)
