### ISSUE TITLE
xml-api template parse error when installing package

### ISSUE THREAD

**Issue by neiser** [alexreinert/debmatic#44]
When executing `apt install xml-api`, I get the following warning:

```
...
Preconfiguring packages ...
xml-api template parse error: Template #1 in /tmp/xml-api.template.7SmYcj does not contain a 'Template:' line

Selecting previously unselected package xml-api.
...
```

The package seems to install fine though. Is this something easy to fix?

**Comment by alexreinert** [comment]
This is not a real error, but a warning. I will fix it anyway.

**Comment by neiser** [comment]
Thanks @alexreinert will you close this issue then once it's fixed?

**Comment by alexreinert** [comment]
Yes
