### ISSUE TITLE
UP Board mit Raspberry-kompatiblem GPIO

### ISSUE THREAD

**Issue by fuerst** [alexreinert/debmatic#45]
Hallo, danke für dieses schöne und nützliche Projekt!

Ist es denkbar, den GPIO-Anschluß eines UP Square Boards mit einem HM-MOD-RPI-PCB zu bestücken und das Funkmodul dann direkt zu nutzen? Laut Hersteller ist der GPIO-Anschluß pin-kompatibel zum Raspberry.

Hier die Spezifikationen: https://up-board.org/upsquared/specifications/

**Comment by alexreinert** [comment]
Aufgrund der Gesamtarchitektur der CCU muss die UART Schnittstelle leider sehr Hardware nah mit eigenen Kernel Modulen angesprochen werden. Für diverse ARM Boards habe ich entsprechende Kernel Module programmiert, für dieses Board konnte ich nicht erkennen, welche Hardware eingesetzt wird. Ohne Testgerät kann ich daher leider nicht sagen, ob das klappt.

**Comment by fuerst** [comment]
Möchtest Du per SSH auf mein Board schauen?

**Comment by alexreinert** [comment]
Ich habe etwas weiter nach Informationen geforscht: Ich halte es nicht für prinzipiell ausgeschlossen eine Unterstützung zu bauen, aber es dürfte einen deutlichen Aufwand bedeuten.
Im Moment sehe ich aber leider nicht die Verbreitung des Boards, welche es rechtfertigen würde, diesen Aufwand zu treiben, zumal man ja auch die HB-RF-USB nutzen kann.

**Comment by fuerst** [comment]
Ja, sehe ich ähnlich. Danke trotzdem für Deine Mühen.
