### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#46]
Hallo, ich habe die Firmware 3.47.18.34 am laufen und bekomme jetzt die Meldung 

Firmware 3.47.15.33 ist verfügbar
--

Woran liegt das.

**Comment by alexreinert** [comment]
Die Firmware 3.47.18 wurde von eQ-3 zurückgezogen.

**Comment by heinog** [comment]
ich habe versucht mit sudo apt update und sudo apt upgrade einen downgrade zu machen.
Es funktioniert aber nicht, ich bleibe auf der höheren Version. Was mache ich falsch?

**Comment by heinog** [comment]
Hallo, ich habe versucht mit sudo apt update und sudo apt upgrade einen downgrade zu machen.
Es bleibt aber bei der höheren Version. Was mache ich falsch?

**Comment by alexreinert** [comment]
Ein Downgrade funktioniert nicht mit ```apt upgrade```, sondern nur mit ```apt install --reinstall``` und Angabe der Versionsnummer (siehe apt Hilfe).
Sofern keine Probleme mit HmIP vorhanden sind, würde ich aber einfach bei der 3.47.18 bleiben, ich gehe davon aus, das eQ-3 zeitnah dann sowieso eine neue Version rausbringen wird.

**Comment by heinog** [comment]
Ok, vielen Dank

**Comment by heinog** [comment]
Eine frage noch, wie bekomme ich ein Addon installiert

**Comment by alexreinert** [comment]
https://github.com/alexreinert/debmatic#addons
