### ISSUE TITLE
RPI-RF-MOD nach System reboot mit falschem LED Status

### ISSUE THREAD

**Issue by dogexan** [alexreinert/debmatic#49]
Hallo,

ich habe folgende Konstellation:
Raspberry Pi 4B mit Raspbian Buster + HB-RF-USB-TK + RPI-RF-MOD

Raspbian ist frisch installiert.
Die Debmatic Installation verläuft reibungslos und der RPI-RF-MOD wird sauber erkannt die LED leuchtet blau.

Nach einem `sudo reboot` wird der RPI-RF-MOD aber nicht mehr selbstständig angesprochen, die LED blink dauerhaft gelb.

Die Weboberfläche ist zu jeder Zeit erreichbar

Nach einem `sudo service debmatic restart` ist der RPI-RF-MOD wieder ansprechbar, die LED leuchtet blau.

Eine Idee woran es liegt?

Vielen Dank im Voraus

**Comment by alexreinert** [comment]
Bitte wenn es gelb blinkt mal in der Konsole ```sudo systemctl list-dependencies debmatic.service``` ausführen und hier posten. Wichtig sind dabei auch die Farben von den Punkten am Anfang der Zeile.

**Comment by dogexan** [comment]
Danke für die schnelle Antwort, hier das Ergebnis:

pi@raspberrypi:~ $ sudo systemctl list-dependencies debmatic.service
debmatic.service
● ├─debmatic-eq3configd.service
● ├─debmatic-hmserver.service
● ├─debmatic-hs485d.service
● ├─debmatic-hssled.service
● ├─debmatic-lighttpd.service
● ├─debmatic-multimacd.service
● ├─debmatic-prepareinterfaceslist.service
● ├─debmatic-rega.service
● ├─debmatic-rfd.service
● ├─debmatic-setinterfaceclock.timer
● ├─debmatic-ssdpd.service
● ├─debmatic-startupfinished.service
● ├─debmatic-updatelgwfirmware.service
● ├─debmatic-updatelgwkey.service
● ├─debmatic-updaterffirmware.service
● ├─pivccu-dkms.service
● ├─system.slice
● └─sysinit.target
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─fake-hwclock.service
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot.mount
●   │ ├─systemd-fsck-root.service
●   │ └─systemd-remount-fs.service
●   └─swap.target


Es ist alles grün bis auf folgende Punkte die grau dargestellt werden:

● ├─debmatic-hs485d.service
● ├─pivccu-dkms.service
●   ├─dev-hugepages.mount
●   ├─sys-fs-fuse-connections.mount
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-machine-id-commit.service


pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.47.15-33
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A705C1
Radio MAC:      0xB7F7D6
SGTIN:          3014F711A0001F58A9A705C1

**Comment by alexreinert** [comment]
Gut, dann sind alle Dienste erfolgreich gestartet. Entweder ist dann da ein Bug in den Closed Binaries vom hss_led oder gibt es vielleicht irgendwelche Service Meldungen?

**Comment by dogexan** [comment]
Keine Service Meldungen, ich habe auch noch kein Homematic Geräte versucht anzulernen. Möglicherweise liegt es wirklich nur an der "Fehlerhaften LED" und die Funktionen sind trotzdem gegeben.




`pi@raspberrypi:~ $ sudo reboot`

Die gelbe LED blinkt wieder


```
pi@raspberrypi:~ $ service debmatic status
● debmatic.service - debmatic
   Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2019-10-24 16:13:40 BST; 9min ago
  Process: 388 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
 Main PID: 388 (code=exited, status=0/SUCCESS)

Oct 24 16:13:20 raspberrypi systemd[1]: Starting debmatic...
Oct 24 16:13:20 raspberrypi initsystem.sh[388]: find: ‘/usr/share/debmatic/lib’: No such file or directory
Oct 24 16:13:27 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:29 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:31 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:33 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:35 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:37 raspberrypi initsystem.sh[388]: cat: /sys/class/net//carrier: No such file or directory
Oct 24 16:13:40 raspberrypi systemd[1]: Started debmatic.
```



`pi@raspberrypi:~ $ sudo service debmatic restart`



```
pi@raspberrypi:~ $ service debmatic status
● debmatic.service - debmatic
   Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2019-10-24 16:25:06 BST; 3min 46s ago
  Process: 1453 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
 Main PID: 1453 (code=exited, status=0/SUCCESS)

Oct 24 16:24:59 raspberrypi systemd[1]: Starting debmatic...
Oct 24 16:24:59 raspberrypi initsystem.sh[1453]: find: ‘/usr/share/debmatic/lib’: No such file or directory
Oct 24 16:25:06 raspberrypi systemd[1]: Started debmatic.

```

LED wieder dauerhaft blau

**Comment by dogexan** [comment]
Haben eben eine Homematic Komponente angemeldet. Auch nach System reboot ist der Aktor noch erreichbar, somit scheint es nur ein falscher Status der LED zu sein.

**Comment by alexreinert** [comment]
In der 3.47.22 habe ich eine Optimierung für die Netzwerkerkennung eingebaut, damit sollte das Problem behoben sein. Bitte mal testen.

**Comment by dogexan** [comment]
Also jetzt blinkt die LED in blau,  nach `sudo service debmatic restart` ist sie wieder konstant blau.

**Comment by Moskito99** [comment]
Hänge mich hier mit rein, da ich davon ausgehe, dass es mit der neuen Version zu tun hat...
Habe heute 3.47.22 installiert. Danach blinkte die LED. Thermostat war nicht mehr ansprechbar. Da ich nur ein Thermostat dran habe, habe ich einen Werksreset durchgeführt. 
Ergebnis ist, das ich jetzt das Thermostat wieder anlernen konnte, aber es nicht mehr steuern kann.
LED blinkt weiterhin fröhlich vor sich hin.

```
pi@raspberrypi:~ $ sudo systemctl list-dependencies debmatic.service
debmatic.service
* |-debmatic-eq3configd.service
* |-debmatic-hmserver.service
* |-debmatic-hs485d.service
* |-debmatic-hssled.service
* |-debmatic-lighttpd.service
* |-debmatic-multimacd.service
* |-debmatic-prepareinterfaceslist.service
* |-debmatic-rega.service
* |-debmatic-rfd.service
* |-debmatic-setinterfaceclock.timer
* |-debmatic-ssdpd.service
* |-debmatic-startupfinished.service
* |-debmatic-updatelgwfirmware.service
* |-debmatic-updatelgwkey.service
* |-debmatic-updaterffirmware.service
* |-pivccu-dkms.service
* |-system.slice
* `-sysinit.target
*   |-dev-hugepages.mount
*   |-dev-mqueue.mount
*   |-fake-hwclock.service
*   |-keyboard-setup.service
*   |-kmod-static-nodes.service
*   |-proc-sys-fs-binfmt_misc.automount
*   |-sys-fs-fuse-connections.mount
*   |-sys-kernel-config.mount
*   |-sys-kernel-debug.mount
*   |-systemd-ask-password-console.path
*   |-systemd-binfmt.service
*   |-systemd-hwdb-update.service
*   |-systemd-journal-flush.service
*   |-systemd-journald.service
*   |-systemd-machine-id-commit.service
*   |-systemd-modules-load.service
*   |-systemd-random-seed.service
*   |-systemd-sysctl.service
*   |-systemd-sysusers.service
*   |-systemd-timesyncd.service
*   |-systemd-tmpfiles-setup-dev.service
*   |-systemd-tmpfiles-setup.service
*   |-systemd-udev-trigger.service
*   |-systemd-udevd.service
*   |-systemd-update-utmp.service
*   |-cryptsetup.target
*   |-local-fs.target
*   | |--.mount
*   | |-boot.mount
*   | |-systemd-fsck-root.service
*   | `-systemd-remount-fs.service
*   `-swap.target
```
^^^Alles grün.

```
pi@raspberrypi:~ $ sudo service debmatic restart
pi@raspberrypi:~ $ service debmatic status      
* debmatic.service - debmatic
   Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2019-11-09 10:45:26 GMT; 4s ago
  Process: 1437 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
 Main PID: 1437 (code=exited, status=0/SUCCESS)

Nov 09 10:45:11 raspberrypi systemd[1]: Starting debmatic...
Nov 09 10:45:26 raspberrypi systemd[1]: Started debmatic.
```

Im HomeMatic wird mir das Thermostat unter Geräte angezeigt. Ein Test schlägt fehl und wenn ich auf einstellen gehe bekomme ich folgende Fehlermeldung:

`Das Gerät mit der Seriennummer 'PEQ1311760' vom Interface 'HM-RCV-50 BidCoS-RF' konnte nicht abgefragt werden!`

**Comment by alexreinert** [comment]
Die LED ist unabhängig von der eigentlichen Funkkommunikation und wird komplett anders angesteuert. Daher hängt das nicht zusammen. Daher bitte neuen Issue aufmachen.

**Comment by Schattenruf** [comment]
Selbes Problem hier. Meine LED blinkt auch nach dem Restart dauerhaft gelb (frisch installierter Pi 3b mit Buster). Allerdings ist eine Lampe bei mir rot:

sudo systemctl list-dependencies debmatic.service
![image](https://user-images.githubusercontent.com/12720317/69654434-18b5b100-1075-11ea-9132-42b94309ce19.png)

**Comment by Schattenruf** [comment]
@alexreinert Irgendwelche Neuigkeiten zu diesem Topic?

**Comment by alexreinert** [comment]
@Schattenruf Welches OS hast du? Welche Dateien liegen unter /var/status?

**Comment by Schattenruf** [comment]
@alexreinert 
`
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

![image](https://user-images.githubusercontent.com/12720317/70557777-c94aa700-1b83-11ea-9a04-1a00a55a04b2.png)

**Comment by alexreinert** [comment]
@Schattenruf Bitte mal rebooten und dann die Ausgabe folgender Befehle posten:
```
sudo debmatic-info
sudo systemctl status debmatic
ls -la /var/status
ip -o -4 addr show
route -4 -n
```

**Comment by Schattenruf** [comment]
@alexreinert Hab gerebootet und hier sind die Ergebnisse:

![image](https://user-images.githubusercontent.com/12720317/70865069-801a9e80-1f59-11ea-977c-b11f0ca72d59.png)
![image](https://user-images.githubusercontent.com/12720317/70865071-86107f80-1f59-11ea-8dfa-f9a928937959.png)
![image](https://user-images.githubusercontent.com/12720317/70865074-8c066080-1f59-11ea-99d4-6ed3f57e02ca.png)
![image](https://user-images.githubusercontent.com/12720317/70865077-91fc4180-1f59-11ea-8ed8-aa2d3d69de71.png)
![image](https://user-images.githubusercontent.com/12720317/70865080-96c0f580-1f59-11ea-9ab5-63a7b95f30d5.png)

**Comment by alexreinert** [comment]
Ok, interessanter Punkt, du nutzt WLAN. Ich schau mal, ob ich dein Problem damit reproduziert bekomme.

**Comment by Schattenruf** [comment]
Also wie gesagt: es funktioniert alles nur die Led leuchtet blau/gelb im
Wechsel. Das aber auch erst seit dem letzten Release...

**Comment by alexreinert** [comment]
Ich konnte das Problem bei mir nachstellen und fixen. Probier mal, ob es bei dir jetzt mit der Version 3.47.22-37 läuft.

**Comment by Schattenruf** [comment]
Sieht allerdings nach Update + Reboot unverändert aus:

![image](https://user-images.githubusercontent.com/12720317/70934065-5dfa4c80-203d-11ea-8151-cd10812c9712.png)
![image](https://user-images.githubusercontent.com/12720317/70934075-63579700-203d-11ea-9738-33de7db7f5c3.png)
![image](https://user-images.githubusercontent.com/12720317/70934080-66eb1e00-203d-11ea-8282-c450f2ee7875.png)
![image](https://user-images.githubusercontent.com/12720317/70934086-69e60e80-203d-11ea-90d2-802584ebfbde.png)
![image](https://user-images.githubusercontent.com/12720317/70934101-6fdbef80-203d-11ea-82fb-28fe03359133.png)
![image](https://user-images.githubusercontent.com/12720317/70934112-766a6700-203d-11ea-8ee8-62798262f35c.png)

**Comment by alexreinert** [comment]
Doch, da ist ein riesiger Unterschied bei den Dateien unter /var/status.
Möglicherweise ist aber zum Startzeitpunkt von debmatic noch keine IP verfügbar. Wie sieht es denn aus, wenn du nur debmatic per systemctl stopst und neu startest?

**Comment by Schattenruf** [comment]
Jetzt leuchtet nix mehr:
![image](https://user-images.githubusercontent.com/12720317/70936553-d1eb2380-2042-11ea-99df-ef09826f4ba3.png)

Sind ein paar Dateien dazugekommen :) Aber warum er das beim reboot nicht gemacht hat, verstehe ich nicht...

**Comment by alexreinert** [comment]
Was heißt, es leuchtet nichts mehr? Erwartungshaltung wäre ja, dass die LED blau leuchtet.
Dass die Dateien fehlen, liegt vermutlich daran, dass es etwas dauert, bis man per WLAN eine IP bekommt. Ich schaue, dass ich das noch etwas optimiert bekomme.

**Comment by Schattenruf** [comment]
Naja es blinkt aktuell nix mehr. Keine LED an. Aber so war es vorher auch.

**Comment by alexreinert** [comment]
Ich habe gestern noch ein weiteres Update bereitgestellt, mit diesem müsste es jetzt auch direkt beim Reboot passen.

**Comment by Schattenruf** [comment]
Scheint gut zu laufen. Bleibt nach reboot dauerhaft blau und blinkt nicht mehr. Vielen dank!

**Comment by dogexan** [comment]
Bei mir gibt es auch keine Probleme mehr mit der LED, vielen Dank auch von mir!

**Comment by Noschvie** [comment]
Hallo
habe "falsche LED-Statusfarbe nach Systemstart" nun auch mehrmals beobachtet.
Hardware: Raspberry Pi 3B+ mit Raspbian Buster + HB-RF-USB-TK + RPI-RF-MOD

Beispielsweise war "debmatic-eq3configd.service" oder "debmatic-ssdpd.service" rot.
![grafik](https://user-images.githubusercontent.com/48217146/93662446-754ce700-fa60-11ea-8069-9a792c562984.png)
![grafik](https://user-images.githubusercontent.com/48217146/93662473-9b728700-fa60-11ea-8c79-c2b7551b1084.png)

Die Funktionalität von Debmatic ist dadurch nicht eingeschränkt.

`sudo service debmatic restart`

Ein Restart von Debmatic bereinigt das Problem.
