### ISSUE TITLE
Can't build kernel modules

### ISSUE THREAD

**Issue by worf0r** [alexreinert/debmatic#5]
Hi Team!

Just tried the Installation on X64...debian-9.7.0-amd64-netinst.iso

Can't install the kernel modules.

Error:
DKMS make.log for pivccu-1.0.22 for kernel 4.9.0-8-amd64 (x86_64)
Mi 13. Feb 22:55:14 CET 2019
make -C /lib/modules/4.9.0-8-amd64/build M=/var/lib/dkms/pivccu/1.0.22/build modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.9.0-8-amd64“ wird betreten
  CC [M]  /var/lib/dkms/pivccu/1.0.22/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.22/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.22/build/pl011_raw_uart.o
/var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.c: In function ‘generic_raw_uart_get_gpio_pin_number’:
/var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.c:722:31: error: too many arguments to function ‘fwnode_get_named_gpiod’
     struct gpio_desc *gpiod = fwnode_get_named_gpiod(fwnode, label, 0, GPIOD_ASIS, label);
                               ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/linux-headers-4.9.0-8-common/include/asm-generic/gpio.h:13:0,
                 from /usr/src/linux-headers-4.9.0-8-common/include/linux/gpio.h:51,
                 from /var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.c:39:
/usr/src/linux-headers-4.9.0-8-common/include/linux/gpio/consumer.h:137:19: note: declared here
 struct gpio_desc *fwnode_get_named_gpiod(struct fwnode_handle *fwnode,
                   ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-4.9.0-8-common/scripts/Makefile.build:307: die Regel für Ziel „/var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.o“ scheiterte
make[4]: *** [/var/lib/dkms/pivccu/1.0.22/build/generic_raw_uart.o] Fehler 1
make[4]: *** Es wird auf noch nicht beendete Prozesse gewartet...
/usr/src/linux-headers-4.9.0-8-common/Makefile:1528: die Regel für Ziel „_module_/var/lib/dkms/pivccu/1.0.22/build“ scheiterte
make[3]: *** [_module_/var/lib/dkms/pivccu/1.0.22/build] Fehler 2
Makefile:152: die Regel für Ziel „sub-make“ scheiterte
make[2]: *** [sub-make] Fehler 2
Makefile:8: die Regel für Ziel „all“ scheiterte
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-4.9.0-8-amd64“ wird verlassen
Makefile:23: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

What to do?

Marc

**Comment by worf0r** [comment]
Ok, das heißt dann aber auch, dass debmatic mit einem Debain stable so erstmal nicht läuft.
Was wäre die Empfehlung? Ubuntu mag ich eigentlich nicht nehmen. Und Kernel compilieren habe ich eigentlich auch seit 10 Jahren hinter mir gelassen. Backports installieren?

**Comment by alexreinert** [comment]
Backports, selber kompilieren oder Ubuntu.

Die Kernel Module könnte ich noch fixen, aber das würde nichts bringen, da die Binaries von eQ-3 mit Dependency auf Kernel 4.14 kompiliert sind.

**Comment by worf0r** [comment]
Ok. Dann sollten wir die Installationsanleitung für debian stable separieren und den Step mit den Backports (als die einfachste Möglichkeit) mit aufnehmen. Das erspart wahrscheinlich zahlreiche Tickets von Usern hier. Du hast das mit der Kernel Version zwar geschrieben, aber bei einem Projekt Namens "debmatic" kann man schon schnell auf den Einfall kommen, dass es mit debian stable direkt laufen sollte :)

Ich werde das mit den Backports heute Abend versuchen. Ist ja keine große Sache.

**Comment by worf0r** [comment]
So, das läuft jetzt mit dem neueren Kern. Ich mache hier zu.
