### ISSUE TITLE
Sicherheitsschlüssel konnte nicht gesetzt werden

### ISSUE THREAD

**Issue by MisterBJ** [alexreinert/debmatic#50]
Servus,
ich habe vor ein, zwei Wochen den Pi3 wegen Umzug neu aufgesetzt und heute auch mit apt-get auf neusten Stand (Stable) gebracht. Es sind noch keine Geräte angemeldet. Beim Einrichten ist es mir nicht Möglich den Sicherheitsschlüssel anzulegen. Es kommt immer ein Dialogfenster mit "Der Schlüssel konnte nicht angelegt werden. Informationen dazu finden Sie in den Servicemeldungen.". Nur die Servicemeldungen bleiben leer. Neustart habe ich auch mehrfach ausprobiert.
Ist das Problem bekannt oder mache ich etwas falsch?
Passwort beinhaltet nur die Erlaubten Zeichen "A-Za-z0-9_" und ist 30 Zeichen lang.

Gruß Björn

**Comment by alexreinert** [comment]
Welche Funkhardware ist angeschlossen?

**Comment by MisterBJ** [comment]
Das HM-MOD-RPI-PCB.

**Comment by alexreinert** [comment]
Ich habe das letzens erst getestet, da ging es, allerdings mit einem deutlich kürzeren Schlüssel ohne Underscore. Ich schau, dass ich das morgen nachgestellt bekomme.
Was liefert debmatic-info?

**Comment by MisterBJ** [comment]
debmatic version: 3.47.15-33
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown

Kann es sein das beim Update etwas schief gelaufen ist?
Vielleicht sollte ich nochmal komplett neu aufsetzen?

**Comment by alexreinert** [comment]
Wurde beim Update einer neuer Kernel installiert? Dann muss danach ein Reboot gemacht werden.
Ansonsten: Was liefert ```sudo dpkg-reconfigure pivccu-modules-dkms```? Bei Fehlern mit Verweis auf eine Logdatei bitte auch deren Inhalt.

**Comment by MisterBJ** [comment]
Das Update lief lange und ich habe es laufen lassen aber eine Fehlermeldung am Ende hatte ich nicht gelesen. Neustarts hatte ich auch mehrmals.

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.19.80-v7+ cannot be found at
/lib/modules/4.19.80-v7+/build or /lib/modules/4.19.80-v7+/source.

**Comment by alexreinert** [comment]
Was ist auf dem System für ein Kernel installiert? Der aktuelle stable Kernel, welcher per apt kommt, kann es nicht sein, der hat Version 4.19.75.

**Comment by alexreinert** [comment]
Und das Problem ist, das zum aktuell laufenden Kernel 4.19.80 keine passenden Kernel Header installiert sind.

**Comment by MisterBJ** [comment]
Merkwürdig,
Noch einmal Upgrade gemacht und der Kernel bleibt bei 4.19.80-v7+.
Okay, ich werde den Pi Morgen mit dem aktuellen Raspbian Buster Lite aufsetzen.
Da muss ja etwas mit dem apt upgrade schiefgelaufen sein.
Ich danke dir erstmal für deine Hilfe!

**Comment by MisterBJ** [comment]
Also ich habe jetzt das aktuelle Raspbian vom 26.09.2019 auf die SD gepackt, mit apt-get auf dem aktuellen Stand gebracht und neugestartet.
uname -r = 4.19.75-v7+

**Comment by alexreinert** [comment]
Ja, hab ich ja oben gesagt, die 4.19.75 ist die aktuelle stable Version vom Raspbian Kernel.

**Comment by MisterBJ** [comment]
Keine Ahnung wie ich an den anderen Kernel gekommen bin. 
Nach Neuinstallation funktioniert es wieder.
Danke dir für deine Hilfe.

Gruß BJörn
