### ISSUE TITLE
Probleme mit der Anzeige von virtuellen Devices

### ISSUE THREAD

**Issue by chriwo83** [alexreinert/debmatic#51]
Ich habe DEBMATIC mit FHEM in Verwendung. Ich habe insgesamt 7 virtuelle Geräte vom Typ "Heizgruppe" (keine HMIP Geräte) in DEBMATIC angelegt. Bei 2 der Geräten wird in FHEM statt der ACTUEL_HUMIDITY immer der Wert 20 ausgelesen. Bei den 5 anderen Geräten passen die Werte. Die Virtuellen Geräte wurden bereits neu angelegt und die analogen Geräte in FHEM ebenfalls.
Gerät: Raspi 3 mit dem alten Funkmodul aufgesteckt.

Gibt es hier schon ähnliche Erfahrungen?

**Comment by alexreinert** [comment]
Sind in der Heizgruppe überhaut Geräte virhanden, welche die Luftfeuchte erfassen? Wenn ja, welche Werte liefern diese als Einzelgerät innerhalb der CCU?

**Comment by chriwo83** [comment]
Ja, sind vorhanden. Die Gruppen bestehen bis auf eine alle aus:
HM-CC-RT-DN (Thermostat)
HM-TC-IT-WM-W-EU (Wandthermostat)
HM-Sec-RHS (in einem Raum habe ich noch keinen Fensterkontakt verbaut)

In DEBMATIC wird hier bei allen Virtuellen Geräten auch nur die Temperatur angezeigt. Hatte bisher noch keine CCU in Verwendung, jetzt weiß ich nicht, ob hier auch die Luftfeuchte stehen solle. Aber da es bei 5 Geräten ausgelesen wird und nur bei 2 nicht...bin ich irgendwie ratlos.

**Comment by alexreinert** [comment]
20 ist der Wert, welcher als Default bei der Luftfeuchtigkeit einer Heizgruppe gelufert wird. Mangels Zugriff auf den Sourcecode des HMServers kann ich leider nicht genau sagen, wann dieser Wert aktualisiert wird. Möglicherweise passiert das nur, wenn sich der Wert der Luftfeuchtigkeit vom Wandthermostat echt verändert.
Ggf. wäre es sinnvoll mal im Homematic Forum zu fragen, an der Stelle ist das nicht debmatic spezifisch, sondern betrifft alle CCU Varianten, weil alle den gleichen HMServer für die virtuellen Geräten verwenden.

**Comment by chriwo83** [comment]
ok, danke. Ich habe mir die Werte mal notiert und werde es, sobald die sich verändert haben gegenprüfen und Bescheid geben.

**Comment by chriwo83** [comment]
stimmt, genau das war das Problem. Anscheinend hatte sich seit der Einrichtung in den beiden Räumen die Luftfeuchte nicht geändert. Danke :)

Thema kann geschlossen werden.
