### ISSUE TITLE
Kernel support (5.3.0-1008-raspi2) für Ubuntu Server on a Raspberry Pi 4

### ISSUE THREAD

**Issue by dogexan** [alexreinert/debmatic#52]
Mit dem offiziellen Ubuntu Server für IOT Geräte schlägt die Installation auf Grund dem unbekannten Kernel fehl.

Ubuntu 19.10

`root@ubuntu:/home/ubuntu# apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done
linux-headers-5.3.0-1008-raspi2/eoan-updates,eoan-security,now 5.3.0-1008.9 arm64 [installed,automatic]
  Linux kernel headers for version 5.3.0 on ARMv8 SMP`

Image:
https://ubuntu.com/download/iot/raspberry-pi

`root@ubuntu:/home/ubuntu# sudo apt install pivccu-modules-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bison build-essential cpp cpp-9 dkms dpkg-dev fakeroot flex g++ g++-9 gcc gcc-9 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libdpkg-perl libfakeroot libfile-fcntllock-perl libfl-dev libgcc-9-dev libgomp1 libisl21 libitm1 liblsan0 libmpc3 libstdc++-9-dev libtsan0 libubsan1 linux-libc-dev m4
  make manpages-dev
Suggested packages:
  bison-doc cpp-doc gcc-9-locales menu debian-keyring flex-doc gcc-9-doc libstdc++6-9-dbg gcc-multilib autoconf automake libtool gdb gcc-doc libgcc1-dbg libgomp1-dbg libitm1-dbg
  libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libquadmath0-dbg glibc-doc bzr libstdc++-9-doc m4-doc make-doc
The following NEW packages will be installed:
  bison build-essential cpp cpp-9 dkms dpkg-dev fakeroot flex g++ g++-9 gcc gcc-9 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libdpkg-perl libfakeroot libfile-fcntllock-perl libfl-dev libgcc-9-dev libgomp1 libisl21 libitm1 liblsan0 libmpc3 libstdc++-9-dev libtsan0 libubsan1 linux-libc-dev m4
  make manpages-dev pivccu-modules-dkms
0 upgraded, 38 newly installed, 0 to remove and 0 not upgraded.
Need to get 39.1 MB of archives.
After this operation, 142 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 m4 arm64 1.4.18-2 [194 kB]
Get:2 https://www.debmatic.de/debmatic stable/main arm64 pivccu-modules-dkms all 1.0.36 [30.2 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 flex arm64 2.6.4-6.2 [307 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libisl21 arm64 0.21-2 [521 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libmpc3 arm64 1.1.0-1 [37.2 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 cpp-9 arm64 9.2.1-9ubuntu2 [8349 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 cpp arm64 4:9.2.1-3.1ubuntu1 [27.6 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libcc1-0 arm64 9.2.1-9ubuntu2 [46.5 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libgomp1 arm64 9.2.1-9ubuntu2 [80.5 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libitm1 arm64 9.2.1-9ubuntu2 [25.0 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libatomic1 arm64 9.2.1-9ubuntu2 [9168 B]
Get:12 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libasan5 arm64 9.2.1-9ubuntu2 [365 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 liblsan0 arm64 9.2.1-9ubuntu2 [126 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libtsan0 arm64 9.2.1-9ubuntu2 [283 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libubsan1 arm64 9.2.1-9ubuntu2 [121 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libgcc-9-dev arm64 9.2.1-9ubuntu2 [914 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 gcc-9 arm64 9.2.1-9ubuntu2 [9106 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 gcc arm64 4:9.2.1-3.1ubuntu1 [5228 B]
Get:19 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libdpkg-perl all 1.19.7ubuntu2 [230 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 make arm64 4.2.1-1.2 [154 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 dpkg-dev all 1.19.7ubuntu2 [679 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libc-dev-bin arm64 2.30-0ubuntu2 [64.1 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports eoan-updates/main arm64 linux-libc-dev arm64 5.3.0-19.20 [1045 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libc6-dev arm64 2.30-0ubuntu2 [2091 kB]
Get:25 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libstdc++-9-dev arm64 9.2.1-9ubuntu2 [1673 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 g++-9 arm64 9.2.1-9ubuntu2 [9466 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 g++ arm64 4:9.2.1-3.1ubuntu1 [1596 B]
Get:28 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 build-essential arm64 12.8ubuntu1 [4620 B]
Get:29 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 dkms all 2.7.1-4ubuntu2 [66.7 kB]
Get:30 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 bison arm64 2:3.4.1+dfsg-4 [627 kB]
Get:31 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libfakeroot arm64 1.24-1 [26.0 kB]
Get:32 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 fakeroot arm64 1.24-1 [61.9 kB]
Get:33 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libalgorithm-diff-perl all 1.19.03-2 [46.6 kB]
Get:34 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libalgorithm-diff-xs-perl arm64 0.04-5build1 [11.0 kB]
Get:35 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libalgorithm-merge-perl all 0.08-3 [12.0 kB]
Get:36 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libfile-fcntllock-perl arm64 0.22-3build3 [33.1 kB]
Get:37 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 libfl-dev arm64 2.6.4-6.2 [6324 B]
Get:38 http://ports.ubuntu.com/ubuntu-ports eoan/main arm64 manpages-dev all 5.02-1 [2250 kB]
Fetched 39.1 MB in 7s (5864 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
Selecting previously unselected package m4.
(Reading database ... 97814 files and directories currently installed.)
Preparing to unpack .../00-m4_1.4.18-2_arm64.deb ...
Unpacking m4 (1.4.18-2) ...
Selecting previously unselected package flex.
Preparing to unpack .../01-flex_2.6.4-6.2_arm64.deb ...
Unpacking flex (2.6.4-6.2) ...
Selecting previously unselected package libisl21:arm64.
Preparing to unpack .../02-libisl21_0.21-2_arm64.deb ...
Unpacking libisl21:arm64 (0.21-2) ...
Selecting previously unselected package libmpc3:arm64.
Preparing to unpack .../03-libmpc3_1.1.0-1_arm64.deb ...
Unpacking libmpc3:arm64 (1.1.0-1) ...
Selecting previously unselected package cpp-9.
Preparing to unpack .../04-cpp-9_9.2.1-9ubuntu2_arm64.deb ...
Unpacking cpp-9 (9.2.1-9ubuntu2) ...
Selecting previously unselected package cpp.
Preparing to unpack .../05-cpp_4%3a9.2.1-3.1ubuntu1_arm64.deb ...
Unpacking cpp (4:9.2.1-3.1ubuntu1) ...
Selecting previously unselected package libcc1-0:arm64.
Preparing to unpack .../06-libcc1-0_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libcc1-0:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libgomp1:arm64.
Preparing to unpack .../07-libgomp1_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libgomp1:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libitm1:arm64.
Preparing to unpack .../08-libitm1_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libitm1:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libatomic1:arm64.
Preparing to unpack .../09-libatomic1_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libatomic1:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libasan5:arm64.
Preparing to unpack .../10-libasan5_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libasan5:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package liblsan0:arm64.
Preparing to unpack .../11-liblsan0_9.2.1-9ubuntu2_arm64.deb ...
Unpacking liblsan0:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libtsan0:arm64.
Preparing to unpack .../12-libtsan0_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libtsan0:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libubsan1:arm64.
Preparing to unpack .../13-libubsan1_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libubsan1:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package libgcc-9-dev:arm64.
Preparing to unpack .../14-libgcc-9-dev_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libgcc-9-dev:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package gcc-9.
Preparing to unpack .../15-gcc-9_9.2.1-9ubuntu2_arm64.deb ...
Unpacking gcc-9 (9.2.1-9ubuntu2) ...
Selecting previously unselected package gcc.
Preparing to unpack .../16-gcc_4%3a9.2.1-3.1ubuntu1_arm64.deb ...
Unpacking gcc (4:9.2.1-3.1ubuntu1) ...
Selecting previously unselected package libdpkg-perl.
Preparing to unpack .../17-libdpkg-perl_1.19.7ubuntu2_all.deb ...
Unpacking libdpkg-perl (1.19.7ubuntu2) ...
Selecting previously unselected package make.
Preparing to unpack .../18-make_4.2.1-1.2_arm64.deb ...
Unpacking make (4.2.1-1.2) ...
Selecting previously unselected package dpkg-dev.
Preparing to unpack .../19-dpkg-dev_1.19.7ubuntu2_all.deb ...
Unpacking dpkg-dev (1.19.7ubuntu2) ...
Selecting previously unselected package libc-dev-bin.
Preparing to unpack .../20-libc-dev-bin_2.30-0ubuntu2_arm64.deb ...
Unpacking libc-dev-bin (2.30-0ubuntu2) ...
Selecting previously unselected package linux-libc-dev:arm64.
Preparing to unpack .../21-linux-libc-dev_5.3.0-19.20_arm64.deb ...
Unpacking linux-libc-dev:arm64 (5.3.0-19.20) ...
Selecting previously unselected package libc6-dev:arm64.
Preparing to unpack .../22-libc6-dev_2.30-0ubuntu2_arm64.deb ...
Unpacking libc6-dev:arm64 (2.30-0ubuntu2) ...
Selecting previously unselected package libstdc++-9-dev:arm64.
Preparing to unpack .../23-libstdc++-9-dev_9.2.1-9ubuntu2_arm64.deb ...
Unpacking libstdc++-9-dev:arm64 (9.2.1-9ubuntu2) ...
Selecting previously unselected package g++-9.
Preparing to unpack .../24-g++-9_9.2.1-9ubuntu2_arm64.deb ...
Unpacking g++-9 (9.2.1-9ubuntu2) ...
Selecting previously unselected package g++.
Preparing to unpack .../25-g++_4%3a9.2.1-3.1ubuntu1_arm64.deb ...
Unpacking g++ (4:9.2.1-3.1ubuntu1) ...
Selecting previously unselected package build-essential.
Preparing to unpack .../26-build-essential_12.8ubuntu1_arm64.deb ...
Unpacking build-essential (12.8ubuntu1) ...
Selecting previously unselected package dkms.
Preparing to unpack .../27-dkms_2.7.1-4ubuntu2_all.deb ...
Unpacking dkms (2.7.1-4ubuntu2) ...
Selecting previously unselected package bison.
Preparing to unpack .../28-bison_2%3a3.4.1+dfsg-4_arm64.deb ...
Unpacking bison (2:3.4.1+dfsg-4) ...
Setting up libisl21:arm64 (0.21-2) ...
Setting up libmpc3:arm64 (1.1.0-1) ...
Setting up cpp-9 (9.2.1-9ubuntu2) ...
Setting up cpp (4:9.2.1-3.1ubuntu1) ...
Setting up libcc1-0:arm64 (9.2.1-9ubuntu2) ...
Setting up libgomp1:arm64 (9.2.1-9ubuntu2) ...
Setting up libitm1:arm64 (9.2.1-9ubuntu2) ...
Setting up libatomic1:arm64 (9.2.1-9ubuntu2) ...
Setting up libasan5:arm64 (9.2.1-9ubuntu2) ...
Setting up liblsan0:arm64 (9.2.1-9ubuntu2) ...
Setting up libtsan0:arm64 (9.2.1-9ubuntu2) ...
Setting up libubsan1:arm64 (9.2.1-9ubuntu2) ...
Setting up libgcc-9-dev:arm64 (9.2.1-9ubuntu2) ...
Setting up gcc-9 (9.2.1-9ubuntu2) ...
Setting up gcc (4:9.2.1-3.1ubuntu1) ...
Setting up libdpkg-perl (1.19.7ubuntu2) ...
Setting up make (4.2.1-1.2) ...
Setting up dpkg-dev (1.19.7ubuntu2) ...
Setting up dkms (2.7.1-4ubuntu2) ...
Setting up libc-dev-bin (2.30-0ubuntu2) ...
Setting up linux-libc-dev:arm64 (5.3.0-19.20) ...
Setting up libc6-dev:arm64 (2.30-0ubuntu2) ...
Setting up libstdc++-9-dev:arm64 (9.2.1-9ubuntu2) ...
Setting up g++-9 (9.2.1-9ubuntu2) ...
Setting up g++ (4:9.2.1-3.1ubuntu1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.8ubuntu1) ...
Setting up m4 (1.4.18-2) ...
Setting up bison (2:3.4.1+dfsg-4) ...
update-alternatives: using /usr/bin/bison.yacc to provide /usr/bin/yacc (yacc) in auto mode
Setting up flex (2.6.4-6.2) ...
Selecting previously unselected package pivccu-modules-dkms.
(Reading database ... 101086 files and directories currently installed.)
Preparing to unpack .../0-pivccu-modules-dkms_1.0.36_all.deb ...
Unpacking pivccu-modules-dkms (1.0.36) ...
Selecting previously unselected package libfakeroot:arm64.
Preparing to unpack .../1-libfakeroot_1.24-1_arm64.deb ...
Unpacking libfakeroot:arm64 (1.24-1) ...
Selecting previously unselected package fakeroot.
Preparing to unpack .../2-fakeroot_1.24-1_arm64.deb ...
Unpacking fakeroot (1.24-1) ...
Selecting previously unselected package libalgorithm-diff-perl.
Preparing to unpack .../3-libalgorithm-diff-perl_1.19.03-2_all.deb ...
Unpacking libalgorithm-diff-perl (1.19.03-2) ...
Selecting previously unselected package libalgorithm-diff-xs-perl.
Preparing to unpack .../4-libalgorithm-diff-xs-perl_0.04-5build1_arm64.deb ...
Unpacking libalgorithm-diff-xs-perl (0.04-5build1) ...
Selecting previously unselected package libalgorithm-merge-perl.
Preparing to unpack .../5-libalgorithm-merge-perl_0.08-3_all.deb ...
Unpacking libalgorithm-merge-perl (0.08-3) ...
Selecting previously unselected package libfile-fcntllock-perl.
Preparing to unpack .../6-libfile-fcntllock-perl_0.22-3build3_arm64.deb ...
Unpacking libfile-fcntllock-perl (0.22-3build3) ...
Selecting previously unselected package libfl-dev:arm64.
Preparing to unpack .../7-libfl-dev_2.6.4-6.2_arm64.deb ...
Unpacking libfl-dev:arm64 (2.6.4-6.2) ...
Selecting previously unselected package manpages-dev.
Preparing to unpack .../8-manpages-dev_5.02-1_all.deb ...
Unpacking manpages-dev (5.02-1) ...
Setting up manpages-dev (5.02-1) ...
Setting up libfile-fcntllock-perl (0.22-3build3) ...
Setting up libalgorithm-diff-perl (1.19.03-2) ...
Setting up libfl-dev:arm64 (2.6.4-6.2) ...
Setting up libfakeroot:arm64 (1.24-1) ...
Setting up fakeroot (1.24-1) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up pivccu-modules-dkms (1.0.36) ...

Creating symlink /var/lib/dkms/pivccu/1.0.36/source ->
                 /usr/src/pivccu-1.0.36

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.3.0-1008-raspi2 ARCH=arm64 all......
cleaning build area...

DKMS: build completed.

dummy_rx8130.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

dw_apb_raw_uart.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

eq3_char_loop.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

fake_hmrf.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

generic_raw_uart.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

hb_rf_usb.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

led_trigger_timer.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

meson_raw_uart.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

pl011_raw_uart.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

plat_eq3ccu2.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

rpi_rf_mod_led.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

rtc-rx8130.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-1008-raspi2/updates/dkms/

depmod......

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Setting up libalgorithm-diff-xs-perl (0.04-5build1) ...
Setting up libalgorithm-merge-perl (0.08-3) ...
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for install-info (6.6.0.dfsg.1-2ubuntu2) ...
Processing triggers for libc-bin (2.30-0ubuntu2) ...
`

Debmatic selber lässt sich sauber installieren, die Weboberfläche lässt sich ebenfalls öffnen. Nur die Hardware (HB-RF-USB-TK + RPI-RF-MOD) lässt sich nicht ansprechen.

**Comment by alexreinert** [comment]
Das dürfte ein Ubuntu Problem sein, man findet mehrere Confirmed Bug Reports, wenn man nach "modinfo: ERROR: missing module or filename" sucht. Die Module selbst werden ja ohne Fehler kompiliert, daher ist das kein Problem mit dem Kernel.
