### ISSUE TITLE
Einstellungen für Firewall?

### ISSUE THREAD

**Issue by MisterBJ** [alexreinert/debmatic#53]
Hallo,
ich habe die aktuelle FW 3.47.15.33 installiert und bei der Inbetriebnahme des neu Aufgesetzten openHab 2.4 (In einem Forum hatte ich bereits ein Beitrag von dir gelesen das man auf 2.5 wechseln muss, das habe ich getan 2.5M4 auf einen Pi3) ist mir aufgefallen das ich in der WebUI der CCU (als Admin) den Button "Firewall konfigurieren" nicht mehr finde. Hat sich dort etwas geändert oder ist bei der Installation ein Fehler aufgetretten?

Viele Grüße,
Björn

**Comment by alexreinert** [comment]
Den gibt es bereits seit der ersten Version von debmatic nicht, weil ich keine Vorgaben machen möchte, welche der vielen Firewall Möglichkeiten genutzt werden soll.

**Comment by MisterBJ** [comment]
Ach so, jetzt bin ich ein wenig aufgeschmiessen da ich nicht weiß bzw. nichts gefunden habe außer diese Seite:
[https://github.com/alexreinert/debmatic/issues/11](url)
Ich weis, eigentlich gehört das nicht her aber wie bekomme ich die Kommunikation mit openHab hin da dieser folgenden Fehler ausgibt:
OFFLINE - COMMUNICATION_ERROR Unknown XML-RPC tag: title

**Comment by MisterBJ** [comment]
Jetzt wird es komisch. Mir ist debmatic-info wieder eingefallen:
debmatic version: 3.47.15-33
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown

Bei mir ist wieder der Kernel 4.19.80-v7+ wie bei #50 installiert.
Es ist aber immer noch die gleiche Installation. Das einzige das ich heute noch ausgeführt habe ist `rpi-update`, kann der Kernel davon kommen?

**Comment by alexreinert** [comment]
Das erklärt vermutlich das Problem mit openHab.
Aber wirklich komisch ist das nicht, rpi-update ist dazu da um auf den den aktuellen testing Kernel zu aktualisieren, welcher dann natürlich nicht mehr zu den installierten Headern passt. Auf einem produktiven System sollte man rpi-update generell vermeiden, weil sich testing Kernel und produktives System etwas beißt. Siehe auch https://www.raspberrypi.org/documentation/linux/kernel/updating.md
Dort steht auch, wie man wieder zurück kommt.

**Comment by MisterBJ** [comment]
Das so tiefgreifend ist war mir nicht klar. Danke dir, habe es zurück gesetzt und es funktioniert wieder.
Als Dank für deine Hilfe habe ich etwas aus deiner A. Wunschliste verschickt.

Gruß Björn

**Comment by anetz89** [comment]
> Den gibt es bereits seit der ersten Version von debmatic nicht, weil ich keine Vorgaben machen möchte, welche der vielen Firewall Möglichkeiten genutzt werden soll.

Wie kann man die Firewall Möglichkeiten dann nutzen und welche gibt es? Ziel ist es einen restricted Access für openHAB einzurichten, wie in der offiziellen Doku beschrieben (https://www.openhab.org/addons/bindings/homematic/). Ist das auch ohne Web-UI möglich?

Mein Setup ist ein openHABian mit installiertem debMatic (was übrigens sehr reibungslos funktioniert hat, vielen Dank!)

**Comment by Tech4Ever** [comment]
ich habe heute auf openhab 5 aktualisiert und installiere gerade meine ganzen Tools, u.a. CCU. ChatGPT hat mir statt zu piVCCU zu debmatic geraten. Gesagt, getan. Ich bekomme nun aber auch ausschließlich den Fehler "OFFLINE - COMMUNICATION_ERROR" im openhab Thing. Auch ich wollte mir dann die Firewall Settings der debmatic CCU anschauen, aber die Funktion ist nicht mehr gegeben ( zumindest nicht über das Webfrontend). Was kann ich sonst noch tun? Oder ist debmatic nicht zu openhab (5) kompatibel?
