### ISSUE TITLE
Fenster Geräte anlernen nicht vollständig sichtbar

### ISSUE THREAD

**Issue by peoples0815** [alexreinert/debmatic#54]
Hallo,
ich habe die aktuelle Version auf meinem Proxmox (Debian 10) installiert und finde das Projekt sehr spannend leider sehe ich das Fenster von Geräte anlernen nicht vollständig, Screenshot anbei.
![debmatic](https://user-images.githubusercontent.com/39387321/68126024-2747f700-ff13-11e9-9f16-105864dacb70.JPG)

**Comment by alexreinert** [comment]
Welche Funkhardware wird verwendet und was wird in der Konsole bei debmatic-info ausgegeben?

**Comment by peoples0815** [comment]
Ich hatte eine alte "umgebaute" CCU2 als Funk-Lan-Gateway eingetragen. 
Gerade habe ich dann mal meinen gekauften Funk-Lan-Gateway eingetragen und schon ist das Fenster vollständig zu sehen.

Hier der Log:
debmatic version: 3.47.15-33
Kernel modules: Available
Raw UART dev:   Not available
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown

**Comment by alexreinert** [comment]
In dem Dialog ist immer nur das zu sehen, was an Protokollen auch verfügbar ist. Ich gehe daher davon aus, dass die umgebaute CCU2 einfach nicht korrekt gefunden wurde oder der zwingende Neustart nach der Einrichtung nicht durchgeführt wurde.
Sehe ich es richtig, dass der Issue damit geschlossen werden kann?

**Comment by peoples0815** [comment]
Der Neustart wurde durchgeführt aber mit meiner CCU2 geht es nicht. Mit dem gekauften Funk-Lan-Gateway jedoch völlig problemlos. 

Somit würde ich das Issue schließen. Danke - Tolles Projekt
