### ISSUE TITLE
2 Homematic Geräte lassen sich nicht aus der Debmatic löschen

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#55]
Hallo, ich habe immer noch das Problem, das ich Homematic Geräte nicht löschen kann.
Die geht auch nach dem Update auf Version 3.47.22.36 nicht.
Das eine Gerät ist ein Funk Türgong mit Signalleuchte, das andere eine Funk Fernbedienung mit Display. Beide Garäte zeigen auch keine Einstellseite mehr an.
Was kann ich noch machen?

**Comment by alexreinert** [comment]
Welche Geräte sind das genau? Was zeigt debmatic-info an? Welche Funkhardware wird verwendet?

**Comment by heinog** [comment]
wie rufe ich debmatic info auf

**Comment by alexreinert** [comment]
In der Konsole (Bildschirm/SSH) als root ```debmatic-info```

**Comment by heinog** [comment]
HM-OU-CF-Pl Funk-Türgong mit Signalleuchte
HM-RC-Dis-H-x-EU Fernbedienung mit LCD Display

Neues HomeMatic Funkmodul für CCU3 (Fertig aufgebaut) - Für RaspberryMatic / piVCCU3 mit externer Antenne

root@heinog-NUC5i3RYH:~# debmatic-info
debmatic version: 3.47.22-36
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A71A53
Radio MAC:      0xBE5A6E
SGTIN:          3014F711A0001F58A9A71A53

**Comment by alexreinert** [comment]
Das sieht erstmal gut aus. Könntest du mir vielleicht ein Backup zukommen lassen, dann kann ich schauen, ob ich es damit nachgestellt bekomme.

**Comment by heinog** [comment]
Ok mache ich, wenn ich heute Mittag zuhause bin.

Alexander Reinert <notifications@github.com> schrieb am Mi. 6. Nov. 2019 um
21:30:

**Comment by heinog** [comment]
Hallo, hier kommt das Debmatic Backup

Am Mi., 6. Nov. 2019 um 21:30 Uhr schrieb Alexander Reinert <
notifications@github.com>:

**Comment by alexreinert** [comment]
Man kann keine Dateien per Mail an einen Githun Issue schicken. Zum Glück für dich, sonst wäre dein Backup jetzt öffentlich im Netz verfügbar.
Schick es mir bitte direkt per Mail (alex at areinert.de)

**Comment by alexreinert** [comment]
Es handelte sich um eine Inkonsistenz in der Regadom. Korrekturanweisungen wurden direkt per Mail geschickt.
