### ISSUE TITLE
debmatic und hb-uni-sensor1

### ISSUE THREAD

**Issue by github6043** [alexreinert/debmatic#57]
Hallo zusammen
Habe auf einer Ubuntu ESXi VM die aktuelle debmatic am drehen. Nun auf der Konsole mit apt installiert. 

Listing... Done
hb-uni-sensor1/stable,now 2.0.3-2 all [installed]

wie kann ich nun weiter konfigurieren ? Wo ist das AddOn bei debmatic sichtbar ?

**Comment by alexreinert** [comment]
Das Addon kann nicht weiter konfiguriert werden, weder bei debmatic, noch bei der CCU. Es stellt einfach nur die notwendigen XML Dateien für den rfd bereit, so dass ein entsprechendes Gerät über den normalen Weg angelernt werden kann und dann auch wie ein normales Homematic Gerät konfiguriert und genutzt werden kann.

**Comment by alexreinert** [comment]
Sind noch Fragen offen?

**Comment by github6043** [comment]
Nein alles klar. Besten dank !
    	
    	

    	
    
  




On Fri, Nov 29, 2019 at 11:23 AM +0100, "Alexander Reinert" <notifications@github.com> wrote:












Sind noch Fragen offen?
