### ISSUE TITLE
Apache Support bzw. allgemeine Kompatibilität mit existierenden Servern

### ISSUE THREAD

**Issue by TinoKossmann** [alexreinert/debmatic#58]
Hallo Alex,

_debmatic_ bringt lighttpd-Konfigurationen mit, die auf den ersten Blick recht umfangreich sind. Besteht die Möglichkeit, zusätzlich Apache-Konfigurationen mitzuliefern bzw. Apache optional als alternativen Webserver verwenden zu können? Auf vielen Systemen ist dieser ja bereits in Nutzung (und belegt Port 80 und 443) und ein paralleler lighttpd (auf anderem Port) mit vorgeschaltetem Apache als Proxy ist suboptimal, wenn es auch anders gehen würde.

Ebenso das Ablegen von Dateien direkt unter /www/ - auch hier können ggf. Kollisionen zu schon vorhanden Dateien entstehen.

Die Firmware unter /firmware/ wäre in meinen Augen ggf. auch unter /usr/lib/firmware/{debmatic,eq3,....}/ o.ä. besser aufgehoben.

Ich könnte mir vorstellen, dass o.a. "Probleme" alle historisch begründet sind und diese noch nicht priorisiert wurden, oder?

**Comment by alexreinert** [comment]
Bei /www und /firmware bin ich ähnlicher Meinung. Rein gibt es hier das Problem, dass manche Dinge leider hart codiert sind und ich da erst die Zeit für finden muss, dass in Ruhe umbauen zu können.
Zwecks Apache: Mit dem letzten Update kam auch die Möglichkeit, debmatic auch auf einen anderen Port zu legen, der Punkt sollte damit bereits erledigt sein, oder?

**Comment by TinoKossmann** [comment]
Jein. Wenn du den debmatic-httptpd auf einen anderen Port (8080 o.ä.) legst, und im Apache einen _ProxyPass_ oder eine _RewriteRule_ in entsprechendem _VirtualHost_ anlegst, laufen ja unnötigerweise 2 Webserver auf dem System. Das kann man zwar so machen, ist aber nicht die schönste Lösung.

Ist halt ein "Schönheits-Problem", welches ich an deiner Stelle aber auch nicht priorisieren würde. V.a., wenn jemand unbedingt den Apache nutzen möchte, kann er den _VirtualHost_ ja konfigurieren und dir die Datei zur Verfügung stellen.

Ich sträube mich momentan noch, die Pakete auf meinem produktiven Server zu installieren. Sollte ich mich durchringen können, gucke ich mir das mit dem Apache aber gerne mal an. Hilfreich wäre vorab aber die saubere Strukturierung in entsprechenden Unterordnern.

**Comment by ingoha** [comment]
Ganz wichtiger Hinweis: Der Port muss auch in /etc/lighttpd/lighttpd.conf geändert werden!
