### ISSUE TITLE
Installation geht gut, Anlernen ist schwierig, "Gerätekommunikation gestört"

### ISSUE THREAD

**Issue by Doreinie** [alexreinert/debmatic#59]
Hallo,
Ich habe folgende Konstellation und bin ein unerfahrener Einsteiger.
Hoffe dass ich hier meine Frage stellen darf.
Habe Raspberry Pi 4B mit Raspbian Buster + RPI-RF-MOD.    
Zum Anlernen und Testen habe ich einen HmIP-SPI, neu, FW: 1.4.0
Raspbian ist frisch installiert. Die Debmatic Installation verläuft reibungslos und der RPI-RF-MOD wird sauber erkannt die LED leuchtet blau.

Das Anlernen des Präsenzmelders gestaltet sich sehr schwierig. Nach vielen Factory-Reset etc hat es dann aber irgendwann geklappt. Aber es gibt Probleme und ich habe keine Ahnung ob es an mir, dem Melder oder dem RaspPi4 oder dem MOD board liegt..
Wenn ich in Status -> Geräte z.B. "Präsenzerkennung ausschalten" klicke gibt es eine Servicemeldung "Gerätekommunikation gestört". (LED blinkt dann blau gün)
Im Status friert die Helligkeit ein auf eine Nummer z.B 57. Auch wenn ich den Melder abdecke verändert sich der Wert nicht.
Auf der Seite "Servicemeldung" ist halte diese Servicemeldung. Der Button "Bestätigen"ist sichbar. kann aber nicht geklickt werden. Wenn "Alle Bestätigen" geklickt wid verschwindet  die Störungsmeldung nicht auch wenn die Timestamp z.B 5 oder 10Min in alt ist.
Die Störung is weg nur nach "sudo service debmatic restart". (LED blau)
Störung Ist aber wieder da wenn Reset Status oder Präsenzerkennung ausschalten geklickt wird.
unten ausdruck von:
a) sudo systemctl list-dependencies debmatic.service
b) sudo debmatic-info
c) sudo service debmatic status

Vielen Dank für die Hilfe, tappe komplett im dunkeln...
LG Reimund

pi@raspberrypi:~ $ sudo systemctl list-dependencies debmatic.service
debmatic.service
● ├─debmatic-eq3configd.service
● ├─debmatic-hmserver.service
● ├─debmatic-hs485d.service
● ├─debmatic-hssled.service
● ├─debmatic-lighttpd.service
● ├─debmatic-multimacd.service
● ├─debmatic-prepareinterfaceslist.service
● ├─debmatic-rega.service
● ├─debmatic-rfd.service
● ├─debmatic-setinterfaceclock.timer
● ├─debmatic-ssdpd.service
● ├─debmatic-startupfinished.service
● ├─debmatic-updatelgwfirmware.service
● ├─debmatic-updatelgwkey.service
● ├─debmatic-updaterffirmware.service
● ├─pivccu-dkms.service
● ├─system.slice
● └─sysinit.target
●   ├─apparmor.service
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─fake-hwclock.service
●   ├─keyboard-setup.service
●   ├─kmod-static-nodes.service
●   ├─plymouth-read-write.service
●   ├─plymouth-start.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-utmp.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─-.mount
●   │ ├─boot.mount
●   │ ├─systemd-fsck-root.service
●   │ └─systemd-remount-fs.service
●   └─swap.target

pi@raspberrypi:~ $ sudo debmatic-info
debmatic version: 3.47.22-36
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   58A9A718BA
Radio MAC:      unknown
SGTIN:          3014F711A0001F58A9A718BA

pi@raspberrypi:~ $ sudo service debmatic status
● debmatic.service - debmatic
   Loaded: loaded (/lib/systemd/system/debmatic.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2019-11-20 22:35:23 CET; 4min 47s ago
  Process: 3112 ExecStart=/usr/share/debmatic/bin/initsystem.sh (code=exited, status=0/SUCCESS)
 Main PID: 3112 (code=exited, status=0/SUCCESS)

Nov 20 22:35:09 raspberrypi systemd[1]: Starting debmatic...
Nov 20 22:35:23 raspberrypi systemd[1]: Started debmatic.

**Comment by alexreinert** [comment]
Wie ist das Funkmodul auf dem Pi angebracht? Wie erfolgt die Stromversorgung? Wird eine externe Antenne am Funkmodul verwendet? Wie weit sind die Geräte auseinander? Wie hoch ist der DutyCycle, wenn es zu den Servicemeldungen kommt?

**Comment by Doreinie** [comment]
Hallo, das Funkmodul is einfach gut aufgesteckt mit einem Zwischenstück damit es auch passt.
Stromzufuhr über den Stecker am RPI-RF-MOD.
Keine externe Antenne. 
Dyty cycle ist bei 2 da es nur ein Testgerät HmIP-SPI gibt.
Der HmIP-SPI war während des Tests mal direkt neben dem RPi4 und mal 2 oder 4m Distanz.
Nun bin ich auf die Idee gekommen den Pi4 den ich auf dem Schreibtisch neben Display und Laptop hatte an einem anderen Ort in Betrieb zu nehmen. Und siehe da alles funktioniert!! 
Entweder Laptop oder Display haben den RPi4 und den Empfang zum HmIP-SPI sehr gestört.
Ist schon recht merkwürdig wie empfindlich die Geräte sind.
Ich habe 4 Tage probiert und mit Debmatic oder auch mit raspberrymatic ohne Erfolg aber mit Verzweiflung probiert. :-)

Reimund

**Comment by alexreinert** [comment]
Gut, freut mich, dass es jetzt klappt.
Klare Empfehlung wäre noch eine externe Antenne, die löst viele Probleme mit dem Empfang.
