### ISSUE TITLE
Ein paar fragen welche ich nicht klären konnte

### ISSUE THREAD

**Issue by disaster123** [alexreinert/debmatic#6]
Wo ist nachher der Unterschied zur occu? Was ist mit hm-cfg-usb2 wird der unterstützt? Danke!

**Comment by alexreinert** [comment]
> Wo ist nachher der Unterschied zur occu?
OCCU ist einfach nur eine Sammlung von Dateien ohne wirkliche Installationsroutine. In debmatic sind diese dann sauber in Pakete verpackt und auf das Debian Ökosystem angepasst.

> Was ist mit hm-cfg-usb2 wird der unterstützt?
Aktuell nein, daher steht er auch nicht in der Auflistung im Readme.

**Comment by disaster123** [comment]
Kann ich denn den hmland daemon benutzen um ein hm lan device zu emulieren?

**Comment by alexreinert** [comment]
Kann ich leider nicht sagen, habe ich nie getestet.

**Comment by disaster123** [comment]
Man hat am Ende ein HM-LAN-IF das funktioniert problemlos hatte ich vor Jahren schonmal im Einsatz. Wird denn HM-LAN-IF unterstützt?

**Comment by alexreinert** [comment]
LAN GW wird unterstützt (steht ja auch im Readme). Wenn sich der daemon exakt wie ein LAN GW verhält, dann sollte es gehen. Aber ich habe es wie gesagt noch nie getestet.

**Comment by disaster123** [comment]
Ok super! Hoffentlich die letzte frage ;-)  in https://homematic-forum.de/forum/viewtopic.php?f=78&t=47718 finde ich keine Kernel patches warum / wieso werden hier spezielle Kernel Module benötigt wohingegen occu keine hat/braucht? Wo ist da mein Denkfehler?

**Comment by alexreinert** [comment]
Sofern wirklich nur ein LAN GW nutzt, braucht man keine Kernel Module. Sobald aber eines der direkt angeschlossenen Funkmodule genutzt wird, braucht man diese, da der Betrieb diese für den Zugriff auf die Hardware über den multimacd notwendig sind.

**Comment by disaster123** [comment]
Installation lief sauber durch. Ich habe nun unter Einstellungen => Systemsteuerung => LAN Gateway Konfiguration im oberen Bereich das HM-LAN hinzugefügt. Interface-Zuordnung bleibt aber leer. Was bedeutet das? Ich habe mehrfach irgendwo gelesen, man soll /etc/config/rfd.conf per Hand editieren...

Aktuell sieht diese wie folgt aus:
```
...

[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#AccessFile = /dev/null
#ResetFile = /dev/ccu2-ic200



[Interface 1]
Type = Lan Interface
Name = hmland
Serial Number = KEQ1111109
Encryption Key = 
IP Address = 192.168.178.101
```

**Comment by disaster123** [comment]
ah OK man muss debmatic nochmal komplett rebooten. Das sieht nun ganz gut aus. Muss ich nun wirklich alle devices neu anlernen? Oder kriege ich die Dinge vom Windows Bidcos Service irgendwie in die ccu?

**Comment by alexreinert** [comment]
Soweit mir bekannt ist, gibt es keine Möglichkeit, Daten vom Windows Bidcos Service in irgendeine CCU zu übernehmen und damit dann auch nicht in debmatic.

**Comment by disaster123** [comment]
Ok vielen Dank für die Klasse Arbeit. Occu ist in der Tat reines gefummel und die Services sind wie Kraut und Rüben organisiert.
Debmatic läuft nun bei mir sauber mit dem HM-CFG-USB2 via hmland und in einem docker Container solange ich die Kernel Treiber nicht brauche.

**Comment by alexreinert** [comment]
Freut mich. Dann mach ich hier zu.
