### ISSUE TITLE
Web Port ändern

### ISSUE THREAD

**Issue by MisterBJ** [alexreinert/debmatic#60]
Hi,

ich habe den Port 80 auf 8081 in der lighttpd.conf geändert aber nach einen Neustart des Pi steht die Web-UI immer noch über Port 80 zur Verfügung.

Gruß,
Björn

**Comment by alexreinert** [comment]
Der Port muss auch in der /etc/debmatic/webui.conf geändert werden.

**Comment by alexreinert** [comment]
Ist die Frage damit beantwortet?

**Comment by MisterBJ** [comment]
Ja, Prima! Hatte leider vergessen zu closen.

**Comment by Doreinie** [comment]
ist das immer noch so, dass der Port in zwei Dateien geändert werden muss oder reicht es in /etc/debmatic/webui.conf 
z.B.: von 80 auf 85
var.debmatic_webui_http_port = 85
