### ISSUE TITLE
JSON-RPC API Methode "Session.login" gestört, sobald WebUI Port ungleich 80 ist

### ISSUE THREAD

**Issue by gerklu** [alexreinert/debmatic#62]
Über die JSON-RPC API Methode "Session.login" ist es möglich mittels Benutzername/Passwort eine WebUI Session zu starten.

Das funktioniert soweit auch mit DebMatic in der Standardkonfiguration.

Wird jedoch der WebUI Standardport von 80 auf 81 geänder (über die webui.conf), kommt es zu einem Fehler und ein Login mit dieser Methode ist nicht möglich.

Beispiel Request Body:

`{"method":"Session.login","params":{"username":"user","password":"password"}}`

Fehler-Response:
```
{
  "version": "1.1",
  "result": null,
  "error": {
    "name": "JSONRPCError",
    "code": 501,
    "message": "invalid credentials or too many sessions"
  }
}
```

Die Fehlerursachen "invalid credentials" oder "too much sessions" können ausgeschlossen werden. Fehler ist reproduzierbar.

**Comment by alexreinert** [comment]
Fixed in 3.47.22-39 bzw. 3.49.17-40. Beide Versionen sind im testing APT Repository verfügbar.

**Comment by alexreinert** [comment]
Beide Versionen sind schon länger im stable APT Repository, daher hier closed
