### ISSUE TITLE
Port Debmatic

### ISSUE THREAD

**Issue by pbu-mu** [alexreinert/debmatic#63]
Ich habe Debmatic und Apache 2 auf einem System laufen. Leider benutzt Debmatic den Port 80, der eigentlich für normale Websites von Apache 2 benutzt wird. Das hat die Auswirkung, dass  Apache 2 nicht läuft.
Nach Umbiegen des Apache http-Ports geht zwar alles. Allerdings ist diese keine schöne Lösung, da dann normale Websites nur mit Angabe des Ports aufgerufen werden können. 

Eine Änderung des Debmatic-Ports über /etc/debmatic/webui.conf funktioniert nur begrenzt. Dann lassen sich in der Debmatic in der Systemsteuerung einige Positionen nicht mehr aufrufen.

Gibt es eine Lösung?

**Comment by alexreinert** [comment]
Duplicate zu #62 
Ich bin dran.
