### ISSUE TITLE
Gewerke

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#64]
Hallo, ich habe mir das Heizungsscript über iobroker in Betrieb genommen und nun leider festgestellt, das bei einigen Geräten die Gewerke auf Englisch eingetragen sind. Kann man das ändern, damit ich die Deutschen Bezeichnungen bekomme? Bei Verschluss steht z.B. funcLock

**Comment by alexreinert** [comment]
Welches Heizungsscript? Wo steht das funcLog? (Screenshot).

**Comment by heinog** [comment]
wenn ich in der Webui auf Geräte gehe und dort auf Gewerke sind einige teile auf Deutsch und andere auf Englisch.
	funcCentral
	funcLight
	funcLock
	funcSecurity
	funcWeather
	Heizung
	Monitored
	Temperatur
Gehe ich auf Gewerkeliste bearbeiten, steht alles auf Deutsch da

**Comment by heinog** [comment]
![liste](https://user-images.githubusercontent.com/56246354/70349379-e706cc00-1864-11ea-880e-7e91a0c328a5.jpg)
![gewerke](https://user-images.githubusercontent.com/56246354/70349381-e706cc00-1864-11ea-8d08-8244732698b4.jpg)

**Comment by alexreinert** [comment]
Dann einfach in die Gewerkeliste gehen und das bearbeiten und neu speichern.

**Comment by heinog** [comment]
Hat funktioniert. Danke
