### ISSUE TITLE
Kein Backup möglich

### ISSUE THREAD

**Issue by heinog** [alexreinert/debmatic#65]
Hallo, ich wollte heute ein älteres Backup zurückspielen. Wenn ich auf dem Button Sicherheit gehe, bleibt das Fenster ausgegraut. Auch ein Neustart über Reboot hat nichts gebracht.
Kann ich das Backup auch über Putty zurückholen?

**Comment by heinog** [comment]
Jetzt haben sich noch 2 weitere Fehler gezeigt.
Beim Neu Anlernen von einer Homematic IP Messteckdose wird der Teilnehmer angezeigt, im Posteingang aber nicht.
 Dann noch das Problem der Favoriten auf der Startseite. Wechsel ich den Favoriten erscheint immer Loading und verschwindet erst wenn ich die Seite neu aufbaue.
![neues Gerät](https://user-images.githubusercontent.com/56246354/70389030-475b5200-19ba-11ea-9bb4-bd58537ac696.jpg)
![startseite](https://user-images.githubusercontent.com/56246354/70389031-475b5200-19ba-11ea-9604-49beda6c06fe.jpg)
![posteingang](https://user-images.githubusercontent.com/56246354/70389032-475b5200-19ba-11ea-9ec1-6de99d1c9257.jpg)

**Comment by alexreinert** [comment]
Mal den Browsercache mit Strg+F5 gelöscht?

**Comment by heinog** [comment]
Ja, habe ich schon gemacht, ohne erfolg

**Comment by heinog** [comment]
Auch das Bild Servicemeldungen sieht merkwürdig aus
![servicemeldungen](https://user-images.githubusercontent.com/56246354/70502867-434a4400-1b22-11ea-9116-8f0b8f7fbbd5.jpg)

**Comment by alexreinert** [comment]
Das sieht alles danach aus, dass die (externen) Javascript Dateien nicht ausgeführt werden. Entweder, weil sie fehlerhaft bzw. alt im Browsercache liegen, oder weil sie nicht geladen werden können. Idealerweise mal mit den Developer Tools des Browser prüfen, ob die Javascripts geladen werden können.

**Comment by heinog** [comment]
Stimmt, es liegt an Google Chrom. Mit Firefox geht es und sieht auch alles gut aus.
Keine Ahnung, warum Chrom probleme macht.
