### ISSUE TITLE
Deinstallieren/Installieren von debmatic 3.47.22-38 schlägt immer fehl

### ISSUE THREAD

**Issue by DenisMtfl** [alexreinert/debmatic#67]
Egal ob install oder remove ich bekomme es nicht mehr zum laufen seit Version -38

dpkg: Fehler beim Bearbeiten des Paketes debmatic (--remove):
 »installiertes debmatic-Skript des Paketes pre-removal«-Unterprozess gab den Fehlerwert 2 zurück
Fehler traten auf beim Bearbeiten von:
 debmatic
E: Sub-process /usr/bin/dpkg returned an error code (1)

**oder**

pi@raspi4:~ $ sudo dpkg --purge --force-all debmatic
(Lese Datenbank ... 269638 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von debmatic (3.47.22-38) ...
Ignoring unknown module: debmatic
Run "service lighttpd force-reload" to enable changes
dpkg: Fehler beim Bearbeiten des Paketes debmatic (--purge):
 »installiertes debmatic-Skript des Paketes pre-removal«-Unterprozess gab den Fehlerwert 2 zurück
Fehler traten auf beim Bearbeiten von:
 debmatic

**Jemand eine Idee?**
**Any idea?**

**Comment by alexreinert** [comment]
Was kommt bei `systemctl force-reload lighttpd.service`?

**Comment by alexreinert** [comment]
(ggf mit sudo)

**Comment by DenisMtfl** [comment]
nichts...

**Comment by DenisMtfl** [comment]
Laut status läuft der auch nicht ... weil da irgendwas kaputt ist.

● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-12-18 11:24:49 CET; 2min 19s ago

Dez 18 11:24:49 raspi4 systemd[1]: lighttpd.service: Service RestartSec=100ms expired, scheduling restart.
Dez 18 11:24:49 raspi4 systemd[1]: lighttpd.service: Scheduled restart job, restart counter is at 5.
Dez 18 11:24:49 raspi4 systemd[1]: Stopped Lighttpd Daemon.
Dez 18 11:24:49 raspi4 systemd[1]: lighttpd.service: Start request repeated too quickly.
Dez 18 11:24:49 raspi4 systemd[1]: lighttpd.service: Failed with result 'exit-code'.
Dez 18 11:24:49 raspi4 systemd[1]: Failed to start Lighttpd Daemon.
Dez 18 11:25:28 raspi4 systemd[1]: /lib/systemd/system/lighttpd.service:6: PIDFile= references path below legacy directory /var/run/, updating /var/run/lighttpd.pid → /run/lighttpd.pi

**Comment by DenisMtfl** [comment]
Warum ist denn die /etc/lighttpd/lighttpd.conf leer?

**Comment by alexreinert** [comment]
Das kann ich dir nicht sagen, definitiv nicht durch debmatic. Aber es erklärt dein Problem.

**Comment by DenisMtfl** [comment]
Hm okay also ich habe jetzt lighttp deinstalliert und dann hat er auch debmatic deinstalliert ...
nun wollte ich debmatic neuinstallieren geht auch aber ist nicht erreichbar ...

**Comment by alexreinert** [comment]
Was heißt nicht erreichbar?

**Comment by DenisMtfl** [comment]
Per Browser nicht ereichbar unter Port 80

**Comment by DenisMtfl** [comment]
Also ... jetzt habe ich lighttp mit --purge nochmal deinstalliert ... debmatic neuinstalliert und nun geht alles wieder. 

**Danke für deine Hilfe trotzdem!** Bin eben doch "nur" .NET Entwickler und kein Linux experte ;)
