### ISSUE TITLE
Addons korrekt deinstallieren

### ISSUE THREAD

**Issue by dogexan** [alexreinert/debmatic#69]
Wie werden aus Debmatic Addons korrekt deinstalliert?
Als Beispiel geht es um dieses Addon "jp-hb-devices"

Installation via `sudo apt install jp-hb-devices`

Deinstallation via `sudo apt remove jp-hb-devices` ?

Wenn ich das Addon per **apt remove** deinstalliere, dann zerschieße ich mir die komplette Debmatic Konfiguration. Sprich keine HM-Geräte sind mehr sichtbar/verfügbar.

Ist die Deinstallation so korrekt oder gibt es für Debmatic einen anderen weg?

Vielen Dank im Voraus

**Comment by alexreinert** [comment]
Das ist der korrekte Weg und ich habe diesen auch mehrfach getestet. Daher bitte genauere Info, bei welchen Versionen das Problem auftaucht.
Wurde nach der Deinstallation der Browsercache gelöscht? Wurde auch ein Neustart von debmatic versucht?

**Comment by dogexan** [comment]
Danke für die schnelle Antwort.

Debmatic Version: 3.47.22.38
Addon jp-hb-devices 2.11-7

Reboot von Debmatic und des kompletten RPI4 wurde ebenfalls gemacht.

Browercache wurde nicht explizit gelöscht. Nur zufälligerweise der PC neugestartet.

Hab das Problem noch ein zweites Mal nachstellen können.

Ich kann gerne das ganze nocheinmal durchspielen mit Browsercache löschen. Allerdings glaube ich nicht daran, dass es alleine der Bowsercache war. Meine Anbindung an FHEM war ebenfalls unbrauchbar geworden. Daher gehe ich davon aus, dass wirkliche alle Geräte gelöscht waren. Das einzigvorhandene war eine Virtuelle Fernbedienung die aus den Zentralen hervorgeht.

Wie gesagt kanns gerne nochmal durchspielen, habe ein Backup vom kompletten Pi
