### ISSUE TITLE
Spezifische Addon Version installieren von jp-hb-devices

### ISSUE THREAD

**Issue by dogexan** [alexreinert/debmatic#70]
Benötig wird die Version 2.6 von jp-hb-devices 
[https://github.com/jp112sdl/JP-HB-Devices-addon/releases/2.6](url)

Benötigt wird diese Version für das Projekt:
[https://technikkram.net/2019/05/anleitung-diy-feuchtigkeitssensor-fuer-gartenbewaesserung-bausatz-homematic](url)

In der Repository ist nur die neuere Version 2.11-7 verfügbar.
siehe:

`pi@rpi4:~ $ apt-cache policy jp-hb-devices`

Output:
```
 jp-hb-devices:
   Installiert:           (keine)
   Installationskandidat: 2.11-7
   Versionstabelle:
      2.11-7 500
         500 https://www.debmatic.de/debmatic stable/main armhf Packages
```

Besteht die Möglichkeit in die Repository auch die Version 2.6 abzulegen?

Bzw. gibt es einen Weg sich die passende Version selbst für Debmatic zu kompilieren?

Vielen Dank im Voraus

**Comment by alexreinert** [comment]
Die Version 2.6 ist nicht mehr mit aktuellen CCU Versionen kompatibel, daher nein.
Alles notwendige zum Selberbauen der Pakete ist hier im Repo zu finden, an  sich ist das ja nur ein bash Script.
