### ISSUE TITLE
Paket für Debian auf 3.49.17 upgraden

### ISSUE THREAD

**Issue by fuerst** [alexreinert/debmatic#73]
Hallo Alex,

`apt`unter Ubuntu installiert noch die Version 3.47.22:

```
# apt download --print-uris debmatic
'https://www.debmatic.de/debmatic/pool/main/d/debmatic/debmatic-3.47.22-38-amd64.deb' ...

# apt-cache policy| fgrep debmatic
 500 https://www.debmatic.de/debmatic stable/main i386 Packages
     origin www.debmatic.de
 500 https://www.debmatic.de/debmatic stable/main amd64 Packages
     origin www.debmatic.de
```

Ist die Version 3.49.17 noch nicht für Debian/Ubuntu verfügbar?

**Comment by alexreinert** [comment]
Wie gehabt kommen die neuen Majorversionen nicht sofort in das stable APT Repository, sondern erst in das testing APT Repository und gehen dann nach ca. 2 Wochen ohne Probleme auch in das stable über.
Die 3.49.22 ist daher aktuell nur im testing verfügbar und kommt in ein paar Tagen dann auch in stable.

**Comment by fuerst** [comment]
Ah, verstehe. Vielen Dank!
