### ISSUE TITLE
Fehler Debmatic 3.49.17.40 Rolladenaktor zeigt immer geschlossen an.

### ISSUE THREAD

**Issue by vw-arneth** [alexreinert/debmatic#76]
Habe heute das neue Update 

3.49.17.40
--
eingespielt.
Leider wird der Rolladenstatus nicht richtig mehr in der Oberfläche angezeigt. Rolladen sind geöffnet, aber er zeigt immer Geschlossen an....

**Comment by alexreinert** [comment]
Browsercache geleert und mit Strg+F5 einen Forced Refresh gemacht?

**Comment by vw-arneth** [comment]
Ja habe ich gemacht. springt immer wieder auf geschlossen Rollo.
