### ISSUE TITLE
Redmatic

### ISSUE THREAD

**Issue by stevechegg** [alexreinert/debmatic#77]
Hallo,
ist es irgendwann möglich Plugins wie Redmatic zu installieren?
Ich suche nach einer Möglichkeit Homekit einzubinden. Gibt es da Möglichkeiten?
Auch Alexa (Echo Dot) Anbindung wäre interessant. Bei der CCU gab es da einige Möglichkeiten allerdings ist bei debmatic (was ich persönlich deutlich besser finde da ich Debian Fan bin) die Nutzung von Addons ja ziemlich eingeschränkt.

Wäre super wenn es irgendwann möglich wäre. Übrigens tolle Arbeit! Ich liebe das Projekt!

Grüße

**Comment by alexreinert** [comment]
Du kannst NodeRed ganz normal unter Debian oder Ubuntu installieren, da braucht es kein extra Addon.

**Comment by alexreinert** [comment]
Noch Fragen offen?

**Comment by stevechegg** [comment]
Ah okay. Danke für den Tipp. Ich kenne es nur von der CCU da gab es ein Addon.
