### ISSUE TITLE
Debmatic mit WLAN

### ISSUE THREAD

**Issue by xerxes87** [alexreinert/debmatic#78]
Hi @alexreinert 
Ich habe gerade debmatic über meine pivccu3 installiert. Ist es möglich, debmatic über wlan zu betreiben? Muss da eine neue netconfig angepasst werden? Vielen Dank!

**Comment by alexreinert** [comment]
Im Gegensatz zu piVCCU braucht debmatic keine Bridge, weil kein Container notwendig ist. Daher braucht man keine besonderen Anpassungen vornehmen, sondern kann die Einrichtung so vornehmen, wie es tausendfach im Internet für Debian/Ubuntu/Raspbian beschrieben ist.

**Comment by xerxes87** [comment]
Super, funktioniert hervorragend mit frischem Raspbian. Vielen Dank!
