### ISSUE TITLE
RF-Status WebUI

### ISSUE THREAD

**Issue by fluxcondensator** [alexreinert/debmatic#79]
Hallo Alex,

hast du geplant, in der Geräteübersicht den RF Status zu integrieren?
Ich habe deine aktuellste SW installiert und betreibe das RF Modul über deine USB Bridge:

debmatic version: 3.49.17-40
Kernel modules: Available
Raw UART dev:   Available
HMRF Hardware:  RPI-RF-MOD
HMIP Hardware:  RPI-RF-MOD
Board serial:   5A...
Radio MAC:      0xB1...
SGTIN:          3014...

Danke für deine Rückmeldung.

**Comment by alexreinert** [comment]
Ja, aber das kann noch etwas dauern, da meine höchste Prio grade eine LAN Variante der HB-RF-USB.

**Comment by fluxcondensator** [comment]
Okay. Berichtest du über deine Arbeit des HB-RF-LAN schon im HM Forum?

**Comment by alexreinert** [comment]
Ja
