### ISSUE TITLE
Homematic IP Schaltsteckdose Wochenprogramm

### ISSUE THREAD

**Issue by Schattenruf** [alexreinert/debmatic#8]
Hallo,

ich habe seit heute eine HM IP Schaltsteckdose. Anlernen ging ohne Probleme, nur kann ich das Wochenprogramm nicht einstellen. Die Option zum Einstellen wird mir zwar angeboten, aber sobald ich meine Konfig abschicke, geht die Web-Ui in eine Dauerschleife für >10 Minuten und es passiert nichts. Wenn man einen 2, Tab öffnet und versucht die Steckdose damit an oder auszuschalten geht das, nur das Wochenprogramm wird nicht übertragen (Ch. 6).

![image](https://user-images.githubusercontent.com/12720317/55019703-ad9f7080-4ff5-11e9-91d7-70142c630bd1.png)
![image](https://user-images.githubusercontent.com/12720317/55019712-b1cb8e00-4ff5-11e9-9ec3-a726e6382af0.png)

**Comment by alexreinert** [comment]
Welche Version ist im Einsatz? Welche Funkhardware wird genutzt?

**Comment by Schattenruf** [comment]
Aktuelle Firmwareversion: | 3.43.15.10
Sowie Gerätefirmware: 2.6.2

Gerät: HMIP-PS

**Comment by alexreinert** [comment]
Welche Funkhardware wird genutzt?

**Comment by Schattenruf** [comment]
Ich habe nur den PI mit rpi-rf-mod und die Steckdose daran angelernt. Das Heizkörperthermostat von HM-IP funktioniert ohne Probleme mit dem Wochenplan nur die Steckdose will nicht.

**Comment by alexreinert** [comment]
Ok, als Funkhardware kommt also das RPI-RF-MOD zum Einsatz. ;-)

**Comment by alexreinert** [comment]
Es gibt eine neue Version 3.43.15.13, welche diverse Patches enthält, die in der CCU3 vorhanden sind, aber nicht in den OCCU Sourcen. Tritt das Problem damit auch auf?

**Comment by Schattenruf** [comment]
Wie kann ich updaten? Über sudo apt update && apt upgrade sind keine Updates verfügbar

**Comment by Schattenruf** [comment]
Gerade ausprobiert. Das Problem bleibt bestehen.

**Comment by alexreinert** [comment]
Ok, ich versuche ein Testgerät zu bekommen, damit ich das nachstellen kann.

**Comment by Schattenruf** [comment]
Auffällig ist auch, das bei einer Datenübertragung normalerweise die Taste blinkt. Hier ist allerdings alles aus. Deaktiviere ich bspw. die Router Funktion blinkt sie kurz.

**Comment by Schattenruf** [comment]
Ok. Wenn weiteres benötigt wird ;)
Grenzt ja schon an Live-Support :P

**Comment by alexreinert** [comment]
Ok, mit einem Testgerät konnte ich das Problem reproduzieren und lokalisieren.
Ich werde auch kurzfristig eine neue Version bereitstellen, aufgrund des Usertreffens wird das aber vermutlich erst nach dem Wochenende sein.
Zum kurzfristigen Beheben reicht es in der Datei /etc/lighttpd/conf-enabled/20-debmatic.conf
```
server.max-request-field-size = 65536
```
als erste Zeile hinzuzufügen.

**Comment by Schattenruf** [comment]
Danke funktioniert!

**Comment by alexreinert** [comment]
Fixed in 3.43.15.15

**Comment by frzlabis** [comment]
Hallo,

ich habe die Version: 3.75.7.115 installiert dennoch habe ich dasselbe Fehlerverhalten wenn ich ein Wochenprogramm für das Keypad HmIP-WKP oder Türschlossantrieb HmIP-DLD übertragen versuche --> Endlosschleife
![image](https://github.com/alexreinert/debmatic/assets/160973097/b113bf5e-2dc8-4c36-91a3-3e1d78a33523)

Ich verwende HB-RF-ETH als Gateway
