### ISSUE TITLE
Problem since changing my IP

### ISSUE THREAD

**Issue by chriwo83** [alexreinert/debmatic#82]
Hello, I changed the IP of my raspi where debmatic is running. Since this day I get this message in debmatic log:

```
Jän. 23 20:48:07 org.apache.http.impl.client.DefaultHttpClient INFO  [vert.x-worker-thread-16] I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://192.168.42.2:14702: Keine Route zum Zielrechner (Host unreachable) 
Jän. 23 20:48:07 org.apache.http.impl.client.DefaultHttpClient INFO  [vert.x-worker-thread-16] Retrying connect to {}->http://192.168.42.2:1470
```

The IP 192.168.42.2 was the old IP and is not used anymore. What can I do to get rid of this message? I am using debmatic and fhem on a raspery pi4 with all actual updates.

**Comment by Noschvie** [comment]
Hello, it seems that I have an issue similar to that: running debmatic on Rpi4 (with DHCP) and HomeMatic WebUI is reachable by the IP address configured by the LAN router but isn't reachable by the hostname configured by the router.
```
pi@raspberrypi:~ $ ping 192.168.1.41
PING 192.168.1.41 (192.168.1.41) 56(84) bytes of data.
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=0.468 ms

pi@raspberrypi:~ $ ping baumgarten
PING baumgarten (192.168.1.41) 56(84) bytes of data.
64 bytes from baumgarten.neunzehn.local (192.168.1.41): icmp_seq=1 ttl=64 time=0.355 ms
```
Any idea how to re-config?
Thanks!
