### ISSUE TITLE
Geräte-Firmware - Übersicht - Update Button ohne Funktion

### ISSUE THREAD

**Issue by loebelch** [alexreinert/debmatic#83]
Ich habe ein neues Device HMIP-PSM in meine Debmatic-Installation angelernt.
Dafür gibt es ein Update von 1.4.0 auf 2.6.2.
Update hat sich übertragen und nun erscheint der bekannte "Update"-Button.

Allerdings passiert aktuell gar nichts, wenn ich auf den Button klicke. 

Habe bereits mehrere Browser ausprobiert, Cache geleert, sowie auch kompletter Restart des Servers auf dem debmatic läuft. Gerät habe ich auch nochmal abgelernt und neu angelernt. Gleiches Verhalten nach Übertragung des FW-Updates - Update Button erscheint, lässt sich aber nicht anklicken.

Für einen anderen HMIP-PSM, hatte ich vor einigen Monaten problemlos das Update ausführen können.

Aktuelle Firmwareversion: | 3.49.17.40

Anbei ein Screenshot:
![image](https://user-images.githubusercontent.com/26137944/73116670-ac531300-3f3a-11ea-8839-e53bc562523a.png)

Ich habe per Developer-Tools auch mal geschaut, ob ein Request herausgeht. 
Hier fällt mir auf, dass ich als Response erhalte:

`{
  "version": "1.1",
  "result": null,
  "error": {
    "name": "JSONRPCError",
    "code": 500,
    "message": "unknown interface (BidCos-RF)"
  }
}`

Das passt nicht zusammen, da dies ein HMIP-Device ist und ich an dieser CCU noch nichtmal einen HM-"Classic" USB-Stick (HmIP-RFUSB) habe.

Was kann ich tun?

**Comment by rawidat** [comment]
Hallo,

gleiches Problem hier mit HmIP-BSM 1.10.12 > 1.12.6. Update Button ohne Funktion.

debmatic Firmwareversion 3.51.6.42 auf Ubuntu Server 18.04 (x86). Als IO ist nur HmIP-RFUSB vorhanden.

Was kann ich tun, um die bereits auf den HmIP-BSM übertragene Firmware zu installieren?

MfG

**Comment by alexreinert** [comment]
Ich habe mir jetzt extra einen neuen HmIP-PSM geholt und auf diesem das Update problemlos einspielen können. Wesentlicher Unterschied: Ich hatte nicht auf dem Radar, dass hier ein HmIP-RFUSB im Einsatz war und habe das ganze über ein RPI-RF-MOD gemacht.
Jetzt muss ich mal schauen, wo ich noch ein neues Gerät herbekomme, auf welchem auch ein Firmware Update installiert werden muss, damit ich das auch mit einem HmIP-RFUSB durchspielen kann.

**Comment by mar565** [comment]
Hallo zusammen,
Ich habe gerade gemerkt, dass bei mir gar keine Gerätupdates angezeigt werden. Soweit ich weiß, gibt es aber neue Firmware. (Beispiel HmIP-eTRV-B: 1.0.20 -> Sollte inzwischen doch eine 2.x.x geben?)
Bin mir nicht sicher, wie ich das Problem angehen soll. Ich finde auch keine Quelle, um die Firmware herunterzuladen und das Update manuel vorzunehmen. Ansonsten funktioniert alles wunderbar.
Kann mir da jemand helfen?

HB-RF-USB + RPI-RF-MOD
Proxmox
Debmatic 3.51.6.43
Logik ausschließlich über ioBroker

**Comment by alexreinert** [comment]
Die Firmwares werden von eQ-3 mit deutlicher Verzögerung (Monate, nicht Tage...) für die CCU bereitgestellt und tauchen dann auf der Startseite der WebUI auf. Für die HmIP-eTRV-B ist meines Wissens nach die 1.0.20 die aktuelle Version, die 2.x gibt es nur für die HmIP- eTRV (ohne -B)

**Comment by mar565** [comment]
In Ordnung, dann weiß ich Bescheid. Wusste nicht, dass es da eine Unterscheidung gibt. Das heißt aber leider auch, dass die HmIP-eTRV-B keinen Flüstermodus bekommen haben. Sehr schade.
Durch die Info, weiß ich wenigestens, dass nur meine HM-RC-Key4-3 Fernbedienungen mit v1.1 nicht aktuell sind.
Danke für die Hilfe.
