### ISSUE TITLE
Firmware Fehler

### ISSUE THREAD

**Issue by smooty1970** [alexreinert/debmatic#86]
Hallo,
gestern bekamen meine 7 Thermostate HmIP-WTH-2 ein Update von Version 2.0.2 auf 2.6.0 - wurde erfolgreich auf die Thermostate übertragen und installiert. Seit heute erscheint nun auf der Startseite, es seien 7 neue Geräte-Firmwareupdates da. Dann klicke ich den Link an, erscheinen die 7 Thermostate:

Gerät | Seriennummer | Aktuell | Neu
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2
HmIP-WTH-2 | 000xxxxxxxxxxxxxxx | 2.6.0 | 2.0.2

Klicke ich dann auf Neu - wird die Version HmIP_WTH_2_update_2_6_0_191202.tgz heruntergeladen....

Die ist aber bereits installiert und in der Firmwareübersicht der CCU enthalten....

![ccu](https://user-images.githubusercontent.com/17856075/73525055-ab285700-440e-11ea-8d96-22a16f8366e7.PNG)
![ccu02](https://user-images.githubusercontent.com/17856075/73525114-cbf0ac80-440e-11ea-88a5-7d938b509eeb.PNG)

**Comment by smooty1970** [comment]
mit aktuelle Firmwareversion 3.51.6.42 besteht das Problem weiterhin - ich schicke das mal an eq3

**Comment by alexreinert** [comment]
Ist die Firmware denn auch an die Geräte übertragen und bei den Geräten aktiviert worden? Nur auf die CCU runterladen ist ja nur die halbe Miete.

**Comment by smooty1970** [comment]
Hallo Alex.

Erst einmal Danke und großes Lob für deine Arbeit. Eine Spende zur Finanzierung habe ich bereits geleistet.

Laut Firmwareübersicht scheinen die Thermostate aktuell:
<img width="776" alt="1" src="https://user-images.githubusercontent.com/17856075/75037921-8bd49500-54b5-11ea-8910-4a0025e3b282.PNG">

Ein Neustart der Thermostate ändert nichts an der Situation. Das scheint am Firmwarefile zu liegen.....

**Comment by smooty1970** [comment]
Wenn ich das Thermostat neu starte, erscheint auch kurz 2.6......

**Comment by alexreinert** [comment]
Hhm, ich habe da eine Idee: Früher musste man ja zwingend nach einen Firmware Update eines HmIP Gerätes dieses neu anlernen. Ich vermute, dass irgendwo in der Verknüpfung auch gespeichert ist, welche Firmware Version das Gerät hat. Vielleicht wird das nicht komplett angepasst eim Firmware Update, sondern erst, wenn man das Gerät neu anlernt. Leider kann ich das aber weder bestätigen noch wiederlegen, da sich das im Closed Source befindent, auf welchen ich keinerlei Zugriff habe und leider habe ich auch keinen Stapel WTHs hier um das irgendwie nachzustellen. :-(

**Comment by smooty1970** [comment]
Soll ich zum Test mal eine ablernen und neu anlernen?

**Comment by alexreinert** [comment]
Ist den Versuch wert, aber dann musst du halt alles komplett neu einstellen (Direktverknüpfungen, Programme, etc.), was mit dem Teil verknüpft war.

**Comment by smooty1970** [comment]
Nachdem meine HmIP Komponenten direkt über Loxone laufen, muss ich nur die XMLAPI ID neu in Loxone hinterlegen...., auf der CCU gibt es bei mir keine Verknüpfungen, Programme usw., die Steuerung macht Loxone via XML...., ich mache das nun mal und melde retour.....

**Comment by smooty1970** [comment]
ein Device gelöscht - abgelernt, neu angelernt - Anzahl von 7 Devices mit Updates hätte sich auf 6 reduzieren müssen - bleibt bei 7 - hat leider nicht zum Erfolg geführt....Browsercache auch gelöscht...

**Comment by smooty1970** [comment]
ich habe noch die originale CCU3 - ich lerne dort mal ein solches Thermostat an und hinterlege die Firmware für das Thermostat - dann müsste es ja dann wirklich am Firmwarefile liegen....

**Comment by smooty1970** [comment]
Ich habe nun ein Thermastat abgelernt, an der originalen CCU3 angelernt und bekomme die gleiche Meldung (Firmware 2.6.0 und blauen Link 2.0.2), wie oben... das scheint wiklich am Firmwarefile zu liegen

**Comment by smooty1970** [comment]
eq3 Support hat diesen Fehler entfernt - sollte nun nicht mehr angezeigt werden....
