### ISSUE TITLE
Cloudmatic

### ISSUE THREAD

**Issue by Goersch** [alexreinert/debmatic#88]
Hallo,
habs dann auch endlich geschafft umzusteigen - leider hab ich ein Problem:

Feb 04 18:17:08 HA-Server systemd[1]: Started Cloudmatic OpenVPN.
Feb 04 18:17:08 HA-Server openvpn[1039]: Options error: In [CMD-LINE]:1: Error opening configuration file: /usr/share/cloudmatic/client.conf
Feb 04 18:17:08 HA-Server openvpn[1039]: Use --help for more information.
Feb 04 18:17:08 HA-Server systemd[1]: cloudmatic-openvpn.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 18:17:08 HA-Server systemd[1]: cloudmatic-openvpn.service: Failed with result 'exit-code'.

Dass die Datei /usr/share/cloudmatic/client.conf fehlt ist offensichtlich - nur wie komme ich an eine heran?

**Comment by Goersch** [comment]
es gibt eine mhcfg - die Daten darin sind OK; wobei den UserKey kann ich nicht verifizieren

**Comment by Goersch** [comment]
habs herausbekommen:

Im Verzeichnis /usr/share/cloudmatic/
sudo bash .\updatecheck.sh
ausgeführt.

Danach
sudo systemctl start cloudmatic-openvpn.service

und schon hat es geklappt...

**Comment by smooty1970** [comment]
Seit der Installation von Add-On Cloudmatic habe ich nun diese Einträge im LOG:
![log](https://user-images.githubusercontent.com/17856075/74642598-90c2dd00-5173-11ea-9ce7-6990c0a67f95.PNG)
Ist das normal?
