### ISSUE TITLE
Falscher Pfad zu VERSION in debmatic-backup

### ISSUE THREAD

**Issue by der-joern** [alexreinert/debmatic#89]
Hallo,

in /usr/share/debmatic/bin/debmatic-backup.sh ist in Zeile 31 der Pfad zu VERSION falsch:

cp /boot/VERSION $TMPDIR/firmware_version

VERSION ist nicht unter /boot/VERSION, sondern (zumindest bei mir) unter /usr/share/debmatic/VERSION zu finden. Das Scipt schlägt daher fehl.

Viele Grüße,
Jörn

**Comment by Noschvie** [comment]
Hallo
bei meiner Installation gibt es beide Files.

```
pi@raspberrypi:~ $ cat /boot/VERSION
VERSION=3.49.17.41
pi@raspberrypi:~ $ cat /usr/share/debmatic/VERSION
VERSION=3.49.17.41
```

**Comment by alexreinert** [comment]
Es existieren sowohl die /boot/VERSION als auch die /usr/share/debmatic/VERSION. Smit ist das kein Bug.
