### ISSUE TITLE
Support of software emulation of the HM-MOD-RPI-PCB (fake emulation)

### ISSUE THREAD

**Issue by holly79** [alexreinert/debmatic#9]
Hi Alex,

do you plan to support the software emulation of the HM-MOD-RPI-PCB like in pivccu?

Regards,
Holly

**Comment by alexreinert** [comment]
Das ist nicht notwendig. In piVCCU ist es notwendig, weil sich Teile der CCU Firmware darauf verlassen, dass immer ein Funkmodul vorhanden ist.
In debmatic wird vereinfacht dafür gesorgt, dass nur das gestartet wird, was ohne Funkmodul läuft, sofern kein Funkmodulvorhanden ist.
Die Software Emulation ist also sogesehen nur ein Workaround.
