### ISSUE TITLE
RPI-RF-MOD - LEDs do not flash, always off.

### ISSUE THREAD

**Issue by Plazmin** [alexreinert/debmatic#94]
I have:
1. CCU3 (Raspberry Pi 3B and RPI-RF-MOD)
2. fresh installation "2020-02-13-raspbian-buster-lite"
3.  installed Debmatic according to the instructions from [https://github.com/alexreinert/debmatic/blob/master/docs/setup/raspberrypi.md](url)

During the boot process and after RPI-RF-MOD LEDs do not flash, always off. Raspberry LEDs works OK.
If I boot oryginal CCU3 OS or Raspberrymatic all works OK.

![1](https://user-images.githubusercontent.com/62091912/76497355-241dc400-643b-11ea-83f5-1a8d96221b03.png)

![2](https://user-images.githubusercontent.com/62091912/76497599-9c848500-643b-11ea-8337-4cc8656deb0a.png)

![3](https://user-images.githubusercontent.com/62091912/76497675-c342bb80-643b-11ea-86bf-783ec7dbe6ab.png)
![4](https://user-images.githubusercontent.com/62091912/76497764-f2592d00-643b-11ea-807e-34fe45cacbce.png)

Where is problem??

**Comment by Plazmin** [comment]
![1a](https://user-images.githubusercontent.com/62091912/76499922-e7a09700-643f-11ea-8cbf-96681e4ac182.png)

Badly recognized device, I have RPI-RF-MOD, maybe there is a problem here.

**Comment by alexreinert** [comment]
Seems that there is a new batch of RPI-RF-MODs which were not supported by the current hardware detection. Can you please try the lastest update in the testing apt Repository (3.51.6-43)?

**Comment by Plazmin** [comment]
After upgrade to 3.51.6-43 the device is recognized correctly. RPI-RF-MOD LEDs are lit, first green then red, finally blue. But the blue does not blink when loading as in CCU3 OS and Raspberrymatic. Is this correct?

**Comment by alexreinert** [comment]
The blue LED is blinking, when there is no internet connection. RaspberryMatic first starts the LED and the network afterwards. In debmatic the system services and the network is started in parallel, because of that, the network connection is establised a litlle bit earlier and often right before the LED starts.

**Comment by Plazmin** [comment]
I understand, thank you for your help. I also noticed that the WEBUI menu is limited. For example, in "CCU maintenace" lacks "Shutdown" and "Restart" options. Are there many such differences?

**Comment by alexreinert** [comment]
debmatic is not intended as dedicated CCU. Because of this I removed some things, which would affect other services on the same system like Reboot or shutdown.
The second big difference is the complettly different way to install updates and addons which follows the debian like way using apt.

**Comment by Plazmin** [comment]
Thank you for your explanation.
