### ISSUE TITLE
HB-RF-USB-TK wird nicht erkannt

### ISSUE THREAD

**Issue by Bastler173** [alexreinert/debmatic#96]
Hallo zusammen,

nachdem nun mein HB-RF-USB-TK und der RPI-RF-MOD Bausatz angekommen sind habe ich die Teile verlötet und zusammengesteckt.

Leider wird nun an das HB-RF-USB_-TK weder an meinem Server mit passthrough zu einer Debian VM noch an meinem Windowsrechner erkannt. Keine der LEDs auf beiden Bausätzen leuchtet. Was mache ich hier falsch?

Vielen Dank und Grüße
der Bastler

**Comment by alexreinert** [comment]
Was für ein OS hat der "Server mit Passthrough"?
Was heißt unter Windows nicht erkannt? Fehlender Treiber (= unbekanntes Gerät) oder wird die Platine komplett nicht erkannt?
Und zu guter letzt: Was sagt der Händler?

**Comment by Bastler173** [comment]
Vielen Dank für die schnelle Antwort.

Es handelt sich um einen ESXi 6.7.0 Update 2, in der VM läuft Debian 10.3 x64 mit Kernel 4.19.0-8-amd64
Im Gerätemanager unter Windows 10 Pro 1909 wird das Gerät erst gar nicht erkannt.
Mit dem Händler hatte ich noch nicht gesprochen.
Das Gerät ist mit einem USB Kabel, ca. 1m lang, verbunden.

**Comment by alexreinert** [comment]
Wird die Platine in ESXi erkannt? Wenn ja, mit welcher USB ID?

**Comment by Bastler173** [comment]
Ein lsusb vor und nach dem Einstecken des USB Anschlusses liefert denselben output. Die Platine scheint nicht erkannt zu werden.

Bus 002 Device 003: ID 8564:1000 Transcend Information, Inc. JetFlash
Bus 002 Device 002: ID 0438:7900 Advanced Micro Devices, Inc.
Bus 002 Device 001: ID 0e0f:8002 VMware, Inc. Root Hub
Bus 001 Device 001: ID 0e0f:8003 VMware, Inc. Root Hub

**Comment by alexreinert** [comment]
Das war nicht meine Frage. Wird sie von ESXi erkannt? Das macht den Unterschied, ob ein Hardware Problem vorliegt oder ob es ein Problem beim Durchreichen ist.
So oder so ist es aber kein debmatic Problem.

**Comment by Bastler173** [comment]
Wie kann ich prüfen, ob die Platine unter dem ESXi erkannt wird? Habe jetzt mal ein kürzeres micro USB Kabel genommen. Damit erscheint an meinem Rechner ein unbekanntes Gerät mit dem Namen HB-RF-USB. Ich probiere es heute Abend mal am ESXi.

**Comment by Bastler173** [comment]
Schnell getestet. Mit einem lsusb wird nun ein neues Gerät am Server erkannt:

Bus 002 Device 004: ID 0403:6f70 Future Technology Devices International, Ltd

**Comment by alexreinert** [comment]
Also fehlerhaftes Kabel. Dann dürfte das Problem spätestens nach einem Neustart erledigt sein.

**Comment by Bastler173** [comment]
Ja, das Kabel war es. Das durchreichen in die VM hat nun funktioniert. Leider kann ich den DRAP nun nicht zu debmatic hinzufügen...

Wähle ich Homematic IP Access Points und Neu, so wird der HmIPW-DRAP auch gefunden. Gebe ich nun das Passwort ein und klicke auf Hinzufügen dauert es viele Sekunden bis die Meldung "Die Verbindung konnte nicht erfolgreich hergestellt werden" erscheint

Die LED des DRAP leuchtet gelb, was laut Handbuch keine Internetverbindung bedeutet. Eine Firewall habe ich nicht im Einsatz und die Internetverbindung besteht (Unitymedia)...

Was könnte hier schief laufen?

**Comment by Bastler173** [comment]
Nach einem Neustart ist der Access Point mit dem Netzwerk und Internet verbunden. Die LED leuchtet dauerhaft blau. Wenn ich dann den Access Point zu debmatic hinzufügen möchte schaltet die Netzwerkverbindung ab (ein Ping bricht auch für 2-3 Sekunden ab), die LED leuchtet kurz orange, dann blinkend gelb, dann dauerhaft gelb. Der Access Point scheint also neu zu starten, sobald ich auf Hinzufügen klicke.

**Comment by alexreinert** [comment]
Da kann ich leider nicht weiterhelfen. Die gesamte Kommunikation mit dem DRAP und auch die Firmware des DRAPs sind Closed Source und ich habe darauf keinen Zugriff. Im Homematic Forum gibt es aber zum DRAP einige ähnliche Berichte auch mit Original CCU3, vielleicht gibt es dort Lösungsansätze.

**Comment by Bastler173** [comment]
Das Anlernen des DRAP hat jetzt doch irgendwie funktioniert. Auch das Eingangsmodul und der Dimmaktor konnten angelernt werden.

Vielen Dank für die Unterstützung :)
