### ISSUE TITLE
kein Zugriff auf webcamconfig.ini

### ISSUE THREAD

**Issue by HeinHan** [alexreinert/debmatic#97]
Habe keinen Zugriff vom Raspi PI 4 und CCU 3 auf den Ordner /usr/local/addons/webcamconfig.ini. Diese wird mir im Status von "CUxD" angezeigt, kann Sie öffnen bearbeiten aber nicht an den richtigen Ort abspeichern. Das geht weder übers Terminal , Dateimanager noch FileZilla etc.  Auch die Befehle wie ls, Find etc. finden den **Ordner** nicht. ROOT Rechte sind gesetzt, Versteckte Dateien sollen mit angezeigt werden.
Software: CCU-Firmware: 3.51.6; CUxD 2.3.4; Raspi PI 4
[Partitionen.txt](https://github.com/alexreinert/debmatic/files/4398913/Partitionen.txt)
[CUxD_Status_2.txt](https://github.com/alexreinert/debmatic/files/4398910/CUxD_Status_2.txt)

**Comment by alexreinert** [comment]
Sicher das die Datei nicht /usr/local/addons/cuxd/webcamconfig.ini lauten muss? Und mit welchem Benutzer wird versucht die Datei zu bearbeiten? Der Benutzer pi hat für solche Vorgänge nicht genug Rechte.

**Comment by HeinHan** [comment]
Hallo,

der angegebene Pfad/Datei existiert bei mir nicht,
weder als PI oder Root. Die Dateien werden mir jedoch im CUxD Status angezeigt. Kann Sie bearbeiten, werden aber in dem Ordner nicht gespeichert sondern unter Download.

Welche Rechte müsste ich evtl . setzen?

Gruß 

Heinz Hansen 
Von meinem iPhone gesendet

**Comment by alexreinert** [comment]
Welcher den genau? /usr/local/addons/webcamconfig.ini (wäre falsch) oder /usr/local/addons/cuxd/webcamconfig.ini?

**Comment by alexreinert** [comment]
Und was ist damit gemeint, dass die unter Download gespeichert wird? Ist das der Versuch das per Browser zu editieren, was nicht funktionieren kann?

**Comment by HeinHan** [comment]
Hallo,

 

Fange  mal von vorne an. Ich habe einen Raspi PI 4 und eine CCU 3 (Vers. 3.51.6) Soweit hat auch alles geklappt mit der

Homematic, auch virtuelle Taster über die CUxD (Vers. 2.4.1). Bei der Installation einer Kamera (Cloudmatic..) begannen

für mich die Probleme. Wollte über FileZilla, WinSCP bzw. Putty auf die Datei Webcamconfig.ini zugreifen um sie zu bearbeiten,

leider ohne Erfolg.   Keine der Programme zeigte mir die Ordner bzw. darin befindlichen Dateien an. Usr/local ja, addons ff nicht mehr.

Das gleiche Ergebnis, wenn ich  direkt über den Raspi per Dateimanager, mc oder Terminal darauf zugreifen wollte bzw. mir dies anzeigen

Lassen wollte. Gehe ich aber über die CUxD Status, sehe ich die Dateien und kann sie über „d“ editieren aber nicht wieder am gleichen Ort

Steichern. Hier der Auszug vom Status:

 

 <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2f&sid=@IxSuNe4gTq@> /usr/local/addons/

 <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2f&sid=@IxSuNe4gTq@> /usr/local/addons/cuxd/ (total 21)

 

07.09.2017 11:57:55              <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fdfu%2f&sid=@IxSuNe4gTq@> dfu/

17.09.2019 16:39:25              <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fextra%2f&sid=@IxSuNe4gTq@> extra/

30.11.2017 15:51:10              <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fuser%2f&sid=@IxSuNe4gTq@> user/

19.11.2015 12:05:00  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fCUXD.PNG&dl=1&sid=@IxSuNe4gTq@> D     10693  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fCUXD.PNG&sid=@IxSuNe4gTq@> CUXD.PNG

19.11.2015 12:05:00  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fajax.gif&dl=1&sid=@IxSuNe4gTq@> D      1924  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fajax.gif&sid=@IxSuNe4gTq@> ajax.gif

18.09.2019 17:32:07  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcproxy.ccc&dl=1&sid=@IxSuNe4gTq@> D      3360  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcproxy.ccc&sid=@IxSuNe4gTq@> cproxy.ccc -> redir.ccc

31.01.2020 10:07:11  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcurl&dl=1&sid=@IxSuNe4gTq@> D    116444  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcurl&sid=@IxSuNe4gTq@> curl -> extra/curl

01.04.2020 11:22:05  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd&dl=1&sid=@IxSuNe4gTq@> D    838100  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd&sid=@IxSuNe4gTq@> cuxd

26.02.2020 17:49:31  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.inc&dl=1&sid=@IxSuNe4gTq@> D     33901  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.inc&sid=@IxSuNe4gTq@> cuxd.inc

04.04.2020 19:39:54  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ini&dl=1&sid=@IxSuNe4gTq@> D       981  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ini&sid=@IxSuNe4gTq@> cuxd.ini

06.04.2020 04:40:02  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ps&dl=1&sid=@IxSuNe4gTq@> D        82  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ps&sid=@IxSuNe4gTq@> cuxd.ps

05.04.2020 17:40:02  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ps.bak&dl=1&sid=@IxSuNe4gTq@> D        82  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fcuxd.ps.bak&sid=@IxSuNe4gTq@> cuxd.ps.bak

19.02.2020 11:56:07  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fdevicelist.inc&dl=1&sid=@IxSuNe4gTq@> D      4976  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fdevicelist.inc&sid=@IxSuNe4gTq@> devicelist.inc

17.09.2019 16:40:56  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fdfu-programmer&dl=1&sid=@IxSuNe4gTq@> D     75012  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fdfu-programmer&sid=@IxSuNe4gTq@> dfu-programmer

18.09.2019 17:32:07  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2findex.ccc&dl=1&sid=@IxSuNe4gTq@> D     48108  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2findex.ccc&sid=@IxSuNe4gTq@> index.ccc

19.11.2015 12:05:00  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2findex.html&dl=1&sid=@IxSuNe4gTq@> D       288  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2findex.html&sid=@IxSuNe4gTq@> index.html

20.05.2019 22:09:22  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fmaintenance.html&dl=1&sid=@IxSuNe4gTq@> D      4513  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fmaintenance.html&sid=@IxSuNe4gTq@> maintenance.html

18.09.2019 17:32:07  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fredir.ccc&dl=1&sid=@IxSuNe4gTq@> D      3360  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fredir.ccc&sid=@IxSuNe4gTq@> redir.ccc

19.11.2015 12:05:00  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2frobots.txt&dl=1&sid=@IxSuNe4gTq@> D        26  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2frobots.txt&sid=@IxSuNe4gTq@> robots.txt

18.09.2019 17:34:54  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fupdate_addon&dl=1&sid=@IxSuNe4gTq@> D      5968  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fupdate_addon&sid=@IxSuNe4gTq@> update_addon

14.05.2016 13:54:36  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fwebcamconfig.ini&dl=1&sid=@IxSuNe4gTq@> D      7814  <http://192.168.178.34/addons/cuxd/index.ccc?file=%2fusr%2flocal%2faddons%2fcuxd%2fwebcamconfig.ini&sid=@IxSuNe4gTq@> webcamconfig.ini

 

Hier das Ergebnis über 

 

pi@raspberrypi:/usr/local $ ls

bin  etc  games  include  lib  man  sbin  share  src       <-- Addon fehlt

 

Versteckte Dateien anzeigen sowie über ROOT brachten keinen Erfolg. Daruf hin,  habe ich die CXuD deinstalliert und wieder installiert,

leider ohne Erfolg.

An den Rechten des Benutzer <pi habe ich nichts geändert, wie gesagt, andere Geräte funktionier über der CUxD Dienst.

 

Gerne schicke ich Dir weitere benötige Dateien. Im Moment lade ich mir ein neues Image  und versuche dies über eine neue SD-Karte

neu zu installieren.

 

Gruß

Heinz Hansen

 

 

 

 

Von: Alexander Reinert <notifications@github.com> 
Gesendet: Montag, 6. April 2020 12:16
An: alexreinert/debmatic <debmatic@noreply.github.com>
Cc: HeinHan <hansen_heinz@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/debmatic] kein Zugriff auf webcamconfig.ini (#97)

 

Und was ist damit gemeint, dass die unter Download gespeichert wird? Ist das der Versuch das per Browser zu editieren, was nicht funktionieren kann?

**Comment by alexreinert** [comment]
Mal eine ganz blöde Frage: Benutzt du wirklich debmatic? Die CUxD Version spricht etwas dagegen.

**Comment by HeinHan** [comment]
Ups, habe ich im falschen Forum gepostet. Habe das doch bei CUxD eingegeben. Sorry

 

Von: Alexander Reinert <notifications@github.com> 
Gesendet: Montag, 6. April 2020 16:52
An: alexreinert/debmatic <debmatic@noreply.github.com>
Cc: HeinHan <hansen_heinz@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [alexreinert/debmatic] kein Zugriff auf webcamconfig.ini (#97)

 

Mal eine ganz blöde Frage: Benutzt du wirklich debmatic? Die CUxD Version spricht etwas dagegen.
